export const sscChangingSentences = [
  {
    exam: "ssc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "(a) The bee is one of the busiest insects. (Positive)<br/>(b) It lives together. (Negative)<br/>(c) Bees collect nectar from the flowers and make honey. (Simple)<br/>(d) They dance most vigorously to find the nectar plentiful. (Exclamatory)<br/>(e) Honey is stored in the hive by bees. (Active voice)<br/>(f) They work hard in spring. (Complex)<br/>(g) No insect is as industrious as the bee. (Comparative)<br/>(h) How greatly they inspire us to work hard! (Assertive)<br/>(i) The bees make us think of the importance of activity. (Passive voice)<br/>(j) We should be industrious like the bee. (Imperative)",
      answers: [
        "(a) Very few insects are as busy as the bee.",
        "(b) It doesn't live alone.",
        "(c) Collecting nectar from the flowers, bees make honey.",
        "(d) How vigorously they dance to find the nectar plentiful!",
        "(e) Bees store honey in the hive.",
        "(f) They work hard when it is spring.",
        "(g) The bee is more industrious than any other insect.",
        "(h) They greatly inspire us to work hard.",
        "(i) We are made to think of the importance of activity by the bees.",
        "(j) Let us be industrious like the bee.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "(a) We have faced a very severe flood recently. (Exclamatory)<br/>(b) The recent flood was one of the most devastating floods in our country. (Positive)<br/>(c) Many people of the flood-affected area became homeless. (Interrogative)<br/>(d) Many conscious people came forward to help the flood victims. (Complex)<br/>(e) The young generation showed a very positive attitude in this regard. (Negative)<br/>(f) They extended their helping hands to mitigate the sufferings of the flood victims. (Complex)<br/>(g) In fact, they could not but come forward. (Affirmative)<br/>(h) Collecting subscription, they bought relief goods for the flood-affected people. (Compound)<br/>(i) They took part in the rescue mission as skillfully as the trained workers. (Comparative)<br/>(j) They were praised highly by the people of the whole country. (Active)",
      answers: [
        "(a) What a severe flood we have faced recently!",
        "(b) Very few floods in our country were as devastating as the recent flood.",
        "(c) Didn't many people of the flood-affected area become homeless?",
        "(d) Many people who were conscious came forward to help the flood victims.",
        "(e) The young generation didn't show a negative attitude in this regard.",
        "(f) They extended their helping hands so that they could mitigate the sufferings of the flood victims.",
        "(g) In fact, they had to come forward.",
        "(h) They collected subscription and bought relief goods for the flood-affected people.",
        "(i) They took part in the rescue mission not less skillfully than the trained workers.",
        "(j) The people of the whole country praised them highly.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "(a) Sunderban is one of the largest Mangrove forests in the world. (Positive)<br/>(b) How nice the forest is! (Assertive)<br/>(c) As soon as I saw the tiger, I climbed upon the tree. (Negative)<br/>(d) Tell him to tell a tale. (Passive)<br/>(e) Everybody knows this. (Interrogative)<br/>(f) If we destroy mangrove forest, we will lose our ecological balance. (Simple)<br/>(g) By visiting the forest, we can enjoy beautiful sights. (Complex)<br/>(h) So, we should save the useful forest. (Imperative)<br/>(i) When it is spring, the forest looks very nice. (Simple)<br/>(j) Going to Sunderbans, we saw many animals there. (Complex)",
      answers: [
        "(a) Very few Mangrove forests in the world are as large as Sunderban.",
        "(b) The forest is very nice.",
        "(c) No sooner had I seen the tiger than I climbed upon the tree.",
        "(d) Let him be told to tell a tale.",
        "(e) Who does not know this?",
        "(f) Destroying mangrove forest will make us lose our ecological balance.",
        "(g) If we visit the forest, we can enjoy beautiful sights.",
        "(h) Let us save the useful forest.",
        "(i) In spring, the forest looks very nice.",
        "(j) When we went to Sunderbans, we saw many animals there.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "(a) War is a curse for the human civilization. (Negative sentence.)<br/>(b) It is not constructive. (Affirmative sentence.)<br/>(c) It destroys civilization. (Interrogative sentence.)<br/>(d) It is the worst evil in civilization. (Positive)<br/>(e) Those who are war mongers make the trouble for all. (Simple sentence.)<br/>(f) We know that war brings destructions. (Passive voice.)<br/>(g) Shouldn't a man learn to live in peace? (Assertive sentence.)<br/>(h) How devastating the war is! (Assertive sentence.)<br/>(i) Nothing is as corrosive as the war. (Superlative degree.)<br/>(j) The evil-minded leaders must be avoided. (Active voice.)",
      answers: [
        "(a) War is not a blessing for the human civilization.",
        "(b) It is destructive.",
        "(c) Doesn't it destroy civilization?",
        "(d) No other evil in civilization is as bad as war.",
        "(e) War mongers make the trouble for all.",
        "(f) It is known to us that destructions are brought by war.",
        "(g) A man should learn to live in peace.",
        "(h) The war is very devastating.",
        "(i) War is the most corrosive thing.",
        "(j) People must avoid the evil-minded leaders.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "(a) English is not a native language. (Affirmative)<br/>(b) Without learning English we cannot hope to get any good job. (Complex)<br/>(c) The man who knows English well, can go abroad. (Simple)<br/>(d) He becomes a very valuable person. (Exclamatory)<br/>(e) You must learn English. (Negative)<br/>(f) Everybody knows this truth. (Imperative)<br/>(g) Our students are going to practice English more and more. (Passive)<br/>(h) Only the foolish can disobey the true importance of English. (Interrogative)<br/>(i) So, let not any more time be wasted. (Active)<br/>(j) If you study well, you will be able to learn it. (Compound)",
      answers: [
        "(a) English is a foreign language.",
        "(b) If we do not learn English, we cannot hope to get any good job.",
        "(c) The man knowing English well can go abroad.",
        "(d) What a valuable person he becomes!",
        "(e) You cannot but learn English.",
        "(f) Let everybody know this truth.",
        "(g) English is going to be practiced more and more by our students.",
        "(h) Who can disobey the true importance of English?",
        "(i) So, do not waste any more time.",
        "(j) Study well, and you will be able to learn it.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "(a) Everybody wants to make a good result in the examination. (Interrogative Sentence)<br/>(b) It is not an easy task. (Affirmative Sentence)<br/>(c) Being industrious, every student can make a good result. (Negative Sentence)<br/>(d) The idle always lag behind. (Complex Sentence)<br/>(e) They must work hard so that they can prosper in life. (Simple Sentence)<br/>(f) Girls can work as much as boys. (Comparative Degree)<br/>(g) Students should also observe the rules of health. (Passive Voice)<br/>(h) An idle student leads a very miserable life. (Exclamatory Sentence)<br/>(i) The light of prosperity can be seen by a hard-working person. (Active Voice)<br/>(j) By working hard, you can also change your condition. (Compound Sentence)",
      answers: [
        "(a) Who doesn't want to make a good result in the examination?",
        "(b) It is a difficult task.",
        "(c) Without being industrious, no student can make a good result.",
        "(d) Those who are idle always lag behind.",
        "(e) They must work hard to prosper in life.",
        "(f) Girls cannot work less than boys.",
        "(g) The rules of health should also be observed by students.",
        "(h) What a miserable life an idle student leads!",
        "(i) A hard-working person can see the light of prosperity.",
        "(j) Work hard, and you can change your condition.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Who does not want to succeed in life? (Assertive)<br/>(b) Being industrious, everyone can prosper in life. (Negative)<br/>(c) It is not an easy thing. (Affirmative)<br/>(d) The idle always has behind. (Complex)<br/>(e) We must work hard so that we can earn money. (Simple)<br/>(f) By working hard, we can improve our lot. (Compound)<br/>(g) The light of prosperity can be seen by a hard-working person. (Active)<br/>(h) Women should work as much as men. (Comparative)<br/>(i) We should remember that industry is the key to success. (Passive)<br/>(j) An idle man leads a very miserable life. (Exclamatory)",
      answers: [
        "(a) Everybody wants to succeed in life.",
        "(b) Without being industrious, none can prosper in life.",
        "(c) It is a difficult thing.",
        "(d) Those who are idle always have behind.",
        "(e) We must work hard to earn money.",
        "(f) We work hard, and we can improve our lot.",
        "(g) A hard-working person can see the light of prosperity.",
        "(h) Women should not work less than men.",
        "(i) It should be remembered that industry is the key to success.",
        "(j) What a miserable life an idle man leads!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "(a) A successful man is greater than any other asset to a country. (Positive)<br/>(b) However, being a successful man is a complicated task. (Negative)<br/>(c) We have to be industrious to prosper in life. (Imperative)<br/>(d) The idle always lag behind. (Complex)<br/>(e) We must work hard so that we can earn money. (Simple)<br/>(f) By working hard, we can improve our lot. (Compound)<br/>(g) The light of prosperity can be seen by a hard-working person. (Active)<br/>(h) Women should work as much as men. (Comparative)<br/>(i) We should remember that industry is the key to success. (Passive)<br/>(j) An idle man leads a very miserable life. (Exclamatory)",
      answers: [
        "(a) No other asset to a country is as great as a successful man.",
        "(b) However, being a successful man is not an easy task.",
        "(c) Let us be industrious to prosper in life.",
        "(d) Those who are idle always lag behind.",
        "(e) We must work hard to earn money.",
        "(f) Let us work hard, and we can improve our lot.",
        "(g) A hard-working person can see the light of prosperity.",
        "(h) Women should not work less than men.",
        "(i) That industry is the key to success should be remembered by us.",
        "(j) What a miserable life an idle man leads!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Dhaka",
    data: {
      questions:
        "(a) How charming a moonlit night is! (Assertive)<br/>(b) It presents a very beautiful sight. (Exclamatory)<br/>(c) It dazzles our eyes and soothes our heart. (Negative)<br/>(d) People of all ages enjoy a moonlit night. (Interrogative)<br/>(e) Little boys and girls make merriment to enjoy themselves. (Complex)<br/>(f) Everybody likes a moonlit night. (Passive)<br/>(g) Though the moon gives us light, it does not have the light of its own. (Compound)<br/>(h) Very few beauties of nature are as charming as a moonlit night. (Comparative)<br/>(i) Unless one enjoys the beauty of a moonlit night, one cannot explain it properly. (Simple)<br/>(j) In fact, a moonlit night is very pleasant. (Negative)",
      answers: [
        "(a) A moonlit night is very charming.",
        "(b) What a beautiful sight it presents!",
        "(c) It not only dazzles our eyes but also does not fail to soothe our hearts.",
        "(d) Don’t people of all ages enjoy a moonlit night?",
        "(e) Little boys and girls make merriment so that they can enjoy themselves.",
        "(f) A moonlit night is liked by everybody.",
        "(g) The moon gives us light, but it does not have light of its own.",
        "(h) A moonlit night is more charming than most other beauties of nature.",
        "(i) Without enjoying the beauty of a moonlit night, one cannot explain it properly.",
        "(j) In fact, a moonlit night is not unpleasant.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Cumilla",
    data: {
      questions:
        "(a) Strategy is the most important thing in the examination. (Comparative)<br/>(b) No answer in the exam should be elaborated unnecessarily. (Active)<br/>(c) When a student gets the question paper, he should read it attentively. (Simple)<br/>(d) Initially the questions may seem difficult. (Negative)<br/>(e) A student should try to answer all the questions to do good in the exam. (Complex)<br/>(f) If a student answers all the questions correctly, he will get good marks. (Simple)<br/>(g) A student should not write irrelevant answers. (Affirmative)<br/>(h) How irritated the examiners become to see such irrelevant answers! (Assertive)<br/>(i) The examinee should not waste time by doing so. (Passive)<br/>(j) By following the process, every student can achieve a good result in an examination. (Negative)",
      answers: [
        "(a) Strategy is more important than any other thing in the examination.",
        "(b) Students should not elaborate any answer in the exam unnecessarily.",
        "(c) Getting the question paper, a student should read it attentively.",
        "(d) Initially, the questions may not seem easy.",
        "(e) A student should try to answer all the questions so that he can do good in the exam.",
        "(f) By answering all the questions correctly, a student will get good marks.",
        "(g) A student should write relevant answers.",
        "(h) The examiners become very irritated to see such irrelevant answers.",
        "(i) Time should not be wasted by the examinee by doing so.",
        "(j) No student can achieve a good result in an examination without following the process.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Chattogram",
    data: {
      questions:
        "(a) Internet is a computer-based networking system. (Interrogative)<br/>(b) It is a speedy transmitting system of information. (Complex)<br/>(c) Its functions are not only smooth but also rapid. (Affirmative)<br/>(d) A man has an internet connection and gets a link soon. (Simple)<br/>(e) Many educational institutions are greatly benefited through the use of internet. (Complex)<br/>(f) A student can visit all the renowned libraries of the world without going there. (Passive)<br/>(g) It plays an effective role in the field of trade and commerce. (Exclamatory)<br/>(h) E-commerce has become one of the most popular topics to the customers. (Comparative)<br/>(i) It helps the customers to buy anything easily without going to market. (Compound)<br/>(j) What an amazing milestone it is in the modern world of communication! (Assertive)",
      answers: [
        "(a) Isn’t the Internet a computer-based networking system?",
        "(b) It is a system that transmits information speedily.",
        "(c) Its functions are both smooth and rapid.",
        "(d) A man with an internet connection gets a link soon.",
        "(e) Many educational institutions are greatly benefited as they use the internet.",
        "(f) All the renowned libraries of the world can be visited by a student without going there.",
        "(g) What an effective role it plays in the field of trade and commerce!",
        "(h) E-commerce has become more popular to customers than most other topics.",
        "(i) It helps the customers to buy anything easily, and they need not go to the market.",
        "(j) It is a very amazing milestone in the modern world of communication.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Dinajpur",
    data: {
      questions:
        "(a) A Journey by train is always enjoyable. (Negative)<br/>(b) People are fond of a journey by train. (Interrogative)<br/>(c) It is not unpleasant. (Affirmative)<br/>(d) When a man makes a journey by train, he can enjoy natural scenery. (Simple)<br/>(e) People like it as it is cheap. (Compound)<br/>(f) There are class distinction in a train and people can buy tickets of various classes. (Complex)<br/>(g) Train is one of the most comfortable vehicles. (Comparative)<br/>(h) A man can enjoy a train journey. (Passive)<br/>(i) It was introduced by the British govt. (Active)<br/>(j) A train journey is very safe. (Exclamatory)",
      answers: [
        "(a) A journey by train is never boring.",
        "(b) Aren’t people fond of a journey by train?",
        "(c) It is pleasant.",
        "(d) By making a journey by train, a man can enjoy natural scenery.",
        "(e) It is cheap, and so people like it.",
        "(f) As there are class distinctions in a train, people can buy tickets of various classes.",
        "(g) Train is more comfortable than most other vehicles.",
        "(h) A train journey can be enjoyed by a man.",
        "(i) The British government introduced it.",
        "(j) How safe a train journey is!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Jessore",
    data: {
      questions:
        "(a) Water is a liquid substance. (Interrogative)<br/>(b) It is used for various purposes in our daily life. (Active)<br/>(c) We drink water to satisfy our thirst. (Complex)<br/>(d) We get water from many sources. (Passive)<br/>(e) Surface water is not safe for drinking. (Affirmative)<br/>(f) We should drink tube-well water. (Imperative)<br/>(g) Polluted water is very dangerous for our life. (Exclamatory)<br/>(h) If we throw wastage and dirts into water, we make it polluted. (Simple)<br/>(i) Pure water is one of the most valuable things for our lives. (Positive)<br/>(j) Who can live without water? (Negative)",
      answers: [
        "(a) Isn’t water a liquid substance?",
        "(b) We use it for various purposes in our daily life.",
        "(c) We drink water so that we can satisfy our thirst.",
        "(d) Water is got from many sources (by us).",
        "(e) Surface water is unsafe for drinking.",
        "(f) Drink tube-well water.",
        "(g) How dangerous polluted water is for our life!",
        "(h) By throwing wastage and dirt into water, we make it polluted.",
        "(i) Very few things for our lives are as valuable as pure water.",
        "(j) Nobody can live without water.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Mymensingh",
    data: {
      questions:
        "(a) Corruption is one of the worst evils. (Positive)<br/>(b) A corrupt person can do anything against morality. (Complex)<br/>(c) People hate a corrupt person. (Passive)<br/>(d) Nobody respects him. (Interrogative)<br/>(e) Though we have strict laws, we are still affected by this evil. (Compound)<br/>(f) No other person is as hated as a corrupt person. (Superlative)<br/>(g) We hope that Bangladesh will be free from this evil. (Simple)<br/>(h) Everybody avoids a corrupt person. (Negative)<br/>(i) A corrupt person leads a very unhappy life. (Exclamatory)<br/>(j) Let us all work together to make Bangladesh a corruption free country. (Assertive)",
      answers: [
        "(a) Very few evils are as bad as corruption.",
        "(b) A person who is corrupt can do anything against morality.",
        "(c) A corrupt person is hated (by people).",
        "(d) Who respects him?",
        "(e) We have strict laws but we are still affected by this evil.",
        "(f) A corrupt person is the most hated person.",
        "(g) Hopefully Bangladesh will be free from this evil.",
        "(h) There is nobody but avoids a corrupt person.",
        "(i) What an unhappy life a corrupt person leads!",
        "(j) We should work together to make Bangladesh a corruption-free country.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Water is one of the most useful elements in nature. (Positive)<br/>(b) It is a very important asset. (Exclamatory)<br/>(c) We cannot pass a single day without water. (Interrogative)<br/>(d) Its main source is the rain that creates streams, lakes, and rivers. (Compound)<br/>(e) We have rain during the monsoon. (Complex)<br/>(f) Heavy rainfall often causes floods. (Passive)<br/>(g) Crops are damaged. (Active)<br/>(h) Our winter is dry and rainless. (Negative)<br/>(i) Does rainless winter bring good harvest? (Assertive)<br/>(j) We can grow more crops if we can make the best use of rain. (Simple)",
      answers: [
        "(a) Very few elements in nature are as useful as water.",
        "(b) What an important asset it is!",
        "(c) Can we pass a single day without water?",
        "(d) Its main source is the rain and it creates streams, lakes, and rivers.",
        "(e) We have rain when it is the monsoon.",
        "(f) Floods are often caused by heavy rainfall.",
        "(g) Flood damages the crops.",
        "(h) Our winter is not only dry but also rainless.",
        "(i) Rainless winter does not bring good harvest.",
        "(j) By making the best use of rain, we can grow more crops.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Sylhet",
    data: {
      questions:
        "(a) Who does not want to succeed in life? (Assertive)<br/>(b) Being industrious, everyone can prosper in life. (Negative)<br/>(c) It is not an easy thing. (Affirmative)<br/>(d) The idle always lag behind. (Complex)<br/>(e) We must work hard so that we can earn money. (Simple)<br/>(f) By working hard, we can improve our lot. (Compound)<br/>(g) The light of prosperity can be seen by a hard working person. (Active)<br/>(h) Women should work as much as men. (Comparative)<br/>(i) We should remember that industry is the key to success. (Passive)<br/>(j) An idle man leads a very miserable life. (Exclamatory)",
      answers: [
        "(a) Everybody wants to succeed in life.",
        "(b) Without being industrious, none can prosper in life.",
        "(c) It is a difficult thing.",
        "(d) Those who are idle always lag behind.",
        "(e) We must work hard to earn money.",
        "(f) We work hard and thus we can improve our lot.",
        "(g) A hard-working person can see the light of prosperity.",
        "(h) Women should not work less than men.",
        "(i) That industry is the key to success should be remembered (by us).",
        "(j) What a miserable life an idle man leads!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Chattogram",
    data: {
      questions:
        "(a) Copying in the exams is one of the greatest social crimes. (Positive)<br/>(b) It is a very serious crime. (Exclamatory)<br/>(c) A student copying in the exam only deceives himself. (Negative)<br/>(d) Copying in the exam cannot bring any benefit. (Passive)<br/>(e) What a shameful practice it is! (Assertive)<br/>(f) By resisting this malady, we can strengthen our education. (Passive)<br/>(g) We all should come forward to stop it and save our students. (Imperative)<br/>(h) Our examination system should be moderated. (Active)<br/>(i) Nothing is as hateful as copying in the exam. (Comparative)<br/>(j) The government is sincere in removing this crime. (Negative)",
      answers: [
        "(a) Very few social crimes are as great as copying in the exams.",
        "(b) What a serious crime it is!",
        "(c) A student copying in the exam deceives none but himself.",
        "(d) Any benefit cannot be brought by copying in the exam.",
        "(e) It is a very shameful practice.",
        "(f) Our education can be strengthened by resisting this malady.",
        "(g) Let's all come forward to stop it and save our students.",
        "(h) The authority should moderate our examination system.",
        "(i) Copying in the exam is more hateful than any other thing.",
        "(j) The government is not insincere in removing this crime.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Cumilla",
    data: {
      questions:
        "(a) We are grateful to the freedom fighters. (Negative)<br/>(b) Their contribution is greater than any other thing. (Superlative)<br/>(c) You should never disrespect or forget our martyrs. (Imperative)<br/>(d) The national memorial has been built with a view to paying tribute to their memories. (Active)<br/>(e) A freedom fighter is the greatest son of the soil. (Comparative)<br/>(f) We got our independence for their sacrifice. (Passive)<br/>(g) They fought very bravely to snatch the red sun of independence. (Exclamatory)<br/>(h) Their courage was more powerful than their weapons. (Positive)<br/>(i) Their contribution will never be forgotten. (Active)<br/>(j) The government has taken some steps to improve their condition. (Passive)",
      answers: [
        "(a) We are not ungrateful to the freedom fighters.",
        "(b) Their contribution is the greatest thing.",
        "(c) Never disrespect or forget our martyrs.",
        "(d) The authority has built the national memorial with a view to paying tribute to their memories.",
        "(e) A freedom fighter is greater than any other son of the soil.",
        "(f) Our independence was got for their sacrifice.",
        "(g) How bravely they fought to snatch the red sun of independence!",
        "(h) Their weapons were not as powerful as their courage.",
        "(i) People will never forget their contribution.",
        "(j) Some steps have been taken by the government to improve their condition.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Barishal",
    data: {
      questions:
        "(a) Jackfruit is one of the largest fruits of Bangladesh. (Positive)<br/>(b) The fruit is very juicy. (Exclamatory)<br/>(c) It tastes very sweet. (Passive)<br/>(d) It contains high calories. (Negative)<br/>(e) Everyone knows it as our national fruit. (Interrogative)<br/>(f) In summer, this fruit is very available. (Negative)<br/>(g) It is mainly found in the month of Jaishtha. (Active)<br/>(h) It is not as costly as the mango. (Comparative)<br/>(i) We should eat the fruit to ensure nutrition. (Imperative)<br/>(j) How beautiful jackfruits look in the trees! (Assertive)",
      answers: [
        "(a) Very few fruits of Bangladesh are as large as jackfruit.",
        "(b) How juicy the fruit is!",
        "(c) It is very sweet when tasted.",
        "(d) It does not contain low calories.",
        "(e) Who does not know it as our national fruit?",
        "(f) In summer, this fruit is not unavailable.",
        "(g) We find it mainly in the month of Jaishtha.",
        "(h) Mango is costlier than it.",
        "(i) Let's eat the fruit to ensure nutrition.",
        "(j) Jackfruits look very beautiful in the trees.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Dhaka",
    data: {
      questions:
        "(a) The moon is the only sub-planet of the earth. (Interrogative)<br/>(b) It is very charming to look at. (Exclamatory)<br/>(c) Everybody is charmed with its beauty. (Active)<br/>(d) Who doesn't like the moon? (Affirmative)<br/>(e) The moon is the most beautiful thing. (Positive)<br/>(f) Only the moon shines at night. (Negative)<br/>(g) Poets have composed many poems about the beauty of it. (Passive)<br/>(h) What an exciting scene the full-moon presents! (Assertive)<br/>(i) The moon is not as big as the earth. (Comparative)<br/>(j) We should go out at night to enjoy a moonlit night. (Imperative)",
      answers: [
        "(a) Isn't the moon the only sub-planet of the earth?",
        "(b) How charming it is to look at!",
        "(c) Its beauty charms everybody.",
        "(d) Everybody likes the moon.",
        "(e) No other thing is as beautiful as the moon.",
        "(f) Nothing but the moon shines at night.",
        "(g) Many poems have been composed about the beauty of it by poets.",
        "(h) The full moon presents a very exciting scene.",
        "(i) The earth is bigger than the moon.",
        "(j) Let's go out at night to enjoy a moonlit night.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Jashore",
    data: {
      questions:
        "(a) I am sure that man is the maker of his own fortune. (Negative)<br/>(b) A man has to make a proper use of his time to shine in life. (Imperative)<br/>(c) Who doesn't know it? (Passive voice)<br/>(d) The lazy suffer miserably in the long run. (Exclamatory)<br/>(e) To kill time is as harmful as to commit suicide. (Comparative)<br/>(f) Our life is only a sum total of hours, days and years. (Negative)<br/>(g) Youth is the most valuable season of life. (Positive)<br/>(h) In youth, our mind can be shaped easily. (Active voice)<br/>(i) We should utilize our time properly in youth. (Imperative)<br/>(j) It is called the seedtime of life. (Active voice)",
      answers: [
        "(a) I am not unsure that man is the maker of his own fortune.",
        "(b) Let a man make a proper use of his time to shine in life.",
        "(c) By whom isn't it known?",
        "(d) How miserably the lazy suffer in the long run!",
        "(e) To kill time is not less harmful than to commit suicide.",
        "(f) Our life is nothing but a sum total of hours, days and years.",
        "(g) No other season of life is as valuable as youth.",
        "(h) In youth, we can shape our mind easily.",
        "(i) Let's utilize our time properly in youth.",
        "(j) We call it the seedtime of life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Newspaper is one of the most useful sources of knowledge. (Positive)<br/>(b) It carries both local and international news. (Negative)<br/>(c) It reflects the whole world like a mirror. (Interrogative)<br/>(d) We cannot help reading newspaper daily. (Affirmative)<br/>(e) It contains daily news. (Passive)<br/>(f) We are helped in many ways by it. (Active)<br/>(g) By reading newspaper, we can enrich our knowledge. (Negative)<br/>(h) It is called the people's parliament. (Active)<br/>(i) Nothing is so important as it. (Comparative)<br/>(j) We should read newspaper to know the outside world more. (Imperative)",
      answers: [
        "(a) Very few sources of knowledge are as useful as newspaper.",
        "(b) It does not fail to carry both local and international news.",
        "(c) Doesn't it reflect the whole world like a mirror?",
        "(d) We must read newspaper daily.",
        "(e) Daily news is contained in it.",
        "(f) It helps us in many ways.",
        "(g) Without reading newspaper, we cannot enrich our knowledge.",
        "(h) People call it the people's parliament.",
        "(i) It is more important than anything.",
        "(j) Let's read newspaper to know the outside world more.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Dinajpur",
    data: {
      questions:
        "(a) Honesty can open a door of peace before a person. (Negative)<br/>(b) He accepted the invitation. (Passive)<br/>(c) Reading books is nobler than any other habit. (Superlative)<br/>(d) Loving country is a very essential virtue. (Exclamatory)<br/>(e) We don't measure our life by months or years. (Active)<br/>(f) Industry is the most important thing for success. (Comparative)<br/>(g) How attentive she was to her study! (Assertive)<br/>(h) Terrorism is one of the most corrosive problems of the modern world. (Positive)<br/>(i) We should do good deeds as our responsibility. (Imperative)<br/>(j) Everybody is fond of glittering things. (Negative)",
      answers: [
        "(a) Dishonesty cannot open any door of peace before a person.",
        "(b) The invitation was accepted by him.",
        "(c) Reading books is the noblest habit.",
        "(d) What an essential virtue loving country is!",
        "(e) We don't measure our life by months or years.",
        "(f) Industry is more important than any other thing for success.",
        "(g) She was very attentive to her study.",
        "(h) Very few problems of the modern world are as corrosive as terrorism.",
        "(i) Let us do good deeds as our responsibility.",
        "(j) There is nobody who is not fond of glittering things.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Mymensingh",
    data: {
      questions:
        "(a) Simplicity is a great virtue. (Exclamatory)<br/>(b) Everybody appreciates this quality. (Negative)<br/>(c) It is one of the best qualities. (Positive)<br/>(d) One should practise this virtue. (Passive)<br/>(e) Very few men are as happy as a simple man. (Comparative)<br/>(f) By practising simplicity, one can earn people's favour. (Negative)<br/>(g) A simple man leads a very carefree life. (Exclamatory)<br/>(h) No other person among us is as happy as a simple man. (Superlative)<br/>(i) Everybody should like simplicity. (Imperative)<br/>(j) So, a simple life should be led by all. (Active)",
      answers: [
        "(a) What a great virtue simplicity is!",
        "(b) There is nobody who does not appreciate this quality.",
        "(c) Very few qualities are as good as it.",
        "(d) This virtue should be practised.",
        "(e) A simple man is happier than most other men.",
        "(f) Without practising simplicity, one cannot earn people's favour.",
        "(g) What a carefree life a simple man leads!",
        "(h) A simple man is the happiest person among us.",
        "(i) Let everybody like simplicity.",
        "(j) So, all should lead a simple life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Sylhet",
    data: {
      questions:
        "(a) The student is known to me. (Active)<br/>(b) She gave me an interesting book. (Passive)<br/>(c) Jashore is older than Magura. (Positive)<br/>(d) Truthfulness is the best quality of a person. (Comparative)<br/>(e) No other city in Bangladesh is as popular as Dhaka. (Superlative)<br/>(f) My friend is always punctual. (Negative)<br/>(g) He is a great fool. (Exclamatory)<br/>(h) How bright the student is! (Assertive)<br/>(i) We should obey our teachers. (Imperative)<br/>(j) Take care of your health. (Passive)",
      answers: [
        "(a) I know the student.",
        "(b) An interesting book was given to me by her.",
        "(c) Magura is not as old as Jashore.",
        "(d) Truthfulness is better than any other quality of a person.",
        "(e) Dhaka is the most popular city in Bangladesh.",
        "(f) My friend is never unpunctual.",
        "(g) What a fool he is!",
        "(h) The student is very bright.",
        "(i) Let's obey our teachers.",
        "(j) Let your health be taken care of.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Dinajpur",
    data: {
      questions:
        "(a) The government has almost completed the construction of the Padma Bridge. (Passive)<br/>(b) This is the largest bridge of Bangladesh. (Comparative degree)<br/>(c) The countrymen will be very happy when it will be opened for use. (Exclamatory)<br/>(d) It is a mega project. (Negative)<br/>(e) We should go to visit it. (Imperative)",
      answers: [
        "(a) The construction of the Padma Bridge has been almost completed by the government.",
        "(b) This is larger than any other bridge of Bangladesh.",
        "(c) How happy the countrymen will be when it will be opened for use!",
        "(d) It is not a small/mini project.",
        "(e) Let us go to visit it.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Cumilla",
    data: {
      questions:
        "(a) Very few conquerors of the world were so great as Taimur. (Superlative)<br/>(b) The province of a powerful prince was once attacked by young Taimur. (Active)<br/>(c) He captured a large village. (Passive)<br/>(d) The army killed Taimur's all soldiers. (Negative)<br/>(e) He did not disguise himself as a rich traveller to survive. (Affirmative)",
      answers: [
        "(a) Taimur was one of the greatest conquerors of the world.",
        "(b) Once young Taimur attacked the province of a powerful prince.",
        "(c) A large village was captured by him.",
        "(d) The army did not leave Taimur's any soldiers.",
        "(e) He disguised himself as a poor traveler to survive.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Chattogram",
    data: {
      questions:
        "(a) Computer is one of the greatest inventions of modern science. (Positive)<br/>(b) Computer is a blessing on earth. (Negative)<br/>(c) We must learn how to use computer. (Imperative)<br/>(d) Computer helps us a lot. (Passive)<br/>(e) Because of its usefulness, it has become very popular. (Exclamatory)",
      answers: [
        "(a) Very few inventions of modern science are as great as computer.",
        "(b) Computer is not a curse on earth.",
        "(c) Let us learn how to use computer.",
        "(d) We are helped a lot by computer.",
        "(e) How popular it has become because of its usefulness!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Dhaka",
    data: {
      questions:
        "(a) Computer is one of the greatest inventions of modern science. (Positive)<br/>(b) In fact, it is a blessing of science. (Negative without changing the original meaning)<br/>(c) It has facilitated the world very greatly. (Exclamatory)<br/>(d) Moreover, it has lessened our workloads. (Passive)<br/>(e) So, we should use it in our everyday life. (Imperative)",
      answers: [
        "(a) Very few inventions of modern science are as great as computer.",
        "(b) In fact, it is not a curse of science.",
        "(c) How greatly it has facilitated the world!",
        "(d) Moreover, our workloads have been lessened by it.",
        "(e) So, let us use it in our everyday life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Jashore",
    data: {
      questions:
        "(a) The freedom fighters are considered to be the real heroes of our country. (Active)<br/>(b) Their contribution will never be forgotten. (Affirmative)<br/>(c) Their sacrifice is greater than any other thing. (Positive)<br/>(d) By taking proper steps, we can improve their condition. (Negative)<br/>(e) We must show proper respect to them. (Passive)",
      answers: [
        "(a) We consider the freedom fighters to be the real heroes of our country.",
        "(b) Their contribution will always be remembered.",
        "(c) No other thing is as great as their sacrifice.",
        "(d) Without taking proper steps, we cannot improve their condition.",
        "(e) Proper respect must be shown to them.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Only you can do the work. (Negative)<br/>(b) No other friend is as great as books. (Superlative)<br/>(c) The rose is a very nice flower. (Exclamatory)<br/>(d) We should be patriots. (Imperative)<br/>(e) He called it laurel. (Passive)",
      answers: [
        "(a) None but you can do the work.",
        "(b) Books are the greatest friend.",
        "(c) What a nice flower the rose is!",
        "(d) Let us be patriots.",
        "(e) It was called laurel by him.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Mymensingh",
    data: {
      questions:
        "(a) Computer is one of the greatest inventions of modern science. (Positive)<br/>(b) In fact, it is a blessing of science. (Negative without changing the original meaning)<br/>(c) It has facilitated the world very greatly. (Exclamatory)<br/>(d) Moreover, it has lessened our workloads. (Passive)<br/>(e) So, we should use it in our everyday life. (Imperative)",
      answers: [
        "(a) Very few inventions of modern science are as great as computer.",
        "(b) In fact, it is not a curse of science.",
        "(c) How greatly it has facilitated the world!",
        "(d) Moreover, our workloads have been lessened by it.",
        "(e) So, let us use it in our everyday life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Dhaka",
    data: {
      questions:
        "(a) Once upon a time, there was a little girl named Tarin. (Compound)<br/>(b) Though she was a nice little girl, she was not an ordinary child. (Simple)<br/>(c) She passed her time in reading and writing. (Interrogative)<br/>(d) Her parents liked her very much. (Negative)<br/>(e) Everyone praised her. (Passive)<br/>(f) She was very attentive to her study. (Exclamatory)<br/>(g) She also helped her mother in her free time. (Complex)<br/>(h) She never told a lie. (Interrogative)<br/>(i) She was one of the most intelligent girls in the school. (Positive)<br/>(j) She worked hard to shine in life. (Complex)",
      answers: [
        "(a) Once upon a time, there was a little girl, and her name was Tarin.",
        "(b) In spite of being a nice little girl, she was not an ordinary child.",
        "(c) Didn’t she pass her time in reading and writing?",
        "(d) Her parents did not dislike her at all.",
        "(e) She was praised by everyone.",
        "(f) How attentive she was to her study!",
        "(g) She also helped her mother when she had free time.",
        "(h) Did she ever tell a lie?",
        "(i) Very few girls in the school were as intelligent as she.",
        "(j) She worked hard so that she could shine in life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Barishal",
    data: {
      questions:
        "(a) Man is the maker of his own fortune. (Interrogative)<br/>(b) If he makes a proper use of his time, he is sure to prosper in life. (Simple)<br/>(c) The person doing otherwise is sure to repent later. (Complex)<br/>(d) The lazy suffer miserably in the long run. (Exclamatory)<br/>(e) To kill time is to commit suicide. (Interrogative)<br/>(f) Our life is nothing but a sum total of hours, days and years. (Assertive)<br/>(g) Youth is the most valuable season of life. (Positive)<br/>(h) In youth, mind is soft and it can be shaped easily. (Simple)<br/>(i) Unless you use the morning hours of life, you have to pay a heavy price afterwards. (Compound)<br/>(j) It is called the seedtime of life. (Active)",
      answers: [
        "(a) Isn’t man the maker of his own fortune?",
        "(b) By making proper use of his time, he is sure to prosper in life.",
        "(c) The person who does otherwise is sure to repent later.",
        "(d) How miserably the lazy suffer in the long run!",
        "(e) Isn’t to kill time to commit suicide?",
        "(f) Our life is only the sum total of hours, days, and years.",
        "(g) No other season of life is as valuable as youth.",
        "(h) In youth, the soft mind can be shaped easily.",
        "(i) Use the morning hours of life, or you have to pay a heavy price afterwards.",
        "(j) People call it the seedtime of life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Chattogram",
    data: {
      questions:
        "(a) Wherever we may cast our eyes, we notice the achievement of science. (Simple)<br/>(b) The electricity lights both the streets and the houses. (Negative)<br/>(c) The radio broadcasts news, songs and lectures. (Passive)<br/>(d) There is cinema to delight in the evening. (Complex)<br/>(e) Computer is one of the most important inventions of modern science. (Positive)<br/>(f) Who can go without it? (Assertive)<br/>(g) Internet is as important as computer. (Comparative)<br/>(h) It helps us to know about the world. (Compound)<br/>(i) It is greater than all other inventions of modern science. (Superlative)<br/>(j) The invention of computer is a great miraculous event. (Exclamatory)",
      answers: [
        "(a) We notice the achievement of science everywhere.",
        "(b) The electricity does not light only the streets but also the houses.",
        "(c) News, songs, and lectures are broadcast by the radio.",
        "(d) When it is evening, there is cinema to delight.",
        "(e) Very few inventions of modern science are as important as computer.",
        "(f) None can go without it.",
        "(g) Internet is not less important than computer.",
        "(h) It helps us, and we know about the world.",
        "(i) It is the greatest of all inventions of modern science.",
        "(j) What a great miraculous event the invention of computer is!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Cumilla",
    data: {
      questions:
        "(a) Health is wealth. (Complex)<br/>(b) A healthy poor man is happier than a sick moneyed man. (Positive)<br/>(c) Though a healthy man is an asset to his family, an unhealthy man is a liability. (Compound)<br/>(d) He can succeed in life. (Interrogative)<br/>(e) So, everybody cannot but be conscious of his health. (Affirmative)<br/>(f) Everybody must take care of his health all the time. (Negative)<br/>(g) Health can be improved by regular physical exercise and a balanced diet. (Active)<br/>(h) People who are poor cannot afford to take a balanced diet. (Simple)<br/>(i) They are very concerned with the quantity of food. (Exclamatory)<br/>(j) Everybody should know it that malnutrition causes weakness. (Passive)",
      answers: [
        "(a) It is health which is wealth.",
        "(b) A sick moneyed man is not as happy as a healthy poor man.",
        "(c) A healthy man is an asset to his family, but an unhealthy man is a liability.",
        "(d) Can’t he succeed in life?",
        "(e) So, everybody must be conscious of his health.",
        "(f) Everybody cannot but take care of his health all the time.",
        "(g) Regular physical exercise and a balanced diet can improve health.",
        "(h) Poor people cannot afford to take a balanced diet.",
        "(i) How concerned they are with the quantity of food!",
        "(j) It should be known to everybody that weakness is caused by malnutrition.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Mymensingh",
    data: {
      questions:
        "(a) Cricket is a very exciting game. (Exclamatory)<br/>(b) People of all ages enjoy this game. (Passive)<br/>(c) It is played all over the world. (Active)<br/>(d) At present, it is the most popular game in our country. (Comparative)<br/>(e) Though cricket is a costly game, people of all classes enjoy playing it. (Simple)<br/>(f) The game is played between two teams each consisting of eleven players. (Complex)<br/>(g) There are two umpires who conduct the game. (Simple)<br/>(h) It is full of thrill and excitement for the spectators. (Interrogative)<br/>(i) Bangladesh is a test-playing country developing its standard day by day. (Compound)<br/>(j) We must try our best to improve its present position. (Negative)",
      answers: [
        "(a) What an exciting game cricket is!",
        "(b) This game is enjoyed by people of all ages.",
        "(c) People all over the world play it.",
        "(d) At present, it is more popular than any other game in our country.",
        "(e) Despite being a costly game, people of all classes enjoy playing cricket.",
        "(f) The game is played between two teams, each of which consists of eleven players.",
        "(g) Two umpires conduct the game.",
        "(h) Isn’t it full of thrill and excitement for the spectators?",
        "(i) Bangladesh is a test-playing country, and it is developing its standard day by day.",
        "(j) We cannot but try our best to improve its present position.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Sylhet",
    data: {
      questions:
        "(a) Haji Mohammad Mohsin was more gracious than any other man in this subcontinent. (Positive)<br/>(b) He was born in Hoogli. (Complex)<br/>(c) He inherited a vast property from his father and sister. (Interrogative)<br/>(d) He did not misuse this wealth. (Passive)<br/>(e) He is called a friend of humanity. (Active)<br/>(f) He did not marry. (Affirmative)<br/>(g) During his lifetime, he spent money lavishly to help the poor. (Compound)<br/>(h) He was very kind to the poor. (Negative)<br/>(i) One day when a thief entered his room, he caught him. (Simple)<br/>(j) He caught the thief but did not punish him. (Complex)",
      answers: [
        "(a) No other man in this subcontinent was as gracious as Haji Mohammad Mohsin.",
        "(b) It was Hoogli where he was born.",
        "(c) Didn’t he inherit a vast property from his father and sister?",
        "(d) This wealth was not misused by him.",
        "(e) People call him a friend of humanity.",
        "(f) He remained unmarried.",
        "(g) During his lifetime, he spent money lavishly, and he helped the poor.",
        "(h) He was not unkind to the poor at all.",
        "(i) One day, he caught a thief entering his room.",
        "(j) Though he caught the thief, he did not punish him.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Terrorism is a devastating phenomenon of the modern world. (Exclamatory)<br/>(b) At present, it is called a challenge to fight against it. (Active)<br/>(c) Who is not now in the threat of violence? (Assertive)<br/>(d) Terrorism is more disastrous than anything. (Positive)<br/>(e) It is one of the most corrosive problems of the modern world. (Comparative)<br/>(f) Nobody wants his children to be terrorist in future. (Interrogative)<br/>(g) Though there is law to punish the terrorists, it is not properly applied. (Simple)<br/>(h) By applying the law properly, we can get rid of it. (Complex)<br/>(i) We have to create social awareness to fight against corruption. (Compound)<br/>(j) We all should avoid the killers of mankind. (Negative)",
      answers: [
        "(a) What a devastating phenomenon of the modern world terrorism is!",
        "(b) At present, people call it a challenge to fight against it.",
        "(c) Everyone is now in the threat of violence.",
        "(d) Nothing is as disastrous as terrorism.",
        "(e) It is more corrosive than most other problems of the modern world.",
        "(f) Who wants his children to be terrorists in the future?",
        "(g) Despite the law to punish the terrorists, it is not properly applied.",
        "(h) If we apply the law properly, we can get rid of it.",
        "(i) We have to create social awareness, and we must fight against corruption.",
        "(j) None of us should mix with the killers of mankind.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "ssc",
    year: 2019,
    board: "Dhaka",
    data: {
      questions:
        "(a) Man is the best creation of God. (Comparative)<br/>(b) Isn't it our responsibility to do good deeds? (Assertive)<br/>(c) Our life is not measured by months or years. (Active)<br/>(d) Honest people lead a happy life. (Complex)<br/>(e) It matters little if a man lives many years or not. (Interrogative)<br/>(f) Nobody is absolutely happy on the earth. (Affirmative)<br/>(g) So, we should not waste time in vain. (Passive)<br/>(h) If we use time properly, we can be benefited. (Simple)<br/>(i) All men must die. (Negative)<br/>(j) Though we take utmost care, we cannot avoid death. (Compound)",
      answers: [
        "(a) Man is better than any other creation of God.",
        "(b) It is our responsibility to do good deeds.",
        "(c) We do not measure our life by months or years.",
        "(d) People who are honest lead a happy life.",
        "(e) Doesn’t it matter little if a man lives many years or not?",
        "(f) Everybody is not absolutely happy on the earth.",
        "(g) So, time should not be wasted by us in vain.",
        "(h) By using time properly, we can be benefited.",
        "(i) No man can escape death.",
        "(j) We take utmost care, but we cannot avoid death.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Barishal",
    data: {
      questions:
        "(a) Internet is a computer-based networking system. (Interrogative)<br/>(b) It is a speedy transmitting system of information. (Complex)<br/>(c) Its functions are smooth and rapid. (Negative)<br/>(d) A man has an internet connection and gets a link soon according to his expectation. (Simple)<br/>(e) Many educational institutions are greatly benefited through the use of internet. (Complex)<br/>(f) A student can visit all the renowned libraries of the world without going there. (Passive)<br/>(g) It plays an effective role in the field of trade and commerce. (Exclamatory)<br/>(h) E-commerce has become one of the most popular topics to the customers. (Positive)<br/>(i) It helps the customers to buy or choose anything without going to market. (Compound)<br/>(j) What an amazing milestone it is in the modern world of communication! (Assertive)",
      answers: [
        "(a) Isn’t internet a computer-based networking system?",
        "(b) It is a transmitting system of information which is speedy.",
        "(c) Its functions are not unsmooth or slow.",
        "(d) A man with an internet connection gets a link soon according to his expectation.",
        "(e) Many educational institutions which use the internet are greatly benefited.",
        "(f) All the renowned libraries of the world can be visited by a student without going there.",
        "(g) What an effective role it plays in the field of trade and commerce!",
        "(h) Very few topics have become as popular to the customers as e-commerce.",
        "(i) It helps the customers, and they can buy or choose anything without going to market.",
        "(j) It is an amazing milestone in the modern world of communication.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Chattogram",
    data: {
      questions:
        "(a) Haji Mohammad Mohsin was a kind man. (Negative)<br/>(b) He did not marry. (Affirmative)<br/>(c) He loved the people cordially. (Passive)<br/>(d) He never thought of his own happiness. (Interrogative)<br/>(e) He led a very simple life. (Exclamatory)<br/>(f) He always helped the needy. (Complex)<br/>(g) He contributed much money for education to educate the poor students. (Complex)<br/>(h) Though he had a vast wealth, he didn't spend for his own. (Compound)<br/>(i) Who does not know his kindness? (Assertive)<br/>(j) He was one of the greatest kind men of the world. (Positive)",
      answers: [
        "(a) Haji Mohammad Mohsin was not an unkind man.",
        "(b) He remained unmarried.",
        "(c) The people were loved cordially by him.",
        "(d) Did he ever think of his own happiness?",
        "(e) What a simple life he led!",
        "(f) He always helped those who were needy.",
        "(g) He contributed much money for education so that he could educate the poor students.",
        "(h) He had a vast wealth, but he didn’t spend for his own.",
        "(i) Everybody knows his kindness.",
        "(j) Very few kind men in the world were as great as he.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Cumilla",
    data: {
      questions:
        "(a) Computer is one of the greatest inventions of modern science. (Positive)<br/>(b) Computer is a blessing on earth. (Negative)<br/>(c) Though it is a blessing, it has dark sides. (Simple)<br/>(d) Computers are now-a-days being used in almost every sphere of life. (Active)<br/>(e) We cannot but depend on it. (Affirmative)<br/>(f) No one can deny its necessity. (Interrogative)<br/>(g) It is the most used device in our life. (Comparative)<br/>(h) It helps us a lot. (Passive)<br/>(i) Because of its usefulness, it has become very popular. (Compound)<br/>(j) Without computer, we cannot imagine our modern life. (Complex)",
      answers: [
        "(a) Very few inventions of modern science are as great as computer.",
        "(b) Computer is not a curse on earth.",
        "(c) In spite of its being a blessing, it has dark sides.",
        "(d) Nowadays, people are using computers in almost every sphere of life.",
        "(e) We must depend on it.",
        "(f) Who can deny its necessity?",
        "(g) It is more used than any other device in our life.",
        "(h) We are helped a lot by it.",
        "(i) It is very useful, and so it has become very popular.",
        "(j) It is computer without which we cannot imagine our modern life.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Patriotism is a noble virtue. (Interrogative)<br/>(b) It is the greatest of all virtues in a man's life. (Comparative)<br/>(c) It persuades a man to do everything just. (Negative)<br/>(d) This quality highly motivates a man so that he can sacrifice his life for the country. (Simple)<br/>(e) What an outstanding quality it is! (Assertive)<br/>(f) A man having patriotic zeal is called a patriot. (Complex)<br/>(g) A patriot fears none but the creator. (Affirmative)<br/>(h) By paying taxes he obeys the law. (Compound)<br/>(i) He is respected by all. (Active)<br/>(j) So, we should be patriots. (Imperative)",
      answers: [
        "(a) Isn’t patriotism a noble virtue?",
        "(b) It is greater than all other virtues in a man’s life.",
        "(c) It does not persuade a man to do everything unjust.",
        "(d) This quality highly motivates a man to sacrifice his life for the country.",
        "(e) It is a very outstanding quality.",
        "(f) A man who has patriotic zeal is called a patriot.",
        "(g) A patriot fears only the Creator.",
        "(h) He pays taxes and obeys the law.",
        "(i) All respect him.",
        "(j) So, let us be patriots.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Sylhet",
    data: {
      questions:
        "(a) Corruption is one of the worst evils. (Positive)<br/>(b) A corrupted man can do anything against morality. (Complex)<br/>(c) People hate a corrupted man. (Passive)<br/>(d) Nobody respects him. (Interrogative)<br/>(e) The man who takes bribe is next to devil. (Simple)<br/>(f) Though we have strict law, we are still affected by this evil. (Compound)<br/>(g) No other person is as hated as a corrupted man. (Superlative)<br/>(h) We hope that Bangladesh will be free from this evil. (Simple)<br/>(i) Everybody avoids a corrupted man. (Negative)<br/>(j) A corrupted man leads a very unhappy life. (Exclamatory)",
      answers: [
        "(a) Very few evils are as bad as corruption.",
        "(b) A man who is corrupted can do anything against morality.",
        "(c) A corrupted man is hated by people.",
        "(d) Who respects him?",
        "(e) The man taking bribe is next to devil.",
        "(f) We have strict law, but we are still affected by this evil.",
        "(g) A corrupted man is the most hated person.",
        "(h) We hope Bangladesh to be free from this evil.",
        "(i) There is nobody but avoids a corrupted man.",
        "(j) What an unhappy life a corrupted man leads!",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Jashore",
    data: {
      questions:
        "(a) Terrorism is a devastating phenomenon of the modern world. (Exclamatory)<br/>(b) At present, it is increasing alarmingly. (Interrogative)<br/>(c) Nothing is as disastrous as terrorism. (Comparative)<br/>(d) It is one of the most corrosive problems of the modern world. (Positive)<br/>(e) A terrorist is more ferocious than any other criminal. (Superlative)<br/>(f) The people who are terrorist do not care for humanity. (Simple)<br/>(g) The terrorist cannot lead a normal life. (Affirmative)<br/>(h) We must resist them. (Passive)<br/>(i) Who does not want to live in peace? (Assertive)<br/>(j) We should work together to fight against terrorism. (Imperative)",
      answers: [
        "(a) What a devastating phenomenon of the modern world terrorism is!",
        "(b) Isn't it increasing alarmingly at present?",
        "(c) Terrorism is more disastrous than anything else.",
        "(d) Very few problems of the modern world are as corrosive as terrorism.",
        "(e) A terrorist is the most ferocious criminal.",
        "(f) The terrorist people do not care for humanity.",
        "(g) The terrorist can only lead an abnormal life.",
        "(h) They must be resisted by us.",
        "(i) Everybody wants to live in peace.",
        "(j) Let us work together to fight against terrorism.",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "ssc",
    year: 2015,
    board: "Dhaka",
    data: {
      questions:
        "(a) Television is one of the most wonderful inventions of modern science. (Positive)<br/>(b) It was not invented overnight. (Active)<br/>(c) Scientists spent many years and worked hard to invent television. (Complex)<br/>(d) Nowadays, almost every family has a television set. (Negative)<br/>(e) People of all ages like to watch television. (Interrogative)<br/>(f) The programmes telecast by television are very interesting. (Complex)<br/>(g) Television should telecast educative programmes. (Passive)<br/>(h) If you watch television, you can learn many things. (Simple)<br/>(i) People spend their free time by watching television. (Compound)<br/>(j) Very few things are so useful as television. (Superlative)",
      answers: [
        "(a) Very few inventions of modern science are as wonderful as television.",
        "(b) Scientists did not invent it overnight.",
        "(c) Scientists spent many years and worked hard so that they could invent television.",
        "(d) Nowadays, there is no family without a television set.",
        "(e) Don't the people of all ages like to watch television?",
        "(f) The programmes which are telecast by television are very interesting.",
        "(g) Educative programmes should be telecast by television.",
        "(h) By watching television you can learn many things.",
        "(i) People watch television and spend their free time.",
        "(j) Television is one of the most useful things.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Chittagong",
    data: {
      questions:
        "(a) My friend invited me to pay a visit to Cox's Bazar. (Complex)<br/>(b) I was very glad. (Negative)<br/>(c) I accepted the invitation. (Passive)<br/>(d) When I reached there, my friend received me cordially. (Simple)<br/>(e) I was excited to see the sea-beach. (Exclamatory)<br/>(f) It is the largest sea-beach in the world. (Comparative)<br/>(g) It is one of the most beautiful sea-beaches in the world. (Positive)<br/>(h) It is called the pleasure seekers' paradise. (Active)<br/>(i) Every year a lot of people come to visit it. (Compound)<br/>(j) If I could visit the sea-beach! (Active)",
      answers: [
        "(a) My friend invited me so that I could pay a visit to Cox's Bazar.",
        "(b) Wasn't I very glad?",
        "(c) The invitation was accepted by me.",
        "(d) My friend received me cordially after my reaching there.",
        "(e) How excited I was to see the sea-beach!",
        "(f) It is larger than any other sea-beach in the world.",
        "(g) Very few sea-beaches in the world are as beautiful as it.",
        "(h) People call it the pleasure seekers' paradise.",
        "(i) Every year a lot of people come and visit it.",
        "(j) I wish I could visit the sea-beach.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Rajshahi",
    data: {
      questions:
        "(a) A flower is a glowing gift of nature. (Interrogative)<br/>(b) Isn't it the symbol of love and beauty? (Affirmative)<br/>(c) Flowers are used on different occasions. (Active)<br/>(d) We present flower to our nearest and dearest person. (Passive)<br/>(e) We need flowers to decorate a place. (Complex)<br/>(f) The rose is the best of all flowers. (Positive)<br/>(g) Having sweet scent and beauty we love it very much. (Compound)<br/>(h) It is lovelier than all other flowers. (Superlative)<br/>(i) The rose is a very nice flower. (Exclamatory)<br/>(j) As the demand for flowers is increasing day by day we should cultivate flower on commercial basis. (Simple)",
      answers: [
        "(a) Isn't a flower a glowing gift of nature?",
        "(b) It is the symbol of love and beauty.",
        "(c) People use flowers on different occasions.",
        "(d) Flower is presented to our nearest and dearest persons by us.",
        "(e) We need flowers so that we can decorate a place.",
        "(f) No other flower is as good as the rose.",
        "(g) A flower has sweet scent and beauty and we love it very much.",
        "(h) It is the loveliest of all flowers.",
        "(i) How nice a flower the rose is!",
        "(j) Because of increasing the demand for flowers day by day, we should cultivate flowers on commercial basis.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Barisal",
    data: {
      questions:
        "(a) Haji Mohammad Muhsin was not an unkind man at all. (Affirmative)<br/>(b) He inherited vast property from his father and sister. (Interrogative)<br/>(c) He was unmarried. (Negative)<br/>(d) During his lifetime, he spent money lavishly to help the poor. (Complex)<br/>(e) One night when he was saying his prayer, a thief broke into his room. (Simple)<br/>(f) Seeing Muhsin the thief cried. (Compound)<br/>(g) The thief was caught. (Active)<br/>(h) How needy the thief was! (Assertive)<br/>(i) He gave the thief some food and money. (Passive)<br/>(j) Muhsin was one of the best philanthropists in the world. (Positive)",
      answers: [
        "(a) Haji Mohammad Muhsin was a very kind man.",
        "(b) Didn't he inherit vast property from his father and sister?",
        "(c) He was not married.",
        "(d) As long as he was alive, he spent money lavishly to help the poor.",
        "(e) One night at the time of saying his prayer, a thief broke into his room.",
        "(f) The thief saw Muhsin and cried.",
        "(g) He caught the thief.",
        "(h) The thief was very needy.",
        "(i) The thief was given food and money by him.",
        "(j) Very few philanthropists in the world were as good as Muhsin.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Sylhet",
    data: {
      questions:
        "(a) The students studying regularly can expect a good result. (Make it a complex sentence)<br/>(b) But most of our students are inattentive to their studies. (Make it a negative sentence without changing the meaning)<br/>(c) They waste their valuable time idly. (Use passive voice)<br/>(d) Wasting time is harmful for them. (Make it an interrogative sentence)<br/>(e) By repeating this activity they make a poor result. (Make it a complex sentence)<br/>(f) Who loves them then? (Make it an assertive sentence without changing the original meaning)<br/>(g) They are treated badly even by their family members. (Use active voice)<br/>(h) If a student fails in the examination, he suffers from inferiority complex. (Make simple sentence)<br/>(i) No other student in the class is as bad as a failed student. (Use superlative)<br/>(j) So a student should be aware of studying regularly and attentively so that he can do well in the examination. (Make it a simple sentence)",
      answers: [
        "(a) The students who are studying regularly can expect a good result.",
        "(b) But most of our students are not attentive to their studies.",
        "(c) Their valuable time is wasted idly by them.",
        "(d) Isn't wasting time harmful for them?",
        "(e) By repeating this activity they make a result which is poor.",
        "(f) Nobody loves them then.",
        "(g) Even their family members treat them badly.",
        "(h) A student failing in the examination suffers from inferiority complex.",
        "(i) A failed student is the worst of all students in the class.",
        "(j) So a student should be aware of studying regularly and attentively to do well in the examination.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "(a) We should read books to acquire knowledge. (Make complex sentence)<br/>(b) Books introduce us to the realm of knowledge. (Use passive voice)<br/>(c) The books of great writers contain noble thoughts and great ideas. (Make interrogative sentence)<br/>(d) By reading good books, we can enrich our mind. (Make compound sentence)<br/>(e) Reading books is a very good habit. (Make exclamatory sentence)<br/>(f) This habit is rarely disliked. (Affirmative)<br/>(g) More and more books should be read. (Use active voice)<br/>(h) No other thing is as interesting as reading books. (Use comparative degree)<br/>(i) When we read good books, we discover new worlds. (Make simple sentence)<br/>(j) Very few friends are as great as a good book. (Make superlative degree)",
      answers: [
        "(a) We should read books so that we can acquire knowledge.",
        "(b) We are introduced to the realm of knowledge by books.",
        "(c) Do the books of great writers contain noble thoughts and great ideas?",
        "(d) We read good books, and we can enrich our mind.",
        "(e) What a very good habit reading books is!",
        "(f) This habit is generally liked.",
        "(g) We should read more and more books.",
        "(h) Reading books is more interesting than any other thing.",
        "(i) Reading good books helps us discover new worlds.",
        "(j) A good book is one of the greatest friends.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "(a) Once upon a time two friends were passing by a forest. (Make it complex sentence)<br/>(b) They were talking about their love for each other. (Make it interrogative meaning)<br/>(c) Suddenly they saw a bear which was coming towards them. (Make it simple sentence)<br/>(d) The first friend climbed up a tree. (Make it a complex sentence)<br/>(e) The later could not climb up a tree. (Make it an affirmative sentence)<br/>(f) He did not find any way. (Make it a passive voice)<br/>(g) He lay down on the ground and feigned death. (Make it a simple sentence)<br/>(h) The bear smelt his ears, nose and face. (Use passive voice)<br/>(i) He was thought to be dead. (Make it a complex sentence)<br/>(j) The bear went away and he escaped himself. (Make it a complex sentence)",
      answers: [
        "(a) Once upon a time, two friends were passing through a forest.",
        "(b) Were they talking about their love for each other?",
        "(c) Suddenly they saw a bear coming towards them.",
        "(d) The first friend, who was agile, climbed up a tree.",
        "(e) The latter was unable to climb up a tree.",
        "(f) No way was found by him.",
        "(g) Lying down on the ground, he feigned death.",
        "(h) His ears, nose, and face were smelt by the bear.",
        "(i) It was thought that he was dead.",
        "(j) After the bear went away, he escaped himself.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        '(a) William Wordsworth is one of the best well-known poets in English literature. (Positive)<br/>(b) He was the second of his father\'s five sons. (Negative)<br/>(c) He was born at Cumberland on April 4, 1770. (Complex)<br/>(d) When he was eight years old, his mother died. (Simple)<br/>(e) At the same year he was sent to the Grammar School of Hawkshead for education. (Compound)<br/>(f) He was only 13 years old when his father died. (Interrogative)<br/>(g) Fundamental education had been given to him at the school. (Active)<br/>(h) The education that he learnt from this institution played better role in his life. (Simple)<br/>(i) The readers called for a new edition of his famous book "The Lyrical Ballads" in 1800. (Passive)<br/>(j) This book brought a huge name and fame in his life. (Exclamatory)',
      answers: [
        "(a) Very few poets in English literature are as well-known as William Wordsworth.",
        "(b) He was not the first or third of his father's five sons.",
        "(c) William Wordsworth, who was born at Cumberland, came into the world on April 4, 1770.",
        "(d) At the age of eight, his mother died.",
        "(e) It was the same year, and he was sent to the Grammar School of Hawkshead for education.",
        "(f) Was he only 13 years old when his father died?",
        "(g) The school gave him fundamental education.",
        "(h) The education learnt from this institution played a better role in his life.",
        '(i) A new edition of his famous book "The Lyrical Ballads" was called for by the readers in 1800.',
        "(j) What a huge name and fame this book brought in his life!",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Cumilla",
    data: {
      questions:
        "(a) Mr. Rahim, one of my cousins, is a good teacher. (Complex)<br/>(b) He is older than I. (Positive degree)<br/>(c) He wants his students to be good citizens. (Complex)<br/>(d) He leaves no stone unturned to teach them morality. (Affirmative)<br/>(e) He becomes very happy when the students achieve good results in public examinations. (Exclamatory)<br/>(f) Mr. Rahim is not only punctual but also sincere. (Simple)<br/>(g) He is the best teacher in our area. (Negative)<br/>(h) He cannot remain sitting in the class. (Affirmative)<br/>(i) He goes to class after taking preparation. (Compound)<br/>(j) All the students respect him very much. (Passive)",
      answers: [
        "(a) Mr. Rahim, who is one of my cousins, is a good teacher.",
        "(b) I am not as old as he is.",
        "(c) He wants that his students should be good citizens.",
        "(d) He does everything to teach them morality.",
        "(e) How happy he becomes when the students achieve good results in public examinations!",
        "(f) Mr. Rahim is both punctual and sincere.",
        "(g) No other teacher in our area is as good as he is.",
        "(h) He remains active in the class.",
        "(i) He takes preparation and then goes to class.",
        "(j) He is respected very much by all the students.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Chattogram",
    data: {
      questions:
        "(a) Is there anybody who does not want to succeed in life? (Assertive)<br/>(b) Do you know it? (Passive)<br/>(c) An industrious man will shine in life. (Complex)<br/>(d) Hard work is needed for success. (Active)<br/>(e) A life with an assignment is an actual life. (Negative)<br/>(f) No one can receive any reward unless he works hard. (Simple)<br/>(g) One can't be successful without it. (Interrogative)<br/>(h) A successful man is very happy. (Exclamatory)<br/>(i) No other man is as happy as a successful man. (Superlative)<br/>(j) A hardworking man is healthier than an idle man. (Positive)",
      answers: [
        "(a) Everybody wants to succeed in life.",
        "(b) Is it known to you?",
        "(c) A man who is industrious will shine in life.",
        "(d) One needs to work hard for success.",
        "(e) A life without an assignment is not an actual life.",
        "(f) Without working hard, no one can receive any reward.",
        "(g) Can one be successful without it?",
        "(h) How happy a successful man is!",
        "(i) A successful man is the happiest man.",
        "(j) An idle man is not as healthy as a hardworking man.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "(a) Long time ago, there lived a young man called Ruplal. (Make compound sentence)<br/>(b) He lived with his family and worked on a farm. (Make interrogative sentence)<br/>(c) It was a beautiful place but there were a lot of problems. (Make complex sentence)<br/>(d) The village people were quarrelsome. (Make negative sentence)<br/>(e) Ruplal decided to go and live alone in the jungle in order to find peace. (Make complex sentence)<br/>(f) So he collected his things and went to live by himself. (Make simple sentence)<br/>(g) Ruplal made a nice little hut for himself in the jungle. (Use passive voice)<br/>(h) How happy I am now! (Make assertive sentence)<br/>(i) My jungle hut is one of the most peaceful places in the world. (Make positive degree)<br/>(j) That night, while Ruplal was sleeping, he heard a noise. (Make simple sentence)",
      answers: [
        "(a) A long time ago, a young man called Ruplal lived, and he was known for his simplicity.",
        "(b) Did he live with his family and work on a farm?",
        "(c) Although it was a beautiful place, there were a lot of problems.",
        "(d) The village people were not peace-loving.",
        "(e) Ruplal decided to go and live alone in the jungle so that he could find peace.",
        "(f) Collecting his things, he went to live by himself.",
        "(g) A nice little hut was made by Ruplal for himself in the jungle.",
        "(h) I am very happy now.",
        "(i) Very few places in the world are as peaceful as my jungle hut.",
        "(j) That night, while sleeping, Ruplal heard a noise.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Jessore",
    data: {
      questions:
        "(a) Corruption is one of the worst evils. (Positive)<br/>(b) A corrupted man can do anything against morality. (Complex)<br/>(c) People hate a corrupted man. (Passive)<br/>(d) Nobody respects him. (Interrogative)<br/>(e) The man who takes bribe is next to devil. (Simple)<br/>(f) Though we have strict law, we are still affected by this evil. (Compound)<br/>(g) No other person is as hated as a corrupted man. (Superlative)<br/>(h) We hope that Bangladesh will be free from this evil. (Simple)<br/>(i) Everybody avoids a corrupted man. (Negative)<br/>(j) A corrupted man leads a very unhappy life. (Exclamatory)",
      answers: [
        "(a) Very few evils are as bad as corruption.",
        "(b) A man who is corrupted can do anything against morality.",
        "(c) A corrupted man is hated by people.",
        "(d) Who respects him?",
        "(e) The man taking bribe is next to devil.",
        "(f) We have strict law, but we are still affected by this evil.",
        "(g) A corrupted man is the most hated person.",
        "(h) We hope for Bangladesh to be free from this evil.",
        "(i) Nobody associates with a corrupted man.",
        "(j) What an unhappy life a corrupted man leads!",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        '(a) Mother Teresa is an icon to many people. (Interrogative)<br/>(b) She is respected by everybody. (Active)<br/>(c) She is one of the greatest persons of the world. (Positive)<br/>(d) She was very kind to the needy and the ill-fated. (Negative)<br/>(e) She believes that charity is a great virtue. (Compound)<br/>(f) Actually, Mother Teresa was a noble-hearted person. (Complex)<br/>(g) Mother Teresa was a very passionate woman. (Exclamatory)<br/>(h) She helped those who were helpless. (Simple)<br/>(i) She set up "Nirmal Hridoy" at Kolkata. (Compound)<br/>(j) Who does not know about the charity of Mother Teresa? (Assertive)',
      answers: [
        "(a) Isn't Mother Teresa an icon to many people?",
        "(b) Everybody respects her.",
        "(c) Very few persons of the world are as great as she.",
        "(d) She was not at all unkind to the needy and the ill-fated.",
        "(e) Charity is a great virtue, and she believes it.",
        "(f) There is no denying the fact that Mother Teresa was a noble-hearted person.",
        "(g) What a passionate woman Mother Teresa was!",
        "(h) She helped the helpless.",
        '(i) She set up "Nirmal Hridoy," and it was at Kolkata.',
        "(j) Everybody knows about the charity of Mother Teresa.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "(a) My friend invited me to pay a visit to Cox's Bazar. (Complex)<br/>(b) I was very glad. (Negative)<br/>(c) I accepted the invitation. (Passive)<br/>(d) When I reached there, my friend received me cordially. (Simple)<br/>(e) I was very excited to see the sea-beach. (Exclamatory)<br/>(f) It is the largest sea-beach in the world. (Positive)<br/>(g) It is one of the most beautiful sea-beaches in the world. (Comparative)<br/>(h) It is called the pleasure seekers' paradise. (Active)<br/>(i) Every year a lot of people come to visit it. (Compound)<br/>(j) If I could visit the sea-beach! (Assertive)",
      answers: [
        "(a) My friend invited me so that I could pay a visit to Cox's Bazar.",
        "(b) I was not unhappy/sad at all.",
        "(c) The invitation was accepted by me.",
        "(d) Reaching there, my friend received me cordially.",
        "(e) How excited I was to see the sea-beach!",
        "(f) No other sea-beach in the world is as large as it.",
        "(g) It is more beautiful than most other sea-beaches in the world.",
        "(h) People call it the pleasure seekers' paradise.",
        "(i) Every year a lot of people come and visit it.",
        "(j) I wish I could visit the sea-beach.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dinajpur",
    data: {
      questions:
        "(a) We are grateful to the freedom fighters. (Negative)<br/>(b) Their contribution is greater than any other thing. (Positive)<br/>(c) The freedom fighters who died in the liberation war are called martyrs. (Compound)<br/>(d) The National Memorial has been built with a view to paying tribute to their memories. (Complex)<br/>(e) A freedom fighter is the greatest son of the soil. (Comparative)<br/>(f) We got our independence for their sacrifice. (Interrogative)<br/>(g) They fought bravely and snatched the red sun of independence. (Simple)<br/>(h) Though their weapons were ordinary, they had much courage in their mind. (Compound)<br/>(i) Their contribution will never be forgotten. (Affirmative)<br/>(j) The government has taken some steps to improve their condition. (Passive)",
      answers: [
        "(a) We are not ungrateful to the freedom fighters.",
        "(b) No other thing is as great as their contribution.",
        "(c) The freedom fighters died in the liberation war, and they are called martyrs.",
        "(d) The National Memorial has been built so that we can pay tribute to their memories.",
        "(e) A freedom fighter is greater than any other son of the soil.",
        "(f) Didn't we get our independence for their sacrifice?",
        "(g) Fighting bravely, they snatched the red sun of independence.",
        "(h) Their weapons were ordinary, but they had much courage in their mind.",
        "(i) Their contribution will always be remembered.",
        "(j) Some steps have been taken to improve their condition by the government.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Jashore",
    data: {
      questions:
        "(a) Strategy is the most important thing in the examination. (Comparative)<br/>(b) Any answer in the exam should not be elaborated. (Active)<br/>(c) When he gets the question paper, he should read it carefully. (Simple)<br/>(d) At first glance, the questions may seem difficult. (Negative)<br/>(e) A student should attempt to answer all the questions to get good marks. (Complex)<br/>(f) If an examinee answers all the questions, the examiner becomes glad to see that. (Simple)<br/>(g) But it is better than not answering at all. (Positive)<br/>(h) It is really sensible. (Exclamatory)<br/>(i) The examinee should not waste time by doing it. (Passive)<br/>(j) Without following this process, you cannot bring a good result in an examination. (Compound)",
      answers: [
        "(a) Strategy is more important than any other thing in the examination.",
        "(b) The examinee should not elaborate any answer in the exam.",
        "(c) Getting the question paper, he should read it carefully.",
        "(d) At first glance, the questions may not seem easy.",
        "(e) A student should attempt to answer all the questions so that he may get good marks.",
        "(f) The examiner becomes glad to see an examinee answering all the questions.",
        "(g) Not answering at all is not as good as it.",
        "(h) How sensible it is!",
        "(i) Time should not be wasted by the examinee by doing it.",
        "(j) Follow this process, or you cannot bring a good result in an examination.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Sylhet",
    data: {
      questions:
        "(a) We should read books to gain knowledge. (Complex)<br/>(b) Books introduce us to the realm of knowledge. (Passive)<br/>(c) The books of great writers contain noble thoughts and great ideas. (Interrogative)<br/>(d) If we read books, we can enrich our minds. (Simple)<br/>(e) Books are the greatest friends. (Positive)<br/>(f) They give us both knowledge and pleasure. (Negative)<br/>(g) As they are our real friends, they remain with us in time of danger. (Compound)<br/>(h) Some books are very interesting. (Exclamatory)<br/>(i) We can build up a developed society by reading books. (Complex)<br/>(j) Nothing but books can remove the darkness of ignorance. (Affirmative)",
      answers: [
        "(a) We should read books so that we can gain knowledge.",
        "(b) We are introduced to the realm of knowledge by books.",
        "(c) Don't the books of great writers contain noble thoughts and great ideas?",
        "(d) By reading books, we can enrich our minds.",
        "(e) No other friends are as great as books.",
        "(f) They give us not only knowledge but also pleasure.",
        "(g) They are our real friends, and they remain with us in time of danger.",
        "(h) How interesting some books are!",
        "(i) If we read books, we can build up a developed society.",
        "(j) Only books can remove the darkness of ignorance.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Chattogram",
    data: {
      questions:
        "(a) Who does not want to succeed in life? (Assertive)<br/>(b) It is not an easy thing. (Affirmative)<br/>(c) Being industrious, everyone can prosper in life. (Negative)<br/>(d) The idle always lag behind. (Complex)<br/>(e) We must work hard so that we can earn money. (Simple)<br/>(f) By working hard, we can improve our lot. (Compound)<br/>(g) The light of prosperity can be seen by a hard-working person. (Active)<br/>(h) Women should work as much as men. (Comparative)<br/>(i) We should remember that industry is the key to success. (Passive)<br/>(j) An idle man leads a very miserable life. (Exclamatory)",
      answers: [
        "(a) Everybody wants to succeed in life.",
        "(b) It is a difficult thing.",
        "(c) Without being industrious, no one can prosper in life.",
        "(d) The people who are idle always lag behind.",
        "(e) We must work hard to earn money.",
        "(f) We work hard, and we can improve our lot.",
        "(g) A hard-working person can see the light of prosperity.",
        "(h) Women should not work less than men do.",
        "(i) That industry is the key to success should be remembered by us.",
        "(j) What a miserable life an idle man leads!",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Cumilla",
    data: {
      questions:
        "(a) Some essential agricultural inputs are to be ensured to increase our food production. (Active)<br/>(b) The farmers who are poor do not get loan on easy terms. (Simple)<br/>(c) What a pity! (Assertive)<br/>(d) The farmers do not get the facilities necessary for food production. (Complex)<br/>(e) Unfortunately, they do not get the due price of their products. (Compound)",
      answers: [
        "(a) We must ensure some essential agricultural inputs to increase our food production.",
        "(b) The poor farmers do not get loan on easy terms.",
        "(c) It is a great pity.",
        "(d) The farmers do not get the facilities that are necessary for food production.",
        "(e) Unfortunately, they do not get the due price of their products, and they suffer.",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
];
