export const sscRightFormsOfVerbs = [
  {
    exam: "ssc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "Our annual prize giving ceremony (a) ------ off yesterday. We (b) ------ our school campus very nicely. The ceremony (c) ------ at 3 p.m. Our Headmaster (d) ------ over the function and the Education Minister (e) ------ the chief guest. The function (f) ------ with the recitation from the Holy Quran. One of our senior teachers (g) ------ out the annual report. The honourable chief guest (h) ------ a brief encouraging speech (i) ------ us to be regular in studies and (j) ------ part in the movement against illiteracy.",
      options: [
        "deliver",
        "take",
        "start",
        "preside",
        "be",
        "advise",
        "decorate",
        "begin",
        "come",
        "read",
      ],
      answers: [
        "(a) came",
        "(b) decorated",
        "(c) started",
        "(d) presided",
        "(e) was",
        "(f) began",
        "(g) read",
        "(h) delivered",
        "(i) advising",
        "(j) take",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "I have a friend named Alisha. She and I (a) ------ in the same class in the same school. Though we (b) ------ from the same village, we are good friends. During last winter I (c) ------ a chance (d) ------ a visit to her village and I (e) ------ a happy time there. While I (f) ------ in her village, I (g) ------ many delicious dishes which (h) ------ by Alisha's mother. Actually, I wanted (i) ------ some more days there. But, as I had some other plans, I had to come back. The memory of that visit (j) ------ ever fresh in my mind.",
      options: [
        "pay",
        "stay",
        "remain",
        "cook",
        "spend",
        "get",
        "enjoy",
        "be",
        "spend",
        "read",
      ],
      answers: [
        "(a) read",
        "(b) are not",
        "(c) got",
        "(d) to pay",
        "(e) spent",
        "(f) was staying",
        "(g) enjoyed",
        "(h) were cooked",
        "(i) to spend",
        "(j) remains",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "E-Commerce is rapidly being (a) ------ in our country. It may be (b) ------ as a business process through electronic transition. Buyers and sellers are not (c) ------ to talk face to face. We may get our required product (d) ------ at home. One of the best opportunities (e) ------ that businessmen from home and abroad can (f) ------ their business using this system (g) ------ in their respective countries. It (h) ------ us with global information, resources and services. It is (i) ------ that it will (j) ------ our domestic business very soon.",
      options: [
        "require",
        "be",
        "provide",
        "spread",
        "promote",
        "define",
        "anticipate",
        "direct",
        "remain",
        "stay",
      ],
      answers: [
        "(a) spread",
        "(b) defined",
        "(c) required",
        "(d) staying",
        "(e) is",
        "(f) promote",
        "(g) remaining",
        "(h) provides",
        "(i) anticipated",
        "(j) promote",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "The price hike of household products (a) ------ now a great problem for us. Everyday we (b) ------ it. Most of the people (c) ------ low income (d) ------ in danger. They (e) ------ of purchasing meat and fish as they (f) ------. We are to (g) ------ over buying even simple products. Many times the buyers (h) ------. The sellers cheat the buyers at the time of (i) ------ something. Some steps have (j) ------ by the government to identify the culprits.",
      options: [
        "weight",
        "require",
        "think",
        "be",
        "face",
        "cheat",
        "bargain",
        "-",
        "be",
        "take",
        "have",
      ],
      answers: [
        "(a) is",
        "(b) face",
        "(c) having",
        "(d) are",
        "(e) can't think",
        "(f) require",
        "(g) bargain",
        "(h) are cheated",
        "(i) weighing",
        "(j) been taken",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "According to the history, women in the past (a) ------ within the four walls. But at present, they (b) ------ no longer captive to their parents' or husbands' house. With the passage of time, the outlook and the attitude have been (c) ------ as men and women are (d) ------ themselves to the changing society. By (e) ------ education they are (f) ------ pilots, doctors, engineers, high officials, etc. They (g) ------ hand in hand with men in all worthy programmes. They are now able to (h) ------ their worth. They (i) ------ much to the economy of the country. Now it has come to the realization of men that no development is possible by (j) ------ half of our population idle at home.",
      options: [
        "receive",
        "contribute",
        "keep",
        "prove",
        "develop",
        "confine",
        "become",
        "adapt",
        "work",
        "be",
      ],
      answers: [
        "(a) were confined",
        "(b) are",
        "(c) developed",
        "(d) adapting",
        "(e) receiving",
        "(f) becoming",
        "(g) work",
        "(h) prove",
        "(i) contribute",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "Everybody (a) ------ that he or she (b) ------ the best. Actually, goodness or badness (c) ------ a little or much, (d) ------ in him or her simultaneously. But they only (e) ------ the good side of them (f) ------ the bad once. We (g) ------ ourselves and (h) ------ the bad. But the reality is that we always (i) ------ others that is not (j) ------.",
      options: [
        "overlook",
        "expect",
        "be",
        "see",
        "backbite",
        "criticize",
        "exist",
        "shun",
        "be",
        "imagine",
      ],
      answers: [
        "(a) imagines",
        "(b) is",
        "(c) being",
        "(d) exists",
        "(e) see",
        "(f) shunning",
        "(g) should not overlook",
        "(h) criticize",
        "(i) backbite",
        "(j) expected",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) ------ on the proper utilization of the resources. We should not (b) ------ a lazy life. We should all (c) ------ up our country. For this reason, we have to (d) ------ hard. No nation can prosper without industry. We should (e) ------ that industry is the key to success. If we (f) ------ the days away, we (g) ------ behind. The nations that (h) ------ industrious (i) ------ the pinnacles of development. So, we should (j) ------ them.",
      options: [
        "lag",
        "reach",
        "lead",
        "follow",
        "depend",
        "build",
        "remember",
        "be",
        "idle",
        "work",
      ],
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remember",
        "(f) idle",
        "(g) will lag",
        "(h) are",
        "(i) reach",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "Self-control is considered a great power. It (a) ------ all other virtues. Man usually (b) ------ on impulses and strong desires. Vicious desires (c) ------ the purity of heart and mind (d) ------ in the degeneration of human nature. It (e) ------ self-control that can help a man (f) ------ up a pure character which is very essential to (g) ------ above the level of immunity. Nothing can (h) ------ to self-control to (i) ------ immunity. So, everybody (j) ------ to be self-controlled.",
      options: [
        "damage",
        "result",
        "be",
        "rise",
        "try",
        "overcome",
        "breed",
        "act",
        "build",
        "compare",
      ],
      answers: [
        "(a) breeds",
        "(b) acts",
        "(c) damage",
        "(d) resulting",
        "(e) is",
        "(f) build",
        "(g) rise",
        "(h) be compared",
        "(i) overcome",
        "(j) should try",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2024,
    board: "Dhaka",
    data: {
      options: [
        "entertain",
        "order",
        "need",
        "become",
        "take",
        "make",
        "want",
        "wish",
        "be",
        "arrive",
      ],
      questions:
        "A birthday party is arranged to celebrate the day when one was born. It (a) ______ a happy occasion. Recently it (b) ______ a tradition to organize a birthday party. For organizing such a party, one (c) ______ to spend both time and money. He/she starts (d) ______ preparation from some days ago. A birthday cake (e) ______ earlier. Then, he/she invites his/her close friends and relatives. Usually, friends (f) ______ to miss such a party. On the appointed day, he/she puts on the best dress and eagerly waits for the invited guests to (g) ______. After the arrival of the guests, he/she cuts the birthday cake. By singing happy birthday to you, everybody (h) ______ him/her. The guests are highly (i) ______ with delicious foods and snacks. Sometimes there is arrangement for music with a view to (j) ______ the party more enjoyable.",
      answers: [
        "(a) is",
        "(b) has become",
        "(c) needs",
        "(d) taking",
        "(e) is",
        "(f) do not want",
        "(g) arrive",
        "(h) wishes",
        "(i) entertained",
        "(j) making",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Cumilla",
    data: {
      options: [
        "ensure",
        "waste",
        "remain",
        "do",
        "execute",
        "create",
        "divide",
        "appear",
        "save",
        "end",
      ],
      questions:
        "Proper time management makes it possible to complete any work timely. If a person (a) ______ his works into smaller portions and (b) ______ them accordingly, the whole work will be (c) ______ in time. Time is not (d) ______ because of doing the work in the planned way. As a result, enough time (e)______. Besides proper use of time (f) ______ by doing the work in this process. As each piece of work (g) ______ quickly, opportunity to do additional works (h) ______. Again, due to time management, no part of work (i)______ difficult and no work (j) ______ pending.",
      answers: [
        "(a) divides",
        "(b) executes",
        "(c) done",
        "(d) wasted",
        "(e) remains",
        "(f) is ensured",
        "(g) is ended",
        "(h) is created",
        "(i) appears",
        "(j) remains",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Chattogram",
    data: {
      options: [
        "command",
        "claim",
        "develop",
        "do",
        "make",
        "prepare",
        "memorize",
        "help",
        "think",
        "exercise",
      ],
      questions:
        "Most of the students of our country are expert in (a) _____ answers. They do not (b) _____ notes themselves. They get them (c) _____ by their tutors. Their tutors (d) _____ their brain for the students. So, the (e) _____ power of the students does not (f) _____. They do not have any (g) _____ of their language. They, of course, (h)_____ well in the examination. But for this, they can (i) _____ no credit of their own. This result does not (j) _____ them in their later life.",
      answers: [
        "(a) memorizing",
        "(b) make",
        "(c) prepared",
        "(d) exercise",
        "(e) thinking",
        "(f) develop",
        "(g) command",
        "(h) do",
        "(i) claim",
        "(j) help",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Dinajpur",
    data: {
      options: [
        "lag",
        "lead",
        "depend",
        "remember",
        "idle",
        "reach",
        "follow",
        "build",
        "be",
        "work",
      ],
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) _______ on the proper utilization of the resources. We should not (b) ______ lazy life. We should all (c) ______ up our country. For this reason, we have to (d) ______ hard. No nation can prosper without industry. We should (e) ______ that industry is the key to success. If we (f) ______ the days away, we (g) ______ behind. The nations that (h)______ industrious (i) ______ the pinnacle of development. So, we should (j) ______ them.",
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remember",
        "(f) idle",
        "(g) will lag",
        "(h) are",
        "(i) have reached",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Jessore",
    data: {
      options: [
        "focus",
        "control",
        "write",
        "read",
        "play",
        "follow",
        "wait",
        "understand",
        "upgrade",
        "be",
      ],
      questions:
        "Text books are the rich sources of information and knowledge. They (a) _____ a vital role in teaching-learning activities. If a student (b) _____ the text books thoroughly, he/she can get a clear idea about different topics. In the class room, teachers (c) _____ on the texts well. Unfortunately, some students (d) _____ the importance of reading text books. Again, in many schools guide books are (e) _____ in the class room. The concerned authority should monitor the class rooms with a view to (f) _____ this unexpected activity. Besides, teachers (g) _____ conscious of their duties and responsibilities. A strong foundation of knowledge is impossible without reading the text books well. These living sources of knowledge (h) _____ by the highly qualified educationists. The government is working relentlessly to (i) _____ the standard of the text books. The nation (j) _____ eagerly for the days when our students will lead Bangladesh applying their knowledge, skill and wisdom.",
      answers: [
        "(a) play",
        "(b) reads",
        "(c) focus",
        "(d) don’t understand",
        "(e) followed",
        "(f) controlling",
        "(g) should be",
        "(h) are written",
        "(i) upgrade",
        "(j) is waiting",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Mymensingh",
    data: {
      options: [
        "talk",
        "live",
        "be",
        "give",
        "suffer",
        "enable",
        "prove",
        "choose",
        "fail",
        "take",
      ],
      questions:
        "There are several reasons why friendship (a) ______ so necessary in human life. A man without a friend feels like a man (b) _____ alone in an isolated place. Moreover, it (c) _____ him lead his life in a better way. By (d) _____ to a friend a man can get relief. The advice (e) _____ by a friend is sometimes more reliable than his own judgement. Thus, it (f) _____ that friendship is really important. But a man must (g) _____ time while (h) _____ a friend. If he (i) _____ to select the right person as a friend, he (j) _____ in the long run.",
      answers: [
        "(a) is",
        "(b) living",
        "(c) enables",
        "(d) talking",
        "(e) given",
        "(f) proves",
        "(g) take",
        "(h) choosing",
        "(i) fails",
        "(j) will suffer",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Rajshahi",
    data: {
      options: [
        "throw",
        "kill",
        "release",
        "be",
        "originate",
        "work",
        "have",
        "ensure",
        "live",
        "pollute",
      ],
      questions:
        "Rivers generally (a) ______ from a mountain or a lake. They (b) ______ very much important for our existence and economy. But unfortunately, we are (c) ______ our rivers by throwing industrial and domestic wastes. Most of the industries (d) ______ waste treatment plants. These kinds of industries are (e) ______ liquid wastes directly and continuously (f) ______ the water. Our unconscious people also (g) ______ different kinds of waste materials into rivers. So, to keep the existence of fishes and other species (h) ______ in the water is impossible. It is high time the government and the people (i) ______ together to save the rivers. Otherwise a happy, prosperous and pollution free environment can’t be (j) ______ for the next generation.",
      answers: [
        "(a) originate",
        "(b) are",
        "(c) polluting",
        "(d) do not have",
        "(e) releasing",
        "(f) polluting",
        "(g) throw",
        "(h) living",
        "(i) worked",
        "(j) ensured",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Sylhet",
    data: {
      options: [
        "enable",
        "exercise",
        "do",
        "mean",
        "bring",
        "give",
        "send",
        "compare",
        "be",
      ],
      questions:
        "Science (a) ______ simply miracle. It (b) ______ about a change over the face of the globe. It (c) ______ man to control the forces of Nature and employ them to his service. With the help of science, we can now (d) ______ messages across the seas, fly in the air like the winged bird. Modern science may (e) ______ to Aladin’s magic lamp. Cinema, radio, television, gramophone, electric fan and watch (f) ______ all the gifts of modern science. The cinema (g) ______ the moving and talking pictures of men and women. It (h) ______ a great influence in our daily life. The radio (i) ______ us to listen to the talks of people living hundreds of miles away from us across seas and mountains. The television (j) ______ pictures seen through the wireless.",
      answers: [
        "(a) is",
        "(b) has brought",
        "(c) enables",
        "(d) send",
        "(e) be compared",
        "(f) are",
        "(g) means",
        "(h) exercises",
        "(i) enables",
        "(j) gives",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2023,
    board: "Dhaka",
    data: {
      options: [
        "obey",
        "be",
        "expect",
        "refer",
        "have",
        "require",
        "respect",
        "hamper",
        "reflect",
        "ensure",
      ],
      questions:
        "Social value (a) ____ to customs, beliefs, special practices and norms. It (b) ____ the culture of a nation. It (c) ____ great educative value in our life. In the past, people were very much conscious of (d) ____ social value in each and every walk of life. Earlier each and every person (e) ____ very careful of social value. But at present our social value is in a great threat. Young people don’t (f) ____ duly to their elders that results in social degradation. As a result, peace and order and decent life are greatly (g) ____. So, with a view to (h) ____ peace and order in society, social value is badly (i) ____. Without social value, we can’t (j) ____ decent, comfortable, happy and peaceful life.",
      answers: [
        "(a) refers",
        "(b) reflects",
        "(c) has",
        "(d) obeying",
        "(e) was",
        "(f) respect",
        "(g) hampered",
        "(h) ensuring",
        "(i) required",
        "(j) expect",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Cumilla",
    data: {
      options: [
        "can",
        "be",
        "find",
        "have",
        "fix",
        "stumble",
        "endow",
        "evaluate",
        "possess",
        "consult",
      ],
      questions:
        "A proverb goes that a man without an aim is a ship without a rudder. Likewise, a man without an aim (a) ____ reach his goal. He (b) ____ in his way of life. So everyman should (c) ____ a definite aim. But nothing is more difficult than the choice of profession Students (d) ____ it very difficult to choose a suitable profession. Choosing profession becomes very difficult because there (e) ____ many paths and courses open to them. They should (f) ____ their aim according to the abilities they are (g) ____ with. All (h) ____ the same abilities and aptitude. Students may (i) ____ their teachers who are able to (j) ____ their abilities.",
      answers: [
        "(a) cannot",
        "(b) stumbles",
        "(c) have",
        "(d) find",
        "(e) are",
        "(f) fix",
        "(g) endowed",
        "(h) don’t possess",
        "(i) consult",
        "(j) evaluate",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Chattogram",
    data: {
      options: [
        "visit",
        "pay",
        "hear",
        "call",
        "appear",
        "live",
        "visit",
        "hear",
        "live",
        "think",
      ],
      questions:
        "Abdur Rahman is a student. He (a) ____ in the SSC Exam this year. He (b) ____ in Chattogram. He (c) ____ there since his birth, but he (d) ____ St. Martins Island yet. He (e) ____ a lot about the beauty of St. Martin’s Island. (f) ____ those he becomes very eager (g) ____ a visit there. As he is free now, he thinks that he (h) ____ the island now. (i) ____ this he becomes so excited that he (j) ____ his friends to a meeting.",
      answers: [
        "(a) will appear",
        "(b) lives",
        "(c) has been living",
        "(d) has not visited",
        "(e) has heard/heard",
        "(f) Hearing",
        "(g) to pay",
        "(h) can visit/should visit",
        "(i) Thinking",
        "(j) calls",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Dinajpur",
    data: {
      options: [
        "die",
        "need",
        "destroy",
        "go",
        "make",
        "keep",
        "cause",
        "get",
        "name",
        "cause",
      ],
      questions:
        "There are various types of fever. Dengue is one of them. It (a) ____ by biting of mosquito (b) ____ ‘Aedes’. It (c) ____ serious health hazard. Vomiting, high temperature, blood platelets etc. make the patient tormented. Many patients (d) ____ if blood platelets (e) ____ below 50. Much care and proper treatment (f) ____ to save dengue affected patient. In order to (g) ____ ourselves free from dengue, we (h) ____ our environment clean. Living place of Aedes larva should (i) ____ with a view to (j) ____ ourselves aloof from mosquito bite. The use of curtain is also essential.",
      answers: [
        "(a) is caused",
        "(b) named",
        "(c) causes",
        "(d) die",
        "(e) go",
        "(f) are needed",
        "(g) get",
        "(h) have to keep/make",
        "(i) be destroyed",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Jessore",
    data: {
      options: [
        "be",
        "bring",
        "neglect",
        "spend",
        "lose",
        "possess",
        "claim",
        "pay",
        "neglect",
        "lose",
      ],
      questions:
        "Most of us (a) ____ the wrong mentality of measuring success in life. Many poor adults (b) ____ that the possession of wealth (c) ____ peace of mind in life. But it (d) ____ not always true. Many have (e) ____ their health to gain wealth, but later (f) ____ much of their wealth to regain health. Isn’t that ironical? Again there are also a number of people who had (g) ____ high prices for possessing their present wealth. They have (h) ____ friends and family and have (i) ____ opportunities to spend precious moments with people around them. Besides, many have (j) ____ peace within themselves for wanting more and more of everything.",
      answers: [
        "(a) possess",
        "(b) claim",
        "(c) brings",
        "(d) is",
        "(e) lost",
        "(f) have spent/spent",
        "(g) paid",
        "(h) neglected",
        "(i) lost",
        "(j) neglected",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Mymensingh",
    data: {
      options: [
        "build",
        "idle",
        "follow",
        "work",
        "remember",
        "be",
        "lag",
        "reach",
        "lead",
        "depend",
      ],
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) ____ on the proper utilization of the resources. We should not (b) ____ a lazy life. We all should become industrious. We all should (c) ____ up our country. For this reason, we have to (d) ____ hard. No nation can prosper without Industry. It should be (e) ____ that industry is the key to success. If we (f) ____ days away, we (g) ____ behind. The nation that (h) ____ industrious (i) ____ the pinnacle of development. So, we should (j) ____ them.",
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remembered",
        "(f) idle",
        "(g) will lag",
        "(h) is",
        "(i) reaches/has reached",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Rajshahi",
    data: {
      options: [
        "obey",
        "be",
        "respect",
        "refer",
        "expect",
        "hamper",
        "have",
        "reflect",
        "ensure",
        "require",
      ],
      questions:
        "Social value (a) ____ to customs, beliefs, special practices and norms. It (b) ____ the culture of a nation. It (c) ____ great educative value in our life. In the past, people were very much conscious of (d) ____ social value in each and every walk of life. Earlier each and every person (e) ____ very careful of social value. But at present our social value is in a great threat. Young people don’t (f) ____ duly to their elders that results in social degradation. As a result, peace and order and decent life are greatly (g) ____. So, with a view to (h) ____ peace and order in society, social value is badly (i) ____. Without social value, we can’t (j) ____ decent, comfortable, happy and peaceful life.",
      answers: [
        "(a) refers",
        "(b) reflects",
        "(c) has",
        "(d) obeying",
        "(e) was",
        "(f) respect",
        "(g) hampered",
        "(h) ensuring",
        "(i) required",
        "(j) expect",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Sylhet",
    data: {
      options: [
        "waste",
        "know",
        "follow",
        "observe",
        "do",
        "make",
        "fall",
        "are",
        "utilize",
        "is",
      ],
      questions:
        "We should (a) ____ the lifestyle of the ants and bees. They (b) ____ good use of their time and store food for the rainy days. They never (c) ____ a single moment in negligence or indolence. So they never (d) ____ into extreme crisis. We (e) ____ the best creatures in creation. We (f) ____ everything good and bad. We can (g) ____ better than the others. We should all (h) ____ every moment properly. Punctuality (i) ____ the best tonic in this regard. We should (j) ____ the footsteps of the famous persons.",
      answers: [
        "(a) observe",
        "(b) make",
        "(c) waste",
        "(d) fall",
        "(e) are",
        "(f) know",
        "(g) do",
        "(h) utilize",
        "(i) is",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Barishal",
    data: {
      options: [
        "make",
        "kill",
        "throw",
        "see",
        "ensure",
        "originate",
        "work",
        "live",
        "be",
        "have",
      ],
      questions:
        "Rivers generally (a) ____ from a mountain or a lake. They (b) ____ very much important for our existence and economy. But unfortunately, we are (c) ____ our rivers, choking it with toxic wastes from dyeing and textile factories. Most of the industries (d) ____ waste treatment plants. This kind of industries are (e) ____ releasing untreated liquid waste directly and (f) ____ the water polluted. Our unconscious people also (g) ____ different kinds of waste materials into the rivers directly. So, to keep existence of fishes and other species (h) ____ in the water is impossible. It is high time the government and the conscious people (i) ____ together to save the rivers. Otherwise a happy, prosperous and pollution free environment for the next generation can’t be (j) ____.",
      answers: [
        "(a) originate",
        "(b) are",
        "(c) killing",
        "(d) don’t have",
        "(e) seen",
        "(f) making",
        "(g) throw",
        "(h) living",
        "(i) worked",
        "(j) ensured",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2022,
    board: "Dinajpur",
    data: {
      options: [
        "have",
        "maintain",
        "dislike",
        "be",
        "create",
        "regard",
        "show",
        "refer",
        "indulge",
        "hamper",
      ],
      questions:
        "Social value denotes customs, beliefs, social practices, and norms. Besides, social value (a) — to the mode of manners and the way of behaviour. Social value is (b) — as the picture of the culture of a nation. It (c) — a great educative value in our life. In the past, people were very much conscious of (d) — social values. Dishonesty, cruelty, misconduct, untruthfulness, rude behaviour, etc. were strongly hated and (e) — in society. At present, our social value (f) — great threat. Young people (g) — due respect to their elders. They are seen (h) — in different types of antisocial activities. As a result, peace and order and decent life are greatly (i) —. It is high time we (j) — social awareness about social values.",
      answers: [
        "(a) refers",
        "(b) regarded",
        "(c) has",
        "(d) maintaining",
        "(e) disliked",
        "(f) is",
        "(g) do not show",
        "(h) indulged",
        "(i) hampered",
        "(j) created",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Cumilla",
    data: {
      options: [
        "know",
        "hinder",
        "hear",
        "begin",
        "call",
        "remember",
        "inspire",
        "be",
        "bear",
        "join",
      ],
      questions:
        "You must have (a) — the name of Kazi Nazrul Islam. He (b) — our national poet. He (c) — as a rebel poet as well. He (d) — into a poor family. But dire needs could not (e) — his potentiality. When the First World War broke out, he (f) — the army. After the war, he (g) — to write poems. At that time, his poems and songs (h) — people against oppression. He (i) — the Shelley of Bangla literature. We should (j) — him for his great deeds.",
      answers: [
        "(a) heard",
        "(b) is",
        "(c) is known",
        "(d) was born",
        "(e) hinder",
        "(f) joined",
        "(g) began",
        "(h) inspired",
        "(i) is called",
        "(j) remember",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Chattogram",
    data: {
      options: [
        "take",
        "eat",
        "deserve",
        "be",
        "thrive",
        "cause",
        "run",
        "know",
        "fail",
        "do",
      ],
      questions:
        "Everybody (a) — that food adulteration (b) — a crime. Adulterated food is poisonous and (c) — fatal diseases. People (d) — this kind of food (e) — a victim to liver disease, cancer, kidney failure, and so on. Some businessmen who are avaricious and (f) — after money only (g) — this heinous work. They (h) — on the miseries of others. They (i) — punishment. Some strict measures should be (j) — to stop this abominable task of the greedy businessmen.",
      answers: [
        "(a) knows",
        "(b) is",
        "(c) causes",
        "(d) eating",
        "(e) fall",
        "(f) run",
        "(g) do",
        "(h) thrive",
        "(i) deserve",
        "(j) taken",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Dhaka",
    data: {
      options: [
        "make",
        "become",
        "conduct",
        "enhance",
        "send",
        "help",
        "do",
        "be",
        "increase",
      ],
      questions:
        "Mobile phone is an important medium of modern communication which (a) — intercommunication. It (b) — our life very easy and comfortable. The world (c) — smaller due to the rapid use of it. Mobile phone connected with the Internet (d) — its users watch TV, and use social media like Facebook, Instagram, Linkedin, etc. We (e) — almost everything by using various mobile apps. We can check mails and (f) — the reply through it. The use of mobile phone (g) — noticeably during COVID-19. Nowadays, teachers and students (h) — dependent on it greatly. It has played a vital role in (i) — online education. But excessive use of it causes unpredictable health hazards. So, we (j) — it excessively.",
      answers: [
        "(a) enhances",
        "(b) makes",
        "(c) has become",
        "(d) helps",
        "(e) can do",
        "(f) send",
        "(g) increased",
        "(h) are",
        "(i) conducting",
        "(j) should not use",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Jashore",
    data: {
      options: [
        "understand",
        "form",
        "consider",
        "owe",
        "take",
        "respect",
        "succeed",
        "acquire",
        "admit",
        "forget",
      ],
      questions:
        "In an educational institution teacher-student relationship is (a) — to be the most important matter, it is such a relationship that is (b) — on the basis of mutual (c) —. A student always (d) — to his teachers because he cannot but (e) — help from them in case of (f) —. The sensible students never (g) — their teachers. Moreover, they (h) — their memorable teachers’ role which helps them (i) — in life. So, they always (j) — their teachers.",
      answers: [
        "(a) considered",
        "(b) formed",
        "(c) understanding",
        "(d) owes",
        "(e) take",
        "(f) acquiring",
        "(g) forget",
        "(h) admit",
        "(i) succeed",
        "(j) respect",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Rajshahi",
    data: {
      options: [
        "understand",
        "be",
        "prevail",
        "respect",
        "stop",
        "prosper",
        "feel",
        "preach",
        "reign",
        "defeat",
      ],
      questions:
        "Truth always (a) — in the world. Falsehood may (b) — for the time being. Those who (c) — engaged in (d) — the truth are (e) — by the people. Those who (f) — interest in telling lies cannot (g) — in life. They may prosper seemingly. But, after all, they become really (h) —. Socrates throughout his life would preach the truth. He tried to make people (i) — what was good for them. He was troubled by the powerful people. Yet, he never (j) — teaching good things.",
      answers: [
        "(a) reigns/prevails",
        "(b) prevail/reign",
        "(c) are",
        "(d) preaching",
        "(e) respected",
        "(f) feel",
        "(g) prosper",
        "(h) defeated",
        "(i) understand",
        "(j) stopped",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Mymensingh",
    data: {
      options: [
        "make",
        "become",
        "conduct",
        "enhance",
        "send",
        "help",
        "do",
        "be",
        "increase",
      ],
      questions:
        "Mobile phone is an important medium of modern communication which (a) — intercommunication. It (b) — our life very easy and comfortable. The world (c) — smaller due to the rapid use of it. Mobile phone connected with the Internet (d) — its users watch TV, and use social media like Facebook, Instagram, Linkedin, etc. We (e) — almost everything by using various mobile apps. We can check mails and (f) — the reply through it. The use of mobile phone (g) — noticeably during COVID-19. Nowadays, teachers and students (h) — dependent on it greatly. It has played a vital role in (i) — online education. But excessive use of it causes unpredictable health hazards. So, we (j) — it excessively.",
      answers: [
        "(a) enhances/has enhanced",
        "(b) has made",
        "(c) has become",
        "(d) helps/can help",
        "(e) do/can do",
        "(f) send",
        "(g) increased",
        "(h) are",
        "(i) conducting",
        "(j) should not use",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2020,
    board: "Barishal",
    data: {
      options: [
        "this",
        "disgrace",
        "with",
        "fortunate",
        "in",
        "have",
        "though",
        "the",
        "stomach",
        "to",
      ],
      questions:
        "Child labour is one of the biggest curses of the 21st century. It is (a) — that this has become very accepted (b) — our society. Only poverty is responsible for (c) —. In a family of five or six children, the parents (d) — to send their kids to work so that they can fill their empty (e) —. These poor and helpless children are rewarded (f) — all kinds of abuse (g) — they work hard all day long. No other thing is as (h) — as child abuse for a nation. (i) — government has taken necessary measures (j) — check it.",
      answers: [
        "(a) unfortunate",
        "(b) in",
        "(c) this",
        "(d) have",
        "(e) stomachs",
        "(f) with",
        "(g) though",
        "(h) disgraceful",
        "(i) The",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Chattogram",
    data: {
      options: [
        "think",
        "positive",
        "arise",
        "hinder",
        "normal",
        "avoid",
        "mainly",
        "hamper",
        "cause",
        "prosperity",
      ],
      questions:
        "Student politics (a) — the normal progress of a student. It brings (b) — to a few but (c) — harm to many. Because of student politics (d) — administration of a college or university is (e) —. As a result, there (f) — session jam. For this problem of the campus, student politics is (g) — responsible. So, we should (h) — about the necessity of student politics. Either we should (i) — student politics or we should bring about a (j) — change in this sector.",
      answers: [
        "(a) hinders/hampers",
        "(b) prosperity",
        "(c) causes",
        "(d) normal",
        "(e) hampered/hindered",
        "(f) arises",
        "(g) mainly",
        "(h) think",
        "(i) avoid",
        "(j) positive",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Cumilla",
    data: {
      options: [
        "dull",
        "the",
        "success",
        "both",
        "victory",
        "if",
        "we",
        "them",
        "keen",
        "easily",
      ],
      questions:
        "Without effort, there can be no (a) — in life. Life loses its interest (b) — there is no struggle. Games become (c) —, if there is no competition in (d) — and if the result can be (e) — foreseen. No matter we win (f) — game or lose it. The (g) — the contest, the greater the interest. A (h) — is not a real triumph unless (i) — the sides are equally strong. Whether (j) — like it or not, life is a continuous competitive examination.",
      answers: [
        "(a) success",
        "(b) if",
        "(c) dull",
        "(d) them",
        "(e) easily",
        "(f) the",
        "(g) keener",
        "(h) victory",
        "(i) both",
        "(j) we",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Dhaka",
    data: {
      options: [
        "dark",
        "the",
        "from",
        "an",
        "learning",
        "often",
        "midst",
        "that",
        "worthy",
        "in",
      ],
      questions:
        "An ideal teacher is (a) — compared with (b) — architect. He is called (c) — architect of a nation. He is the light of (d) — and makes the illiterate people (e) — citizens of our country. But it is a matter of regret (f) — the teachers are not held (g) — due respect in our society. They lead a humble life in the (h) — of want. Still they keep the light of education burning in order to remove the (i) — of illiteracy and superstitions (j) — the society.",
      answers: [
        "(a) often",
        "(b) an",
        "(c) the",
        "(d) learning",
        "(e) worthy",
        "(f) that",
        "(g) in",
        "(h) midst",
        "(i) darkness",
        "(j) from",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Mymensingh",
    data: {
      options: [
        "rest",
        "nation",
        "culture",
        "the",
        "walks",
        "throughout",
        "history",
        "tradition",
        "some",
        "number",
      ],
      questions:
        "Festivals have always been integral parts of our tradition and culture. We have a (a) — of festivals which we celebrate (b) — the year. Some of our (c) — festivals are related to our (d) — of Independence and Language Movement. (e) — are related to our religions and the (f) — are related to our art and (g) —. Whatever may be (h) — occasion, people from all (i) — of the society take part in these festivals spontaneously. We should continue the (j) — of our festivals.",
      answers: [
        "(a) number",
        "(b) throughout",
        "(c) national",
        "(d) history",
        "(e) Some",
        "(f) rest",
        "(g) culture",
        "(h) the",
        "(i) walks",
        "(j) tradition",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Rajshahi",
    data: {
      options: [
        "develop",
        "fear",
        "conscious",
        "both",
        "for",
        "punish",
        "be",
        "towards",
      ],
      questions:
        "Nowadays, parents are very (a) — of the harmful effect of (b) — on children. Child Psychologists think that (c) — physical and mental punishment can be disastrous (d) — a child’s growth and (e) —. It may lead to (f) — and hatred of the person who (g) — the child. Again, if a child (h) — punished, he may lack initiative. He may also feel hostile (i) — others. So, rude behaviour gradually (j) — in him.",
      answers: [
        "(a) conscious",
        "(b) punishment",
        "(c) both",
        "(d) for",
        "(e) development",
        "(f) fear",
        "(g) punishes",
        "(h) is",
        "(i) towards",
        "(j) develops",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Sylhet",
    data: {
      options: [
        "about",
        "between",
        "of",
        "basic",
        "no",
        "educate",
        "almost",
        "will",
        "light",
        "light",
      ],
      questions:
        "Education removes our ignorance and gives us the (a) — of knowledge in respect (b) — imparting education. There should be (c) — discrimination (d) — man and woman. Education is one of the (e) — human rights. If we deprive woman of the (f) — of education (g) — half of our population (h) — remain in darkness. No development can be brought (i) — without the participation of woman. So, the government is doing everything to (j) — the womanfolk.",
      answers: [
        "(a) light",
        "(b) of",
        "(c) no",
        "(d) between",
        "(e) basic",
        "(f) right",
        "(g) almost",
        "(h) will",
        "(i) about",
        "(j) educate",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2019,
    board: "Barishal",
    data: {
      options: [
        "bewitching",
        "rising",
        "sight",
        "within",
        "longest",
        "the",
        "charming",
        "mangrove",
        "wild",
        "beautiful",
      ],
      questions:
        "The sea-beach of Cox’s Bazar is a (a) — gift of nature. The blue water of the sea and its (b) — waves are always a pleasant (c) — which cools our mind (d) — a moment. It is the (e) — sea-beach in the world. (f) — Saint Martin’s Island is also a gift of nature in the Bay of Bengal. The beauty of the island is simply (g) —. The Sundarbans, the largest (h) — forest of the world is another beautiful gift of nature. Its (i) — life and mysterious setting make it more (j) —.",
      answers: [
        "(a) bewitching",
        "(b) rising",
        "(c) sight",
        "(d) within",
        "(e) longest",
        "(f) the",
        "(g) charming",
        "(h) mangrove",
        "(i) wild",
        "(j) beautiful",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Chattogram",
    data: {
      options: [
        "full",
        "made",
        "objects",
        "water",
        "clothes",
        "forces",
        "currents",
        "on",
        "important",
        "the",
      ],
      questions:
        "The world is (a) — of uncountable natural and man (b) — objects. Natural (c) — are stones, trees, air, and (d) —. Man-made objects are houses, cars, (e) — and chemicals. Natural (f) — are cyclones, earthquakes, volcanoes, storms, and ocean (g) —. Life exists (h) — different conditions. It is very (i) — to keep (j) — environment clean.",
      answers: [
        "(a) full",
        "(b) made",
        "(c) objects",
        "(d) water",
        "(e) clothes",
        "(f) forces",
        "(g) currents",
        "(h) on",
        "(i) important",
        "(j) the",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Cumilla",
    data: {
      options: [
        "with",
        "boon",
        "a",
        "hinder",
        "in",
        "of",
        "eradicate",
        "lagging",
        "jointly",
        "development",
      ],
      questions:
        "Bangladesh is beset (a) — many problems. Illiteracy is one of them. It is not a (b) — to us. It is undoubtedly (c) — curse. It (d) — all kinds of developments of a country. It also causes many other problems (e) — our society. As most of our people are not conscious (f) — the importance of education, we cannot take proper step to (g) — illiteracy. As a result, we are (h) — behind. We have to depend on the foreign aids. All of us should come forward (i) — to remove illiteracy from the society. Then the (j) — of the country will be possible.",
      answers: [
        "(a) with",
        "(b) boon",
        "(c) a",
        "(d) hinders",
        "(e) in",
        "(f) of",
        "(g) eradicate",
        "(h) lagging",
        "(i) jointly",
        "(j) development",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Dhaka",
    data: {
      options: [
        "anticipated",
        "disaster",
        "the",
        "sustain",
        "to",
        "erosion",
        "indiscriminately",
        "an",
        "imperative",
        "for",
      ],
      questions:
        "It is (a) — that the new century is now facing various challenges especially environmental (b) —. Feeding the ever-growing population is (c) — first and foremost challenge for Bangladesh. It is very difficult to (d) — the current level of agricultural production. Because our agricultural land is being reduced due (e) — human habitat, industrialization, river (f) — etc. Besides, we are losing our forests gradually. Trees are being cut down (g) — resulting in (h) — increase of pollution. So, it is (i) — to check the reckless alarming condition (j) — our own existence.",
      answers: [
        "(a) anticipated",
        "(b) disaster",
        "(c) the",
        "(d) sustain",
        "(e) to",
        "(f) erosion",
        "(g) indiscriminately",
        "(h) an",
        "(i) imperative",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Dinajpur",
    data: {
      options: [
        "advancement",
        "with",
        "connection",
        "network",
        "of",
        "smaller",
        "within",
        "short",
        "thirsty",
        "miracle",
      ],
      questions:
        "Internet is the latest discovery of science. It is the greatest (a) — in this field. It is a computerized process (b) — a telephone set. To get internet (c) — it requires a modem, telephone line and a different sort of software for using the (d) — system. Nowadays the internet is (e) — great use to us. It has made the world (f) — and brought the world (g) — our reach. We can get any information in a very (h) — time. It has not only widened our knowledge but also made us (i) — for the unknown. It's a (j) — like Aladdin’s magic lamp.",
      answers: [
        "(a) advancement",
        "(b) with",
        "(c) connection",
        "(d) network",
        "(e) of",
        "(f) smaller",
        "(g) within",
        "(h) short",
        "(i) thirsty",
        "(j) miracle",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Jashore",
    data: {
      options: [
        "the",
        "treatment",
        "of",
        "generally",
        "and",
        "a",
        "sick",
        "the",
        "by",
        "to",
      ],
      questions:
        "A hospital is the home for (a) — sick. It gives medical (b) — to them at free (c) — cost. A hospital is (d) — run by the government. A hospital has outdoor (e) — indoor sections. (f) — great number of the (g) — people are treated in (h) — outdoor section. People attacked (i) — serious illness are admitted (j) — the indoor section.",
      answers: [
        "(a) the",
        "(b) treatment",
        "(c) of",
        "(d) generally",
        "(e) and",
        "(f) a",
        "(g) sick",
        "(h) the",
        "(i) by",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Rajshahi",
    data: {
      options: [
        "recently",
        "victim",
        "that",
        "the",
        "by",
        "faulty",
        "endanger",
        "awareness",
        "strict",
        "accused",
      ],
      questions:
        "Road accidents have (a) — become a regular phenomenon in our country. As a result of the accidents many persons fall (b) — to untimely death. It is reported (c) — most of the accidents occur for (d) — violation of traffic rules, (e) — unskilled drivers and unconscious passers-by. Many unlicensed and (f) — vehicles also (g) — the passengers and the passers-by. So, in order to save us from the accidents the government is trying to create (h) — among the people and has passed (i) — laws against the (j) —.",
      answers: [
        "(a) recently",
        "(b) victim",
        "(c) that",
        "(d) the",
        "(e) by",
        "(f) faulty",
        "(g) endanger",
        "(h) awareness",
        "(i) strict",
        "(j) accused",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Sylhet",
    data: {
      options: [
        "adulteration",
        "of",
        "hardly",
        "which",
        "or",
        "at",
        "the",
        "into",
        "for",
        "which",
      ],
      questions:
        "The issue of food (a) — has drawn the attention (b) — general people. We (c) — find any food in our country. (d) — is not adulterated in one way (e) — other. (f) — present, sub-standard foods are sold in most of (g) — hotels. Very recently government has directed a mobile court to look (h) — the matter of food. They are catching dishonest hoteliers red-handed (i) — using unhygienic ingredients (j) — are really harmful for human body.",
      answers: [
        "(a) adulteration",
        "(b) of",
        "(c) hardly",
        "(d) which",
        "(e) or",
        "(f) at",
        "(g) the",
        "(h) into",
        "(i) for",
        "(j) which",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2017,
    board: "Chattogram",
    data: {
      options: [
        "for",
        "of",
        "beneficial",
        "between",
        "saying",
        "on",
        "participation",
        "physically",
        "an",
        "personality",
      ],
      questions:
        "Sports are very essential (a) — us. There are various types (b) — sports. Among them cricket, football, volleyball etc. are very popular. All types of sports are (c) — to us. There is a relation (d) — the body and the mind. 'A sound mind in a sound body' is a wise (e) —. In order to win success in life we should have sound health which depends (f) — regular (g) — in games and sports. Sports keep us (h) — fit. Sport exercise is (i) — important influence in forming one’s (j) —.",
      answers: [
        "(a) for",
        "(b) of",
        "(c) beneficial",
        "(d) between",
        "(e) saying",
        "(f) on",
        "(g) participation",
        "(h) physically",
        "(i) an",
        "(j) personality",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Cumilla",
    data: {
      options: ["a", "an", "the", "x"],
      questions:
        "In (a) — last 25 years (b) — world has lost one-third of its natural wealth, according to (c) — international conservation organization world wild fund. (d) — earth’s forest, wetlands, seas and coasts are in (e) — worse state today than they were before. Forests are cut down. Moreover, they are being burnt indiscriminately resulting in (f) — increase in carbon-di-oxide and ultimately in (g) — water level rising as a consequence of global warming. It is anticipated that (h) — new century will face (i) — overwhelming environmental (j) — catastrophe.",
      answers: [
        "(a) the",
        "(b) the",
        "(c) an",
        "(d) The",
        "(e) a",
        "(f) an",
        "(g) the",
        "(h) the",
        "(i) an",
        "(j) x",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dhaka",
    data: {
      options: [
        "a",
        "on",
        "to",
        "properly",
        "speaking",
        "rote",
        "by",
        "then",
        "speakers",
      ],
      questions:
        "Learning is (a) — continuous process. Learning a language depends on a process based (b) — language skills. We need to practice four skills (c) — learn a language (d) —. We learn by listening, (e) —, reading and writing. But we have to learn not by (f) — but by understanding. We know that (g) — child starts to learn its mother tongue (h) — listening and lip sing and (i) — speaking. Native (j) — learn their language easily by listening and speaking.",
      answers: [
        "(a) a",
        "(b) on",
        "(c) to",
        "(d) properly",
        "(e) speaking",
        "(f) rote",
        "(g) a",
        "(h) by",
        "(i) then",
        "(j) speakers",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dinajpur",
    data: {
      options: [
        "the",
        "appreciation",
        "of",
        "entirely",
        "or",
        "forward",
        "friendship",
        "in",
        "for",
      ],
      questions:
        "Gratefulness is (a) — acknowledgement and the (b) — of help received from others. In the society we cannot do all things. Sometimes, we need the help (c) — others. We are (d) — dependent on the society. A man may be in danger (e) — in problem at any time. It is a natural instinct in man to come (f) — to help the needy because of his fellow-feeling, (g) — and kinship. Gratefulness comes from (h) — depth of heart and finds its manifestation (i) — books, words and deeds of the grateful man. The grateful man feels highly obliged (j) — the benefit he has received.",
      answers: [
        "(a) the",
        "(b) appreciation",
        "(c) of",
        "(d) entirely",
        "(e) or",
        "(f) forward",
        "(g) friendship",
        "(h) the",
        "(i) in",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Jashore",
    data: {
      options: [
        "maker",
        "a",
        "does",
        "surely",
        "in",
        "to",
        "life",
        "of",
        "the",
        "repent",
      ],
      questions:
        "Man is the (a) — of his own fate. If he makes (b) — proper division of his time and (c) — his duties accordingly, he will (d) — improve and prosper (e) — life. But if he does otherwise, he is sure (f) — suffer when it is too late. To waste time is as bad as to commit suicide. In fact, our (g) — is nothing but the sum total (h) — hours, days and years. If we waste (i) — morning hours of life, we shall have to (j) — afterwards.",
      answers: [
        "(a) maker",
        "(b) a",
        "(c) does",
        "(d) surely",
        "(e) in",
        "(f) to",
        "(g) life",
        "(h) of",
        "(i) the",
        "(j) repent",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Rajshahi",
    data: {
      options: [
        "suitable",
        "ages",
        "numerous",
        "The",
        "early",
        "a",
        "fresh",
        "Moreover",
        "maintain",
        "make",
      ],
      questions:
        "Morning walk is an exercise (a) — for the people of all (b) —. It gives us (c) — benefits. (d) — people who wake up (e) — and go out for (f) — walk, can enjoy (g) — morning air. (h) — this exercise helps them (i) — good health. Again, they can (j) — a good start of their work.",
      answers: [
        "(a) suitable",
        "(b) ages",
        "(c) numerous",
        "(d) The",
        "(e) early",
        "(f) a",
        "(g) fresh",
        "(h) Moreover",
        "(i) maintain",
        "(j) make",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Sylhet",
    data: {
      options: [
        "a",
        "in",
        "number",
        "movement",
        "for",
        "the",
        "up",
        "forward",
        "at",
      ],
      questions:
        "Traffic jam is (a) — problem in all towns and cities (b) — Bangladesh. It occurs where a (c) — of vehicles crowd so close that (d) — becomes impossible (e) — sometime. It is more common where (f) — streets are narrow and have many bends. Weak traffic control system is also largely responsible (g) — it. It is very annoying and time killing. When caught in a traffic jam, we simply get stuck (h) — at one place. We can neither move (i) — nor backward. We have to wait and look repeatedly (j) — our watch.",
      answers: [
        "(a) a",
        "(b) in",
        "(c) number",
        "(d) movement",
        "(e) for",
        "(f) the",
        "(g) for",
        "(h) up",
        "(i) forward",
        "(j) at",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2016,
    board: "Chattogram",
    data: {
      options: [
        "for",
        "successful",
        "need",
        "of",
        "in",
        "sure",
        "put",
        "careless",
        "about",
        "a",
      ],
      questions:
        "A stitch (a) — time saves nine. This is (b) — very well-known proverb. Some people don’t care (c) — anything. They (d) — off a job (e) — tomorrow, though they are not (f) — whether the day will come. In this way, they can’t finish a work when they (g) — it. Then they say, “Alas! If we were not (h) — about our jobs when we had a lot (i) — time we could be (j) —“.",
      answers: [
        "(a) in",
        "(b) a",
        "(c) about",
        "(d) put",
        "(e) for",
        "(f) sure",
        "(g) need",
        "(h) careless",
        "(i) of",
        "(j) successful",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Cumilla",
    data: {
      options: [
        "too",
        "favourable",
        "people",
        "soon",
        "an",
        "motherland",
        "grow",
        "buy",
        "in",
        "become",
      ],
      questions:
        "Our (a) — Bangladesh is (b) — agricultural country. Most of our (c) — are engaged (d) — cultivation. Many cultivators are (e) — poor to (f) — and use modern tools. Still they can (g) — bumper crops if the climate is (h) —. We hope to (i) — a developed nation (j) —.",
      answers: [
        "(a) motherland",
        "(b) an",
        "(c) people",
        "(d) in",
        "(e) too",
        "(f) buy",
        "(g) grow",
        "(h) favourable",
        "(i) become",
        "(j) soon",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dhaka",
    data: {
      options: [
        "with",
        "at",
        "a",
        "bread",
        "dislike",
        "responsible",
        "to",
        "of",
        "privilege",
        "in",
      ],
      questions:
        "We live in society. So we must learn how to live (a) — peace and amity (b) — others. We have to respect others’ rights and (c) — and liking and (d) — as we expect others to respect us. We have (e) — lot of duties and (f) — in society. Education should aim (g) — making each individual fully aware (h) — these duties and responsibilities. It is true that one has (i) — learn how to earn the (j) —.",
      answers: [
        "(a) in",
        "(b) with",
        "(c) privileges",
        "(d) disliking",
        "(e) a",
        "(f) responsibilities",
        "(g) at",
        "(h) of",
        "(i) to",
        "(j) bread",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dinajpur",
    data: {
      options: [
        "of",
        "for",
        "a",
        "afford",
        "and",
        "expensive",
        "the",
        "influence",
      ],
      questions:
        "Travelling has a beneficial (a) — on our minds. The human mind always craves (b) — change. This is (c) — by travelling in new lands. There is none who does not feel (d) — thrill of joy at the new sight (e) — experience. Travelling gives us an opportunity to enjoy (f) — most charming scenes (g) — nature. Though it is (h) —, it can bring a change both in body (i) — mind. Thus travelling can help one to complete his knowledge and can be (j) — perfect man.",
      answers: [
        "(a) influence",
        "(b) for",
        "(c) achieved",
        "(d) a",
        "(e) of",
        "(f) the",
        "(g) of",
        "(h) expensive",
        "(i) and",
        "(j) a",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Jessore",
    data: {
      options: [
        "of",
        "the",
        "for",
        "at",
        "which",
        "adulterate",
        "hardly",
        "or",
        "into",
      ],
      questions:
        "The issue of food (a) — has drawn the attention (b) — general people. We (c) — find any food in our country (d) — is not adulterated in one way (e) — other. (f) — present, sub-standard foods are sold in most of (g) — hotels. Very recently government has directed a mobile court to look (h) — the matter of food (i) —. They are catching dishonest hoteliers red handed (j) — using unhygienic food ingredients.",
      answers: [
        "(a) adulteration",
        "(b) of",
        "(c) hardly",
        "(d) which",
        "(e) or",
        "(f) At",
        "(g) the",
        "(h) into",
        "(i) adulteration",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Rajshahi",
    data: {
      options: [
        "in",
        "develop",
        "without",
        "remove",
        "of",
        "between",
        "do",
        "the",
      ],
      questions:
        "Education (a) — our ignorance and gives us light (b) — knowledge. (c) — respect (d) — imparting education, there should be no discrimination (e) — man and woman. Education is one of the human rights. If we deprive women of (f) — right of education, almost half of our population will remain (g) — darkness. No (h) — can be brought about (i) — participation of women. So government is (j) — everything to educate women folk.",
      answers: [
        "(a) removes",
        "(b) of",
        "(c) With",
        "(d) to",
        "(e) between",
        "(f) the",
        "(g) in",
        "(h) development",
        "(i) without",
        "(j) doing",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Sylhet",
    data: {
      options: [
        "about",
        "accurate",
        "dominate",
        "the",
        "wonder",
        "a",
        "towards",
        "energy",
        "of",
        "substitute",
      ],
      questions:
        "The modern world is undoubtedly a world of computers. It has brought (a) — a great change in our way of life. It works as a (b) — for human brain. It has enabled us to perform any difficult work (c) — in a few seconds. In the field (d) — medical science, printing, education etc. computers are doing (e) — jobs. In (f) — western countries, computers (g) — every sphere of man’s life. Our country is also gradually moving (h) — a computer culture. It saves both our time and (i) —. If we make a constructive use of it, it can render (j) — great service to mankind.",
      answers: [
        "(a) about",
        "(b) substitute",
        "(c) accurately",
        "(d) of",
        "(e) wonderful",
        "(f) the",
        "(g) dominate",
        "(h) towards",
        "(i) energy",
        "(j) a",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2015,
    board: "Barisal",
    data: {
      options: [
        "give",
        "a",
        "symbol",
        "to be",
        "by",
        "last",
        "in",
        "but",
        "the",
        "cultivate",
      ],
      questions:
        "A flower is (a) — gift of nature. It is a (b) — of beauty. It (c) — us pleasure. There is nobody (d) — loves flower. But it is (e) — matter of sorrow that a flower does not (f) — long. It blooms (g) — the morning and fades away very soon. Nowadays flowers (h) — cultivated in our country. Many people earn their livelihood (i) — flower (j) —.",
      answers: [
        "(a) the",
        "(b) symbol",
        "(c) gives",
        "(d) but",
        "(e) a",
        "(f) last",
        "(g) in",
        "(h) are",
        "(i) by",
        "(j) cultivation",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Chittagong",
    data: {
      options: [
        "in",
        "dark",
        "the",
        "from",
        "an",
        "learning",
        "often",
        "that",
        "worthy",
        "our",
      ],
      questions:
        "A teacher is (a) — compared with (b) — architect. He is called (c) — architect of a nation. He is the light of (d) — and makes the illiterate people (e) — citizens of our country. But it is a matter of regret (f) — the teachers are not held (g) — due respect in (h) — society. They lead a humble life in the midst of want. Still they keep the light of education burning in order to remove the (i) — of illiteracy and superstitions (j) — the society.",
      answers: [
        "(a) often",
        "(b) an",
        "(c) the",
        "(d) learning",
        "(e) worthy",
        "(f) that",
        "(g) in",
        "(h) our",
        "(i) darkness",
        "(j) from",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Dhaka",
    data: {
      options: ["to", "a", "for", "in", "work", "prepare", "the", "by"],
      questions:
        "It is useful (a) — students to take part (b) — social service. (c) — taking part (d) — social service, they can benefit themselves as well as (e) — nation. Student life is (f) — period of (g) — for future life. If the students do social (h) —, they will be better prepared for giving service (i) — the nation on completion of their education. As the students have no family burden and as they get enough time during the large vacation, they can do (j) — great deal of work for the people.",
      answers: [
        "(a) for",
        "(b) in",
        "(c) By",
        "(d) in",
        "(e) the",
        "(f) the",
        "(g) preparation",
        "(h) work",
        "(i) to",
        "(j) a",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Rajshahi",
    data: {
      options: ["in", "for", "of", "life", "a", "the", "when", "reap", "sow"],
      questions:
        "Youth is (a) — best time of (b) —. This is the time (c) — it is most important (d) — one to remember the maxim, “As you (e) —, so shall you reap.” One must sow (f) — seeds of industry, truthfulness, honesty and other virtues (g) — this season to (h) — the harvest of prosperity and happiness. Whatever takes root in (i) — man at this time lasts throughout the rest (j) — his life and moulds his future.",
      answers: [
        "(a) the",
        "(b) life",
        "(c) when",
        "(d) for",
        "(e) sow",
        "(f) the",
        "(g) in",
        "(h) reap",
        "(i) a",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Sylhet",
    data: {
      options: [
        "a",
        "the",
        "precious",
        "for",
        "great",
        "have",
        "wise",
        "which",
        "off",
      ],
      questions:
        "Time is very (a) — thing. Time (b) — is lost once is lost forever. There is (c) — proverb, “Time and tide wait for none.” It is time which does not (d) — the relative feelings. It does not wait (e) — anyone if it is not used (f) —. It is really essential to realize (g) — importance of time in our life. Those who have become (h) — would make proper use of time. They never put (i) — their work for tomorrow. That’s why, they have contributed (j) — lot to the society.",
      answers: [
        "(a) precious",
        "(b) which",
        "(c) a",
        "(d) have",
        "(e) for",
        "(f) wisely",
        "(g) the",
        "(h) great",
        "(i) off",
        "(j) a",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
];
