export const sscRightFormsOfVerbs = [
  {
    exam: "ssc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "Our annual prize giving ceremony (a) ------ off yesterday. We (b) ------ our school campus very nicely. The ceremony (c) ------ at 3 p.m. Our Headmaster (d) ------ over the function and the Education Minister (e) ------ the chief guest. The function (f) ------ with the recitation from the Holy Quran. One of our senior teachers (g) ------ out the annual report. The honourable chief guest (h) ------ a brief encouraging speech (i) ------ us to be regular in studies and (j) ------ part in the movement against illiteracy.",
      options: [
        "deliver",
        "take",
        "start",
        "preside",
        "be",
        "advise",
        "decorate",
        "begin",
        "come",
        "read",
      ],
      answers: [
        "(a) came",
        "(b) decorated",
        "(c) started",
        "(d) presided",
        "(e) was",
        "(f) began",
        "(g) read",
        "(h) delivered",
        "(i) advising",
        "(j) take",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "I have a friend named Alisha. She and I (a) ------ in the same class in the same school. Though we (b) ------ from the same village, we are good friends. During last winter I (c) ------ a chance (d) ------ a visit to her village and I (e) ------ a happy time there. While I (f) ------ in her village, I (g) ------ many delicious dishes which (h) ------ by Alisha's mother. Actually, I wanted (i) ------ some more days there. But, as I had some other plans, I had to come back. The memory of that visit (j) ------ ever fresh in my mind.",
      options: [
        "pay",
        "stay",
        "remain",
        "cook",
        "spend",
        "get",
        "enjoy",
        "be",
        "spend",
        "read",
      ],
      answers: [
        "(a) read",
        "(b) are not",
        "(c) got",
        "(d) to pay",
        "(e) spent",
        "(f) was staying",
        "(g) enjoyed",
        "(h) were cooked",
        "(i) to spend",
        "(j) remains",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "E-Commerce is rapidly being (a) ------ in our country. It may be (b) ------ as a business process through electronic transition. Buyers and sellers are not (c) ------ to talk face to face. We may get our required product (d) ------ at home. One of the best opportunities (e) ------ that businessmen from home and abroad can (f) ------ their business using this system (g) ------ in their respective countries. It (h) ------ us with global information, resources and services. It is (i) ------ that it will (j) ------ our domestic business very soon.",
      options: [
        "require",
        "be",
        "provide",
        "spread",
        "promote",
        "define",
        "anticipate",
        "direct",
        "remain",
        "stay",
      ],
      answers: [
        "(a) spread",
        "(b) defined",
        "(c) required",
        "(d) staying",
        "(e) is",
        "(f) promote",
        "(g) remaining",
        "(h) provides",
        "(i) anticipated",
        "(j) promote",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "The price hike of household products (a) ------ now a great problem for us. Everyday we (b) ------ it. Most of the people (c) ------ low income (d) ------ in danger. They (e) ------ of purchasing meat and fish as they (f) ------. We are to (g) ------ over buying even simple products. Many times the buyers (h) ------. The sellers cheat the buyers at the time of (i) ------ something. Some steps have (j) ------ by the government to identify the culprits.",
      options: [
        "weight",
        "require",
        "think",
        "be",
        "face",
        "cheat",
        "bargain",
        "-",
        "be",
        "take",
        "have",
      ],
      answers: [
        "(a) is",
        "(b) face",
        "(c) having",
        "(d) are",
        "(e) can't think",
        "(f) require",
        "(g) bargain",
        "(h) are cheated",
        "(i) weighing",
        "(j) been taken",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "According to the history, women in the past (a) ------ within the four walls. But at present, they (b) ------ no longer captive to their parents' or husbands' house. With the passage of time, the outlook and the attitude have been (c) ------ as men and women are (d) ------ themselves to the changing society. By (e) ------ education they are (f) ------ pilots, doctors, engineers, high officials, etc. They (g) ------ hand in hand with men in all worthy programmes. They are now able to (h) ------ their worth. They (i) ------ much to the economy of the country. Now it has come to the realization of men that no development is possible by (j) ------ half of our population idle at home.",
      options: [
        "receive",
        "contribute",
        "keep",
        "prove",
        "develop",
        "confine",
        "become",
        "adapt",
        "work",
        "be",
      ],
      answers: [
        "(a) were confined",
        "(b) are",
        "(c) developed",
        "(d) adapting",
        "(e) receiving",
        "(f) becoming",
        "(g) work",
        "(h) prove",
        "(i) contribute",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "Everybody (a) ------ that he or she (b) ------ the best. Actually, goodness or badness (c) ------ a little or much, (d) ------ in him or her simultaneously. But they only (e) ------ the good side of them (f) ------ the bad once. We (g) ------ ourselves and (h) ------ the bad. But the reality is that we always (i) ------ others that is not (j) ------.",
      options: [
        "overlook",
        "expect",
        "be",
        "see",
        "backbite",
        "criticize",
        "exist",
        "shun",
        "be",
        "imagine",
      ],
      answers: [
        "(a) imagines",
        "(b) is",
        "(c) being",
        "(d) exists",
        "(e) see",
        "(f) shunning",
        "(g) should not overlook",
        "(h) criticize",
        "(i) backbite",
        "(j) expected",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) ------ on the proper utilization of the resources. We should not (b) ------ a lazy life. We should all (c) ------ up our country. For this reason, we have to (d) ------ hard. No nation can prosper without industry. We should (e) ------ that industry is the key to success. If we (f) ------ the days away, we (g) ------ behind. The nations that (h) ------ industrious (i) ------ the pinnacles of development. So, we should (j) ------ them.",
      options: [
        "lag",
        "reach",
        "lead",
        "follow",
        "depend",
        "build",
        "remember",
        "be",
        "idle",
        "work",
      ],
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remember",
        "(f) idle",
        "(g) will lag",
        "(h) are",
        "(i) reach",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "Self-control is considered a great power. It (a) ------ all other virtues. Man usually (b) ------ on impulses and strong desires. Vicious desires (c) ------ the purity of heart and mind (d) ------ in the degeneration of human nature. It (e) ------ self-control that can help a man (f) ------ up a pure character which is very essential to (g) ------ above the level of immunity. Nothing can (h) ------ to self-control to (i) ------ immunity. So, everybody (j) ------ to be self-controlled.",
      options: [
        "damage",
        "result",
        "be",
        "rise",
        "try",
        "overcome",
        "breed",
        "act",
        "build",
        "compare",
      ],
      answers: [
        "(a) breeds",
        "(b) acts",
        "(c) damage",
        "(d) resulting",
        "(e) is",
        "(f) build",
        "(g) rise",
        "(h) be compared",
        "(i) overcome",
        "(j) should try",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Mymensingh",
    data: {
      questions:
        "The flood (a) ——recently in Chattogram division (b)——all records of the past. Never before did water level rise so high nor (c) ——- the duration so long. Normal activities have been (d)——-for a long time. Thousands of people have (e) ——- homeless and clothless. The miseries of flood (f) ———- people know no bounds. Crops have been greatly (g)———- Herds of cattle (h) ——— away. Thousands of people (i)——- their shelters They (j)———- now living under the open air.",
      options: [
        "break",
        "take",
        "wash",
        "damage",
        "occurre",
        "stop",
        "be",
        "affect",
        "become",
        "lose",
      ],
      answers: [
        "(a) occurred",
        "(b) broke",
        "(c) was",
        "(d) stopped",
        "(e) become",
        "(f) affected",
        "(g) damaged",
        "(h) washed",
        "(i) lost",
        "(j) are",
      ],

      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2024,
    board: "Dhaka",
    data: {
      options: [
        "entertain",
        "order",
        "need",
        "become",
        "take",
        "make",
        "want",
        "wish",
        "be",
        "arrive",
      ],
      questions:
        "A birthday party is arranged to celebrate the day when one was born. It (a) ______ a happy occasion. Recently it (b) ______ a tradition to organize a birthday party. For organizing such a party, one (c) ______ to spend both time and money. He/she starts (d) ______ preparation from some days ago. A birthday cake (e) ______ earlier. Then, he/she invites his/her close friends and relatives. Usually, friends (f) ______ to miss such a party. On the appointed day, he/she puts on the best dress and eagerly waits for the invited guests to (g) ______. After the arrival of the guests, he/she cuts the birthday cake. By singing happy birthday to you, everybody (h) ______ him/her. The guests are highly (i) ______ with delicious foods and snacks. Sometimes there is arrangement for music with a view to (j) ______ the party more enjoyable.",
      answers: [
        "(a) is",
        "(b) has become",
        "(c) needs",
        "(d) taking",
        "(e) is",
        "(f) do not want",
        "(g) arrive",
        "(h) wishes",
        "(i) entertained",
        "(j) making",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Cumilla",
    data: {
      options: [
        "ensure",
        "waste",
        "remain",
        "do",
        "execute",
        "create",
        "divide",
        "appear",
        "save",
        "end",
      ],
      questions:
        "Proper time management makes it possible to complete any work timely. If a person (a) ______ his works into smaller portions and (b) ______ them accordingly, the whole work will be (c) ______ in time. Time is not (d) ______ because of doing the work in the planned way. As a result, enough time (e)______. Besides proper use of time (f) ______ by doing the work in this process. As each piece of work (g) ______ quickly, opportunity to do additional works (h) ______. Again, due to time management, no part of work (i)______ difficult and no work (j) ______ pending.",
      answers: [
        "(a) divides",
        "(b) executes",
        "(c) done",
        "(d) wasted",
        "(e) remains",
        "(f) is ensured",
        "(g) is ended",
        "(h) is created",
        "(i) appears",
        "(j) remains",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Chattogram",
    data: {
      options: [
        "command",
        "claim",
        "develop",
        "do",
        "make",
        "prepare",
        "memorize",
        "help",
        "think",
        "exercise",
      ],
      questions:
        "Most of the students of our country are expert in (a) _____ answers. They do not (b) _____ notes themselves. They get them (c) _____ by their tutors. Their tutors (d) _____ their brain for the students. So, the (e) _____ power of the students does not (f) _____. They do not have any (g) _____ of their language. They, of course, (h)_____ well in the examination. But for this, they can (i) _____ no credit of their own. This result does not (j) _____ them in their later life.",
      answers: [
        "(a) memorizing",
        "(b) make",
        "(c) prepared",
        "(d) exercise",
        "(e) thinking",
        "(f) develop",
        "(g) command",
        "(h) do",
        "(i) claim",
        "(j) help",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Dinajpur",
    data: {
      options: [
        "lag",
        "lead",
        "depend",
        "remember",
        "idle",
        "reach",
        "follow",
        "build",
        "be",
        "work",
      ],
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) _______ on the proper utilization of the resources. We should not (b) ______ lazy life. We should all (c) ______ up our country. For this reason, we have to (d) ______ hard. No nation can prosper without industry. We should (e) ______ that industry is the key to success. If we (f) ______ the days away, we (g) ______ behind. The nations that (h)______ industrious (i) ______ the pinnacle of development. So, we should (j) ______ them.",
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remember",
        "(f) idle",
        "(g) will lag",
        "(h) are",
        "(i) have reached",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Jessore",
    data: {
      options: [
        "focus",
        "control",
        "write",
        "read",
        "play",
        "follow",
        "wait",
        "understand",
        "upgrade",
        "be",
      ],
      questions:
        "Text books are the rich sources of information and knowledge. They (a) _____ a vital role in teaching-learning activities. If a student (b) _____ the text books thoroughly, he/she can get a clear idea about different topics. In the class room, teachers (c) _____ on the texts well. Unfortunately, some students (d) _____ the importance of reading text books. Again, in many schools guide books are (e) _____ in the class room. The concerned authority should monitor the class rooms with a view to (f) _____ this unexpected activity. Besides, teachers (g) _____ conscious of their duties and responsibilities. A strong foundation of knowledge is impossible without reading the text books well. These living sources of knowledge (h) _____ by the highly qualified educationists. The government is working relentlessly to (i) _____ the standard of the text books. The nation (j) _____ eagerly for the days when our students will lead Bangladesh applying their knowledge, skill and wisdom.",
      answers: [
        "(a) play",
        "(b) reads",
        "(c) focus",
        "(d) don’t understand",
        "(e) followed",
        "(f) controlling",
        "(g) should be",
        "(h) are written",
        "(i) upgrade",
        "(j) is waiting",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Mymensingh",
    data: {
      options: [
        "talk",
        "live",
        "be",
        "give",
        "suffer",
        "enable",
        "prove",
        "choose",
        "fail",
        "take",
      ],
      questions:
        "There are several reasons why friendship (a) ______ so necessary in human life. A man without a friend feels like a man (b) _____ alone in an isolated place. Moreover, it (c) _____ him lead his life in a better way. By (d) _____ to a friend a man can get relief. The advice (e) _____ by a friend is sometimes more reliable than his own judgement. Thus, it (f) _____ that friendship is really important. But a man must (g) _____ time while (h) _____ a friend. If he (i) _____ to select the right person as a friend, he (j) _____ in the long run.",
      answers: [
        "(a) is",
        "(b) living",
        "(c) enables",
        "(d) talking",
        "(e) given",
        "(f) proves",
        "(g) take",
        "(h) choosing",
        "(i) fails",
        "(j) will suffer",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Rajshahi",
    data: {
      options: [
        "throw",
        "kill",
        "release",
        "be",
        "originate",
        "work",
        "have",
        "ensure",
        "live",
        "pollute",
      ],
      questions:
        "Rivers generally (a) ______ from a mountain or a lake. They (b) ______ very much important for our existence and economy. But unfortunately, we are (c) ______ our rivers by throwing industrial and domestic wastes. Most of the industries (d) ______ waste treatment plants. These kinds of industries are (e) ______ liquid wastes directly and continuously (f) ______ the water. Our unconscious people also (g) ______ different kinds of waste materials into rivers. So, to keep the existence of fishes and other species (h) ______ in the water is impossible. It is high time the government and the people (i) ______ together to save the rivers. Otherwise a happy, prosperous and pollution free environment can’t be (j) ______ for the next generation.",
      answers: [
        "(a) originate",
        "(b) are",
        "(c) polluting",
        "(d) do not have",
        "(e) releasing",
        "(f) polluting",
        "(g) throw",
        "(h) living",
        "(i) worked",
        "(j) ensured",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Sylhet",
    data: {
      options: [
        "enable",
        "exercise",
        "do",
        "mean",
        "bring",
        "give",
        "send",
        "compare",
        "be",
      ],
      questions:
        "Science (a) ______ simply miracle. It (b) ______ about a change over the face of the globe. It (c) ______ man to control the forces of Nature and employ them to his service. With the help of science, we can now (d) ______ messages across the seas, fly in the air like the winged bird. Modern science may (e) ______ to Aladin’s magic lamp. Cinema, radio, television, gramophone, electric fan and watch (f) ______ all the gifts of modern science. The cinema (g) ______ the moving and talking pictures of men and women. It (h) ______ a great influence in our daily life. The radio (i) ______ us to listen to the talks of people living hundreds of miles away from us across seas and mountains. The television (j) ______ pictures seen through the wireless.",
      answers: [
        "(a) is",
        "(b) has brought",
        "(c) enables",
        "(d) send",
        "(e) be compared",
        "(f) are",
        "(g) means",
        "(h) exercises",
        "(i) enables",
        "(j) gives",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2024,
    board: "Barishal",
    data: {
      questions:
        "Rivers generally (a) ___ from a mountain or a lake. They (b) ___ very much important for our existence and economy. But unfortunately we are (c) ___ our rivers by throwing industrial and domestic wastes. Most of the industries (d) ___ waste treatment plants. These kinds of industries are (e) ___ liquid wastes and continuously (f) ___ the water. Our unconscious people also (g) ___ different kinds of waste materials into rivers. So, to keep the existence of fishes and other species (h) ___ in the water is impossible. It is high time the government and the people (i) ___ together to save the rivers. Otherwise a happy, prosperous and pollution free environment can't be (j) ___ for the next generation.",
      options: [
        "throw",
        "kill",
        "work",
        "have",
        "release",
        "be",
        "ensure",
        "live",
        "originate",
        "pollute",
      ],
      answers: [
        "(a) originate",
        "(b) are",
        "(c) polluting",
        "(d) do not have",
        "(e) releasing",
        "(f) polluting",
        "(g) throw",
        "(h) living",
        "(i) worked",
        "(j) ensured",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2023,
    board: "Dhaka",
    data: {
      options: [
        "obey",
        "be",
        "expect",
        "refer",
        "have",
        "require",
        "respect",
        "hamper",
        "reflect",
        "ensure",
      ],
      questions:
        "Social value (a) ____ to customs, beliefs, special practices and norms. It (b) ____ the culture of a nation. It (c) ____ great educative value in our life. In the past, people were very much conscious of (d) ____ social value in each and every walk of life. Earlier each and every person (e) ____ very careful of social value. But at present our social value is in a great threat. Young people don’t (f) ____ duly to their elders that results in social degradation. As a result, peace and order and decent life are greatly (g) ____. So, with a view to (h) ____ peace and order in society, social value is badly (i) ____. Without social value, we can’t (j) ____ decent, comfortable, happy and peaceful life.",
      answers: [
        "(a) refers",
        "(b) reflects",
        "(c) has",
        "(d) obeying",
        "(e) was",
        "(f) respect",
        "(g) hampered",
        "(h) ensuring",
        "(i) required",
        "(j) expect",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Cumilla",
    data: {
      options: [
        "can",
        "be",
        "find",
        "have",
        "fix",
        "stumble",
        "endow",
        "evaluate",
        "possess",
        "consult",
      ],
      questions:
        "A proverb goes that a man without an aim is a ship without a rudder. Likewise, a man without an aim (a) ____ reach his goal. He (b) ____ in his way of life. So everyman should (c) ____ a definite aim. But nothing is more difficult than the choice of profession Students (d) ____ it very difficult to choose a suitable profession. Choosing profession becomes very difficult because there (e) ____ many paths and courses open to them. They should (f) ____ their aim according to the abilities they are (g) ____ with. All (h) ____ the same abilities and aptitude. Students may (i) ____ their teachers who are able to (j) ____ their abilities.",
      answers: [
        "(a) cannot",
        "(b) stumbles",
        "(c) have",
        "(d) find",
        "(e) are",
        "(f) fix",
        "(g) endowed",
        "(h) don’t possess",
        "(i) consult",
        "(j) evaluate",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Chattogram",
    data: {
      options: [
        "visit",
        "pay",
        "hear",
        "call",
        "appear",
        "live",
        "visit",
        "hear",
        "live",
        "think",
      ],
      questions:
        "Abdur Rahman is a student. He (a) ____ in the SSC Exam this year. He (b) ____ in Chattogram. He (c) ____ there since his birth, but he (d) ____ St. Martins Island yet. He (e) ____ a lot about the beauty of St. Martin’s Island. (f) ____ those he becomes very eager (g) ____ a visit there. As he is free now, he thinks that he (h) ____ the island now. (i) ____ this he becomes so excited that he (j) ____ his friends to a meeting.",
      answers: [
        "(a) will appear",
        "(b) lives",
        "(c) has been living",
        "(d) has not visited",
        "(e) has heard/heard",
        "(f) Hearing",
        "(g) to pay",
        "(h) can visit/should visit",
        "(i) Thinking",
        "(j) calls",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Dinajpur",
    data: {
      options: [
        "die",
        "need",
        "destroy",
        "go",
        "make",
        "keep",
        "cause",
        "get",
        "name",
        "cause",
      ],
      questions:
        "There are various types of fever. Dengue is one of them. It (a) ____ by biting of mosquito (b) ____ ‘Aedes’. It (c) ____ serious health hazard. Vomiting, high temperature, blood platelets etc. make the patient tormented. Many patients (d) ____ if blood platelets (e) ____ below 50. Much care and proper treatment (f) ____ to save dengue affected patient. In order to (g) ____ ourselves free from dengue, we (h) ____ our environment clean. Living place of Aedes larva should (i) ____ with a view to (j) ____ ourselves aloof from mosquito bite. The use of curtain is also essential.",
      answers: [
        "(a) is caused",
        "(b) named",
        "(c) causes",
        "(d) die",
        "(e) go",
        "(f) are needed",
        "(g) get",
        "(h) have to keep/make",
        "(i) be destroyed",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Jessore",
    data: {
      options: [
        "be",
        "bring",
        "neglect",
        "spend",
        "lose",
        "possess",
        "claim",
        "pay",
        "neglect",
        "lose",
      ],
      questions:
        "Most of us (a) ____ the wrong mentality of measuring success in life. Many poor adults (b) ____ that the possession of wealth (c) ____ peace of mind in life. But it (d) ____ not always true. Many have (e) ____ their health to gain wealth, but later (f) ____ much of their wealth to regain health. Isn’t that ironical? Again there are also a number of people who had (g) ____ high prices for possessing their present wealth. They have (h) ____ friends and family and have (i) ____ opportunities to spend precious moments with people around them. Besides, many have (j) ____ peace within themselves for wanting more and more of everything.",
      answers: [
        "(a) possess",
        "(b) claim",
        "(c) brings",
        "(d) is",
        "(e) lost",
        "(f) have spent/spent",
        "(g) paid",
        "(h) neglected",
        "(i) lost",
        "(j) neglected",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Mymensingh",
    data: {
      options: [
        "build",
        "idle",
        "follow",
        "work",
        "remember",
        "be",
        "lag",
        "reach",
        "lead",
        "depend",
      ],
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) ____ on the proper utilization of the resources. We should not (b) ____ a lazy life. We all should become industrious. We all should (c) ____ up our country. For this reason, we have to (d) ____ hard. No nation can prosper without Industry. It should be (e) ____ that industry is the key to success. If we (f) ____ days away, we (g) ____ behind. The nation that (h) ____ industrious (i) ____ the pinnacle of development. So, we should (j) ____ them.",
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remembered",
        "(f) idle",
        "(g) will lag",
        "(h) is",
        "(i) reaches/has reached",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Rajshahi",
    data: {
      options: [
        "obey",
        "be",
        "respect",
        "refer",
        "expect",
        "hamper",
        "have",
        "reflect",
        "ensure",
        "require",
      ],
      questions:
        "Social value (a) ____ to customs, beliefs, special practices and norms. It (b) ____ the culture of a nation. It (c) ____ great educative value in our life. In the past, people were very much conscious of (d) ____ social value in each and every walk of life. Earlier each and every person (e) ____ very careful of social value. But at present our social value is in a great threat. Young people don’t (f) ____ duly to their elders that results in social degradation. As a result, peace and order and decent life are greatly (g) ____. So, with a view to (h) ____ peace and order in society, social value is badly (i) ____. Without social value, we can’t (j) ____ decent, comfortable, happy and peaceful life.",
      answers: [
        "(a) refers",
        "(b) reflects",
        "(c) has",
        "(d) obeying",
        "(e) was",
        "(f) respect",
        "(g) hampered",
        "(h) ensuring",
        "(i) required",
        "(j) expect",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Sylhet",
    data: {
      options: [
        "waste",
        "know",
        "follow",
        "observe",
        "do",
        "make",
        "fall",
        "are",
        "utilize",
        "is",
      ],
      questions:
        "We should (a) ____ the lifestyle of the ants and bees. They (b) ____ good use of their time and store food for the rainy days. They never (c) ____ a single moment in negligence or indolence. So they never (d) ____ into extreme crisis. We (e) ____ the best creatures in creation. We (f) ____ everything good and bad. We can (g) ____ better than the others. We should all (h) ____ every moment properly. Punctuality (i) ____ the best tonic in this regard. We should (j) ____ the footsteps of the famous persons.",
      answers: [
        "(a) observe",
        "(b) make",
        "(c) waste",
        "(d) fall",
        "(e) are",
        "(f) know",
        "(g) do",
        "(h) utilize",
        "(i) is",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Barishal",
    data: {
      options: [
        "make",
        "kill",
        "throw",
        "see",
        "ensure",
        "originate",
        "work",
        "live",
        "be",
        "have",
      ],
      questions:
        "Rivers generally (a) ____ from a mountain or a lake. They (b) ____ very much important for our existence and economy. But unfortunately, we are (c) ____ our rivers, choking it with toxic wastes from dyeing and textile factories. Most of the industries (d) ____ waste treatment plants. This kind of industries are (e) ____ releasing untreated liquid waste directly and (f) ____ the water polluted. Our unconscious people also (g) ____ different kinds of waste materials into the rivers directly. So, to keep existence of fishes and other species (h) ____ in the water is impossible. It is high time the government and the conscious people (i) ____ together to save the rivers. Otherwise a happy, prosperous and pollution free environment for the next generation can’t be (j) ____.",
      answers: [
        "(a) originate",
        "(b) are",
        "(c) killing",
        "(d) don’t have",
        "(e) seen",
        "(f) making",
        "(g) throw",
        "(h) living",
        "(i) worked",
        "(j) ensured",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2022,
    board: "Dinajpur",
    data: {
      options: [
        "have",
        "maintain",
        "dislike",
        "be",
        "create",
        "regard",
        "show",
        "refer",
        "indulge",
        "hamper",
      ],
      questions:
        "Social value denotes customs, beliefs, social practices, and norms. Besides, social value (a) — to the mode of manners and the way of behaviour. Social value is (b) — as the picture of the culture of a nation. It (c) — a great educative value in our life. In the past, people were very much conscious of (d) — social values. Dishonesty, cruelty, misconduct, untruthfulness, rude behaviour, etc. were strongly hated and (e) — in society. At present, our social value (f) — great threat. Young people (g) — due respect to their elders. They are seen (h) — in different types of antisocial activities. As a result, peace and order and decent life are greatly (i) —. It is high time we (j) — social awareness about social values.",
      answers: [
        "(a) refers",
        "(b) regarded",
        "(c) has",
        "(d) maintaining",
        "(e) disliked",
        "(f) is",
        "(g) do not show",
        "(h) indulged",
        "(i) hampered",
        "(j) created",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Cumilla",
    data: {
      options: [
        "know",
        "hinder",
        "hear",
        "begin",
        "call",
        "remember",
        "inspire",
        "be",
        "bear",
        "join",
      ],
      questions:
        "You must have (a) — the name of Kazi Nazrul Islam. He (b) — our national poet. He (c) — as a rebel poet as well. He (d) — into a poor family. But dire needs could not (e) — his potentiality. When the First World War broke out, he (f) — the army. After the war, he (g) — to write poems. At that time, his poems and songs (h) — people against oppression. He (i) — the Shelley of Bangla literature. We should (j) — him for his great deeds.",
      answers: [
        "(a) heard",
        "(b) is",
        "(c) is known",
        "(d) was born",
        "(e) hinder",
        "(f) joined",
        "(g) began",
        "(h) inspired",
        "(i) is called",
        "(j) remember",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Chattogram",
    data: {
      options: [
        "take",
        "eat",
        "deserve",
        "be",
        "thrive",
        "cause",
        "run",
        "know",
        "fail",
        "do",
      ],
      questions:
        "Everybody (a) — that food adulteration (b) — a crime. Adulterated food is poisonous and (c) — fatal diseases. People (d) — this kind of food (e) — a victim to liver disease, cancer, kidney failure, and so on. Some businessmen who are avaricious and (f) — after money only (g) — this heinous work. They (h) — on the miseries of others. They (i) — punishment. Some strict measures should be (j) — to stop this abominable task of the greedy businessmen.",
      answers: [
        "(a) knows",
        "(b) is",
        "(c) causes",
        "(d) eating",
        "(e) fall",
        "(f) run",
        "(g) do",
        "(h) thrive",
        "(i) deserve",
        "(j) taken",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Dhaka",
    data: {
      options: [
        "make",
        "become",
        "conduct",
        "enhance",
        "send",
        "help",
        "do",
        "be",
        "increase",
      ],
      questions:
        "Mobile phone is an important medium of modern communication which (a) — intercommunication. It (b) — our life very easy and comfortable. The world (c) — smaller due to the rapid use of it. Mobile phone connected with the Internet (d) — its users watch TV, and use social media like Facebook, Instagram, Linkedin, etc. We (e) — almost everything by using various mobile apps. We can check mails and (f) — the reply through it. The use of mobile phone (g) — noticeably during COVID-19. Nowadays, teachers and students (h) — dependent on it greatly. It has played a vital role in (i) — online education. But excessive use of it causes unpredictable health hazards. So, we (j) — it excessively.",
      answers: [
        "(a) enhances",
        "(b) makes",
        "(c) has become",
        "(d) helps",
        "(e) can do",
        "(f) send",
        "(g) increased",
        "(h) are",
        "(i) conducting",
        "(j) should not use",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Jashore",
    data: {
      options: [
        "understand",
        "form",
        "consider",
        "owe",
        "take",
        "respect",
        "succeed",
        "acquire",
        "admit",
        "forget",
      ],
      questions:
        "In an educational institution teacher-student relationship is (a) — to be the most important matter, it is such a relationship that is (b) — on the basis of mutual (c) —. A student always (d) — to his teachers because he cannot but (e) — help from them in case of (f) —. The sensible students never (g) — their teachers. Moreover, they (h) — their memorable teachers’ role which helps them (i) — in life. So, they always (j) — their teachers.",
      answers: [
        "(a) considered",
        "(b) formed",
        "(c) understanding",
        "(d) owes",
        "(e) take",
        "(f) acquiring",
        "(g) forget",
        "(h) admit",
        "(i) succeed",
        "(j) respect",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Rajshahi",
    data: {
      options: [
        "understand",
        "be",
        "prevail",
        "respect",
        "stop",
        "prosper",
        "feel",
        "preach",
        "reign",
        "defeat",
      ],
      questions:
        "Truth always (a) — in the world. Falsehood may (b) — for the time being. Those who (c) — engaged in (d) — the truth are (e) — by the people. Those who (f) — interest in telling lies cannot (g) — in life. They may prosper seemingly. But, after all, they become really (h) —. Socrates throughout his life would preach the truth. He tried to make people (i) — what was good for them. He was troubled by the powerful people. Yet, he never (j) — teaching good things.",
      answers: [
        "(a) reigns/prevails",
        "(b) prevail/reign",
        "(c) are",
        "(d) preaching",
        "(e) respected",
        "(f) feel",
        "(g) prosper",
        "(h) defeated",
        "(i) understand",
        "(j) stopped",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Mymensingh",
    data: {
      options: [
        "make",
        "become",
        "conduct",
        "enhance",
        "send",
        "help",
        "do",
        "be",
        "increase",
      ],
      questions:
        "Mobile phone is an important medium of modern communication which (a) — intercommunication. It (b) — our life very easy and comfortable. The world (c) — smaller due to the rapid use of it. Mobile phone connected with the Internet (d) — its users watch TV, and use social media like Facebook, Instagram, Linkedin, etc. We (e) — almost everything by using various mobile apps. We can check mails and (f) — the reply through it. The use of mobile phone (g) — noticeably during COVID-19. Nowadays, teachers and students (h) — dependent on it greatly. It has played a vital role in (i) — online education. But excessive use of it causes unpredictable health hazards. So, we (j) — it excessively.",
      answers: [
        "(a) enhances/has enhanced",
        "(b) has made",
        "(c) has become",
        "(d) helps/can help",
        "(e) do/can do",
        "(f) send",
        "(g) increased",
        "(h) are",
        "(i) conducting",
        "(j) should not use",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2022,
    board: "Sylhet",
    data: {
      questions:
        "Communicative competence in English is urgently (a) ___ in our country. The present world (b) ___ fast and (c) ___ on with the advancement of technology. With a view to (d) ___ pace with the present world, we cannot help (e) ___ English. The present curriculum has (f) ___ learning English by (g) ___ the books (h) ___ with modern information. But readers should be (i) ___ to read more supplementary books. (j) ___ an ICT based skill can be very productive to keep pace with this advanced world.",
      options: [
        "develop",
        "have",
        "need",
        "go",
        "emphasize",
        "motivate",
        "keep",
        "enrich",
        "learn",
        "modify",
      ],
      answers: [
        "(a) needed",
        "(b) is developing",
        "(c) goes",
        "(d) keeping",
        "(e) learning",
        "(f) emphasized",
        "(g) modifying",
        "(h) enriched",
        "(i) motivated",
        "(j) Developing",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2022,
    board: "Barishal",
    data: {
      questions:
        "1st January (a) ___ now as the book festival in Bangladesh. On this day, students (b) ___ in school and madrashas get new text books free of cost. Books (c) ___ the most important teaching aids for the students. If students (d) ___ books in time, their academic progress will be greatly hampered. So, the present government (e) ___ this epoch-making programme. This programme will undoubtedly play a vital role in (f) ___ the standard of education. By getting books on this day, students can start (g) ___ their preparation from the very beginning of the academic year. Guardians of the students also become happy to (h) ___ new books in the hands of their children. So, this programme should be (i) ___ for building an educated nation. The people of Bangladesh (j) ___ ever grateful to the present government for taking this noble initiative.",
      options: [
        "get",
        "continue",
        "upgrade",
        "see",
        "read",
        "remain",
        "take",
        "observe",
        "be",
        "start",
      ],
      answers: [
        "(a) is observed",
        "(b) remaining",
        "(c) are",
        "(d) do not get",
        "(e) has started",
        "(f) upgrading",
        "(g) taking",
        "(h) see",
        "(i) continued",
        "(j) will remain",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2020,
    board: "Dhaka",
    data: {
      questions:
        "Traffic jam is a common affair in big cities of our country. Increasing number of vehicles (a) --- traffic jam. Mainly it (b) --- in the congested areas. Overtaking tendency also (c) --- traffic jam. Some drivers (d) --- the traffic rules and (e) --- carelessly. It (f) --- a lot of pains to the people. Ambulances (g) --- patients cannot (h) --- hospital timely. Students and office-going people also (i) --- due to traffic jam. This problem should be (j) --- immediately.",
      options: [
        "drive",
        "solve",
        "create",
        "suffer",
        "occur",
        "reach",
        "cause",
        "carry",
        "violate",
        "give",
      ],
      answers: [
        "(a) creates/causes",
        "(b) occurs",
        "(c) causes/creates",
        "(d) violate",
        "(e) drive",
        "(f) gives",
        "(g) carrying",
        "(h) reach",
        "(i) suffer",
        "(j) solved",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Barishal",
    data: {
      questions:
        "Gender inequality is a barrier to the overall development of a country. Gender equality (a) --- to the condition in which both men and women (b) --- equally and fairly in all circumstances. Without (c) --- the participation of the both, the social and economic development (d) ---. Elimination of gender disparity is a demand of the day with a view to (e) --- human rights. Our government, already (f) --- some initiatives in different sectors so that women can (g) --- pace with men. But our social set up is (h) --- a barrier in different ways. We should (i) --- our outlook and come forward to (j) --- gender inequality from the society.",
      options: [
        "ensure",
        "take",
        "imagine",
        "eliminate",
        "refer",
        "establish",
        "create",
        "broaden",
        "treat",
        "keep",
      ],
      answers: [
        "(a) refers",
        "(b) are treated",
        "(c) ensuring",
        "(d) cannot be imagined",
        "(e) establishing",
        "(f) has taken",
        "(g) keep",
        "(h) creating",
        "(i) broaden",
        "(j) eliminate",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Chattogram",
    data: {
      questions:
        "Self-control (a) --- a great power. It (b) --- all other virtues. Man generally (c) --- on impulses and strong desires. Vicious desires (d) --- the purity of heart and mind (e) --- the degradation of human nature. It is self-control that can help a man (f) --- up a pure character which is very essential (g) --- above the level of inhumanity. Nothing can (h) --- to self-control to (i) --- inhumanity. So, everybody (j) --- for being self-controlled.",
      options: [
        "act",
        "damage",
        "breed",
        "rise",
        "result",
        "consider",
        "overcome",
        "compare",
        "build",
        "be",
      ],
      answers: [
        "(a) is considered",
        "(b) breeds",
        "(c) acts",
        "(d) damage",
        "(e) resulting",
        "(f) build",
        "(g) rise",
        "(h) be compared",
        "(i) overcome",
        "(j) should endeavor",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Cumilla",
    data: {
      questions:
        "According to the history, women in the past were (a) --- within the four walls. But at present, they (b) --- no longer captive to their parents' or husbands' house. With the passage of time, the outlook and attitude have been (c) --- as men and women are (d) --- themselves to the changing society. By (e) --- education, they are (f) --- pilots, doctors, engineers, high officials, etc. They are (g) --- hand in hand with men in all worthy programmes. They are now able to (h) --- their worth. They (i) --- much to the economy of the country. Now, it has come to the realization of men that no development is possible by (j) --- half of our population idle at home.",
      options: [
        "contribute",
        "confine",
        "keep",
        "prove",
        "work",
        "develop",
        "be",
        "receive",
        "become",
        "adapt",
      ],
      answers: [
        "(a) confined",
        "(b) are",
        "(c) developed",
        "(d) adapting",
        "(e) receiving",
        "(f) becoming",
        "(g) working",
        "(h) prove",
        "(i) are contributing",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Mymensingh",
    data: {
      questions:
        "You must have (a) --- the name of Kazi Nazrul Islam. He (b) --- our national poet. He (c) --- as a rebel poet as well. He (d) --- into a poor family. But dire needs could not (e) --- his potentiality. When the First World War broke out, he (f) --- the army. After the war, he (g) --- to write poems. At that time, his poems and songs (h) --- people against oppression. He (i) --- the Shelley of Bangla literature. We should (j) --- him for his great deeds.",
      options: [
        "know",
        "hinder",
        "hear",
        "begin",
        "call",
        "remember",
        "inspire",
        "be",
        "bear",
        "join",
      ],
      answers: [
        "(a) heard",
        "(b) is",
        "(c) is known",
        "(d) was born",
        "(e) hinder",
        "(f) joined",
        "(g) began",
        "(h) inspired",
        "(i) is called",
        "(j) remember",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Sylhet",
    data: {
      questions:
        "Traffic jam is a common affair in big cities of our country. Increasing number of vehicles (a) --- traffic jam. Mainly it (b) --- in the congested areas. Overtaking tendency also (c) --- traffic jam. Some drivers (d) --- the traffic rules and (e) --- carelessly. It (f) --- a lot of pains to the people. Ambulances (g) --- patients cannot (h) --- hospital timely. Students and office-going people also (i) --- due to traffic jam. This problem should be (j) --- immediately.",
      options: [
        "cause",
        "carry",
        "violate",
        "occur",
        "drive",
        "solve",
        "create",
        "suffer",
        "give",
        "reach",
      ],
      answers: [
        "(a) creates",
        "(b) occurs",
        "(c) causes",
        "(d) violate",
        "(e) drive",
        "(f) gives",
        "(g) carrying",
        "(h) reach",
        "(i) suffer",
        "(j) solved",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Rajshahi",
    data: {
      questions:
        "We (a) --- to our nature for (b) --- us with her gifts lavishly. We (c) --- a large area of land but the negligible area of land that (d) --- to us, is very fertile. We (e) --- ungrateful to our soil. But our activities (f) --- that we have (g) --- ungrateful to our soil. We are constantly (h) --- soil pollution by our unwise activities. As a result, our fertile land is (i) --- its fertility which has (j) --- us to grow crops easily.",
      options: [
        "have",
        "bestow",
        "owe",
        "be",
        "belong",
        "enable",
        "cause",
        "show",
        "lose",
        "be",
      ],
      answers: [
        "(a) owe",
        "(b) bestowing",
        "(c) do not have",
        "(d) belongs",
        "(e) are not/should not be",
        "(f) show",
        "(g) been",
        "(h) causing",
        "(i) losing",
        "(j) enabled",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2020,
    board: "Dinajpur",
    data: {
      questions:
        'Education (a) ___ mankind. It (b)___ to light which (c) ___ the darkness of ignorance and helps us to distinguish between right and wrong. The primary purpose of education is the liberation of man from the restrictions of habits and attitudes which (d) ___ his humanity. In our country, the govt. (e) ___ "Food for Education Programme" so that every man (f)___ proper education. The govt. has taken such a programme with a view to (g) ___ the poor. In order to (h) ___ maximum benefit from education, we must (i) ___ our children morally so that they (j) ___ love for humanity.',
      options: [
        "educate",
        "enlighten",
        "get",
        "remove",
        "limit",
        "encourage",
        "ensure",
        "start",
        "compare",
        "have",
      ],
      answers: [
        "(a) enlightens",
        "(b) is compared",
        "(c) removes",
        "(d) limit",
        "(e) has started",
        "(f) can get",
        "(g) encouraging",
        "(h) ensure",
        "(i) educate",
        "(j) have",
      ],

      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Jashore",
    data: {
      questions:
        "Everybody (a) ____ that food adulteration (b)____ a crime. Adulterated food is poisonous and (c) ____ diseases. People (d) ____ this kind of food (e) ____ victim to liver disease, cancer, kidney failure and so on. Some businessmen who are avaricious and (f) ____ after money only (g) ____this heinous work. They (h) ____ on the miseries of others. They (i) ____ punishment. Some strict measures should be (j) ____ to stop this abominable task of the greedy businessmen.",
      options: [
        "take",
        "eat",
        "deserve",
        "be",
        "thrive",
        "cause",
        "run",
        "know",
        "fall",
        "do",
      ],
      answers: [
        "(a) knows",
        "(b) is",
        "(c) causes",
        "(d) eating",
        "(e) fall",
        "(f) running",
        "(g) do",
        "(h) thrive",
        "(i) deserve",
        "(j) taken",
      ],

      isDifficult: true,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2019,
    board: "Dhaka",
    data: {
      questions:
        "Patriotism is a noble virtue. It (a) --- a man to shed the last drop of blood to (b) --- the freedom of his country. A man without patriotism (c) --- not better than a beast. A true patriot (d) --- by all. He always (e) --- for the welfare of his country. On the other hand, the unpatriotic men (f) --- only for their own interest. Those who (g) --- for the country are true patriots. They (h) --- even after their death. That is why, the freedom fighters who (i) --- their lives in 1971 are remembered and (j) --- forever.",
      options: [
        "inspire",
        "defend",
        "be",
        "honor",
        "think",
        "die",
        "sacrifice",
      ],
      answers: [
        "(a) inspires",
        "(b) defend",
        "(c) is",
        "(d) is honored",
        "(e) thinks",
        "(f) think",
        "(g) die",
        "(h) are remembered",
        "(i) sacrificed",
        "(j) honored",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Barishal",
    data: {
      questions:
        "Patriotism is a noble virtue. It (a) --- a man to shed the last drop of blood to (b) --- the freedom of his country. A man without patriotism (c) --- not better than a beast. A true patriot (d) --- by all. He always (e) --- for the welfare of his country. On the other hand, the unpatriotic men (f) --- only for their own interest. Those who (g) --- for the country are true patriots. They (h) --- even after their death. That is why, the freedom fighters who (i) --- their lives in 1971 are remembered and (j) --- forever.",
      options: [
        "emerge",
        "be",
        "bring",
        "confine",
        "find",
        "give",
        "work",
        "earn",
      ],
      answers: [
        "(a) inspires",
        "(b) defend",
        "(c) is",
        "(d) is honored",
        "(e) works",
        "(f) work",
        "(g) die",
        "(h) are remembered",
        "(i) sacrificed",
        "(j) honored",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Chattogram",
    data: {
      questions:
        "One day Mina and her parrot, Mithu (a) --- a tall tree to pick a mango. She (b) --- mango and (c) --- it to her mother. Although Mina had picked the mango, her mother (d) --- the largest share of the fruit to Raju. Mina (e) --- very disappointed. At dinner Mina (f) --- that Raju as usual (g) --- an egg but she (h) --- not. Mithu was not pleased to see that. Mother (i) --- to see if the children (j) --- their hands before they started eating.",
      options: [
        "climb",
        "pick",
        "take",
        "give",
        "feel",
        "notice",
        "get",
        "do",
        "want",
        "wash",
      ],
      answers: [
        "(a) climbed",
        "(b) picked",
        "(c) took",
        "(d) gave",
        "(e) felt",
        "(f) noticed",
        "(g) got",
        "(h) did",
        "(i) wanted",
        "(j) had washed",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Cumilla",
    data: {
      questions:
        "Love for one's own country (a) --- as patriotism. Everyone should (b) --- a great love for his country. Many of our freedom-fighters (c) --- their lives in 1971 for the sake of our country. The countrymen (d) --- them forever. Some people are (e) --- persistently for the development of the country. They are also patriots. Everybody (f) --- a patriot. When any natural calamity (g) --- in the country, a patriot (h) --- by the affected people. We (i) --- the footprint of the patriots. We should refrain from (j) --- any crime that is harmful for our country.",
      options: [
        "know",
        "have",
        "sacrifice",
        "remember",
        "work",
        "respect",
        "occur",
        "stand",
        "follow",
        "commit",
      ],
      answers: [
        "(a) is known",
        "(b) have",
        "(c) sacrificed",
        "(d) will remember",
        "(e) working",
        "(f) respects",
        "(g) occurs",
        "(h) stands",
        "(i) should follow",
        "(j) committing",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Rajshahi",
    data: {
      questions:
        "In an educational institution teacher-student relationship is (a) --- to be the most important matter. It is such a relationship that is (b) --- on the basis of mutual (c) ---. A student always (d) --- to his teachers because he cannot but (e) --- help from them in case of (f)--- knowledge. The sensible students never (g) --- their teachers. Moreover, they (h) --- their memorable teachers' role which helps them (i) --- in life. So, they always (j) --- their teachers.",
      options: [
        "acquiring",
        "admit",
        "considered",
        "formed",
        "forget",
        "owes",
        "respect",
        "succeed",
        "take",
        "understanding",
      ],
      answers: [
        "(a) considered",
        "(b) formed",
        "(c) understanding",
        "(d) owes",
        "(e) take",
        "(f) acquiring",
        "(g) forget",
        "(h) admit",
        "(i) succeed",
        "(j) respect",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Sylhet",
    data: {
      questions:
        "At present Bangladesh (a)--- unemployment problem. This problem already (b)--- an alarming dimension. The government (c)--- to cope with this problem. But this problem cannot be (d)--- without (e)--- the unemployed skillful. So, education (f)--- a must. It (g)--- a man to get a job. Job does not mean (h)--- official work only. Self-employment is a solution of this problem. It means (i)--- oneself in economic activities. The government is giving financial help and training to the educated youths with a view to (j)--- them self-reliant.",
      options: [
        "face",
        "create",
        "try",
        "solve",
        "make",
        "be",
        "help",
        "do",
        "engage",
        "make",
      ],
      answers: [
        "(a) is facing",
        "(b) has created",
        "(c) is trying",
        "(d) solved",
        "(e) making",
        "(f) is",
        "(g) helps",
        "(h) doing",
        "(i) engaging",
        "(j) making",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Jashore",
    data: {
      questions:
        "Most of the students of our country are expert in (a)--- answers. They do not (b)--- notes themselves. They get them (c)--- by their tutors. Their tutors (d)--- their brain for the students. So, the (e)--- power of the students does not (f)---. They do not have any (g)--- on their language. They, of course, (h)--- well in the examination. But for this, they can (i)--- no credit of their own. This result does not (j)--- them in their later life.",
      options: [
        "memorize",
        "make",
        "prepare",
        "exercise",
        "think",
        "develop",
        "command",
        "do",
        "claim",
        "help",
      ],
      answers: [
        "(a) memorizing",
        "(b) make",
        "(c) prepared",
        "(d) exercise",
        "(e) thinking",
        "(f) develop",
        "(g) command",
        "(h) do",
        "(i) claim",
        "(j) help",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Dinajpur",
    data: {
      questions:
        "Adult allowance (a)--- a noble program initiated by the present government. In most of the developed countries of the world this kind of program is (b)--- by the government. The government should pursue that their old age is (c)--- and comfortable. But in our country the adult is (d)--- on their own sons or daughters. The adult loses the ability to work and (e)--- at this age. They (f)--- offensively by their own issues. They have to (g)--- their days depending on others. The allowance should be (h)--- and the true needy (i)--- to have this allowance. It is expected that the local leaders (j)--- their duty impartially to select the right person for this purpose.",
      options: [
        "be",
        "take",
        "secure",
        "depend",
        "earn",
        "treat",
        "pass",
        "increase",
        "allow",
        "do",
      ],
      answers: [
        "(a) is",
        "(b) taken",
        "(c) secured",
        "(d) dependent",
        "(e) earn",
        "(f) are treated",
        "(g) pass",
        "(h) increased",
        "(i) are allowed",
        "(j) will do",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2018,
    board: "All",
    data: {
      questions:
        "One day the great poet Ferdousi (a) — by Sultan Mahmood to (b) — Shahanama in honour of the Sultan. The Sultan (c) — to pay Ferdousi a gold coin for each verse. Ferdousi (d) — the writing and it (e) — found (f) — sixty thousand verses. Now Sultan (g) — to pay sixty thousand gold coins. He (h) — to pay silver coins instead of gold coins. The poet (i) — to take silver coins and (j) — to his village.",
      options: [
        "promise",
        "contain",
        "be",
        "return",
        "finish",
        "agree",
        "want",
        "ask",
        "refuse",
        "compose",
      ],
      answers: [
        "(a) was asked",
        "(b) compose",
        "(c) promised",
        "(d) finished",
        "(e) was",
        "(f) containing",
        "(g) wanted",
        "(h) refused",
        "(i) agreed",
        "(j) returned",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "ssc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        'Edison never (a) --- to school. All education that he ever got (b) --- to him by his mother. At the age of twelve, he was put to (c) --- on a railway. Having a great deal to do with newspapers, he (d) --- to pick up the art of (e) --- and he printed a newspaper of his own named "The Weekly Herald". One day he (f) --- a station-master\'s child which was nearly (g) --- over by a train. The station-master, out of gratitude, (h) --- him how to use the telegraph. Young Edison soon (i) --- great skill at the telegraph. When only twenty, Edison (j) --- a new telegraph which was extremely useful.',
      options: [
        "go",
        "give",
        "work",
        "manage",
        "print",
        "rescue",
        "run",
        "teach",
        "acquire",
        "invent",
      ],
      answers: [
        "(a) went",
        "(b) was given",
        "(c) work",
        "(d) managed",
        "(e) printing",
        "(f) rescued",
        "(g) run",
        "(h) taught",
        "(i) acquired",
        "(j) invented",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "There are several reasons why friendship (a) --- so necessary in human life. A man without a friend is like a man (b) --- in wilderness. Moreover, it (c) --- him to understand his surrounding in a better way. By (d) --- to a friend, a man can get relief. The advice (e) --- by a friend is sometimes more reliable than his own judgment. Thus, it is (f) --- that friendship is really important. But a man must (g) --- time while (h) --- a friend. If he (i) --- to select the right person as a friend, he (j) --- in the long run.",
      options: [
        "be",
        "live",
        "enable",
        "speak",
        "give",
        "see",
        "take",
        "choose",
        "fail",
        "suffer",
      ],
      answers: [
        "(a) is",
        "(b) living",
        "(c) enables",
        "(d) speaking",
        "(e) given",
        "(f) seen",
        "(g) take",
        "(h) choosing",
        "(i) fails",
        "(j) will suffer",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dinajpur",
    data: {
      questions:
        "Child labor has (a) --- internationally by the UN. To make a child (b) --- the work that's suitable for a man is punishable. Yet in the third world countries, the number of child-labor (c) --- up day by day. Bangladesh (d) --- one of these countries. Though government is committed to (e) --- rich people to engage children in laborious work, things are not so easy. Poverty (f) --- the first impediment in this field. The poor parents want to get additional earning by (g) --- their children in work. Many children (h) --- at different sectors now. But this should not be (i) --- on. We should immediately (j) --- this problem.",
      options: [
        "forbid",
        "do",
        "go",
        "be",
        "dissuade",
        "employ",
        "work",
        "carry",
        "address",
      ],
      answers: [
        "(a) been forbidden",
        "(b) do",
        "(c) is going",
        "(d) is",
        "(e) dissuade",
        "(f) is",
        "(g) employing",
        "(h) are working",
        "(i) carried",
        "(j) address",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Jashore",
    data: {
      questions:
        'One day a scholar (a) --- a river with a boat. Suddenly a ghastly wind (b) --- to blow. The scholar (c) --- with fear the boatman (d) --- him if he (e) --- how to swim. The answer from the scholar (f) --- negative. Then the boatman (g) ---, "Very soon you are going to (h) ---. You (i) --- a lot of knowledge but it (j) --- to use at this moment."',
      options: [
        "tremble",
        "say",
        "ask",
        "have",
        "come",
        "cross",
        "drown",
        "begin",
        "know",
        "be",
      ],
      answers: [
        "(a) was crossing",
        "(b) began",
        "(c) was trembling/trembled",
        "(d) asked",
        "(e) knew",
        "(f) was",
        "(g) said",
        "(h) drown",
        "(i) have",
        "(j) won't come",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Comilla",
    data: {
      questions:
        "English (a) --- (be) the most widely used international language. It (b) --- (learn) to communicate with the foreigners for various purposes such as (c) --- (maintain) cooperation, co-existence and exchanging business information. There are also certain jobs which (d) --- (require) a good functional knowledge of English. The jobs of a pilot, a postman, a telephone operator, a tour guide, a mechanic, a receptionist of an international hotel, an executive of a multinational firm etc. (e) --- (be) a few of them. Besides, a student (f) --- (wish) to go for higher studies must learn English because the books on advanced education are mostly (g) --- (write) in English. So, the importance and demand of learning English in our country can in no way, be (h) --- (ignore). Rather, we should (i) --- (put) high importance on (j) --- (learn) English to make room for ourselves in the competitive world.",
      options: [
        "is",
        "is learned",
        "maintaining",
        "require",
        "are",
        "wishing",
        "written",
        "ignored",
        "put",
        "learning",
      ],
      answers: [
        "(a) is",
        "(b) is learned",
        "(c) maintaining",
        "(d) require",
        "(e) are",
        "(f) wishing",
        "(g) written",
        "(h) ignored",
        "(i) put",
        "(j) learning",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Chattogram",
    data: {
      questions:
        "Price hike of household products (a) --- now a problem for us. Every day we (b) --- it. Most of our people (c) --- low income are in danger. They (d) --- of purchasing meat and fish as they (e) ---. The price of vegetables is also high. We are to bargain (f) --- simple product. Many times, the buyers (g) ---. There (h) --- a fixed price for every time. Then it (i) --- possible to make the buyers free from harassment. Government (j) --- to fulfil our expectation.",
      options: [
        "have",
        "think",
        "try",
        "be",
        "buy",
        "require",
        "face",
        "cheat",
      ],
      answers: [
        "(a) is",
        "(b) face",
        "(c) having",
        "(d) can't think",
        "(e) require",
        "(f) to buy",
        "(g) are cheated",
        "(h) should be",
        "(i) will be",
        "(j) is trying",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Barishal",
    data: {
      questions:
        "Malaria (a) — by a kind of mosquito. If a mosquito (b) — a man who (c) — malaria, it will carry away some of the germs of the disease. If this mosquito then bites a healthy man, the germs may (d) — into his blood and he gets malaria. Mosquitoes (e) — their eggs in the standing water. If there was no standing water, there would be no mosquitoes and so there (f) — no malaria. Sometimes, people (g) — kerosene oil on standing water and this (h) — the mosquitoes before they (i) — big enough to (j) — away.",
      options: [
        "kill",
        "have",
        "fly",
        "get",
        "carry",
        "put",
        "lay",
        "bite",
        "be",
        "would be",
      ],
      answers: [
        "(a) is carried",
        "(b) bites",
        "(c) has",
        "(d) get",
        "(e) lay",
        "(f) would be",
        "(g) put",
        "(h) kills",
        "(i) are",
        "(j) fly",
      ],

      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Sylhet",
    data: {
      questions:
        "A walk by the riverside in the evening (a) --- very useful and pleasant. One (b) --- not only beautiful sight but also (c) --- fresh air. It (d) --- the mind when one (e) --- a walk by the river-side. Bangladesh is a riverine country and you can (f) --- yourself of this opportunity of (g) --- by the riverside. In the cities there are parks where you can go for a walk. This will help you (h) --- fit. But if you (i) --- it regularly, you will not be able to (j) --- the benefit.",
      options: [
        "act",
        "be",
        "refresh",
        "enjoy",
        "take",
        "reap",
        "walk",
        "avail",
        "keep",
        "do",
      ],
      answers: [
        "(a) is",
        "(b) enjoys",
        "(c) gets",
        "(d) refreshes",
        "(e) takes",
        "(f) avail",
        "(g) walking",
        "(h) keep",
        "(i) do not do",
        "(j) reap",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "Bangladesh is full of natural resources. The prosperity of the country (a) --- on the proper utilization of the resources. We should not (b) --- a lazy life. We should all (c) --- up our country. For this reason, we have to (d) --- hard. No nation can prosper without industry. It should be (e) --- that industry is the key to success. If we (f) --- the days away, we (g) --- behind. The nations that (h) --- industrious (i) --- the pinnacle of development. So we (j) --- them.",
      options: [
        "build",
        "idle",
        "remember",
        "be",
        "work",
        "lag",
        "reach",
        "depend",
        "lead",
        "follow",
      ],
      answers: [
        "(a) depends",
        "(b) lead",
        "(c) build",
        "(d) work",
        "(e) remembered",
        "(f) idle",
        "(g) will lag",
        "(h) are",
        "(i) have reached",
        "(j) should follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "Happiness (a) --- a relative term. A person with a crown (b) --- in a palace may not be happy whereas a day labourer may (c) --- happiness (d) --- in a shabby hut. Again happiness (e) --- from person to person. A beggar (f) --- be happy if he (g) --- a coin but a businessman who can (h) --- a huge sum of money a day (i) --- not be happy. Everyone (j) --- to be happy.",
      options: ["vary", "can", "have", "want", "live", "may", "spend", "get"],
      answers: [
        "(a) is",
        "(b) living",
        "(c) have",
        "(d) living",
        "(e) varies",
        "(f) can",
        "(g) gets",
        "(h) earn",
        "(i) may",
        "(j) wants",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        "The Republic of Maldives (a) --- one of the smallest countries of South Asia. It (b) --- 1199 islands that (c) --- into 26 major atolls. People who (d) --- to these islands from different parts of the world (e) --- here since 3000 years ago. The natural beauties (f) --- by the God attract the tourists to enjoy them. As a result, a lot of foreign currencies (g) --- every year from the tourism that (h) --- a lot to the national economy. So, the Maldives (i) --- as the best tourist destination. Special importance (j) --- by the government of the Maldives for the enhancement of tourism.",
      options: [
        "come",
        "rank",
        "be",
        "gift",
        "give",
        "has",
        "live",
        "contribute",
        "cluster",
        "earn",
      ],
      answers: [
        "(a) is",
        "(b) has",
        "(c) are clustered",
        "(d) came",
        "(e) have lived",
        "(f) gifted",
        "(g) are earned",
        "(h) contributes",
        "(i) ranks",
        "(j) is given",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Comilla",
    data: {
      questions:
        '"Health (a) --- wealth," (b) --- the proverb. We cannot (c) --- it. We cannot (d) --- it. We must (e) --- our body by (f) --- the rules of health. People (g) --- against germs that (h) --- the body since their birth. Medicines (i) --- to kill germs, but we have to (j) --- the body fit by ourselves through the maintenance of the rules of health.',
      options: [
        "struggle",
        "keep",
        "purchase",
        "harm",
        "go",
        "invent",
        "build",
        "follow",
        "be",
        "borrow",
      ],
      answers: [
        "(a) is",
        "(b) goes",
        "(c) purchase",
        "(d) borrow",
        "(e) keep",
        "(f) following",
        "(g) struggle",
        "(h) harm",
        "(i) are invented",
        "(j) keep",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Chattogram",
    data: {
      questions:
        "Many students (a) --- their studies from the beginning of the year. When the examination (b) ---, they start (c) --- very seriously. Sometimes they (d) --- notes from their friends. Most of the time they get their notes (e) --- by their private tutors. They (f) --- these notes without (g) ---. As a result, their power of (h) --- does not develop. If they find any new question in the examination, they can't (i) --- it properly. As a result, many students can't do well in the examination. If they had read seriously from the very beginning of the year, they (j) --- better result in the examinations.",
      options: [
        "understand",
        "answer",
        "approach",
        "neglect",
        "memorize",
        "read",
        "collect",
        "prepare",
        "think",
        "do",
      ],
      answers: [
        "(a) neglect",
        "(b) approaches",
        "(c) reading",
        "(d) collect",
        "(e) prepared",
        "(f) memorize",
        "(g) understanding",
        "(h) understanding",
        "(i) answer",
        "(j) would have done",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "Men (a) --- ever since they first appeared on the earth. In primitive time, they did not travel for pleasure but to find new places. They (b) --- themselves with simple weapons. Their journeys (c) --- long, tiring and often dangerous. Being intelligent, they soon (d) --- easier ways of travelling. They (e) --- on the backs of their domestic animals. They (f) --- boat and used it to travel across water. Travelling, of course, has now (g) --- a highly organised business. There are vehicles which (h) --- us with comforts and security. If we want to go abroad, we (i) --- a passport and a visa. If we (j) --- any of them, our journey may be ruined.",
      options: [
        "lose",
        "protect",
        "ride",
        "become",
        "need",
        "discover",
        "travel",
        "be",
        "provide",
        "make",
      ],
      answers: [
        "(a) have travelled",
        "(b) protected",
        "(c) were",
        "(d) discovered",
        "(e) rode",
        "(f) made",
        "(g) become",
        "(h) provide",
        "(i) need",
        "(j) lose",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Jessore",
    data: {
      questions:
        "At present Bangladesh (a) --- unemployment problem. This problem already (b) --- an alarming dimension. The government (c) --- to cope with this problem. But this problem cannot be (d) --- without (e) --- them skillful. Education (f) --- a must. It (g) --- a man to get a job. Job does not mean (h) --- official work only. Self-employment is a solution of this problem. It means (i) --- oneself in economic activities. The government is giving the educated youths financial help and training with a view to (j) --- them self-reliant.",
      options: [
        "engage",
        "do",
        "turn",
        "face",
        "be",
        "help",
        "solve",
        "make",
        "try",
        "create",
      ],
      answers: [
        "(a) faces",
        "(b) has created",
        "(c) is trying",
        "(d) solved",
        "(e) making",
        "(f) is",
        "(g) helps",
        "(h) doing",
        "(i) engaging",
        "(j) making",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2016,
    board: "Barishal",
    data: {
      questions:
        "The other name of water is life. We cannot (a) ___ a single moment without it. Water is (b) ___ not only for drinking purposes but also for household works and industrial works. Water becomes (c) ___ in many ways. The mills and factories pollute water by (d) ___ waste into it. Water (e) ___ polluted by chemicals and different elements. Sometimes people (f) ___ from many diseases. We should (g) ___ very careful about it. We must (h) ___ for safe source of drinking water. Otherwise we must (i) ___ in danger. Let us (j) ___ water from pollution.",
      options: [
        "pollute",
        "suffer",
        "save",
        "do",
        "look",
        "fall",
        "become",
        "be",
        "use",
        "throw",
      ],
      answers: [
        "(a) do",
        "(b) used",
        "(c) polluted",
        "(d) throwing",
        "(e) becomes",
        "(f) suffer",
        "(g) be",
        "(h) look",
        "(i) fall",
        "(j) save",
      ],

      isDifficult: false,
      isCompleted: false,
    },
  },

  {
    exam: "ssc",
    year: 2015,
    board: "Dhaka",
    data: {
      questions:
        "Today women are playing an important role in all spheres of life. Once they were (a) --- by men. They are no longer (b) --- within the four walls of their parents' or husbands' house. They have (c) --- out of the kitchen and are (d) --- hand in hand with men. By (e) --- higher education, they are becoming pilots, doctors, engineers, teachers, administrators etc. They have (f) --- able to prove their worth. They (g) --- much to the economy of the country. Now, it (h) --- to the realization of the men that true development of the country is never possible (i) --- half of the population idle at home. So, it (j) --- no telling that women are playing a great role in the socio-economic condition of the country.",
      options: [
        "take",
        "work",
        "come",
        "dominate",
        "confine",
        "contribute",
        "be",
        "need",
        "keep",
        "come",
      ],
      answers: [
        "(a) dominated",
        "(b) confined",
        "(c) come",
        "(d) working",
        "(e) taking",
        "(f) been",
        "(g) are contributing",
        "(h) has come",
        "(i) by keeping",
        "(j) needs",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Chittagong",
    data: {
      questions:
        "Today women (a) --- an important role in all spheres of life. They no longer (b) --- to the four walls of their husband's house. They have (c) --- out of their kitchens and (d) --- hand in hand with men in all the development works of the government. By (e) --- higher education they (f) --- pilots, doctors, engineers, teachers, administrators etc. They have (g) --- able to prove their worth. They (h) --- much to the economy of the country. Now it has (i) --- to the realization of the men that true development of the country is never possible (j) --- half of the population idle at home.",
      options: [
        "contribute",
        "come",
        "be",
        "play",
        "keep",
        "need",
        "receive",
        "work",
        "confine",
        "be",
      ],
      answers: [
        "(a) are playing",
        "(b) are confined",
        "(c) come",
        "(d) are working",
        "(e) receiving",
        "(f) are becoming",
        "(g) been",
        "(h) are contributing",
        "(i) come",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Rajshahi",
    data: {
      questions:
        "According to the history, women in the past were (a) --- within the four walls. But at present they (b) --- no longer captive to their parents' or husbands' house. With the passage of time the outlook and attitude have been (c) --- as men and women are (d) --- themselves with the changing society. By (e) --- education they are (f) --- pilots, doctors, engineers, high officials etc. They are (g) --- hand in hand with men in all worthy programmes. They (h) --- now able to prove their worth. They (i) --- much to the economy of the country. Now it has come to the realization of men that no development is possible by (j) --- half of our population idle at home.",
      options: [
        "contribute",
        "confine",
        "keep",
        "enable",
        "work",
        "develop",
        "receive",
        "become",
        "adopt",
        "be",
      ],
      answers: [
        "(a) confined",
        "(b) are",
        "(c) developed",
        "(d) adapting",
        "(e) receiving",
        "(f) becoming",
        "(g) working",
        "(h) are",
        "(i) contribute",
        "(j) keeping",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Barisal",
    data: {
      questions:
        "Traffic jam (a) --- a common affair in the big cities of our country. This problem (b) --- the ultimate consequences of rapid growth of population and the number of vehicles. Most often this problem (c) --- in the congested areas where the roads are very narrow. Overtaking tendency also (d) --- traffic jam. Some drivers (e) --- the traffic rules. They (f) --- the vehicles carelessly. Traffic jam (g) --- great sufferings to the ambulances (h) --- patients. Office goers and school going children also (i) --- a lot due to traffic jam. However, this problem (j) --- to an extent by imposing traffic rules strictly.",
      options: [
        "cause",
        "suffer",
        "be",
        "drive",
        "solve",
        "be",
        "obey",
        "occur",
        "carry",
      ],
      answers: [
        "(a) is",
        "(b) is",
        "(c) occurs",
        "(d) causes",
        "(e) do not obey",
        "(f) drive",
        "(g) causes",
        "(h) carrying",
        "(i) suffer",
        "(j) should be solved",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Sylhet",
    data: {
      questions:
        "You must have (a) --- the name of Kazi Nazrul Islam. He (b) --- our national poet. He (c) --- as a rebel poet as well. But he (d) --- in a poor family. But dire needs could not (e) --- his personality. When the first World War broke out, he (f) --- the army. After the war, he (g) --- to write poems. He wrote especially for the downtrodden. He (h) --- the Shelley of Bangla Literature. His poems and songs (i) --- the Bangalee in Liberation War. So we should (j) --- his footprints in our life.",
      options: [
        "be",
        "call",
        "hear",
        "engulf",
        "know",
        "begin",
        "bear",
        "follow",
        "inspire",
        "join",
      ],
      answers: [
        "(a) heard",
        "(b) is",
        "(c) is known",
        "(d) was born",
        "(e) engulf",
        "(f) joined",
        "(g) began",
        "(h) is called",
        "(i) inspired",
        "(j) follow",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
];
