export const suffixPrefix = [
  {
    exam: "ssc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "We should bear in mind that habit is the second nature of human being. If anyone becomes (a) ---(custom)--- to good manners he can't (b) ---(behave)--- with anyone. So, moral (c) ---(educate)--- is important. From the early part of life, (d) ---(child)--- must be taught the (e) ---(differ)--- between right and wrong and trained to follow what is right and what is wrong. Here --- Ø ---(train)--- means the (g) ---(form)--- of habit on right lines. It is every parent's (h) ---(responsible)--- to teach their children moral lessons at home. They also have to (i) ---(sure)--- that their children do not mix with any bad company. The moral (j) ---(teach)--- at an early age will help them become good citizens in future.",
      answers: [
        "(a) accustomed",
        "(b) misbehave",
        "(c) education",
        "(d) children",
        "(e) difference",
        "(f) training",
        "(g) formation",
        "(h) responsibility",
        "(i) ensure",
        "(j) teachings",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "Malnutrition is a great problem in our society. It is because our common people are very often (a) ______ (aware) of the food value. They don't know which foods are (b) ______ (nutrition) and which foods are not. They only prefer costly and (c) ______ (taste) food. For this reason, many of them suffer from (d) ______ (very) health problems. Many of the parents let their (e) ______ (child) eat excessive fast food. As a result, children get (f) ______ (bulk) and lead an (g) ______ (health) life. Though some people spend much money for food, they hardly understand the (h) ______ (important) of a balanced diet and for eating (i) ______ (proper) diet their children suffer from the (j) ______ (deficient) of vitamins, minerals or other elements of foods and for this reason, they cannot enjoy a healthy life.",
      answers: [
        "(a) unaware",
        "(b) nutritious",
        "(c) tasty",
        "(d) various",
        "(e) children",
        "(f) bulky",
        "(g) unhealthy",
        "(h) importance",
        "(i) improper",
        "(j) deficiency",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "(a) ______ (persevere) is needed to be (b) ______ (success) in life. Those who are not persevere in life, become (c) ______ (success) in their mission and only blame their lot for their (d) ______ (fortune). (e) ______ (persevere) people do not fail. (f) ______ (sincere) is another important virtue which (g) ______ (able) a person to accomplish a job (h) ______ (fruit). Student life is the (i) ______ (form) period of man's life. One should not (j) ______ (use) this period of life.",
      answers: [
        "(a) Perseverance",
        "(b) successful",
        "(c) unsuccessful",
        "(d) misfortune",
        "(e) Perseverant",
        "(f) Sincerity",
        "(g) enables",
        "(h) fruitfully",
        "(i) formative",
        "(j) misuse",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "Our national (a) ______ (memory) symbolizes the nation's respect for the martyrs of the (b) ______ (liberate) war. It is an (c) ______ (achieve) which is (d) ______ (measure). Our (e) ______ (free) fighters showed their unique (f) ______ (hero) in the war against the well armed soldiers of Pakistan. The Pakistani soldiers killed our people (g) ______ (mercy). They continued atrocities in (h) ______ (associate) with the local (i) ______ (collaborate). (j) ______ (exet), they were defeated in the end.",
      answers: [
        "(a) memorial",
        "(b) liberation",
        "(c) achievement",
        "(d) immeasurable",
        "(e) freedom",
        "(f) heroism",
        "(g) mercilessly",
        "(h) association",
        "(i) collaborators",
        "(j) However",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "The (a) ______ (ward) beauty of a man is not his real beauty. His (b) ______ (ward) beauty makes him a true man. Everyman has certain (c) ______ (born) qualities whereby he can become a useful man and thus a (d) ______ (celebrate) person. So, we may say that (e) ______ (in) values are more (f) ______ (import) than outer one. But, it is very sad that we remain (g) ______ (care) about mental development. We always (h) ______ (main) busy with how to (i) ______ (rich) our outer show which is really (j) ______ (value).",
      answers: [
        "(a) outward",
        "(b) inward",
        "(c) inborn",
        "(d) celebrated",
        "(e) inner",
        "(f) important",
        "(g) careless",
        "(h) remain",
        "(i) enrich",
        "(j) valueless",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "(a) ______ (kind) is a divine virtue. So we should not be (b) ______ (kind) to the people in distress and even to the (c) ______ (low) animals. Some naughty boys (d) ______ (joy) beating the lower animals like dogs and cats. This is an (e) ______ (rational) behaviour. They are (f) ______ (harm). They are dumb (g) ______ (create). Some animals are very (h) ______ (faith) and they feel no (i) ______ (hesitate) to risk their lives for our (j) ______ (protect).",
      answers: [
        "(a) Kindness",
        "(b) unkind",
        "(c) lower",
        "(d) enjoy",
        "(e) irrational",
        "(f) harmless",
        "(g) creatures",
        "(h) faithful",
        "(i) hesitation",
        "(j) protection",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "Smart Bangladesh is a new term. It refers to the vision of (a) ______ (make) Bangladesh technologically advanced and digitally (b) ______ (empower) nation. The (c) ______ (govern) has changed the name of (d) ______ (digit) Bangladesh to smart Bangladesh. Smart Bangladesh means making smart citizens, society, economy and smart government. Activities in (e) ______ (educate), health, agriculture and financial sector will be (f) ______ (transform) into smart system. In smart Bangladesh, everything will be done (g) ______ (technology) and also the urban (h) ______ (admin) will be directed by the computer and internet. A smart village will be a rural community where local citizens can connect with the (i) ______ (globe) market through the use of digital technology and open innovative platforms. Smart Bangladesh is not just a vision but a reality that (j) ______ (rapid) taking shape and marching ahead.",
      answers: [
        "(a) Making",
        "(b) empowered",
        "(c) governmental",
        "(d) digital",
        "(e) education",
        "(f) transformed",
        "(g) technologically",
        "(h) administration",
        "(i) global",
        "(j) rapidly",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "There are (a) ______ (vary) forms of physical exercise. But every form is not (b) ______ (suit) for all. Walking is good for all. In the morning, fresh air is (c) ______ (avail). So it is (d) ______ (benefit) to health. It is also very (e) ______ (please) and (f) ______ (enjoy). It also (g) ______ (freshes) our mind. The (h) ______ (nature) beauty (i) ______ (witch)-us. We become (j) ______ (health) and wealthy.",
      answers: [
        "(a) various",
        "(b) suitable",
        "(c) available",
        "(d) beneficial",
        "(e) pleasing",
        "(f) enjoyable",
        "(g) refreshes",
        "(h) natural",
        "(i) bewitches",
        "(j) healthy",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Dhaka",
    data: {
      questions:
        "Books are our best friends. They introduce us to the realm of (a) ______ (limit) knowledge. The books of great (b) ______ (write) contain noble thoughts and great ideas. We can (c) ______ (rich) our mind by reading books. The reading of books brings (d) ______ (perfect). No spiritual progress and worldly (e) ______ (prosper) can be imagined (f) ______ (with) reading books. (g) ______ (True) speaking, reading books is such a thing which has no (h) ______ (alternate). So, we should read books on (i) ______ (vary) topics so that we may bring proper (j) ______ (develop) of our spirit.",
      answers: [
        "(a) unlimited",
        "(b) writers",
        "(c) enrich",
        "(d) perfection",
        "(e) prosperity",
        "(f) without",
        "(g) Truly",
        "(h) alternative",
        "(i) various",
        "(j) development",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Cumilla",
    data: {
      questions:
        "The other name of water is life. Clean water is (a) ______ (drink). Dirty water is (b) ______ (safe). Clean water is (c) ______ (contaminate) and (d) ______ (suit) for drinking. Bangladesh is a (e) ______ (river) country. But we get (f) ______ (adequate) water for use. The water of most of our rivers is (g) ______ (filth) and (h) ______ (poison). We should keep surface water clean for our health and (i) ______ (long). The government should play an (j) ______ (act) role to keep water safe.",
      answers: [
        "(a) drinkable",
        "(b) unsafe",
        "(c) uncontaminated",
        "(d) suitable",
        "(e) riverine",
        "(f) inadequate",
        "(g) filthy",
        "(h) poisonous",
        "(i) longevity",
        "(j) active",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Chattogram",
    data: {
      questions:
        "Mobile phone is a great (a) ______ (invent) of modern science. The (b) ______ (consume) of mobile phone are increasing day by day. People are getting benefits. But it is (c) ______ (fortunate) that mobile phone sometimes (d) ______ (come) a cause of health hazard, especially the (e) ______ (child) are affected much. According to the (f) ______ (science) mobile phone causes brain tumours, genetic damage and many other (g) ______ (cure) diseases. They believe that (h) ______ (visible) uncontrolled radioactivity of mobile phone causes (i) ______ (repairable) damage to human body. They say that the (j) ______ (govern) should control radioactive sources.",
      answers: [
        "(a) invention",
        "(b) consumers",
        "(c) unfortunate",
        "(d) becomes",
        "(e) children",
        "(f) scientists",
        "(g) incurable",
        "(h) invisible",
        "(i) irreparable",
        "(j) government",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Dinajpur",
    data: {
      questions:
        "Honey is (a) ______ (nature) produced by honey bees through (b) ______ (collect) of nectar from (c) ______ (differ) flowers and then store them in the hive. But now-a-days there are (d) ______ (keep) who rear bees in (e) ______ (wood) hives and produce honey (f) ______ (commercial). This is (g) ______ (full) chemical and hazard free activity. With the support of the govt. and (h) ______ (government) organizations (i) ______ (approximate) 300 bee keepers have been trained for honey (j) ______ (produce).",
      answers: [
        "(a) naturally",
        "(b) collecting",
        "(c) different",
        "(d) beekeepers",
        "(e) wooden",
        "(f) commercially",
        "(g) fully",
        "(h) non-government",
        "(i) approximately",
        "(j) production",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Jashore",
    data: {
      questions:
        "A computer consists of both hardwares and softwares. The (a) ______ (touch) components are called hardwares. On the other hand the (b) ______ (touchable) programmes are called softwares. Hardwares and softwares are interdependent. Without one, the other is (c) ______ (value). Software (d) ______ (design) are called software engineers. Software engineering is a (e) ______ (demand) subject in a university. A well designed software can solve any problem. Business organizations (f) ______ (include) banks are completely dependent on softwares. In fact, office (g) ______ (manage) can't be thought of without the application of proper softwares. For the (h) ______ (develop) of our software industry, the government has already set up a number of hightec parks. Our software engineers are working (i) ______ (restless) to develop newer softwares to make our life easy and (j) ______ (comfort).",
      answers: [
        "(a) touchable",
        "(b) untouchable",
        "(c) valueless",
        "(d) designers",
        "(e) demanding",
        "(f) including",
        "(g) management",
        "(h) development",
        "(i) restlessly",
        "(j) comfortable",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Mymensingh",
    data: {
      questions:
        "Life without leisure and (a) ______ (relax) is dull. Life becomes (b) ______ (charm) if one does not have any time to enjoy the (c) ______ (beauty) objects of nature. (d) ______ (monotony) work hinders the (e) ______ (smooth) of work. Leisure (f) ______ (rich) our spirit to work. Everybody knows that (g) ______ (work) is (h) ______ (harm). Leisure does not mean (i) ______ (idle). It gives freshness by (j) ______ (charge) our energy.",
      answers: [
        "(a) relaxation",
        "(b) charmless",
        "(c) beautiful",
        "(d) monotonous",
        "(e) smoothness",
        "(f) enriches",
        "(g) overwork",
        "(h) harmful",
        "(i) idleness",
        "(j) recharging",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Rajshahi",
    data: {
      questions:
        "The nature of mother's love is the same in all countries. It is (a) ______ (universe). For our (b) ______ (exist) on earth, we (c) ______ (great) owe to our father and mother, (d) ______ (special) to our mother. A mother's love is (e) ______ (parallel) and unique. A child's (f) ______ (relate) with its mother is (g) ______ (heaven) and (h) ______ (spirit). We can (i) ______ (hard) see a mother (j) ______ (different) to her children.",
      answers: [
        "(a) universal",
        "(b) existence",
        "(c) greatly",
        "(d) especially",
        "(e) unparalleled",
        "(f) relation",
        "(g) heavenly",
        "(h) spiritual",
        "(i) hardly",
        "(j) indifferent",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2024,
    board: "Sylhet",
    data: {
      questions:
        "Child labour is considered a matter of (a) ______ (grace) for a nation. Wherever children are employed either it is domestic work or factory work, either it is rickshaw pulling or working in a shop or hotel, they are (b) ______ (treated). Their (c) ______ (employ) don't give them their due rights. Children work for longer period in (d) ______ (healthy) and (e) ______ (favourable) condition and what is (f) ______ (sorrow) they are not given due wages. Many children do the work of the adults and often do the (g) ______ (risk) and (h) ______ (danger) work. Strict laws should be (i) ______ (forced) against employing children in manual work. Their parents should be (j) ______ (courage) to send their children to school.",
      answers: [
        "(a) disgrace",
        "(b) maltreated",
        "(c) employers",
        "(d) unhealthy",
        "(e) unfavourable",
        "(f) sorrowful",
        "(g) risky",
        "(h) dangerous",
        "(i) enforced",
        "(j) encouraged",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Chattogram",
    data: {
      questions:
        "Vocabulary is very important in learning a language properly. To (a) ___ (rich) your vocabulary, you have to read books and learn new words by knowing their meanings (b) ___ (accurate). You may use a dictionary to know the (c) ___ (known) words or try to understand the (d) ___ (context) meaning of them. Repeated reading will help you understand the (e) ___ (specify) topic (f) ___ (clear) and use them in (g) ___ (vary) situations. Language learning is a (h) ___ (continue) process and your (i) ___ (proficient) will come today or tomorrow. What is needed most is (j) ___ (continue). It also needs your (k) ___ (sincere). A common language is required for (l) ___ (interact) among people from (m) ___ (differ) countries and contexts. Without a common language it is difficult to perform activities at the (n) ___ (nation) level.",
      answers: [
        "(a) enrich",
        "(b) accurately",
        "(c) unknown",
        "(d) contextual",
        "(e) specific",
        "(f) clearly",
        "(g) various",
        "(h) continuous",
        "(i) proficiency",
        "(j) continuation",
        "(k) sincerity",
        "(l) interaction",
        "(m) different",
        "(n) international",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Cumilla",
    data: {
      questions:
        "Facebook is a social (a) ___ (network) site. It has gained much (b) ___ (popular) among the young (c) ___ (generate). Sometimes, our young generation waste their (d) ___ (value) time by (e) ___ (browse) facebook. So, in this respect parental (f) ___ (supervise) is a must. Many people (g) ___ (fine) facebook as an (h) ___ (embarrass) (i) ___ (invade) on others' (j) ___ (person) privacy. However, it plays a (k) ___ (signify) role in (l) ___ (socialize) as well as (m) ___ (nature) understanding and (n) ___ (operation).",
      answers: [
        "(a) networking",
        "(b) popularity",
        "(c) generation",
        "(d) valuable",
        "(e) browsing",
        "(f) supervision",
        "(g) define",
        "(h) embarrassing",
        "(i) invasion",
        "(j) personal",
        "(k) significant",
        "(l) socialization",
        "(m) natural",
        "(n) co-operation",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Barishal",
    data: {
      questions:
        "Bangladesh is blessed with many seasons. Winter is one of them. It is the (a) ___ (cold) of all seasons. It is usually (b) ___ (rain). Though ours is a small country, the (c) ___ (cold) of winter is not (d) ___ (equal) felt in all regions. In some regions, (e) ___ (special) in the (f) ___ (north) districts, people experience (g) ___ (bite) cold in winter. Nature looks dull and (h) ___ (gloom). During night and morning, the whole of nature remains (i) ___ (cover) with fog and mist. Then the poor suffer (j) ___ (great) for want of warm clothes. Again in some (k) ___ (hill) areas there is (l) ___ (severe) of cold. (m) ___ (where) in the vast (n) ___ (South) areas people experience less cold.",
      answers: [
        "(a) coldest",
        "(b) rainless",
        "(c) coldness",
        "(d) equally",
        "(e) especially",
        "(f) northern",
        "(g) biting",
        "(h) gloomy",
        "(i) covered",
        "(j) greatly",
        "(k) hilly",
        "(l) severity",
        "(m) whereas",
        "(n) southern",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Dhaka",
    data: {
      questions:
        "Knowledge (a) ___ (light) our mind. It enables a man to have (b) ___ (master) over all forces of nature. There are so many wild beasts which are (c) ___ (strong) than man. There are forces in nature such as (d) ___ (light) and thunder, flood and earthquake, etc. which can destroy a man and (e) ___ (civil) in a moment. But a man rules over them all and makes them serve (f) ___ (accord) to his wish. He makes use of the solar power to (g) ___ (bright) the night. He is the (h) ___ (conquer) of time and space. All discoveries and (i) ___ (invent) are the results of (j) ___ (know). It makes him (k) ___ (doubt) the mightiest of all the (l) ___ (create) in the universe. To maintain (m) ___ (superior) man has to work (n) ___ (through) his life.",
      answers: [
        "(a) enlightens",
        "(b) mastery",
        "(c) stronger",
        "(d) lightning",
        "(e) civilization",
        "(f) according",
        "(g) brighten",
        "(h) conqueror",
        "(i) inventions",
        "(j) knowledge",
        "(k) undoubtedly",
        "(l) creations",
        "(m) superiority",
        "(n) throughout",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Jashore",
    data: {
      questions:
        "In ancient time, textbook was the most (a) ___ (resource) thing for a student. (b) ___ (teach) were only guides and source of (c) ___ (inform). The students had to collect all (d) ___ (inform) news from their teachers. There was hardly any guide book or other (e) ___ (refer) book in the market. So, teachers gave (f) ___ (deliver) of a lecture by studying the text books, and so the students had (g) ___ (depend) on their teachers' (h) ___ (proficient). As a result, there existed (i) ___ (measure) relationship between them. The (j) ___ (popular) of these great teachers was never on the wane. Students had (k) ___ (devote) to maintain a healthy relation with their (l) ___ (honour) teachers. Teachers also maintained an ever bond of (m) ___ (friend) with their (n) ___ (affection) students.",
      answers: [
        "(a) resourceful",
        "(b) Teachers",
        "(c) information",
        "(d) informative",
        "(e) reference",
        "(f) delivery",
        "(g) dependence",
        "(h) proficiency",
        "(i) immeasurable",
        "(j) popularity",
        "(k) devotion",
        "(l) honourable",
        "(m) friendship",
        "(n) affectionate",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Rajshahi",
    data: {
      questions:
        "Bangladesh is mainly a (a) ___ (river) and (b) ___ (agriculture) country. (c) ___ (major) of her people live in villages and most of them are farmers. (d) ___ (fortunate), the condition of our farmers is (e) ___ (satisfactory). They can (f) ___ (hard) lead a carefree life. Their life is full of miseries and (g) ___ (advantages). They can't plough their land (h) ___ (proper) due to (i) ___ (finance) and (j) ___ (technology) support. They need assistance from the (k) ___ (govern) to come out of their age-old (l) ___ (convention) method. Scientific system of cultivation is going to be (m) ___ (gradual) successful and (n) ___ (effect).",
      answers: [
        "(a) riverine",
        "(b) agricultural",
        "(c) Majority",
        "(d) Unfortunately",
        "(e) unsatisfactory",
        "(f) hardly",
        "(g) disadvantages",
        "(h) properly",
        "(i) financial",
        "(j) technological",
        "(k) government",
        "(l) conventional",
        "(m) gradually",
        "(n) effective",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Dinajpur",
    data: {
      questions:
        "The purpose of (a) ___ (educate) is to make a man fully (b) ___ (equip) to be (c) ___ (use) to himself and to society. A (d) ___ (true) educated person should be self-reliant with regard to his (e) ___ (person) needs. He should be well-mannered (f) ___ (thought), sympathetic and (g) ___ (operative). He should be (h) ___ (truth), honest, punctual and (i) ___ (duty). (j) ___ (punctual) is a virtue that makes a nation (k) ___ (prosper). An educated person tries to (l) ___ (move) the (m) ___ (suffer) of his countrymen. He also helps others in attaining (n) ___ (self-reliant).",
      answers: [
        "(a) education",
        "(b) equipped",
        "(c) useful",
        "(d) truly",
        "(e) personal",
        "(f) thoughtful",
        "(g) cooperative",
        "(h) truthful",
        "(i) dutiful",
        "(j) Punctuality",
        "(k) prosperous",
        "(l) remove",
        "(m) sufferings",
        "(n) self-reliance",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2023,
    board: "Mymensingh",
    data: {
      questions:
        "The freedom fighters are the (a) ___ (hero) sons of our land. They fought to save our (b) ___ (gold) Bangla in 1971. We have got the (c) ___ (independent) of our loving motherland by their (d) ___ (super) sacrifice. Some of the (e) ___ (free) fighters are still (f) ___ (live). Most of the freedom (g) ___ (fight) are now (h) ___ (actual) above 70 years old. (i) ___ (deed), we are very (j) ___ (luck) to see them (k) ___ (direct). As they are our heroic sons, we should respect them (l) ___ (profound). We must remember them (m) ___ (ever). Because they laid down their lives (n) ___ (keep) all behind.",
      answers: [
        "(a) heroic",
        "(b) golden",
        "(c) independence",
        "(d) supreme",
        "(e) freedom",
        "(f) alive",
        "(g) fighters",
        "(h) actually",
        "(i) Indeed",
        "(j) lucky",
        "(k) directly",
        "(l) profoundly",
        "(m) forever",
        "(n) keeping",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Dinajpur",
    data: {
      questions:
        "The nature of a mother's love is the same in all countries. It is (a) --- (universe) for our (b) --- (exist) on earth, we (c) --- (great) owe to our father and mother. (d) --- (special) to our mother. A mother's love is (e) --- (parallel) and unique. A child's (f) --- (relate) with its mother is (g) --- (heaven) and (h) --- (spirit). We (i) --- (different) see a mother (j) --- (care) to her child's well-being.",
      answers: [
        "(a) universal",
        "(b) existence",
        "(c) greatly",
        "(d) especially",
        "(e) unparalleled",
        "(f) relationship/relation",
        "(g) heavenly",
        "(h) spiritual",
        "(i) hardly",
        "(j) indifferent",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Cumilla",
    data: {
      questions:
        "(a) --- (Forestation) means cutting down of trees (b) --- (discriminately). Bangladesh is a (c) --- (dense) populated country. This huge population needs more shelter, (d) --- (agriculture) land, fuel, and furniture, etc. For all these reasons, people cut trees. Moreover, there are (e) --- (honest) people who cut trees for making money (f) --- (legally). The (g) --- (remove) of trees causes serious damage to the soil as trees give (h) --- (protect) to soil as well. The temperature will rise and it will cause greenhouse effect. One day, the country will be (i) --- (suitable) for living. So, tree (j) --- (plant) programme should be extended throughout the country.",
      answers: [
        "(a) Deforestation",
        "(b) indiscriminately",
        "(c) densely",
        "(d) agricultural",
        "(e) dishonest",
        "(f) illegally",
        "(g) removal",
        "(h) protection",
        "(i) unsuitable",
        "(j) plantation",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Chattogram",
    data: {
      questions:
        "Life without leisure and (a) --- (relax) is dull. Nobody can work without rest. Life becomes (b) --- (charm) if man does not have any time to enjoy (c) --- (beauty) objects of nature. (d) --- (monotony) work hinders the (e) --- (smooth) of work. Leisure (f) --- (new) our spirit to work. Everybody knows that (g) --- (work) is (h) --- (harm). Leisure does not mean (i) --- (idle). It gives (j) --- (fresh) to our mind.",
      answers: [
        "(a) relaxation",
        "(b) charmless",
        "(c) beautiful",
        "(d) Monotonous",
        "(e) smoothness",
        "(f) renews",
        "(g) overwork",
        "(h) harmful",
        "(i) idleness",
        "(j) freshness/refreshment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Dhaka",
    data: {
      questions:
        "Health is wealth. To keep in good health, we have to follow many things. Physical exercise is one of them. It increases our appetite and improves (a) --- (digest) power. If anybody suffers from (b) --- (digest), he should take physical exercise. Proper (c) --- (digest) of food removes his loss of appetite. Physical exercise removes (d) --- (constipate) and helps proper blood (e) --- (circulate). Our antibodies will be (f) --- (act) if our blood circulation is (g) --- (normal). (h) --- (proper) blood circulation in our bodies may cause many (i) --- (predictable) physical problems. So, we must take physical exercise for the (j) --- (improve) of blood circulation.",
      answers: [
        "(a) digestive",
        "(b) indigestion",
        "(c) digestion",
        "(d) constipation",
        "(e) circulation",
        "(f) active",
        "(g) normal",
        "(h) Improper",
        "(i) unpredictable",
        "(j) improvement",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Jashore",
    data: {
      questions:
        "Life without leisure and (a) --- (relax) is dull. Life becomes (b) --- (charm) if one does not have any time to enjoy the (c) --- (beauty) objects of nature. (d) --- (monotony) work hinders the (e) --- (smooth) of work. Leisure (f) --- (rich) our spirit to work. Everybody knows that (g) --- (work) is (h) --- (harm). Leisure does not mean (i) --- (idle). It gives freshness to (j) --- (recreate) our energy.",
      answers: [
        "(a) relaxation",
        "(b) charmless",
        "(c) beautiful",
        "(d) monotonous",
        "(e) smoothness",
        "(f) enriches",
        "(g) overwork",
        "(h) harmful",
        "(i) idleness",
        "(j) recreate",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Rajshahi",
    data: {
      questions:
        "Everybody knows that (a) --- (smoke) is a (b) --- (danger) bad habit. It is (c) --- (harm) to health. It is also (d) --- (cost). A (e) --- (smoke) should not smoke (f) --- (public). Smoking creates (g) --- (pollute). A single puff of cigarette contains (h) --- (numerable) harmful particles that cause many (i) --- (respirator) diseases which are (j) --- (curable).",
      answers: [
        "(a) smoking",
        "(b) dangerous",
        "(c) harmful",
        "(d) costly",
        "(e) smoker",
        "(f) publicly",
        "(g) pollution",
        "(h) innumerable",
        "(i) respiratory",
        "(j) incurable",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2022,
    board: "Mymensingh",
    data: {
      questions:
        "Health is wealth. To keep in good health, we have to follow many things. Physical exercise is one of them. It increases our appetite and improves (a) --- (digest) power. If anybody suffers from (b) --- (digest), he should take physical exercise. Proper (c) --- (digest) of food removes his loss of appetite. Physical exercise removes (d) --- (constipate) and helps proper blood (e) --- (circulate). Our antibodies will be (f) --- (act) if our blood circulation is (g) --- (normal). (h) --- (proper) blood circulation in our bodies may cause many (i) --- (predictable) physical problems. So, we must take physical exercise for the (j) --- (improve) of blood circulation.",
      answers: [
        "(a) digestive",
        "(b) indigestion",
        "(c) digestion",
        "(d) constipation",
        "(e) circulation",
        "(f) inactive",
        "(g) abnormal",
        "(h) improper",
        "(i) unpredictable",
        "(j) improvement",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Dhaka",
    data: {
      questions:
        "Bangladesh is an (a) --- (dependent) country, but she is still burdened with poverty, (b) --- (population), (c) --- (employ), corruption, food (d) --- (deficient), natural calamities, power crisis, etc. Considering all these, the present (e) --- (govern) has aimed at making a digital Bangladesh to (f) --- (come) most of these problems. The actual aim of (g) --- (digit) Bangladesh is to establish technology-based government which will emphasize the overall (h) --- (develop) of the country and the nation. The country has (i) --- (ready) fixed its target for the (j) --- (achieve) of Digital Bangladesh by 2021.",
      answers: [
        "(a) independent",
        "(b) overpopulation",
        "(c) unemployment",
        "(d) deficiency",
        "(e) government",
        "(f) overcome",
        "(g) digital",
        "(h) development",
        "(i) already",
        "(j) achievement",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Barishal",
    data: {
      questions:
        "Mobile phone is a great (a) --- (invent) of modern science. The (b) --- (consume) of mobile phone are increasing day by day. People are getting benefits. But it is (c) --- (fortunate) that mobile phone sometimes (d) --- (comes) a cause of health hazard, especially the (e) --- (child) are affected much. According to the (f) --- (science) mobile phone causes brain tumours, genetic damage and many other (g) --- (cure) diseases. They believe that (h) --- (visible) uncontrolled radioactivity of mobile phone causes (i) --- (repairable) damage to human body. They say that the (j) --- (govern) should control radioactive sources.",
      answers: [
        "(a) invention",
        "(b) consumers",
        "(c) unfortunate",
        "(d) becomes",
        "(e) children",
        "(f) scientists",
        "(g) incurable",
        "(h) invisible",
        "(i) irreparable",
        "(j) government",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Chattogram",
    data: {
      questions:
        "Life without (a) --- (sure) and pleasure is dull. Life becomes (b) --- (charm) if it does not have any time to enjoy the (c) --- (beauty) objects of nature. (d) --- (monotony) work hinders the (e) --- (smooth) of work. Leisure (f) --- (new) our spirit to work. Everybody knows that (g) --- (work) is (h) --- (harm). Leisure does not mean (i) --- (averse) to work. It gives freshness and (j) --- (create) to our mind.",
      answers: [
        "(a) leisure",
        "(b) charmless",
        "(c) beautiful",
        "(d) monotonous",
        "(e) smoothness",
        "(f) renews",
        "(g) overwork",
        "(h) harmful",
        "(i) aversion",
        "(j) recreation",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Cumilla",
    data: {
      questions:
        "Most of the books of famous (a) --- (write) are put on sale in the book fair. Most of the (b) --- (visit) buy different (c) --- (publish). Almost no visitor returns from the fair without making any purchase. The (d) --- (buy) like to buy at a fair price. Our book fair is always (e) --- (crowd). As (f) --- (vary) books are (g) --- (play) in a fair, the buyers get a scope to choose books. They buy (h) --- (choose) books after a long search. This facility is (i) --- (available) in any place other than a book fair. A book fair is always (j) --- (come) to the students.",
      answers: [
        "(a) writers",
        "(b) visitors",
        "(c) publications",
        "(d) buyers",
        "(e) crowded",
        "(f) various",
        "(g) displayed",
        "(h) chosen",
        "(i) unavailable",
        "(j) welcoming",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Mymensingh",
    data: {
      questions:
        "Education is essential for any kind of (a) --- (develop). The poor socio-economic condition of our country can be (b) --- (large) attributed to many people's (c) --- (accessibility) to education. Many (d) --- (literate) people do not have any knowledge of health, sanitation and (e) --- (populate) control. It (f) --- (able) us to perform our duties (g) --- (proper). Education helps us to adopt a (h) --- (ration) attitude. It provides us with an (i) --- (lightened) awareness about things and this awareness is a (j) --- (requisite) for social development.",
      answers: [
        "(a) development",
        "(b) largely",
        "(c) inaccessibility",
        "(d) illiterate",
        "(e) population",
        "(f) enables",
        "(g) properly",
        "(h) rational",
        "(i) enlightened",
        "(j) prerequisite",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Sylhet",
    data: {
      questions:
        "King Solomon was (a) --- (fame) for his (b) --- (wise). He was blessed with (c) --- (ordinary) knowledge and it was really beyond people's (d) --- (imagine). One day, the Queen of Sheba wanted to test how wise he was. Solomon was given two kinds of flowers. One was (e) --- (nature) and the other was (f) --- (artifice). As he had a close (g) --- (associate) with nature, he had been (h) --- (success) to differentiate them. In this way, his (i) --- (repute) of (j) --- (multidimension) knowledge spread all over the world.",
      answers: [
        "(a) famous",
        "(b) wisdom",
        "(c) extraordinary",
        "(d) imagination",
        "(e) natural",
        "(f) artificial",
        "(g) association",
        "(h) successful",
        "(i) reputation",
        "(j) multidimensional",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2020,
    board: "Rajshahi",
    data: {
      questions:
        "(a) --- (persevere) is needed to be (b) --- (success) in life. Those who do not persevere in life become (c) --- (success) in their mission and only blame their lot for their (d) --- (fortune). (e) --- (persevere) people always become successful. (f) --- (sincere) is another important virtue which (g) --- (able) a person to accomplish a job (h) --- (fruit). Student life is the (i) --- (form) period of a man's life. One should not (j) --- (use) this period of life.",
      answers: [
        "(a) Perseverance",
        "(b) successful",
        "(c) unsuccessful",
        "(d) misfortune",
        "(e) Perseverant/Persevering",
        "(f) Sincerity",
        "(g) enables",
        "(h) fruitfully",
        "(i) formative",
        "(j) misuse",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Dhaka",
    data: {
      questions:
        "A good student is always (a) --- (mind) to his studies. He is (b) --- (respect) to his (c) --- (teach) and superiors. He never (d) --- (honor) anybody. He is free from (e) --- (behavior) and never rude to his classmates. As he is (f) --- (study), he never wastes his time in vain. He is also sincere and listens to his teachers (g) --- (attentive) so that he can be (h) --- (success) in life. His punctuality and (i) --- (determine) help him to (j) --- (take) and solve any difficult work or job.",
      answers: [
        "(a) mindful",
        "(b) respectful",
        "(c) teachers",
        "(d) dishonors",
        "(e) misbehavior",
        "(f) studious",
        "(g) attentively",
        "(h) successful",
        "(i) determination",
        "(j) undertake",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Barishal",
    data: {
      questions:
        "Life without leisure and (a) --- (relax) is dull. Nobody can work without rest. Life becomes (b) --- (charm) if one doesn't have any time to enjoy (c) --- (beauty) objects of nature. Work becomes (d) --- (monotony) if there is no break in it. It hinders the (e) --- (smooth) of life. Leisure (f) --- (new) our spirit to work. Everybody knows that (g) --- (work) is (h) --- (harm). Leisure doesn't mean (i) --- (idle). It gives (j) --- (fresh) to our mind.",
      answers: [
        "(a) relaxation",
        "(b) charmless",
        "(c) beautiful",
        "(d) monotonous",
        "(e) smoothness",
        "(f) renews",
        "(g) overwork",
        "(h) harmful",
        "(i) idleness",
        "(j) refreshment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Chattogram",
    data: {
      questions:
        "Load shedding is not (a) --- (desire). It is harmful to the (b) --- (civil). It makes our life (c) --- (tolerable) and boring. Because of (d) --- (deficient) of electricity load-shedding. Our country is densely (e) --- (people). The storage of electricity is (f) --- (sufficient) to provide electricity with all. As a result, load shedding is seen (g) --- (repeat). But this problem must be removed (h) --- (immediate). So, the (i) --- (govern) must be conscious of it. Only pragmatic steps can (j) --- (move) this serious problem from the country.",
      answers: [
        "(a) desirable",
        "(b) civilization",
        "(c) intolerable",
        "(d) deficiency",
        "(e) populated",
        "(f) insufficient",
        "(g) repeatedly",
        "(h) immediately",
        "(i) government",
        "(j) remove",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Cumilla",
    data: {
      questions:
        "Success in life depends on the proper (a) --- (utilize) of time. Those who waste their (b) --- (value) time in (c) --- (idle), reduce the time of their important work. (d) --- (punctual) is another great virtue of human beings that (e) --- (rich) the (f) --- (man) life. If one takes lesson from the (g) --- (biography) of successful persons, one will learn that they never keep any work (h) --- (do) for the next day. (i) --- (obvious), they were true to their words. So, they got a (j) --- (respect) position in the society.",
      answers: [
        "(a) utilization",
        "(b) valuable",
        "(c) idleness",
        "(d) punctuality",
        "(e) enriches",
        "(f) human",
        "(g) autobiography",
        "(h) undone",
        "(i) obviously",
        "(j) respectable",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Rajshahi",
    data: {
      questions:
        "Bangladesh is a (a) --- (river) and (b) --- (agriculture) country. So, we cannot ignore the (c) --- (important) of rivers. Our agriculture is largely (d) --- (depend) on the rivers. But we get (e) --- (sufficient) water for use from the rivers. There are (f) --- (differ) reasons behind it. At first, the water of many rivers (g) --- (dry) up in summer. Again, the water of some rivers is (h) --- (extreme) poisonous. This poisonous water is (i) --- (suit) for our agriculture. So, water pollution should be prevented at any cost for the (j) --- (better) of our agriculture.",
      answers: [
        "(a) riverine",
        "(b) agricultural",
        "(c) importance",
        "(d) dependent",
        "(e) insufficient",
        "(f) different",
        "(g) dries",
        "(h) extremely",
        "(i) unsuitable",
        "(j) betterment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Sylhet",
    data: {
      questions:
        "Those who lead a (a) --- (luxury) life are always (b) --- (different) to the miseries of the poor. They enjoy life in (c) --- (amuse) and (d) --- (merry). They are (e) --- (centered) people. They have little (f) --- (realize) of the (g) --- (bounded) suffering of the poor. They remain indifferent to their (h) --- (suffer). They feel (i) --- (comfort) to work for their (j) --- (better).",
      answers: [
        "(a) luxurious",
        "(b) indifferent",
        "(c) amusement",
        "(d) merriment",
        "(e) self-centered",
        "(f) realization",
        "(g) unbounded",
        "(h) sufferings",
        "(i) uncomfortable",
        "(j) betterment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Jashore",
    data: {
      questions:
        "Life without leisure and (a) --- (relax) is dull. Nobody can work without rest. Life becomes (b) --- (charm) if man does not have any time to enjoy (c) --- (beauty) objects of nature. (d) --- (monotony) work hinders the (e) --- (smooth) of work. Leisure (f) --- (new) our spirit of work. Everybody knows that (g) --- (work) is (h) --- (harm). Leisure does not mean (i) --- (idle). It gives (j) --- (fresh) to our mind.",
      answers: [
        "(a) relaxation",
        "(b) charmless",
        "(c) beautiful",
        "(d) monotonous",
        "(e) smoothness",
        "(f) renews",
        "(g) overwork",
        "(h) harmful",
        "(i) idleness",
        "(j) freshness",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2019,
    board: "Dinajpur",
    data: {
      questions:
        "Bangladesh is a (a) --- (river) and (b) --- (agriculture) country. So, we cannot ignore the (c) --- (important) of rivers. Our agriculture is largely (d) --- (depend) on the rivers. But we get (e) --- (sufficient) water for use from the rivers. There are (f) --- (differ) reasons behind it. At first, the water of many rivers (g) --- (dry) up in summer. Again, the water of some rivers is (h) --- (extreme) poisonous. This poisonous water is (i) --- (suit) for our agriculture. So, water pollution should be prevented at any cost for the (j) --- (better) of our agriculture.",
      answers: [
        "(a) riverine",
        "(b) agricultural",
        "(c) importance",
        "(d) dependent",
        "(e) insufficient",
        "(f) different",
        "(g) dries",
        "(h) extremely",
        "(i) unsuitable",
        "(j) betterment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        "Flowers are the symbol of love and (a) --- (pure). They are (b) --- (know) for their beauty and fragrance. Some flowers are (c) --- (note) for their fragrance and some are for their beauty. But the rose is favorite to us for its color and beauty. Its mother place is the city of Paris. The (d) --- (Japan) are exceptionally famous for its (e) --- (cultivate). At present most of the countries grow rose in plenty. It (f) --- (general) grows from June to November. Its scent makes us (g) --- (cheer). It makes people lively, lovely, (h) --- (affection) and so on. By (i) --- (grow) roses in plenty, we can export them and solve our (j) --- (employ) problem.",
      answers: [
        "(a) purity",
        "(b) known",
        "(c) noted",
        "(d) Japanese",
        "(e) cultivation",
        "(f) generally",
        "(g) cheerful",
        "(h) affectionate",
        "(i) growing",
        "(j) unemployment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "Early rising is the habit of (a) --- (get) up from bed early in the morning. An early (b) --- (rise) can enjoy the (c) --- (fresh) of the morning air. He can hear the (d) --- (melody) songs of the birds. Again, he can start his day's work (e) --- (early) than others. An early riser does not suffer from (f) --- (physic) problems very often. So, he need not go to any (g) --- (physic) (h) --- (frequent). Thus, an early riser enjoys (i) --- (very) benefits and leads a (j) --- (peace) life.",
      answers: [
        "(a) getting",
        "(b) riser",
        "(c) freshness",
        "(d) melodious",
        "(e) earlier",
        "(f) physical",
        "(g) physician",
        "(h) frequently",
        "(i) various",
        "(j) peaceful",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Dinajpur",
    data: {
      questions:
        "Life without leisure and (a) --- (relax) is dull. Life becomes (b) --- (charm) if one does not have any time to enjoy the (c) --- (beauty) objects of nature. (d) --- (monotony) work hinders the (e) --- (smooth) of work. Leisure (f) --- (rich) our spirit to work. Everybody knows that (g) --- (work) is (h) --- (harm). Leisure does not mean (i) --- (idle). It gives freshness to (j) --- (create) our energy.",
      answers: [
        "(a) relaxation",
        "(b) charmless",
        "(c) beautiful",
        "(d) Monotonous",
        "(e) smoothness",
        "(f) enriches",
        "(g) overwork",
        "(h) harmful",
        "(i) idleness",
        "(j) recreate",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Jashore",
    data: {
      questions:
        "You should bear in mind that (a) --- (confidence) assists a man to reach the goal of life. The lack of (b) --- (determine) leads one to lose the confidence. You need it in order to (c) --- (come) the problems of life. Fix a target and then try (d) --- (sincere) to gain success. Don't lose heart if you fail. Remember that (e) --- (fail) is the pillar of success. Whereas, success without (f) --- (compete) is not enjoyable. Determination keeps you (g) --- (mental) strong and make (h) --- (prepare) for struggling to reach the goal. Nobody can be (i) --- (success) in his mission. Failure makes him more (j) --- (determine) to work hard.",
      answers: [
        "(a) self-confidence",
        "(b) determination",
        "(c) overcome",
        "(d) sincerely",
        "(e) failure",
        "(f) competition",
        "(g) mentally",
        "(h) prepared",
        "(i) successful",
        "(j) determined",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Cumilla",
    data: {
      questions:
        "A balanced diet is a good mixture of (a) --- (pre modify the noun) foods. It is essential for us (b) --- (post modify the adjective with an infinitive) a healthy life. There are many benefits of eating a (c) --- (pre modify the noun) diet because it prevents (d) --- (use determiner to pre-modify the noun) diseases. As a result, we do not get sick (e) --- (post modify the verb with an adverb). We should take (f) --- (pre modify the noun with a possessive) diet according to our needs. We should not eat the (g) --- (use adjective to pre-modify the noun) foods for the whole week. We can keep fit (h) --- (use a participle) a balanced diet. But it is not easy (i) --- (post modify the adjective with an infinitive) a balanced diet. Here (j) --- (use a determiner) nutritionist can help us.",
      answers: [
        "(a) nutritious",
        "(b) to lead",
        "(c) balanced",
        "(d) many",
        "(e) easily",
        "(f) our",
        "(g) same",
        "(h) by eating",
        "(i) to maintain",
        "(j) a",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Chattogram",
    data: {
      questions:
        "(a) --- (kind) is a divine virtue. So, we should not be (b) --- (kind) to the people in distress and even to (c) --- (low) animals. Some naughty boys (d) --- (beat) the lower animals like dogs and cats. This is an (e) --- (rational) behavior. Animals are dumb (f) --- (create). They are (g) --- (harm) beings. Some animals are very (h) --- (faith) and they feel no (i) --- (hesitate) to risk their lives for our (j) --- (protect).",
      answers: [
        "(a) Kindness",
        "(b) unkind",
        "(c) lower",
        "(d) enjoy beating",
        "(e) irrational",
        "(f) creatures",
        "(g) harmless",
        "(h) faithful",
        "(i) hesitation",
        "(j) protection",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2017,
    board: "Sylhet",
    data: {
      questions:
        "Food (a) --- (adulterate) is a crime. Adulterated food is (b) --- (poison) and causes (c) --- (curable) diseases. Some (d) --- (greed) businessmen are responsible for this (e) --- (wicked). The steps so far taken by the government against those (f) --- (honest) businessmen (g) --- (real) deserve praise. (h) --- (present), the fraudulent businessmen are much alarmed. (i) --- (hope), we will be able to shun this (j) --- (practice) very soon.",
      answers: [
        "(a) adulteration",
        "(b) poisonous",
        "(c) incurable",
        "(d) greedy",
        "(e) wickedness",
        "(f) dishonest",
        "(g) really",
        "(h) Presently",
        "(i) Hopefully",
        "(j) malpractice",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Dhaka",
    data: {
      questions:
        "Man is the (a) --- (make) of his own fate. If we are (b) --- (attentive) in our mission, we will face (c) --- (suit) situation in life. If we are (d) --- (care), we may invite (e) --- (fortune). We should be (f) --- (care) in choosing our friends because a friend of (g) --- (character) nature may (h) --- (lead) us. An (i) --- (ambition) man always tries to (j) --- (grade) himself.",
      answers: [
        "(a) maker",
        "(b) inattentive",
        "(c) unsuitable",
        "(d) careless",
        "(e) misfortune",
        "(f) careful",
        "(g) characterless",
        "(h) mislead",
        "(i) ambitious",
        "(j) upgrade",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Rajshahi",
    data: {
      questions:
        "Many people do not like to (a) --- (close) their faults. They think that they are (b) --- (perfect). But everyone should bear in mind that only the (c) --- (wise) can be perfect. So, we should be very (d) --- (care) in our (e) --- (act). We must not be (f) --- (difference) to our faults. If we are not (g) --- (watch) to our activities, we cannot (h) --- (move) our fault. We may fall in (i) --- (danger) situation. So, we should be (j) --- (mind) to our deeds.",
      answers: [
        "(a) disclose",
        "(b) imperfect",
        "(c) wisest",
        "(d) careful",
        "(e) action",
        "(f) indifferent",
        "(g) watchful",
        "(h) remove",
        "(i) dangerous",
        "(j) mindful",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Cumilla",
    data: {
      questions:
        "Bangladesh is an (a) --- (agriculture) country. Her (b) --- (prosper) depends on agriculture. But the farmers are (c) --- (literate) and (d) --- (ignore) of modern methods of cultivation. They follow the (e) --- (tradition) method. As a result, they cannot (f) --- (prove) their condition. The (g) --- (govern) should take (h) --- (effect) steps to (i) --- (rich) their condition. It will (j) --- (strength) our economy.",
      answers: [
        "(a) agricultural",
        "(b) prosperity",
        "(c) illiterate",
        "(d) ignorant",
        "(e) traditional",
        "(f) improve",
        "(g) government",
        "(h) effective",
        "(i) enrich",
        "(j) strengthen",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Chittagong",
    data: {
      questions:
        "Education is the (a) --- (light) of human soul. It makes a man (b) --- (use) to himself and to his society. It is compared with light which (c) --- (light) darkness. An (d) --- (educate) man is a burden to the society. The (e) --- (educate) people can never contribute to the (f) --- (develop) of the country. They are (g) --- (able) to differentiate between right and wrong. Education (h) --- (able) us to serve the nation (i) --- (proper). So, we should try to be (j) --- (educate) to serve the humanity.",
      answers: [
        "(a) enlightenment",
        "(b) useful",
        "(c) enlightens",
        "(d) uneducated",
        "(e) uneducated",
        "(f) development",
        "(g) unable",
        "(h) enables",
        "(i) properly",
        "(j) educated",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Barisal",
    data: {
      questions:
        "An ideal student is always (a) --- (mind) to his studies. He is never (b) --- (attentive) to his duties. He is (c) --- (respect) to his teachers and seniors. His (d) --- (behave) is always praise-worthy. He is never (e) --- (polite) to anybody. He is (f) --- (obey) to his parents and teachers. He never keeps (g) --- (friend) with bad boys. He is always (h) --- (help) to his classmates. An ideal student is a (i) --- (love) personality to all. His (j) --- (simple) makes him great.",
      answers: [
        "(a) mindful",
        "(b) inattentive",
        "(c) respectful",
        "(d) behaviour",
        "(e) impolite",
        "(f) obedient",
        "(g) friendship",
        "(h) helpful",
        "(i) lovable",
        "(j) simplicity",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Sylhet",
    data: {
      questions:
        "Students should be (a) --- (obey) to their teachers. The teachers try to (b) --- (light) their students. Their (c) --- (teach) is always praise-worthy. The students should not be (d) --- (respect) to their teachers. The (e) --- (educate) process may (f) --- (success) if the students are (g) --- (attentive). The (h) --- (attentive) students will not be able to learn their lessons (i) --- (proper). So, they should be (j) --- (mind) to their studies.",
      answers: [
        "(a) obedient",
        "(b) enlighten",
        "(c) teaching",
        "(d) disrespectful",
        "(e) education",
        "(f) succeed",
        "(g) inattentive",
        "(h) inattentive",
        "(i) properly",
        "(j) mindful",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Jessore",
    data: {
      questions:
        "Honesty is a great (a) --- (virtuous). An honest man is liked and (b) --- (trust) by all. The (c) --- (honest) people are not respected in the society. They are (d) --- (famous) for their (e) --- (honest). They always try to (f) --- (deceive) people. The (g) --- (deceive) of an honest man is always (h) --- (praise). His (i) --- (simple) makes him (j) --- (attract) to all.",
      answers: [
        "(a) virtue",
        "(b) trusted",
        "(c) dishonest",
        "(d) infamous",
        "(e) dishonesty",
        "(f) deceive",
        "(g) behaviour",
        "(h) praiseworthy",
        "(i) simplicity",
        "(j) attractive",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2015,
    board: "Dinajpur",
    data: {
      questions:
        "Man is the (a) --- (make) of his own (b) --- (fortunate). If he makes proper (c) --- (divide) of his time and does his duties (d) --- (accord), he is sure to (e) --- (prove) his life. On the other hand, if he does (f) --- (other), he will have to (g) --- (suffering) a lot. His (h) --- (fortunate) will make him (i) --- (happy) in life. So, we should be very (j) --- (care) in our duties.",
      answers: [
        "(a) maker",
        "(b) fortune",
        "(c) division",
        "(d) accordingly",
        "(e) improve",
        "(f) otherwise",
        "(g) suffer",
        "(h) misfortune",
        "(i) unhappy",
        "(j) careful",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "Load-shedding is one of the most common problems of Bangladesh. Lives of our citizens are (a) --- (serious) hampered for load shedding. Students face (b) --- (difficult) in reading during load shedding. (c) --- (Industry) activities are also hampered. We should use electricity (d) --- (honest) and (e) --- (frugal) and should create (f) --- (aware) among people to solve this (g) --- (nation) problem. Besides, government should take (h) --- (effect) steps to (i) --- (grade) our power stations to mitigate the (j) --- (advantages) of our people.",
      answers: [
        "(a) seriously",
        "(b) difficulties",
        "(c) Industrial",
        "(d) honestly",
        "(e) frugally",
        "(f) awareness",
        "(g) national",
        "(h) effective",
        "(i) upgrade",
        "(j) disadvantages",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "Those who live a (a) --- (luxury) life are always (b) --- (different) to the miseries of the poor. They enjoy life in (c) --- (amuse) and (d) --- (merry). They are (e) --- (centered) people. They have little (f) --- (realize) of the (g) --- (bounded) sufferings of the poor. They remain indifferent to their (h) --- (suffer). They feel (i) --- (comfort) to work for their (j) --- (better).",
      answers: [
        "(a) luxurious",
        "(b) indifferent",
        "(c) amusement",
        "(d) merriment",
        "(e) self-centered",
        "(f) realization",
        "(g) unbounded",
        "(h) suffering",
        "(i) uncomfortable",
        "(j) betterment",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        "Agriculture is the soul of our national economy. But the farmers of our country are (a) --- (literate). They are (b) --- (ignore) of the scientific methods of (c) --- (cultivate). As a result, our agriculture is still a (d) --- (gamble) in the hands of nature. Sometimes heavy flood damages standing crops and invites (e) --- (fame) in an epidemic form. Besides, sometimes drought makes cultivation (f) --- (possible). Then (g) --- (poor) is seen everywhere. As a result, poor farmers cannot buy (h) --- (science) tools for agriculture. Moreover, the tools are not (i) --- (avail) to buy them. So, it is said that (j) --- (irrigate) is really costly in our country.",
      answers: [
        "(a) illiterate",
        "(b) ignorant",
        "(c) cultivation",
        "(d) gamble",
        "(e) famine",
        "(f) impossible",
        "(g) poverty",
        "(h) scientific",
        "(i) available",
        "(j) irrigation",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Cumilla",
    data: {
      questions:
        "The other name of water is life. Clean water is (a) --- (drink). Dirty water is (b) --- (safe). Clean water is (c) --- (contaminate) and (d) --- (suit) for drinking. Bangladesh is a (e) --- (river) country. But we get (f) --- (adequate) water for use. The water of our rivers is (g) --- (filth) and (h) --- (poison). We should keep water clean for health, happiness and (i) --- (long). The Government should play an (j) --- (act) role to keep water safe.",
      answers: [
        "(a) drinkable",
        "(b) unsafe",
        "(c) uncontaminated",
        "(d) suitable",
        "(e) riverine",
        "(f) inadequate",
        "(g) filthy",
        "(h) poisonous",
        "(i) longevity",
        "(j) active",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Chittagong",
    data: {
      questions:
        "The aim of (a) --- (educated) is to make a man fully equipped to be (b) --- (use) to himself and to society. A (c) --- (true) educated person should be self-reliant with regard to his (d) --- (person) needs. He should be well-mannered, (e) --- (thought), sympathetic and co-operative. He should be (f) --- (truth), honest, punctual and (g) --- (duty). Punctuality is a virtue that makes a nation (h) --- (prosper). An educated person tries to (i) --- (move) the sufferings of his countrymen. He also helps others in attaining (j) --- (self-reliants).",
      answers: [
        "(a) education",
        "(b) useful",
        "(c) truly",
        "(d) personal",
        "(e) thoughtful",
        "(f) truthful",
        "(g) dutiful",
        "(h) prosperous",
        "(i) remove",
        "(j) self-reliance",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "A student has to be (a) --- (punctual) to make a (b) --- (success) result. (c) --- (Punctual) is a good habit. A student who is (d) --- (punctual) can never prosper in life. He faces many (e) --- (difficult) in life. (f) --- (honest) is another virtue for a student. An (g) --- (honest) student can never be (h) --- (success). The (i) --- (teach) community can play a (j) --- (vital) role to make students punctual and honest.",
      answers: [
        "(a) punctual",
        "(b) successful",
        "(c) Punctuality",
        "(d) unpunctual",
        "(e) difficulties",
        "(f) Honesty",
        "(g) dishonest",
        "(h) successful",
        "(i) teaching",
        "(j) vital",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "ssc",
    year: 2016,
    board: "Jessore",
    data: {
      questions:
        "Man is a social being. He lives in society for his (a) --- (exist) and (b) --- (better). He cannot live (c) --- (dependent). His (d) --- (social) helps him to live in (e) --- (harmonious) with others. The (f) --- (social) people are hated by all. They create (g) --- (disturb) in society. We should be (h) --- (tolerate) to live (i) --- (peace). The (j) --- (tolerate) of others makes us noble.",
      answers: [
        "(a) existence",
        "(b) betterment",
        "(c) independently",
        "(d) socialization",
        "(e) harmony",
        "(f) unsocial",
        "(g) disturbance",
        "(h) tolerant",
        "(i) peacefully",
        "(j) tolerance",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
];
