export const connectors = [
  {
    exam: "hsc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "A lion was drinking water from a brook. (a) --- a lamb was also drinking water from the downstream of the same brook. The lion saw the lamb and decided to devour it. (b) -- he was thinking about how to accomplish his evil design. (c)--- he hit upon a plan. (d) --- the lion complained that the lamb was disturbing him by muddying water. But the lamb said that he was drinking water from downstream. (e) --- the questions of muddying water on his part did not arise. (f)--- the lamb argued that it was the lion that was muddying the water for him as he was drinking water upstream. (g) --- the lion retorted that the lamb spoke ill of him a year ago. (h)--- the lamb said that he was not born a year ago. The lion grew into a rage. (i)--- he said that perhaps his father spoke ill of him last year. (j)--- the lion had the right to take revenge and kill the lamb.",
      answers: [
        "(a) as",
        "(b) so",
        "(c) that",
        "(d) while",
        "(e) in fact",
        "(f) if",
        "(g) which",
        "(h) who",
        "(i) and",
        "(j) therefore/so",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "(a) --- I was walking along the road the other day, I happened to notice a small brown leather purse lying on the pavement. I picked it up and opened it to see (b) ---- I could find out the owner’s name. There was nothing inside. It (c) --- some small change and a rather old photograph a picture of a woman and a young girl about twelve years old who looked like the woman’s daughter. I put the photograph back (d) --- took the purse to the police station. (e) --- I handed it to the sergeant-in-charge. Before I left, the sergeant made a note of my name and address In case the owner of the purse wanted to write and thank me. That evening I went to have dinner with an uncle and aunt of mine. They had also invited another person, a young woman, (f) ---- there would be four people at the table. The young woman’s face was familiar, (g) --- I could not remember where I had seen it. I was quite sure, (h) --- we had not met before. (i) --- Conversation, however, the young woman happened to mark that she had lost her purse that afternoon. I at once remembered where I had seen her face. She was the young woman in the photograph (j) --- she was now much older.",
      answers: [
        "(a) while",
        "(b) whether/if",
        "(c) had",
        "(d) and",
        "(e) then/there",
        "(f) and",
        "(g) but",
        "(h) that",
        "(i) during",
        "(j) but",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Cumilla",
    data: {
      questions:
        "Mobile phone has become an essential gadget for everybody. (a) — it has become very popular. (b) — it has created a number of problems. It has (c) — advantages (d) — disadvantages. (e) — it helps to connect people. (f) — it helps to exchange information (g) — it can be used for various purpose. (h) — it has a few disadvantages. (i) — it can cause a lot of troubles. (j) — its advantages are more than its disadvantages.",
      answers: [
        "(a) As/Because/And",
        "(b) But/However",
        "(c) both/not only",
        "(d) and/but also",
        "(e) Firstly/First of all/At first",
        "(f) Secondly/Again",
        "(g) Furthermore/Thirdly/Then again/Moreover/Beside",
        "(h) However",
        "(i) which/that",
        "(j) However/Nevertheless/Above all/In fact",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "The gifts of science are uncountable. (a) --- we cast our eyes, we see the wonders of science. Satellite TV channels are means through (b) --- we can see and hear the events (c) --- are happening all over the world. (d) ---, today we have specialized satellite channels on almost every interest. (e) ---, people now have more choices and more freedom about television programmes. Satellite channels help us a lot by reporting on climatic conditions of different parts of the world. (f) ---, we can be aware of storms, cyclones and tidal bores, (g) --- satellite channels are helping us to a great extent to enrich our own culture and tradition. (h) --- satellite channels are playing a favourable role, it is (i) --- doing harm to our young and new generation. (j) --- still we cannot deny the immense benefits we are getting from satellite channels.",
      answers: [
        "(a) wherever",
        "(b) which",
        "(c) that",
        "(d) in fact/really",
        "(e) therefore",
        "(f) thus",
        "(g) in addition/moreover/besides",
        "(h) though/although",
        "(i) also",
        "(j) but",
      ],
      isDifficult: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Chattogram",
    data: {
      questions:
        "Bangladesh is mainly an agricultural country. (a)---, her economy and prosperity depend on agriculture. (b)---, our agriculture depends on the mercy of nature. (c)---, if there is sufficient rain, people can plough their lands and sow seeds in time. (d)---, they can reap a good harvest. (e)--- if it does not rain in time, the farmers cannot grow the crops easily and they do not have a good harvest. (f)---, without water our agriculture is lifeless. The rain is not always beneficial to our agriculture (g) ---, sometimes it rains so much that it causes floods. (h) ---, our crops go underwater and most often, they are totally destroyed. (i)---, the farmers who constitute the most part of our professional people, lose everything. (j)---, we can safely conclude that our economy depends on rain.",
      answers: [
        "(a) So/Thus/In fact",
        "(b) Again/but",
        "(c) Hence/So/Therefore",
        "(d) As a result/That is why",
        "(e) On the contrary/but/on the other hand",
        "(f) Therefore/true that/in fact",
        "(g) for example/for instance",
        "(h) That is why/As a result/When/Then/Consequently",
        "(i) Consequently/Thus/So/As a result/For this",
        "(j) Finally/At last/So/In fine/In short",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        "Honesty is a noble virtue. The man possessing this invaluable quality is the happiest man on earth, (a)---. To be honest, a man should have trustworthiness. (b)---, nobody trusts a liar. A liar may prosper for the time being. (c)---, he goes to the dogs. (d)---. we should be honest. It is said that honesty is the best policy. (e)--- dishonesty is the sign of downfall. God helps those who are honest. (f)---, dishonest people are cursed. (g)--- children should be taught honesty from childhood. It is widely observed that children follow their parents. (h)--- business of life. (i)---, children should be allowed to mix with those friends who are honest. (j)--- they can mould their characters.",
      answers: [
        "(a) indeed/undoubtedly",
        "(b) Because",
        "(c) But",
        "(d) So/Therefore",
        "(e) Whereas/But",
        "(f) On the other hand/On the contrary",
        "(g) So/Therefore/For this reason",
        "(h) That is why/Hence",
        "(i) In addition/Besides",
        "(j) Thus/In this way",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        "Mobile phone has added a new dimension into our communication system. It has made the world closer to us. (a) ---, it has made worldwide communication easier. We use it for our day-to-day communication. (b) ---, it has been a part and parcel in our life as we cannot go for a single day without using it. We use it for rapid communication. (c) --- mobile phone is not free from defect. It has some negative sides as well. (d) --, excessive use of mobile phone may cause our hearing problem. (e) ---, it is a means of money wastage. (f) ---, it is seen that many underground crimes are being done with the use of mobile networks. (g) ---, the radiation from mobile phone may cause cancer to the users. (h) ---, we are aware of these harmful effects. (i) ---, we are not aware of using the mobile phone. (j)---, we must have to be conscious about the negative impact of mobile phone and accordingly, we should use it carefully.",
      answers: [
        "(a) Besides/Moreover",
        "(b) So/In fact",
        "(c) But/However",
        "(d) Firstly/At first",
        "(e) Secondly",
        "(f) Thirdly",
        "(g) Finally",
        "(h) However/Unusually/Generally",
        "(i) But",
        "(j) So/Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "Man is a social being. (a) ---, man cannot live alone. (b) ---, man has been living together from time immemorial. Living in society is not an easy task. If we want to live in a society, we have to follow certain rules and regulations of that society. (c) ---, we have to be cooperative. (d) ----, we must help others when they need it. (e) ---, we have to be careful not to hurt others by our words or activities. (f) ----, we must control our emotions and behave well with others. (g) ---, we should not think and live only for us. (h) ---, we should always work for the betterment of the society. (i) ---, we should sacrifice our lives for others. (j)---, sacrificing our lives for others can make us immortal.",
      answers: [
        "(a) so",
        "(b) in fact",
        "(c) firstly",
        "(d) therefore/in other words",
        "(e) secondly",
        "(f) that is why",
        "(g) thirdly",
        "(h) rather",
        "(i) so",
        "(j) in fact",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Cumilla",
    data: {
      questions:
        "Trees are a vital part of our environment, (a) ---, they bear a great impact on the climate. (b) --- we are not careful about them. (c) ---, we destroy trees at random. (d) ---, one day the country will bear the consequence of greenhouse effect. (e) --- ours is an agricultural country, our economy depends upon it. (f) ---, our agriculture is dependent on rain, (g) --- trees play a vital role on our climate, (h) ---, trees keep the soil strong. (i) ---, trees save us from flood (j) --- many other natural calamities.",
      answers: [
        "(a) In fact/Actually",
        "(b) Yet/But",
        "(c) Rather",
        "(d) As a result/This is why/Consequently/besides",
        "(e) As/Since/then",
        "(f) Besides/Moreover/In addition/consequently",
        "(g) Again/Besides/however",
        "(h) Next/In addition",
        "(i) Furthermore/at the same time",
        "(j) Thus/moreover",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Barishal",
    data: {
      questions:
        "Water is a vital element of the environment (a)--- this element is polluted in many ways. (b)--- farmers use chemical fertilizers and insecticides in their field. (c) --- rain and flood wash away these chemicals, they get mixed with water in rivers, canals and ponds (d) --- pollute it. (e)--- mills and factories throw their poisonous chemicals and waste product into water. (f) --- water vehicles also pollute water by dumping food waste and human waste into it. (g) --- insanitary latrines and unsafe drains also contribute to water pollution. Water is called life. (h) --- we cannot allow this pollution to continue. We have to raise an awareness about it. (i) ---, laws should be enforced strictly. (j) --- we fail to check water pollution, we will suffer.",
      answers: [
        "(a) but",
        "(b) Firstly/At first",
        "(c) When/As",
        "(d) and",
        "(e) Secondly/Second/Moreover/Besides",
        "(f) Moreover/Besides/Furthermore/Thirdly",
        "(g) Finally/Ultimately/Again",
        "(h) So/For this/Therefore",
        "(i) in this respect/Therefore/Moreover",
        "(j) If",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Sylhet",
    data: {
      questions:
        "Honesty is a noble virtue. The man possessing this invaluable quality is the happiest man on earth, (a)---. To be honest, a man should have trustworthiness. (b)---, nobody trusts a liar. A liar may prosper for the time being. (c)---, he goes to the dogs. (d)---. we should be honest. It is said that honesty is the best policy. (e)--- dishonesty is the sign of downfall. God helps those who are honest. (f)---, dishonest people are cursed. (g)--- children should be taught honesty from childhood. It is widely observed that children follow their parents. (h)--- business of life. (i)---, children should be allowed to mix with those friends who are honest. (j)--- they can mould their characters.",
      answers: [
        "(a) indeed/undoubtedly",
        "(b) Because",
        "(c) But",
        "(d) So/Therefore",
        "(e) Whereas/But",
        "(f) On the other hand/On the contrary",
        "(g) So/Therefore/For this reason",
        "(h) That is why/Hence",
        "(i) In addition/Besides",
        "(j) Thus/In this way",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Kh Set",
    data: {
      questions:
        "Many people think that money can do everything in life. (a) ---, it is a must for our life, it is not the thing that necessarily brings happiness. (b)---, it is absolutely a psychological matter. The person who is contented with what he gets and (c) --- he is really happy. Money can do something with happiness (d)--- it cannot give us happiness. (e) ---, we can see that the richest men of our society are not the happiest men. (f) ---, they lead a life burdened with cares and anxieties (g) --- pass sleepless nights. (h) --- there are a large number of poor men (i) --- are happy and enjoy a sound sleep. (j)---, money cannot ensure happiness.",
      answers: [
        "(a) Although/Though",
        "(b) actually",
        "(c) what",
        "(d) but",
        "(e) That is why/for this reason/so/therefore",
        "(f) virtually",
        "(g) and",
        "(h) on the other hand",
        "(i) who",
        "(j) This way/Thus",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Kha Set",
    data: {
      questions:
        "Time and tide wait for none. (a) ---, no one can stop the onward march of time. (b)---, we should not waste a single moment in vain. (c) ---, we should make proper use of every single moment of our life. (d)---, the students should understand the value of time. It is a matter of great regret that some of the students pass away their valuable time in Facebook. (e) ---, they kill their time. (f)---, they cannot prepare their lesson well. (g) --- they always have poor preparation for the examination. (h) ---, they cannot do well in the examination. (i)---, they do not stop wasting time. (j) ---, they continue to waste their time using Facebook till it is too late for them.",
      answers: [
        "(a) As a matter of fact/In fact",
        "(b) So/Therefore/hence/for this reason",
        "(c) Rather/Instead",
        "(d) Especially/Particularly/However",
        "(e) Thus/In this way",
        "(f) As a result/Consequently/For this reason",
        "(g) So/Eventually/hence/as such/and",
        "(h) As a result/Finally/consequence/Consequently/for this",
        "(i) Yet/But/nevertheless/nonetheless/notwithstanding that",
        "(j) Rather/On the contrary/On the other hand/Even",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dhaka",
    data: {
      questions:
        "Trees are a vital part of our environment. (a) ---, they bear a great impact on the climate. (b) --- we are not careful about them. (c) ---, we destroy trees at random. (d) ---, one day the country will bear the consequence of greenhouse effect. (e) --- ours is an agricultural country, our economy depends upon it. (f) --- trees play a vital role on our climate, (g) ---, trees keep the soil strong. (h) ---, trees save us from flood. (i)--- tress provide us timber. (j)---- trees are our best friend.",
      answers: [
        "(a) In fact/Actually",
        "(b) But",
        "(c) Rather",
        "(d) As a result",
        "(e) Since",
        "(f) Besides",
        "(g) Firstly",
        "(h) Secondly",
        "(i) Moreover",
        "(j) So/Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Rajshahi",
    data: {
      questions:
        "Unemployment is a great problem in our country. (a) ---, it is the burning question of the day. (b) --- almost all the countries of the world suffer from the curse of unemployment problem. (c)--- Bangladesh is the worst sufferer of this so-called problem. (d) ---, nowhere in the world this problem is so acute as in our country. (e) ---, there are many reasons behind it. (f) ---, our country is industrially backward. (g) ---, our system of education fails to give the student an independent start of life. (h) ---, it has little provision for vocational training. (i) ---, our students and youths have a false sense of dignity. (j) ---, they run after jobs blindly.",
      answers: [
        "(a) In fact/Actually/Also/indeed/Really",
        "(b) Now/At present",
        "(c) But/However",
        "(d) But/Truly",
        "(e) However",
        "(f) Firstly/For example",
        "(g) Besides/Secondly",
        "(h) Actually/Thirdly",
        "(i) Again/In addition",
        "(j) Therefore/So/Hence/Finally/Lastly/Eventually",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Cumilla",
    data: {
      questions:
        "Unemployment is a great curse. (a) --- all the countries of the world suffer from the curse. (b) --- nowhere in the world, this problem is so acute as in our country. (c) --- there are many reasons behind it. (d) ---, our country is industrially backward. (e) --- our traditional education system is not service-oriented. (f) ---, our students and youths have a false sense of dignity. (g) ---, they run after jobs only. (h) ---, unemployment problem should be removed at any cost. (i) --- our education system should be changed (j) --- more mills and factories should be established.",
      answers: [
        "(a) Intact/Nowadays/Nearly/Almost",
        "(b) but/However",
        "(c) Actually/Therefore/Really",
        "(d) For example/Firstly/At first",
        "(e) Besides/Secondly",
        "(f) Moreover/Thirdly",
        "(g) So/As a result/For that/For this",
        "(h) However/Anyway/Of course/Nevertheless",
        "(i) Moreover/Besides/For that/For this",
        "(j) In addition/Above all/Finally/At last",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Jashore",
    data: {
      questions:
        "Honesty is a noble virtue. The man (a) --- possesses this rare quality is the happiest man on earth. To be honest, a man should have trustworthiness (b) --- nobody trusts a liar. A liar may prosper for the time being, (c) --- ultimately he goes to the dogs. (d) --- we should be honest. It is said that honesty is the best policy (e) --- dishonesty is the sign of downfall. God helps those who are honest. (f) --- dishonest people are cursed; Childhood is the best time (g) --- children should be taught honesty. It is said (h)--- children should be allowed to mix with those friends (i) ---are honest. (j) --- they can mould their characters.",
      answers: [
        "(a) who",
        "(b) because",
        "(c) but",
        "(d) So",
        "(e) whereas",
        "(f) Moreover",
        "(g) therefore",
        "(h) hence/that",
        "(i) in addition",
        "(j) Thus",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Sylhet",
    data: {
      questions:
        "Education is essential in our life. (a) --- we are not properly educated, we cannot live an honourable life in society. It teaches us (b) --- how to earn but also how to spend. (c) ---, it teaches (d) --- to live in amity with others in society. (e) ---, we must get the proper education. (f) --- we should bear in mind (g) --- education is not only what we learn at educational institutions but also (h) --- we learn outside these institutions. (i) ---, education is a lifelong process. It begins just after our birth (j) --- ends only in death.",
      answers: [
        "(a) If",
        "(b) not only",
        "(c) In fact/Indeed",
        "(d) how",
        "(e) Therefore/So",
        "(f) On the other hand",
        "(g) that",
        "(h) what",
        "(i) In fact/In brief",
        "(j) and",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Barishal",
    data: {
      questions:
        "We should always keep in mind (a) --- all kinds of physical exercise are not suitable for all. (b) --- different people have different capacities. (c) ---, harder exercise (d) --- wrestling and gymnastics are suitable for young people (e) --- they have the energy to perform them. Weaker and old people should take the milder exercise (f)--- walking, jogging and freehand exercise. Over exercise never does good, (g) --- it breaks down the health. (h) ---, we should always take those exercises (i) --- would suit us. Physical exercise is important for the preservation of good health. It (j) --- builds our character.",
      answers: [
        "(a) that",
        "(b) For/Because",
        "(c) For example/for instance",
        "(d) like/such as",
        "(e) as/since/because",
        "(f) like/such as",
        "(g) rather/instead",
        "(h) So/As a result/Therefore",
        "(i) which/that",
        "(j) also",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Chattogram",
    data: {
      questions:
        "We must be aware of the dangers of smoking. It is harmful to us in various ways. It causes various diseases (a) --- blood pressure, heart attack, bronchitis, cancer, etc. (b) --- it pollutes air. (c) --- smoking causes harm to (d) ---the smokers (e)--- the non-smokers who remain by them. (f) --- we should give up smoking. (g) ---it is (h) --- great an addiction to get rid of. (i) --- nothing is impossible for us. (j) --- we are determined to give up, we can certainly do it.",
      answers: [
        "(a) such as/like",
        "(b) firstly/moreover/besides/also",
        "(c) Secondly/Moreover/Besides/Furthermore",
        "(d) not only/both",
        "(e) but also/and",
        "(f) So/Therefore/Hence/For this",
        "(g) but",
        "(h) so/such",
        "(i) but/however",
        "(j) If",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dinajpur",
    data: {
      questions:
        "We cannot walk on a road in the darkness without light. (a) ---, we cannot step forward in our life without education. (b) ---, throughout the ages, education has always been compared to light and (c) --- ignorance has been compared to darkness. (d) --- the light of education enlightens us. (e) ---, it broadens our mind and widens our outlook. (f) ---, it is education which helps us to become a good citizen. (g) ---, education creates good citizens and ensures the smooth development of country. (h) --- ignorance stands on the way of development of an individual. (i)--- ignorance has a detrimental effect on the overall development of a nation. (j) ---, we should come forward to educate every single person of our country and thereby, ensure the development of our country.",
      answers: [
        "(a) Similarly/In the same way",
        "(b) Traditionally/So/Therefore",
        "(c) reversely/on the other hand",
        "(d) Certainly/Of course/Actually",
        "(e) Moreover/Truly/In fact/Besides",
        "(f) Surely/Again",
        "(g) Therefore/Thus/Hence",
        "(h) On the other hand/But",
        "(i) Hence/Moreover/However",
        "(j) So/Therefore/That’s way",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Dhaka",
    data: {
      questions:
        "Once there lived a grasshopper and an ant. The ant was hard-working. (a)---, the grasshopper was lazy. (b) ---, he idled away his time dancing and sleeping. (c) --- he sometimes advised the ant not to work so hard. (d) ---, the ant paid no heed to the grasshopper. (e) ---, he continued to work hard gathering food for the coming winter. (f) ---, winter came, covering everything with snow. The surface of the earth went under the snow-cover. (g) --- the grasshopper could not find any food. (h) ---, he had nothing in stock. (i) ---, he went to the ant for help. The ant gave him some food for the day. (j) ---, the long winter was ahead, and the grasshopper was really worried about his survival.",
      answers: [
        "(a) But/On the other hand/On the contrary/Conversely",
        "(b) That's why/So/Therefore/Hence",
        "(c) Moreover/Besides/Furthermore",
        "(d) But/However/Anyway",
        "(e) Rather/Instead/This",
        "(f) Then/As usual/Eventually/Meanwhile/At last",
        "(g) That is why/As a result/Consequently/As a consequence/So",
        "(h) Moreover/Besides/Unfortunately",
        "(i) So",
        "(j) Eventually/This/Finally",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Rajshahi",
    data: {
      questions:
        "Air is an important element of our environment. (a) ---, clean air is essential for our life. (b) ---, air is polluted in many ways. (c) ---, one thing that pollutes air is smoke. Smoke is produced from different sources. (d) ---, we make fire to cook food and it creates smoke. (e) ---, buses and trucks plying in the roads emit smoke. (f) ---, the burning of coal in the railway engine also produces smoke. (g) ---, the mills and factories also produce a huge amount of smoke. (h)--- melt tar for road constructions which produces black smoke (i) --- all these smokes mix with the air and pollute it. (j) ---, smoke from different sources is causing serious harm to our environment.",
      answers: [
        "(a) Indeed/Actually/In fact/Undoubtedly/Certainly",
        "(b) However",
        "(c) For example/As a matter fact/Certainly",
        "(d) First/Firstly",
        "(e) Second/Secondly",
        "(f) Besides/Likewise",
        "(g) Third/Thirdly/Moreover",
        "(h) In addition/Moreover/Furthermore",
        "(i) As a result/Consequently/Ultimately/Then",
        "(j) Thus/So/In short",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Cumilla",
    data: {
      questions:
        "Mobile phones are one of the most commonly used gadgets in today's world. (a) ---, mobile phones have made our life easy and convenient. (b) --- they are a blessing till we use them judiciously. (c) ---, they are very beneficial; they have some disadvantages. (d) ---, excessive use of the device acts as a barrier to quality communication. (e) ---, mobile phones waste a lot of time. (f) ---, they are the causes of many ailments such as weak eyesight, strain on brain, headaches, dry eyes, sleeplessness and more. (g) ---, they have created a lack of privacy in people's lives. (h) ---, we see how the device is both a boon and a bane. (i) --- ,we must not let mobile phones control our lives. (j) --- we must know when to draw the line.",
      answers: [
        "(a) Indeed/For example",
        "(b) However",
        "(c) Although/Though",
        "(d) For instance",
        "(e) Moreover",
        "(f) Furthermore",
        "(g) Additionally",
        "(h) Thus/Therefore",
        "(i) So/Hence",
        "(j) Therefore/For this reason",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Jashore",
    data: {
      questions:
        "Drug addiction is a great curse of the present world. (a) --- a few things were used as drugs. (b) --- the number of drugs has increased. (c) ---, cocaine, marijuana, opium, heroine, morphine, etc. (d) --- drugs offer another world to the addicted ones. (e) --- they do not know that this addiction destroys the inner part of the body of addicted persons. (f) ---, why do many people take drugs? The reasons are many. (g)---, some people are tempted by their so-called friends to have a taste of a drug. (h) ---, they are trapped forever. (i) --- some people take drugs to forget the frustration of their life. (j) --- , those who become drug addicts cannot live a normal life.",
      answers: [
        "(a) Earlier/In the past/Previously",
        "(b) Nowadays/Recently/However/On the contrary/Gradually/At present",
        "(c) For example/For instance",
        "(d) All these",
        "(e) But/Unfortunately",
        "(f) Then/However/Yet/Still/Anyway",
        "(g) Firstly/Often",
        "(h) Secondly/But",
        "(i) Thirdly/Moreover",
        "(j) Consequently/Eventually/At last/Finally",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Chattogram",
    data: {
      questions:
        "We want success (a) --- prosperity in life. (b) --- we do not do what are needed in achieving these. (c) --- we want to make our life glorious, we must follow some rules. (d)--- we have to be industrious. (e) --- without hard work. success in life is impossible. (f) --- we should be sincere in our activities. Some people think that good luck is at the root of all achievements in life. (g) --- to them nothing is further from truth than it. (h) --- every success in life depends totally on our activities. (i) --- we spend time in idleness, we must suffer. (j) --- we should be honest in life because this virtue helps us greatly to gain our goal.",
      answers: [
        "(a) and",
        "(b) But/However",
        "(c) If",
        "(d) Firstly",
        "(e) Because/For",
        "(f) Secondly",
        "(g) But/However",
        "(h) In fact/Actually",
        "(i) If",
        "(j) Therefore/So",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Mymensingh",
    data: {
      questions:
        "The old sailor spoke so strangely (a)-- the guest stood still. The feast began (b) --- the guest could hear the music and laughter, (c) --- for some reasons he could not join the others. The old man told him about his last journey on the sea. They had sailed away to the south (d)---- they had arrived in the cold grey sea. (e) --- the sea was frozen. (f) --- the ice was all around them. The big sails opened wide (g) --- the strong wind blew them quickly through the icy waters. The weather was very cold. (h) ---, there were no birds and animals in that snow covered country. But one day the sailors saw an albatross flying towards the ship. All men were very pleased to see it and they gave it food and water. It came to the ship everyday (i) --- they called it. (j) --- one day, the old sailor killed the bird and after that everyone had to undergo terrible sufferings.",
      answers: [
        "(a) that",
        "(b) and",
        "(c) but",
        "(d) until",
        "(e) Moreover/Naturally/Even",
        "(f) Again/And/Besides",
        "(g) as/and",
        "(h) Therefore/So/And/Hence",
        "(i) when/whenever",
        "(j) But/Unfortunately",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Barishal",
    data: {
      questions:
        "Mobile phone has added a new dimension into our communication system. It has made the world closer to us. (a) ---, it has made worldwide communication easier. We use it for our day-to-day communication. (b) ---, it has been a part and parcel in our life as we cannot go for a single day without using it. We use it for rapid communication. (c) --- mobile phone is not free from defect. It has some negative sides as well. (d) --, excessive use of mobile phone may cause our hearing problem. (e) ---, it is a means of money wastage. (f) ---, it is seen that many underground crimes are being done with the use of mobile networks. (g) ---, the radiation from mobile phone may cause cancer to the users. (h) ---, we are aware of these harmful effects. (i) ---, we are not aware of using the mobile phone. (j)---, we must have to be conscious about the negative impact of mobile phone and accordingly, we should use it carefully.",
      answers: [
        "(a) Besides/Moreover",
        "(b) So/In fact",
        "(c) But/However",
        "(d) Firstly/At first",
        "(e) Secondly",
        "(f) Thirdly",
        "(g) Finally",
        "(h) However/Unusually/Generally",
        "(i) But",
        "(j) So/Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dhaka",
    data: {
      questions:
        "Happiness is a relative term. (a) ----, it depends upon some factors. (b) ---, contentment is the key to happiness. (c) --- contentment varies from person to person. (d) ---, a beggar may be contented with only ten taka. (e) ---, a wealthy person may be dissatisfied even after getting one million taka. (f) ---, it is said that contentment brings happiness. (g) ---, we must learn to be contented with what we have. (h) ---, this learning is the simplest way to remain happy. (i) ---, we must remember that our life is short. (j) ---, in this short life we cannot get everything (k) --- we want. (l) --- we want everything, we will not get happiness. (m) ---, we will get frustrated and we will plunge into the world of sadness. (n) ---, it is always better to be contented with what we have than to live in eternal sadness.",
      answers: [
        "(a) As",
        "(b) Moreover/Furthermore/Also",
        "(c) However",
        "(d) For example",
        "(e) On the other hand",
        "(f) Consequently/As a result",
        "(g) Therefore",
        "(h) Actually/In fact",
        "(i) Additionally",
        "(j) However",
        "(k) even if",
        "(l) If",
        "(m) Rather",
        "(n) Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Rajshahi",
    data: {
      questions:
        "The greatness of a book (a) --- depends on the acceptability of readers. (b) --- we read a book (c ) — once, we can discover many things in it. (d) --- basing on one reading, we cannot judge the standard of a book. (e) --- a book is praised (f) ---, we have no doubt about the greatness of the book. (g) --- the first reading, we may not understand the book. But if it is read more than once, we will see (h) --- it is read (i) --- praised. So, the great books are those (j) — have passed the test of time. (k) --- the appeal of a great book does not decrease. (l) --- the greatness of a book is newly felt (m) --- time passes. (n)---, a great book is widely read and reread by people all over the world.",
      answers: [
        "(a) mainly/generally/greatly",
        "(b) If",
        "(c) for",
        "(d) But",
        "(e) If/When",
        "(f) highly",
        "(g) During/Through",
        "(h) why",
        "(i) and",
        "(j) which",
        "(k) In fact/Actually",
        "(l) Rather",
        "(m) when",
        "(n) So/Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Sylhet",
    data: {
      questions:
        "Bangladesh is a free and sovereign country. (a) --- it was a part of Pakistan from 1947 to 1971. In 1971 it became independent (b) --- started its journey as a free nation. (c) --- the journey was not smooth at all. On 7 March, 1971 (d) --- Bangabandhu delivered his speech, the common mass got united (e) --- started their preparation for a war. The Pakistani forces started mass killing (f) --- killed about 30 lakh innocent people. They thought (g) --- they could suppress the Bangalees within a few days. (h) --- the brave sons of our land proved them wrong. (i) --- the freedom fighters didn't have modem weapons in their hand, they were the real patriots and courageous. (j) ---, after few months they became successful in their mission. (k) --- the long waited date came (l) --- the Bangalees got their victory on 16 December, 1971. (m) --- we are the citizens of a free land (n) --- marching forward to the way of lasting development very quickly.",
      answers: [
        "(a) Previously",
        "(b) and",
        "(c) But",
        "(d) when",
        "(e) and",
        "(f) and",
        "(g) that",
        "(h) But/Fortunately",
        "(i) Though/Although",
        "(j) As a result",
        "(k) At last/Finally/Eventually",
        "(l) and",
        "(m) At present/Now",
        "(n) and",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Jashore",
    data: {
      questions:
        "Leisure is the moment (a) --- a man is totally free from his work. In leisure, a man is (b) --- free from work but also from worries and tension. (c) --- it is a time, (d) --- a man is his own master and the mind is relaxed (e) --- the body is at rest. (f) --- life is full of duties. By performing our duties one after another, it our seems (g) --- our life is an exhausting business. This is the tragedy of our life that we cannot avoid our work and worries. (h) --- leisure helps us to break this chain and enable us to refresh ourselves and revive our spirit. Leisure breaks the monotony of existence with a touch of variety. (i) ---; into developed countries, we will see that people love to spend their leisure in different ways. (j) ---, they never idle away their leisure time. (k) --- it is seen that some people love to go for travelling, some enjoy sight-seeing in different places. (l) --- some people spend their free time playing different types of games. (m) --- leisure is always a source of joy. (n) --- everybody should try to find leisure to enjoy it to make the life happy and peaceful.",
      answers: [
        "(a) when",
        "(b) not only",
        "(c) Basically",
        "(d) when",
        "(e) as well as",
        "(f) However",
        "(g) that",
        "(h) Hence/In this regard",
        "(i) If",
        "(j) Moreover/In fact",
        "(k) For example/Often",
        "(l) Besides",
        "(m) Undoubtedly",
        "(n) So",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dinajpur",
    data: {
      questions:
        "A cyclone is a devastating storm in Bangladesh that moves at a high speed. (a) --- it causes immense harm to people and property. (b) --- the inhabitants of coastal regions are the main victims of cyclone. (c) --- the cyclone of Bangladesh originates from the Bay of Bengal. (d) --- it is accompanied by thunders and heavy showers. (e) --- unbearable heat is felt for a few days. (f) --- one day the sky becomes terribly dark and strong winds begin to blow. (g) --- a terrible situation is created that lasts for hours. (h) --- it causes a great havoc causing death to people and other animals. (i) --- dwelling houses are blown away. (j) --- the cyclone is followed by scarcity of food and outbreak of various diseases. (k) --- the great loss caused by cyclone can be reduced. (l) --- prior warning can be given to people using modern technology of weather forecast. (m) --- people and domestic animals of the cyclone-prone areas can be shifted to cyclone shelters. (n) --- a quick relief work and medical facilities should be ensured.",
      answers: [
        "(a) Moreover",
        "(b) Specifically/Specially",
        "(c) Actually/Mainly",
        "(d) Moreover/Also",
        "(e) Beforehand",
        "(f) Suddenly/Later",
        "(g) Then/Ultimately",
        "(h) Eventually",
        "(i) As a result",
        "(j) Subsequently",
        "(k) However",
        "(l) Firstly/For example",
        "(m) Secondly/Besides/additionally",
        "(n) Finally/Moreover",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Barishal",
    data: {
      questions:
        "Scientists have always wondered (a) --- there is life anywhere out in the space. They have joined together in a major project called the communication with Extra Terrestrial Intelligence (b) --- seeks to establish contact with any other living beings in the universe. (c) ---, they are beaming out radio signals into the space. It was thought (d) --- there exists life on Mars. (e) --- two viking spacecrafts (f) --- landed on Mars in 1976 did not provide much evidence of life there. The pictures sent by them showed (g) --- the Mars has a sky; (h) --- , the sky is red instead of a blue one like ours. Its gravity is about half (i) --- strong (j) --- that of Earth. (k) ---, the atmosphere is also much thinner than our planet. It has deserts, high mountains, canals, volcanoes, craters etc. as well as summer (l) --- winter. (m) ---, there are no trees, (n) --- life forms.",
      answers: [
        "(a) whether/if",
        "(b) which",
        "(c) so",
        "(d) that",
        "(e) But",
        "(f) that/which",
        "(g) that",
        "(h) however",
        "(i) as",
        "(j) as",
        "(k) Besides",
        "(l) and",
        "(m) Moreover",
        "(n) let alone",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Mymensingh",
    data: {
      questions:
        "Time, by its very nature, is fleeting. (a) --- , time once gone is gone forever. (b) --- the sincere people realize the value of time. (c) --- not everyone is aware of the value of time. (d) --- it is seen that many of us waste time. (e) --- we realize the significance of lost time when it is too late. (f) --- we suffer in life. (g) --- all of us should make the best use of time. (h) ---- proper time management is the key to success in student life. (i) --- we find that an ideal student is the one who makes the best use of time. (j) --- ,a lazy student fails to make the grade as he kills time. (k) --- the teachers advise their students not to waste time. (l) --- they warn the students against their addiction to social networking sites and gaming. (m) --- students should follow the advice of their teachers. (n) --- ,they will suffer in the long run.",
      answers: [
        "(a) That's why",
        "(b) Only",
        "(c) But/However",
        "(d) Sometimes/Often",
        "(e) Unfortunately",
        "(f) As a result/Therefore",
        "(g) So",
        "(h) In fact/Undoubtedly",
        "(i) For example/For instance",
        "(j) On the other hand/Meanwhile",
        "(k) So/As a result/That's why",
        "(l) Besides/Moreover",
        "(m) Therefore/Hence",
        "(n) Otherwise",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Cumilla",
    data: {
      questions:
        "Health (a) --- is the root of all happiness, can be enjoyed taking adequate care of body and mind. People (b) --- are always under mental stress and suffer from anxieties can not enjoy a good health. (c) --- to enjoy good health, it is also necessary to keep our mind sound. They are doctors (d) --- say that simple and carefree life is more conducive to health. Many people, (e) --- are not aware of health rules. They (f) --- take physical exercise (g) --- take proper food. (h) --- , a huge number of people of our country live below poverty line. (i) --- they can not afford to eat good food. (j) --- they can not enjoy good health. (k) --- , awareness about health rules (l) --- following them are very important in maintaining good health. (m) --- only healthy people can contribute to the national development. (n) --- we must be careful of our health.",
      answers: [
        "(a) which",
        "(b) who",
        "(c) So",
        "(d) who",
        "(e) however",
        "(f) neither",
        "(g) nor",
        "(h) In fact/Moreover",
        "(i) Therefore/Hence/So",
        "(j) As a result/So",
        "(k) Indeed/For this reason",
        "(l) and",
        "(m) Because",
        "(n) So/Therefore/Hence",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Chattogram",
    data: {
      questions:
        "Early rising is one of the best habits (a) --- a man can posses. (b) --- the benefits of early rising are many. (c) ---, if we get up Early, we get enough time to work (d)---, we can enjoy the fresh air of the morning which refreshes our body and mind. (e) --- we can take some exercises or a walk. (f), in the morning nature smiles with colourful flowers and chirping of birds. (g)---, Early rising takes us to close contact with wonderful world of nature (h) --- we will suffer a lot. (i) ----, if we do not get up early in the morning, we do not have enough time to do our work. (j) ---, we can not finish our work in time. (k) --- late rising from bed tells upon our health. (l) --- we can never enjoy the freshness of nature. (m) ---, Early rising keeps us safe and sound both physically and mentally (n) ---, we should make a habit of early rising.",
      answers: [
        "(a) that",
        "(b) In fact/Actually",
        "(c) Firstly",
        "(d) Thus/Then",
        "(e) Secondly",
        "(f) More importantly",
        "(g) Thus",
        "(h) However/On the other",
        "(i) First of all/Firstly",
        "(j) As a result",
        "(k) Secondly",
        "(l) In addition/Moreover",
        "(m) As a whole",
        "(n) So/Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dhaka",
    data: {
      questions:
        "Teaching is a noble profession. (a) --- to be a teacher, one must possess some noble qualities too. (b) --- he should be a student. (c) --- teaching is related to knowledge, he can't acquire knowledge (d) --- he is a student. (e) --- a teacher thinks (f) --- he knows everything; he can't be a good teacher. (g) --- a thirst for knowledge is the second best quality of a teacher. (h) --- a teacher should be a psychologist. Different students have different ways of learning. (i) --- the teacher needs to teach his students by studying their psychology. Fourthly a teacher should have good delivery power. (j) --- his voice should be clear (k) --- artistic. (l) --- a teacher should be an actor (m) --- he needs to behave according to the classroom situation. And (n) --- a teacher must be a good human being.",
      answers: [
        "(a) In order",
        "(b) Firstly",
        "(c) Since",
        "(d) unless",
        "(e) If",
        "(f) that",
        "(g) Secondly",
        "(h) Thirdly",
        "(i) Therefore",
        "(j) Furthermore",
        "(k) and",
        "(l) Moreover",
        "(m) because",
        "(n) finally",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Rajshahi",
    data: {
      questions:
        "Mobile phone is a miracle of modern science. It has brought about a revolutionary development in the arena of communication. (a) --- it has eliminated distance (b) --- promoted human relationship. (c) --- it helps to promote business. (d) --- gearing the pace of business, it ensures the smooth growth of economy. (e) --- it can solve many problems of mathematics. (f) --- it has become a daily necessity. (g) --- it is not free from demerits. (h) --- becomes detrimental to the reckless users. (i) --- the use of mobile phone by the teenagers has to be regulated. (j) --- they will go to ruin. (k) --- if we want to save our young generation, we have to be more vigilant. (l) --- parents, teachers and neighbors can play positive role in this regard. (m) --- the people who are addicted to wanton mobile phone have to be more cautious. (n) --- they maintain abstinence; it will positively influence their offspring.",
      answers: [
        "(a) Firstly",
        "(b) and",
        "(c) Secondly",
        "(d) For/With a view to/By",
        "(e) Additionally",
        "(f) Therefore",
        "(g) However",
        "(h) For example",
        "(i) Thus",
        "(j) Otherwise",
        "(k) And",
        "(l) Furthermore/Moreover",
        "(m) Moreover/Besides",
        "(n) If",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Barishal",
    data: {
      questions:
        "Time and tide wait for none. (a) --- no one can stop the march of time. (b) ---, it is very important to value our time. (c) ---, if time once has gone, we cannot regain it. (d) ---, we should not waste a single moment in vain. (e) --- we should make the proper use of very single moment of our life. (f) ---, the students should understand the value of time. (g) ---, it is a matter of great regret that some of the students pass away their valuable time in Facebook. (h) ---, they kill their time, (i) --- they cannot prepare their lessons well. (j) ---, they always have a poor preparation for the examination. (k) --- they cannot do well in the examination. (l) --- they don't stop wasting time. (m) ---, they continue to waste their time using different social media sites (n) --- it is too late for them.",
      answers: [
        "(a) that is why/truly/actually",
        "(b) Therefore",
        "(c) Indeed/In fact",
        "(d) Hence",
        "(e) Moreover",
        "(f) Especially/Mainly",
        "(g) However/But",
        "(h) When/As",
        "(i) then/so",
        "(j) As a result/As a consequence/Consequently",
        "(k) Finally/At last/At the end",
        "(l) still/nevertheless",
        "(m) Instead/Rather",
        "(n) until",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dinajpur",
    data: {
      questions:
        "My name is Amerigo. I am 13 years old (a) --- live on the street alone. My mother does not live with me. (b) ---, does not want me. (c) ---, she told me to go away. (d) ---, my mother is separated from my father. (e) --- she is married to another man. Probably she is happy with him. (f) ---, my father lives very far away. (g) ---, I cannot go there. (h) --- I want to go to him, he doesn't take me either. I begged him to send to me some money (i) --- I could buy a bus ticket. I am still waiting (j) --- he hasn't answered. (k) --- the streets are now my home. I used to do some works (l) ---, collecting trash, selling ice-cream of a owner etc. I sold ice-cream of the owner but he gave me nothing in return. (m) ---, I had to starve sometimes. (n) ---, my life is very hard without my parents.",
      answers: [
        "(a) and",
        "(b) Because/Besides",
        "(c) Moreover",
        "(d) Unfortunately/Actually",
        "(e) Now",
        "(f) On the other hand",
        "(g) That's why/So",
        "(h) Even if",
        "(i) so that",
        "(j) but",
        "(k) For this reason/As a result",
        "(l) such as",
        "(m) As a result",
        "(n) Thus/So",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Chattogram",
    data: {
      questions:
        "Self-confidence is essential to attain success in life. (a) --- a person having self-confidence has won half of the battle. Self-confidence enables a man to prosper by creating some other virtues requisite for success. (b) --- when a self-confident man fails to attain success, he becomes determined to reach his goal. This determination gives rise to some other virtues in him. (c) ---, he becomes diligent. He does not yield to failure. (d) --- he endeavours more in the process. (e) --- he becomes more sincere in his work. (f) --- he becomes successful. (g) --- a man devoid of self-confidence stumbles at every step, (h) --- he loses vitality to go ahead. (i) --- he does not try once more. (j) --- he is heard to curse his fortune. (k) --- the brave who have self-confidence can have their names enlisted in the list of the greatest men on earth. (l) --- this process has been going on since prehistoric time. (m) --- we must follow the track of the greatest people. (n) --- we have to be failure in life and lament.",
      answers: [
        "(a) In fact/Actually",
        "(b) Thus/Hence",
        "(c) Firstly",
        "(d) Rather",
        "(e) Secondly",
        "(f) Finally",
        "(g) On the other hand/On the contrary",
        "(h) Naturally/Usually",
        "(i) Even",
        "(j) As a result/Often",
        "(k) Actually/In fact",
        "(l) And",
        "(m) So/Hence",
        "(n) Otherwise",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Jashore",
    data: {
      questions:
        "The internet has transformed the way we live. (a) ---, it has become an integral part of our life. On the one hand, this technology has brought us many benefits. (b) ---, it has many negative sides. (c) --- the internet, our communication systems have become much faster and more efficient. (d) ---, we can make bank transactions and pay our bills from home now. (e) ---, the internet allows us to access health information easily and, (f) ---, saves many lives. (g) ---, our learning opportunities have greatly increased, thanks to digital technologies. (h) ---, the internet is not an unmixed blessing. (i) ----, its harmful effects far outweigh its benefits. (j) ---, we should take precautions about using this technology. (k) ---, we must be careful not to become addicted to internet browsing. Second, we should keep an eye on our younger family members, (l) --- there are potential dangers in the virtual world. (m) ---, online gambling and cyberbullying are very common on the internet nowadays. (n) ---, it can be said that the internet technology is doing us more harm than good.",
      answers: [
        "(a) In fact/actually",
        "(b) On the other hand",
        "(c) Because of",
        "(d) Firstly",
        "(e) Secondly",
        "(f) thus",
        "(g) Thirdly",
        "(h) However",
        "(i) Unfortunately/Sometimes",
        "(j) so",
        "(k) Firstly",
        "(l) because/as/since",
        "(m) Thirdly",
        "(n) So/To conclude/In conclusion",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Mymensingh",
    data: {
      questions:
        "Honesty is a noble virtue. The man (a) --- possesses this uncommon quality is the happiest man in the world. Truly speaking a man should have trustworthiness (b) ---- nobody believes a liar. A liar may prosper for the time being, (c) --- ultimately he goes to the dogs. (d) --- we should be honest in our life. It is believed that honesty is the best policy. (e) --- dishonesty is the sign of down fall. God helps those who are honest. (f) --- dishonest people are cursed. Childhood is the best time (g) --- children should be taught honesty. It is seen that children follow their parents. (h) ---, parents should be honest (i) --- they should be allowed to mix with those friends who are really honest. (j) --- parents should tell stories of honest people to children. (k) ---, they can tell the story of honest people from history. (l) --- parents should teach children how to distinguish between the right and the wrong. (m) --- children build up their character. (n) --- parents can show the path of honesty to children.",
      answers: [
        "(a) who",
        "(b) because/since/as",
        "(c) but",
        "(d) That's why/So",
        "(e) On the other hand",
        "(f) But/However",
        "(g) when",
        "(h) For this reason/That's why",
        "(i) and",
        "(j) Besides/Additionally",
        "(k) For example/For instance/To illustrate",
        "(l) Also",
        "(m) Accordingly",
        "(n) Thus",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Cumilla",
    data: {
      questions:
        "Junk food is very popular nowadays. (a) --- the children are very much fond of junk food. (b) --- the children are do we know what junk food actually is? Junk food is such kind of processed food (c) --- has been produced for its pungent taste rather than for its health value. (d) --- it contains high calories, salt, added sugar, saturated fat etc. (e) --- its nutritional value is very low. (f) ---- its appearance is very appealing and mouth watering. (g) ---- it can attract anybody. (h) --- it is harmful for health. (i) --- it consists of harmful substances, it may lead to a higher risk of obesity, cardiovascular diseases and other chronic health problems. (j) --- , it can also affect brain. (k) --- addiction to it may even result in the rejection of healthier foods such as fruits, vegetables, salads etc. (l) ---, the sugar used in junk food can damage our teeth and skin. (m) ---, we should avoid having junk food. (n) --- we should remember that health is the root of all happiness.",
      answers: [
        "(a) Especially",
        "(b) But",
        "(c) that/which",
        "(d) In one hand",
        "(e) On the other hand",
        "(f) But",
        "(g) Thus",
        "(h) However",
        "(i) Since",
        "(j) Furthermore",
        "(k) Additionally",
        "(l) Moreover",
        "(m) Therefore",
        "(n) Ultimately",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Mymensingh",
    data: {
      questions:
        "Mobile phone has added a new dimension to our daily life. It has brought the world closer to us. (a) ______, it has made the worldwide communication easier. (b) ______, we can talk to others, chat with friends and send e-mails. (c) ______, using social media has become handy with this device. (d) ______, we can capture our special moments. (e) ______, many other apps help us learn new things. (f) ______, mobile phone can show us the whole world through the Internet. (g) ______, it has been a part that is part of our life. We cannot go for a single day without using it. (h) ______, it is not free from defects. It has some negative sides also. (i) ______, excessive use of mobile phone may damage our hearing power. (j) ______, it is a means of wasting time. (k) ______, many crimes are being done with the use of mobiles. (l) ______, harmful radiation from it may cause cancer to the users. (m) ______, we are not aware of these bad effects. (n) ______, we will fall in health hazard.",
      answers: [
        "(a) In fact/Indeed/Actually",
        "(b) Besides",
        "(c) Moreover",
        "(d) In other words",
        "(e) In addition",
        "(f) Thus/In this way",
        "(g) So/Hence/Therefore",
        "(h) Yet/Nevertheless",
        "(i) Firstly",
        "(j) Secondly",
        "(k) Thirdly",
        "(l) Finally",
        "(m) Yet/Nevertheless",
        "(n) As a result/As a consequence",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "In life we want to be perfect. (a) ____, to attain perfection is impossible (b) ____ man is basically imperfect. (c) ____, we should try to be great. (d) ____ it is not easy to be great because we have to attain certain virtues. (e) ____, we should be truthful (f) ____ truthfulness gives rise to many other virtues. (g) ____ we have to be honest (h) ____ honest people are valued everywhere. (i) ____ dishonest people are hated by all. (j) ____ we can conclude that to be great is more important than to be perfect. (k) ____ the idea of perfection varies from person to person. (l) ____, one’s idea of perfection changes. (m) ____ learning how to be perfect is basically a lifelong deal. (n) ____, the road to perfection is something that we learn and understand along this journey of life.",
      answers: [
        "(a) However",
        "(b) as/since",
        "(c) Rather/Nevertheless/However",
        "(d) As a matter of fact/In fact/Generally/Usually/Again",
        "(e) First/Firstly/First of all",
        "(f) as/because",
        "(g) Second/Secondly",
        "(h) because",
        "(i) On the other hand/On the contrary",
        "(j) At last/Finally",
        "(k) Because",
        "(l) Again",
        "(m) So",
        "(n) Yet",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "A journey is always a source of pleasure. (a) — a journey by boat is more interesting, it is very easy to enjoy a journey by boat here. Bring that autumn, the day was closed. (b) — I would be suitable time for me to make a journey by boat. (c) — I proposed to some of my friends who are and how we have accepted my proposal. (d) — I was made a plan. (e) — we hired a boat and started a journey at 11 am. We were very fortunate indeed as the boatman was very expert. (g) — We wanted you calm from an outlet. (h) — specific barges was slightly pushing the sail. (i) — we had no trouble during the journey. (j) — we had a lot of enjoyment of a lot; if we beat was dancing on the small wave and it thrilled us a boat man. (k) — we also enjoyed a 'Blutarily agile' one after a boatman. (l) — we were delighted at the setting, the scene unchanged as very much.",
      answers: [
        "(a) In fact",
        "(b) In addition/Additionally/However",
        "(c) As a result/Therefore",
        "(d) Thus/As a result",
        "(e) Firstly/At first",
        "(f) Then/Secondly/Next",
        "(g) In fact",
        "(h) Besides",
        "(i) Additionally/Moreover",
        "(j) Meanwhile",
        "(k) Finally/At last",
      ],
      isDifficult: true,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "A thing of beauty is a joy forever. (a) ______, a flower is a symbol of beauty and purity. (b) ______, flower cultivation was rare in our country. (c) ______ the scenario has been changed. (d) ______ people cultivate flowers not only for enjoying their beauty but also for earning money. (e) ______, in big cities and towns, many flower shops have flourished and different types of flowers are sold there. (f) ______ the demand of flowers is increasing day by day. (g) ______ they are of great use to us. (h) ______ flowers play an important role in making our mood cheerful and happy. (i) ______ they are used for decorating homes. (j) ______ flowers are regarded as a symbol of mourning and tribute to someone. (k) ______ in many popular and social events, flowers are needed for more or spot decoration. (l) ______ we express our love and affection towards anyone with flowers. (m) ______ flowers are great source of honey, perfume, medicine and even food. (n) ______ the use of flowers in our daily life has become wide in different ways.",
      answers: [
        "(a) In fact",
        "(b) In the past",
        "(c) But",
        "(d) Nowadays/Now",
        "(e) In addition/Moreover",
        "(f) Consequently/As a result",
        "(g) So",
        "(h) Indeed/Actually",
        "(i) Firstly",
        "(j) Secondly",
        "(k) Thirdly",
        "(l) Fourthly",
        "(m) Finally",
        "(n) Thus/In this way",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "There is a proverb (a) — every man is for himself. (b) — it does not mean that he will be selfish. (c) — only works for himself destroying the rights of others. (d) — it means that he will protect his own right, without harming others. He will show love and respect (e) — for his relatives (f) — for other fellow people. (g) — sometimes we find some people (h) — think of themselves only (i) — snatch away other’s part. (j) — educational institutions don’t mould our children’s mind with moral lessons. (k) — they are busy with how they can produce huge number of citizens with certificates. (l) — these men are in their professions, they start thinking of them merely (m) — indulge in personal gaining. (n) — our education needs to make us learn how to be a man for men.",
      answers: [
        "(a) that",
        "(b) But",
        "(c) who",
        "(d) Yet",
        "(e) not only",
        "(f) but also",
        "(g) However",
        "(h) who",
        "(i) and",
        "(j) Because",
        "(k) Instead",
        "(l) When",
        "(m) and",
        "(n) Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "Happiness is a relative term. (a) ______ it depends upon some factors. Contentment is the key to happiness. (b) ______ contentment varies from person to person. (c) ______, a beggar may be contented with only ten taka. (d) ______, a wealthy person may be unsatisfied even after getting one million taka. It is said (e) ______ contentment brings happiness. (f) ______ we must learn to be contented with (g) ______ we have. This learning is the simplest way to remain happy. (h) ______, we must remember that our life is short and, in this short life, we cannot get everything what we want. If we want everything, we will not get happiness. (i) ______ we will get frustrated and we will plunge into the world of sadness. (j) ______, it is always better to be contented with what we have than to live in eternal sadness. (k) ______, we should bear in mind that great men of the world didn’t long for much wealth (l) ______ they remained happy with a little. (m) ______, man can mould his own life worthy (n) ______ he values the necessity of life morally.",
      answers: [
        "(a) Because",
        "(b) In fact/Additionally/Moreover/Also",
        "(c) For example/For instance",
        "(d) Meanwhile/On the other hand/On the contrary",
        "(e) that",
        "(f) So/Therefore",
        "(g) what",
        "(h) Actually/In fact",
        "(i) Rather",
        "(j) Hence",
        "(k) Moreover",
        "(l) but",
        "(m) Therefore",
        "(n) if",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "Unemployment is a great curse. (a) ______ all the countries of the world suffer from the curse. (b) ______ nowhere in the world this problem is so acute as in our country. (c) ______ there are many reasons behind it. (d) ______ our country is industrially backward. (e) ______ our traditional education system is not service-oriented. (f) ______ our students and youths have false sense of dignity. (g) ______ they run after job only. (h) ______ unemployment problem should be removed at any cost. (i) ______ we want to remove it truly. Our education system should be changed. (j) ______ more truths and factories should be established. (k) ______ the educated youth should change their attitude to life. (l) ______ they can work in agriculture field, cultivate fish, grow vegetables etc. (m) ______ they can start small business. (n) ______ self employment is a possible solution to this great problem.",
      answers: [
        "(a) At present/Now/In fact",
        "(b) But/Truly speaking",
        "(c) Obviously/However/Surely",
        "(d) Firstly",
        "(e) Secondly",
        "(f) Thirdly",
        "(g) So/Therefore",
        "(h) Hence",
        "(i) Indeed",
        "(j) Additionally",
        "(k) Moreover",
        "(l) Besides",
        "(m) On top of that/Also",
        "(n) Therefore",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "Most of the people of Bangladesh are not able to realise the importance of water. (a) — millions of liters are wasted every year. (b) — facing pure water crisis. (c) — Government campaign may help to reduce unnecessary water consumption. (d) — water is a very important resource for various reasons. (e) — we need to drink clean water to survive. (f) — we need to keep ourselves clean. (g) — without water, we cannot grow crops. (h) — we cannot provide animals with food. (i) — Government should do more to make people recognize this. (j) — the human population is growing, the climate is changing too. (k) — there may not be enough water for everyone in future. (l) — water treatment processes costs lost and use a large amount of electricity. (m) — reduced water consumption would save money and electricity for the future. It will reduce green house gas emissions. (n) — we should encourage people to change wasteful habits now before it is too late.",
      answers: [
        "(a) Rather/Instead",
        "(b) With a view to/Regarding",
        "(c) Under these circumstances",
        "(d) In fact/Indeed",
        "(e) Besides",
        "(f) Moreover",
        "(g) Consequently/As a result",
        "(h) So",
        "(i) As/Since",
        "(j) In addition",
        "(k) In this way",
        "(l) Therefore",
        "(m) Moreover",
        "(n) Hence/Thus",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Chattogram",
    data: {
      questions:
        "Everybody wants to be happy in life. Happiness is a relative term. (a) ______ it depends upon some factors. (b) ______ contentment is the key to happiness. (c) ______ it varies from person to person. (d) ______ a beggar may be contented with only ten taka. (e) ______ a wealthy person may be unsatisfied even after getting one million taka. (f) ______ it is said that contentment brings happiness. (g) ______ we must learn to be contented with what we have. (h) ______ this learning is the simplest way to remain happy. (i) ______ we must remember that our life is short. (j) ______ in this short life, we cannot get everything. (k) ______ we want. (l) ______ if we want everything, we will not get happiness. (m) ______ we will get frustrated and plunge into the world of sadness. (n) ______ it is always better to be contented with what we have than to live in eternal sadness.",
      answers: [
        "(a) Because",
        "(b) In fact/Indeed",
        "(c) However",
        "(d) For example/For instance",
        "(e) Meanwhile/On the other hand/On the contrary",
        "(f) Consequently/As a result/Therefore",
        "(g) Therefore",
        "(h) Actually/In fact",
        "(i) In addition",
        "(j) But",
        "(k) That",
        "(l) If",
        "(m) Rather/Instead",
        "(n) So/Hence",
      ],
      isDifficult: true,
      isCompleted: true,
    },
  },
];
