export const modifiers = [
  {
    exam: "hsc",
    year: 2025,
    board: "Mymensingh",
    data: {
      questions:
        "Al Mahmud, (a) ___ (use an appositive), was born in Brahmanbaria in 1936. He is renowned for (b) ___ (use participle to pre-modify the noun) rural life and culture. He emerged as a (c) ___ (pre-modify the noun) poet in the 1960s and played a (d) ___ (pre-modify the noun) role in modernizing Bengali poetry. His celebrated works, which include 'Lok Lokantor', 'Kaler Kolosul' and 'Somail Kabir', show (e) ___ (post-modify the verb) his mastery in vivid imagery and symbolism. (f) ___ (use possessive) poetry often explores themes of love and loss, struggle and socio-political conditions of Bangladesh. Despite a number of controversies for his political ideology, his literary contributions remained unparalleled. His influence on (g) ___ (use a noun adjective to pre-modify the noun) poetry continues (h) ___ (use an infinitive to post-modify the verb) the later generations of poets. This (i) ___ (pre-modify the noun) genius passed away (j) ___ (use a prepositional phrase to post-modify the verb) of 82 in 2019.",
      answers: [
        "(a) a celebrated writer",
        "(b) depicting/portraying",
        "(c) notable/renowned",
        "(d) significant/prominent",
        "(e) skillfully",
        "(f) His",
        "(g) Bangla",
        "(h) to inspire/to motivate",
        "(i) great/towering/exceptional",
        "(j) at the age",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "Bangladesh is criss-crossed with hundreds of rivers. (a) ___ (use a demonstrative to pre-modify the noun) rivers are the gifts of Almighty Allah. They play a very important role in our (b) ___ (pre-modify the noun) economy. There are hundreds of big and small rivers in (c) ___ (use possessive to pre-modify the noun) country. The big rivers flow (d) ___ (use adverbial phrase to post-modify the verb) but small ones flow only during the rainy season. Our rivers are of great use and important to us. They are (e) ___ (pre-modify the verb) related to our economy and prosperity of our country. These rivers are sources of communication, wealth and property, energy and fish. All the rivers play a (f) ___ (pre-modify the noun) role in our (g) ___ (use a noun adjective to pre-modify the noun) system. We use boats, launches, steamers (h) ___ (use infinitive to pre-modify the noun) goods through riverway which is cheaper and easier than carrying by land in our country. Moreover, people (i) ___ (use present participle to post-modify the noun) by the riverside can earn their livelihood, by catching fish. The silt (j) ___ (use past participle to post-modify the noun) by the river water increases the fertility of our agricultural land.",
      answers: [
        "(a) These",
        "(b) national",
        "(c) our",
        "(d) all the year round",
        "(e) closely",
        "(f) vital/important",
        "(g) communication",
        "(h) to carry",
        "(i) living",
        "(j) left",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "Once a wolf went to a stream to quench (a) ___ (use possessive to pre-modify the noun) thirst with water. While he was drinking water, he saw (b) ___ (use article to pre-modify the noun) lamb that was also drinking water over there. At the sight of the lamb, his mouth began (c) ___ (use an infinitive phrase to post modify the verb). He turned to the lamb and said, 'How dare you make the water muddy? Can't you see that I am drinking water from the (d) ___ (use an adjective to pre-modify the noun) stream?' The lamb got so (e) ___ (use an adverb to pre-modify the adjective) frightened that it could not speak for a while. Then it replied, 'Sir, I beg (f) ___ (use possessive to pre-modify the noun) pardon. The water is running down (g) ___ (post modify the verb with prepositional phrase) to me. How can I make it muddy?' The wolf said, 'But you bleated me and called me names (h) ___ (post modify the verb with an adverb).' The lamb replied, 'Sir, I was not even born then. How could I abuse you last year?' The wolf (i) ___ (use a relative pronoun to post modify the noun) was determined to eat (j) ___ (use a demonstrative to pre-modify the noun) poor lamb, said to it, 'Then it must have been your father, or mother or brother. You must suffer for your race.'",
      answers: [
        "(a) his",
        "(b) a",
        "(c) to water with greed",
        "(d) clear",
        "(e) much/terribly",
        "(f) your",
        "(g) from your end",
        "(h) last year",
        "(i) that",
        "(j) that",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "The necessity of learning English is the demand of today’s world. But many people in (a) ____ (Pre-modify the noun with a possessive) country do not realize it. As we are living in a (b) ____ (Pre-modify the noun with an adjective) village, it has become essential (c) ____ (Post-modify the adjective with an infinitive phrase). So, if we know English (d) ____ (Post-modify the verb with an adverb), we can communicate with people all over the world. Surely, English has become an important element of our (e) ____ (Use an adjective to pre-modify the noun) development. This language ensures an (f) ____ (Use an adjective to pre-modify the noun) access to all the information in the world computers. (g) ____ (Use a participle phrase to pre-modify the clause), we can progress personally and professionally. If we fail to have a good command over the language, we will lag behind (h) ____ (Post-modify the verb using an adverbial). With (i) ____ (Use a demonstrative to pre-modify the noun) language, we can get access to art, literature and culture from various countries. So, it is clear that English is (j) ____ (Use an adverb to pre-modify the verb) spoken all over the world.",
      answers: [
        "(a) our",
        "(b) global",
        "(c) to communicate with people all over the world",
        "(d) properly/accurately",
        "(e) national",
        "(f) easy",
        "(g) Having learnt English",
        "(h) badly",
        "(i) this",
        "(j) widely",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "hsc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "It was a hot (a) ___ (use a noun adjective to pre-modify the noun) day. A (b) ___ (pre-modify the noun) crow flew all over the fields looking for water. For a long time, she could not find any water. She felt (c) ___ (use an intensifier to pre-modify the adjective) weak, almost giving up hope. Suddenly, she saw a water jug below her. She flew (d) ___ (post modify the verb) to see if there was any water inside. Yes, she could see some water inside the jug. The crow tried (e) ___ (use an infinitive phrase to post modify the verb). Sadly, she found that the neck of the jug was too narrow. Then she tried to push the jug down for the water to flow out. But she found (f) ___ (use a demonstrative to pre-modify the noun) jug too heavy. The crow thought (g) ___ (use a phrase to post modify the verb) what to do. (h) ___ (use a participle to pre-modify) she saw some pebbles nearly. She (i) ___ (pre-modify the verb) had a good idea. She started picking up the pebbles one by one, dropping each into the jug. As more and more pebbles filled in the jug, the water level kept rising. Soon it was high (j) ___ (post-modify the adjective) for the crow to drink. The crow quenched its thirst and flew away.",
      answers: [
        "(a) summer",
        "(b) thirsty",
        "(c) very",
        "(d) down",
        "(e) to drink water",
        "(f) that",
        "(g) for a while",
        "(h) Looking",
        "(i) instantly",
        "(j) enough",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "hsc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "A day in which it rains (a) —— (post modify the verb) all day long, is called a rainy day. The sky remains overcast with (b) —— (pre modify the noun) clouds. People cannot go out without (c) —— (pre modify the noun with a determiner) umbrella. It affects our (d) —— (pre modify the noun) activities. Even the school and colleges are shut down. But many people like (e) —— (post modify the verb with an infinitive phrase) in the rain. They go to an (f) —— (pre modify the noun) space and enjoy the rain. The working class people suffer a lot (g) —— (post modify the verb). They do not work and spend (h) —— (post modify the noun) day which brings misfortune to them. They cannot earn (i) —— (post modify the verb with an infinitive) their family. So, a (j) —— (pre modify the noun) day is a curse to the poor.",
      answers: [
        "(a) continuously",
        "(b) dark",
        "(c) an",
        "(d) daily",
        "(e) to walk around",
        "(f) open",
        "(g) due to rain",
        "(h) entire",
        "(i) to support",
        "(j) rainy",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "Long ago there lived (a) ______ (use article to pre-modify the noun) merchant. He used to deal in salt. He had a donkey to carry the load. He used to sell (b) ______ (Use possessive to pre-modify the noun) salt loaded on the donkey. He had to cross a stream (c) ______ (Use an infinitive) to other village. Once his donkey fell (d) ______ (post modify the verb with prepositional phrase) and (e) ______ (Use quantifier to pre-modify the noun) of the salt was dissolved in water. The donkey (f) ______ (Use an adverb to pre-modify the verb) crossed the stream due to the light weight of salt (g) ______ (post modify the verb with prepositional phrase). The donkey was happy. The merchant next day loaded the donkey with a lot of cotton. The donkey once again repeated the (h) ______ (Use adjective to pre-modify the noun) trick. He fell into the stream. (i) ______ (Use a demonstrative to pre-modify the noun) time his load became very heavy. The donkey carried the heavy load. It was very tiring for him to move on. The donkey now realized his mistake. He stopped falling down into (j) ______ (Use determiner to pre-modify the noun) stream. The merchant had taught the donkey a good lesson.",
      answers: [
        "(a) a",
        "(b) his",
        "(c) to go",
        "(d) into the river",
        "(e) much",
        "(f) easily",
        "(g) without difficulty",
        "(h) same",
        "(i) This",
        "(j) the",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "Weather affects our life (a) ——— (post-modify the verb). We put on (b) ——— (pre-modify the noun) clothes when it is cold. We go out with an umbrella in the (c) ——— (pre-modify the noun) season. During the summer, we use fans (d) ——— (post-modify the verb with an infinitive phrase). However, sunshine and rain are (e) ——— (pre-modify the adjective with an intensifier) essential for us. Winter is also helpful for us. Vegetables grow (f) ——— (post-modify the verb with an adverbial phrase) in winter. (g) ——— (pre-modify the noun) rainfall helps to grow bumper crops. All the seasons have more or (h) ——— (pre-modify the noun) advantages. And they have (i) ——— (pre-modify the noun with a determiner) great influence on the environment. But the weather pattern is changing (j) ——— (post-modify the verb) because of global warming.",
      answers: [
        "(a) greatly",
        "(b) warm",
        "(c) rainy",
        "(d) to cool ourselves",
        "(e) very",
        "(f) plentifully in our country",
        "(g) Timely",
        "(h) less",
        "(i) a",
        "(j) rapidly",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "Yesterday a beggar came to our house. He stood at the gate wearing a (a) ___ (pre-modify the noun) dress. He was (b) — (pre-modify the adjective) weak, and could not speak clearly. He told me that he had been starving for two days and requested me (c) — (use an infinitive phrase to post-modify the verb). I felt pity for the (d) ___ (pre-modify the noun) man. I told him (e) — (use an infinitive phrase to post-modify the verb) and gave him (f) — (use a quantifier to pre-modify the noun) food. He began to eat instantly. He was eating (g) — (post-modify the verb with an adverbial phrase). I noticed that the clothes he wore, were not only dirty but also torn. So, I gave him some clothes too. He became extremely happy getting (h) — (pre-modify the noun with a determiner) clothes. He was (i) — (pre-modify the adjective with an intensifier) happy that tears of joy came out of his eyes. He then thanked me and blessed me (j) — (use a prepositional phrase).",
      answers: [
        "(a) dirty/ragged",
        "(b) extremely",
        "(c) to give him some food",
        "(d) helpless",
        "(e) to wait outside",
        "(f) some",
        "(g) with great eagerness",
        "(h) those",
        "(i) so",
        "(j) with a grateful heart",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dhaka",
    data: {
      questions:
        "Once there lived a (a) ___ (pre-modify the noun) fox in a jungle. One day, while he was walking (b) ___ (post-modify the verb) through the jungle he fell into a trap and lost his tail. He felt (c) ___ (pre-modify the adjective) unhappy and sad. But the fox was very cunning. He hit upon a plan. He invited all the foxes (d) ___ (post-modify the verb with an infinitive) to a meeting. When all the foxes arrived, the fox without a tail said, 'My dear friends, listen to me, please, I have discovered a (e) ___ (pre-modify the noun) thing. It is that our tails are (f) ___ (pre-modify the adjective) useless. They look ugly and dirty. So, we should cut off our tails, shouldn't we?' All foxes listened to the cunning fox (g) ___ (post-modify the verb). Most of them agreed (h) ___ (post-modify the verb with an infinitive) their tails. But an old and (i) ___ (pre-modify the noun) fox said to him, 'My friend, your plan is nice but evil. Actually, you want to cut off our tails because you have (j) ___ (pre-modify the noun with a determiner) tail of your own.'",
      answers: [
        "(a) clever",
        "(b) alone",
        "(c) extremely",
        "(d) to come",
        "(e) strange",
        "(f) completely",
        "(g) attentively",
        "(h) to cut off",
        "(i) wise",
        "(j) no",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dinajpur",
    data: {
      questions:
        "Rainy season is the proper time for (a) ___ (use a noun adjective to pre-modify the noun) plantation. It is the time when (b) ___ (use article to pre-modify the noun) environment is the most suitable one for the (c) ___ (use an adjective to pre-modify the noun) growth of trees. We should plant trees according to (d) ___ (use possessive to pre-modify the noun) suitability of the land. There are (e) ___ (use quantifier to pre-modify the noun) fallow lands around us. We can plant saplings on (f) ___ (use a demonstrative) lands. Sea-beaches, low-lying areas, road sides etc. can be brought under the scheme of tree plantation. We can easily engage landless people (g) ___ (use an infinitive phrase to post-modify the verb) the saplings and ensure their safe growth. The success of tree plantation programme requires (h) ___ (use article to pre-modify the noun phrase) united effort. The Government, the NGOs and the educated section of the society should work (i) ___ (post-modify the verb with adverbial) in this regard. Everybody should come forward spontaneously to contribute to (j) ___ (use a demonstrative to pre-modify the noun phrase) noble campaign.",
      answers: [
        "(a) tree",
        "(b) the",
        "(c) proper",
        "(d) its",
        "(e) many",
        "(f) these",
        "(g) to plant",
        "(h) a",
        "(i) together",
        "(j) this",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Cumilla",
    data: {
      questions:
        "Man has (a) ___ (use determiner to pre-modify the noun phrase) inborn curiosity to know the unknown and (b) ___ (use an infinitive phrase). He likes to see new places and wants to know about (c) ___ (pre-modify the noun) nations, their cultures, manners and religions. Bookish knowledge is (d) ___ (use adjective phrase). In order to have practical knowledge one has to go for travelling. (e) ___ (use an adverbial phrase) people had to suffer much for travelling as they did not have (f) ___ (pre-modify the noun) transports. Nowadays travelling has become much easier and comfortable for the invention of Aeroplan, buses, ships, speedy trains etc. Travelling plays a (g) ___ (use an intensifier to pre-modify the adjective) important role in acquiring knowledge. So, the students go for (h) ___ (pre-modify the noun with a noun adjective) tour which also helps to remove (i) ___ (pre-modify the noun with a possessive) boredom of study. In fact, everyone should travel to develop practical knowledge which cannot be acquired by sitting (j) ___ (post-modify the verb).",
      answers: [
        "(a) an",
        "(b) to explore the world",
        "(c) different",
        "(d) not enough",
        "(e) In the past",
        "(f) modern",
        "(g) very",
        "(h) study",
        "(i) their",
        "(j) idly",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Jashore",
    data: {
      questions:
        "Kazi Nazrul Islam is one of (a) ___ (use determiner to pre-modify the noun) best poets Bengal has (b) ___ (use an adverb to pre-modify the verb) produced. A (c) ___ (use an adjective to pre-modify the noun) writer, he contributed to many branches of Bangla literature. However, it is his poems and songs that earned him the (d) ___ (pre-modify the noun) reputation. Through his writings, Nazrul aimed (e) ___ (use an infinitive to post-modify the verb) the society because he was (f) ___ (pre-modify the verb) troubled by old values and religious superstitions. It is (g) ___ (use an intensifier to pre-modify the adjective) important to note that while Nazrul fought against religious bigotry, he composed (h) ___ (use a determiner to pre-modify the noun) songs that (i) ___ (pre-modify the verb) glorified religion. Sadly, a/an (j) ___ (pre-modify the noun) disease untimely ended his literary career in his early forties.",
      answers: [
        "(a) the",
        "(b) ever",
        "(c) versatile",
        "(d) highest",
        "(e) to reform",
        "(f) deeply",
        "(g) very",
        "(h) many",
        "(i) also",
        "(j) incurable",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Mymensingh",
    data: {
      questions:
        "A library is a (a) ___ (pre-modify the noun) house of knowledge. The students (b) ___ (use a participle) in all classes visit it in their leisure period. Usually a college library is housed in two rooms. (c) ___ (pre-modify the noun) almirahs are placed in one room. The other room is the (d) ___ (use a participle to modify the noun) room where magazines, Journals and newspapers are placed. Hundreds of books are arranged (e) ___ (post-modify the verb). So any type of book can be traced in no time. The books cater to the needs and interests (f) ___ (use a pre-positional phrase). Generally there are two separate sections in the library. One of them contains reference books like (g) ___ (use nouns) etc. The other section contains books (h) ___ (use a pre-positional phrase). Every student has a (i) ___ (use a noun adjective to modify noun) card. The reading room is always crowded (j) ___ (post-modify the verb) in the afternoon.",
      answers: [
        "(a) store",
        "(b) studying",
        "(c) Wooden",
        "(d) reading",
        "(e) systematically",
        "(f) of all",
        "(g) dictionaries, encyclopedias",
        "(h) for leisure reading",
        "(i) library",
        "(j) mostly",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Rajshahi",
    data: {
      questions:
        "Trees, (a) ___ (use an appositive), are essential for maintaining eco-system. Without trees, the balance of eco-system will be (b) ___ (post-modify the verb) lost. Trees provide us with (c) ___ (pre-modify the noun) elements without which we cannot live on this earth. It is a matter of (d) ___ (pre-modify the noun) concern that we are falling trees (e) ___ (post-modify the verb). As a dire consequence, the global temperature is rising (f) ___ (post-modify the verb). The existence of flora and fauna is at an (g) ___ (use a pre-modifier) risk. Polar ice caps are melting and (h) ___ (use a noun adjective) level is rising. (i) ___ (use a present participle phrase), we can avoid such a catastrophe. If we want to keep our (j) ___ (use a noun adjective) earth safe and sound, we have to plant trees and protect our forests.",
      answers: [
        "(a) our green friends",
        "(b) completely",
        "(c) vital",
        "(d) great",
        "(e) indiscriminately",
        "(f) alarmingly",
        "(g) increasing",
        "(h) water",
        "(i) Planting more trees",
        "(j) green",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Sylhet",
    data: {
      questions:
        "The Internet is (a) ___ (use intensifier) important in modern life. It helps us (b) ___ (post-modify verb with infinitive) information quickly. (c) ___ (pre-modify noun with participle) the Internet, students can learn new skills. It provides (d) ___ (pre-modify noun) opportunities for online education. Many people earn money (e) ___ (post-modify verb with adverb) through online jobs. However, (f) ___ (pre-modify noun) use may cause health problems. We should use it (g) ___ (post-modify verb with adverb). Parents must guide (h) ___ (pre-modify noun with possessive) children about safe browsing. The government should ensure (i) ___ (pre-modify noun) access for all citizens. Remember, the Internet is (j) ___ (post-modify adjective with prepositional phrase) when used properly.",
      answers: [
        "(a) extremely",
        "(b) to get",
        "(c) Using",
        "(d) unlimited",
        "(e) easily",
        "(f) excessive",
        "(g) wisely",
        "(h) their",
        "(i) equal",
        "(j) very beneficial",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Rangpur",
    data: {
      questions:
        "A (a) ___ (pre-modify noun) morning is always refreshing. The sun rises (b) ___ (post-modify verb with adverb), painting the sky (c) ___ (post-modify verb with prepositional phrase). Farmers go (d) ___ (post-modify verb with infinitive) their work. Birds sing (e) ___ (post-modify verb with adverb) on tree branches. The (f) ___ (pre-modify noun) air smells fresh after overnight rain. School children walk (g) ___ (post-modify verb with adverb) to their institutions. This time is (h) ___ (pre-modify adjective) suitable for morning walk. Elderly people gather (i) ___ (post-modify verb with prepositional phrase) for exercise. We should all develop (j) ___ (pre-modify noun) habit of early rising.",
      answers: [
        "(a) winter",
        "(b) beautifully",
        "(c) with golden light",
        "(d) to start",
        "(e) sweetly",
        "(f) cool",
        "(g) cheerfully",
        "(h) most",
        "(i) in parks",
        "(j) good",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dhaka",
    data: {
      questions:
        "Cricket is an (a) --- (pre-modify the noun) game. It is not a game of (b) --- (use possessive to pre-modify the noun) country. A (c) ---- (use a noun adjective to pre-modify the noun) match is played between two teams. (d) --- (use a distributive pronoun to pre-modify the noun) team consists of eleven players. A cricket field must be (e) --- (post-modify the noun). It requires two wooden bats, a ball & two sets of stamps. (f) --- (use a numeral adjective to pre-modify the noun) Umpires conduct the game. Sometimes, a third umpire is required (g) --- (use an infinitive to post-modify the verb) an acute confusion. (h) --- (use a participle to pre-modify the noun) the opportunity, the batter hits the ball away at a good distance and runs to the opposite wicket. If (i) --- (use an indefinite pronoun to pre-modify the noun) batter is out, next batter comes in his place. Both teams try (j) --- (use an adverbial phrase to post modify) to out all batters of the opposite.",
      answers: [
        "(a) international/elite",
        "(b) our",
        "(c) cricket",
        "(d) Each",
        "(e) well-maintained",
        "(f) Two",
        "(g) to resolve/clear",
        "(h) Having/Taking",
        "(i) any",
        "(j) hard enough",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Rajshahi",
    data: {
      questions:
        "People around were just watching as the (a) — (pre-modify the noun) boy started (b) — (post-modify the verb) into the (c) — (pre-modify the noun) canal. Then the traffic constable came. (d) —- (pre-modify the noun with a present participle) no time, he jumped into the canal. The (e) — (pre-modify the noun with an adjective) constable did not think of his (f) — (pre-modify the noun) life. He was (g) — (use an intensifier to pre-modify the adjective) kind that he risked his life. People (h) — (post-modify the noun) by canal praised him (i) — (post-modify the verb with an adverb). This type of person is a model (j) — (post-modify the noun).",
      answers: [
        "(a) young",
        "(b) drowning",
        "(c) deep",
        "(d) Wasting",
        "(e) police",
        "(f) own",
        "(g) so",
        "(h) standing/sitting",
        "(i) enormously/greatly/cheerfully/a lot/tremendously",
        "(j) for the society/of dedication and sacrifice",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Cumilla",
    data: {
      questions:
        "Amerigo, (a) --- (use noun in apposition) lives alone. His parents now live separate and none of them wants (b) --- (use an infinitive to post modify the verb) his responsibility. (c) --- (use possessive to pre-modify the noun) mother told him to go away because she is married to another man. (d) --- (use determiner to pre-modify the noun) streets are now his home. He wanted (e) --- (use an adjective to pre-modify the noun) money from his father to buy a (f) --- (use a noun adjective to pre-modify the noun) ticket. But his father did not answer. He earns his living by working hard. (g) --- (use adverbial to pre-modify the verb) he finds work. (h) --- (use demonstrative to pre-modify the noun) works are risky for him. Once he sold ice cream (i) --- (use a prepositional phrase to post modify the verb). But he got (j) --- (use quantifier to pre-modify the noun) money in return from the owner of the ice cream shop.",
      answers: [
        "(a) a street child",
        "(b) to take",
        "(c) His",
        "(d) The",
        "(e) some",
        "(f) bus",
        "(g) hardly",
        "(h) These",
        "(i) on the beach",
        "(j) no",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Jashore",
    data: {
      questions:
        "Language plays a (a) ____ (pre-modify the adjective with an intensifier) important role in our life. We use language from the time we wake up (b) ___ (post-modify the verb) till we go to bed at night. We use language not only in our (c) ____ (pre-modify the noun) hours. but also in our dreams. We use language (d) ____ (post-modify the verb with an infinitive) what we feel and to say what we like or dislike. We also use language (e)____ (post modify the verb with an infinitive) information. Language is (f) ____ (pre-modify the adjective) present in our life. It is an (g) ____ (pre-modify the noun) part of our life. As an (h) ____ (pre-modify the noun) nation we also have a language. But we had to struggle (i) ____ (use adverb to post-modify the verb) to establish the right to our language. Many (j) ____ (pre-modify the noun with an adjective) sons of our country sacrificed their lives for our mother-tongue.",
      answers: [
        "(a) very",
        "(b) in the morning",
        "(c) conscious/active",
        "(d) to express",
        "(e) to share/to gather",
        "(f) always",
        "(g) integral/inevitable",
        "(h) independent",
        "(i) a lot/hard/enormously",
        "(j) brave/courageous",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Sylhet",
    data: {
      questions:
        "Drug addiction among the young generation has become a (a) _____ (pre modify the noun) concern. Drug is mainly used as medicine (b) ____ (use an infinitive to post modify the verb) diseases and an excess of taking drug for no disease is called drug addiction. It has grasped the young generation (c) ____ (post modify the verb). They take drugs to forget (d) ____ (use possessive to pre modify the noun) sadness. (e) _____ (pre modify the noun) people take drugs (f) ____ (use adverb to post modify). Drug addiction causes (g) ____ (pre personalize the noun) harm to human body. (h) ____ (use a participle) them aware, we can remove this curse from our society. All concerned should take initiatives (i) ____ (use an infinitive to post modify the verb) it. The criminals should be punished with an (j) ____ (use a noun adjective) hand.",
      answers: [
        "(a) major",
        "(b) to cure",
        "(c) heavily",
        "(d) their",
        "(e) Young",
        "(f) widely/recklessly",
        "(g) severe",
        "(h) Making",
        "(i) to prevent",
        "(j) iron",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Barishal",
    data: {
      questions:
        "Kazi Nazrul Islam is called the Shelley of Bangla literature. He was a (a) --- (pre modify the noun) poet. He wrote (b) --- (post modify the verb) in almost all branches of Bangla literature. Nazrul, (c) --- (use an appositive to post modify the noun), won the attention of everybody in his childhood. He wrote ceaselessly until the death of (d) --- (use a possessive to pre modify the noun) poetic flare. He composed (e) --- (pre modify the noun) songs (f) --- (post modify the noun with an adjective clause). His literary works have enriched (g) —- (pre modify the noun) Literature. His poems and songs played a great role (h) --- (use an infinitive to post modify the verb) in our war of Liberation. He (i) --- (pre modify the verb) sang the songs of equality in his poems. He is (j) --- (pre modify the noun with determiner) pride, no doubt.",
      answers: [
        "(a) revolutionary/rebel",
        "(b) relentlessly/tirelessly",
        "(c) an orphan child/a prodigy",
        "(d) his",
        "(e) many",
        "(f) which are loved/appreciated by all",
        "(g) Bengali/Bangla",
        "(h) to encourage people",
        "(i) always",
        "(j) our",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dinajpur",
    data: {
      questions:
        "An (a) ____ (pre-modify the noun) student is he, who has (b) ____ (use a quantifier to pre-modify the noun) good qualities. he studies (c) ____ (post modify the verb). He knows that the (d) ____ (pre-modify the noun) duty of a student is to study. So, he never neglects (e) ____ (use a possessive) duty. He even makes the proper use of (f) ___ (use a determiner to pre-modify the noun) moment. Sabuj, (g)___ (post modify the noun with an appositive) of our class is an example of a good student. Sabuj is (h) ___ (pre-modify the adjective) helpful to us. I try (i) ____ (modify the verb with an infinitive) a boy like Sabuj. I want to be one of the (j) ____ (pre-modify the noun) stars in the class.",
      answers: [
        "(a) ideal",
        "(b) many",
        "(c) regularly",
        "(d) main",
        "(e) his",
        "(f) every",
        "(g) a student",
        "(h) very",
        "(i) to be",
        "(j) brightest",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Mymensingh",
    data: {
      questions:
        "The purpose of education is to bring about (a) ___ (use an adjective to pre-modify the noun) changes in (b) ___ (use a possessive to pre-modify the noun) behaviour. It also brings changes in our lives and society (c) ___ (use a relative clause to post-modify the noun). If it fails to do so, it can't be called education. Education is not only receiving certificates and getting grades. It is (d) ___ (use an intensifier to pre-modify the adjective) more than that, we can apply our (e) ____ use a part participle to pre-modify the noun) knowledge in our engagement with the world that lies (f) ____ (use an adverb to post-modify the verb). We can do that in (g) ____ (use an adjective to pre-modify the noun) ways. One way is civic engagement which is (h) ____ (use an adverb to pre-modify the verb 'appreciated') appreciated all over the world. Civic engagement means working to make difference in civic life (i) ____ (use a prepositional phrase to post-modify the noun life'). A person (j) ____ (use a past participle to post modify the noun) civically is concerned about civic issues like injustice, discrimination and other forms of social ills.",
      answers: [
        "(a) positive/effective",
        "(b) our",
        "(c) in which we live/where we live",
        "(d) much/far",
        "(e) acquired",
        "(f) around",
        "(g) many/different",
        "(h) greatly",
        "(i) of a person",
        "(j) behaved",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Chattogram",
    data: {
      questions:
        "We know that (a) --- (use quantifier to pre-modify the noun) species are important for maintaining (b) --- (pre-modify the noun) balance. If one is lost, the whole natural environment changes (c) --- (post-modify the verb). In order to protect the environment from being spoilt, we should protect (d) --- (use possessive to pre-modify the noun) wildlife. (e) --- (use determiner to pre-modify the noun phrase) good news is that many countries are taking action (f) --- (use infinitive phrase to post-modify the verb). George Lay Cock, (g) --- (use appositive to post-modify the noun) writes, 'Mankind must develop a concern for wild creatures and determine that (h) --- (use demonstrative to pre-modify the noun) wild species will not perish (i) --- (use prepositional phrase as post-modifier). We have to save wild animals (j) --- (use relative clause as post-modifier).",
      answers: [
        "(a) all",
        "(b) environmental/ecological",
        "(c) drastically/often for worse/greatly",
        "(d) our",
        "(e) The",
        "(f) to protect (the wildlife)",
        "(g) a famous environmentalist/author of several books on wildlife",
        "(h) these",
        "(i) in the near future",
        "(j) which are in the risk of extinction",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dhaka",
    data: {
      questions:
        "Arsenic is a (a)---(pre-modify the noun) substance. It is (b)---(use an intensifier to pre-modify the adjective) dangerous for human health. (c)---(use a demonstrative to pre-modify the noun) substance is found in the water of the tube well. There are (d)---(use quantifier to pre-modify the noun) villages in (e)---(use possessive to pre-modify the noun) country. Most of our (f)---(use a noun adjective to pre-modify the noun) people drink tube well water. As a result, many of them are suffering from the arsenic problem. This problem is (g)---(pre-modify the verb) found in North Bengal. We should take proper measures (h)---(post-modify the verb with an infinitive phrase). Government is trying to mark the tube wells having arsenic (i)---(use a participle to post modify the verb) red colour. People should be refrained from drinking water of (j) – (use demonstrative to pre-modify the noun) tube wells. Otherwise, they will suffer from arsenicosis.",
      answers: [
        "(a) harmful/poisonous/detrimental",
        "(b) very/extremely",
        "(c) this",
        "(d) many/several",
        "(e) our",
        "(f) village/common village",
        "(g) mostly/usually/unexpectedly/nowadays",
        "(h) to remain safe/to remove this problem/to purify the water",
        "(i) painting",
        "(j) those/these",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Rajshahi",
    data: {
      questions:
        "Taking food is essential. We take food (a) — (use an infinitive phrase to post-modify the verb). We can not survive on earth if we do not take food. In fact (b) — (use a quantifier to pre-modify the noun phrase) living beings need to take food. But it is a matter of great regret that (c) — (use possessive to pre-modify the noun) food is being adulterated. (d) — (use a noun-adjective to pre-modify the noun) adulteration is increasing (e) — (use an intensifier to pre-modify the adverb) alarmingly that we cannot stop it. (f) — (use a determiner to pre-modify the noun phrase) dishonest businessmen use (g) – (pre-modify the noun) chemicals in food and fruits to make illegal and quick money. But they do not think about (h) – (use a possessive to pre-modify the noun) health. (i) — (use present participle) adulterated food, people get sick. They are often attacked with different fatal diseases. So (j) — (use a gerund) food safety is a must today.",
      answers: [
        "(a) to survive/to live",
        "(b) all/every",
        "(c) our",
        "(d) Food",
        "(e) so",
        "(f) Some",
        "(g) harmful",
        "(h) our",
        "(i) Taking/Eating",
        "(j) ensuring",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Cumilla",
    data: {
      questions:
        "Newspaper plays a very (a) —- (pre-modify the noun) role in modern civilization. It publishes news and views of home and abroad. Only (b) – (pre-modify the noun) knowledge is not enough in this competitive world. A newspaper helps a man (c) – (post modify the verb with an infinitive) his general knowledge. Besides academic books, one should read newspapers (d) — (post modify the verb). The newspaper helps one (e) — (post-modify the verb with an infinitive) the facts of the world. (f) – (pre-modify the verb with a present participle phrase) regularly, one can be aware of everything. There are (g) – (pre-modify the noun) kinds of newspaper. One should select the newspaper (h) — (postmodify the verb). One should choose the (i) — (pre-modify the noun) paper because many newspapers present news partially. Whatever the paper is, it (j) – (pre-modify the verb) helps a man.",
      answers: [
        "(a) significant/important",
        "(b) bookish",
        "(c) to increase/to enrich",
        "(d) everyday/regularly",
        "(e) to know",
        "(f) Reading newspaper",
        "(g) different/various",
        "(h) properly/rightly/justly/wisely",
        "(i) impartial",
        "(j) always/really/actually/truly",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Jashore",
    data: {
      questions:
        "Air and water are the most (a) — (pre-modify the noun with an adjective) elements of the environment. But we pollute them (b) – (post-modify the verb with an adverb). Mills and factories use fuel (c) — (post-modify the verb with an infinitive) their products. The burning of this fuel creates smoke (d) — (post-modify the verb with an adverbial). Motor vehicles also pollute the air, (e) – (use an appositive). Water is polluted by (f) – (pre-modify the noun with a quantifier) kinds of waste and filth. We pollute water (g) – (post-modify the verb with present participle phrase) into water. Farmers use (h)---(pre modify the noun with an adjective) fertilizers and insecticides and pollute water. (i)---(pre-modify the noun with a past participle) water is (j)---(pre-modify the adjective with an intensifier) harmful to health.",
      answers: [
        "(a) essential/valuable",
        "(b) indiscriminately",
        "(c) to manufacture",
        "(d) on a large scale/hugely/enormously",
        "(e) an important element of our environment",
        "(f) all/various/different",
        "(g) throwing waste",
        "(h) chemical",
        "(i) Polluted/Contaminated",
        "(j) very",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Chattogram",
    data: {
      questions:
        "We can’t think of our existence without language. It plays a (a) — (use an intensifier) important role in our life. We use language from the time we wake up (b) — (post-modify the verb) till we go to bed at night. We use language not only in our (c) — (pre-modify the noun) hours but also in our dreams. We use language (d) – (use an infinitive) what we feel and to say what we like or dislike. We also use language (e) — (post-modify the verb with an infinitive) information. Language is (f) – (pre-modify the adjective) present in our life. It is an (g) – (pre-modify the noun) part of our life. As an (h) — (pre-modify the noun) nation, we also have a language. But we had to struggle (i) — (post-modify the verb) to establish the right of our language. Many (j) — (pre-modify the noun) sons sacrificed their lives for the language.",
      answers: [
        "(a) very",
        "(b) in the morning",
        "(c) walking",
        "(d) to express",
        "(e) to get/convey/exchange",
        "(f) ever/always",
        "(g) essential/integral",
        "(h) independent",
        "(i) hard",
        "(j) valiant",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Sylhet",
    data: {
      questions:
        "A library is a (a) — (pre-modify the noun) of knowledge. The students (b) — (use a participle) to all classes visit it in their library periods. Our college library is housed in two rooms. (c) — (pre-modify the noun) almirahs are placed in one room. The other room is the (d) – (use a participle to modify the noun) room where magazines, journals and newspapers are placed. There are about five thousand books in our library which are arranged (e) — (post-modify the verb). Any type of book can be traced in no time. The books cater to the needs and interests (f) — (use a prepositional phrase). There are two separate sections in the library. One of them contains reference books like (g) – (use nouns) etc. The other section contains books (h) — (use prepositional phrase). Every student has a library (i) —- (use a noun). The reading room is always crowded (j) — (post-modify the verb) in the afternoon.",
      answers: [
        "(a) store house",
        "(b) coming",
        "(c) Some/Several",
        "(d) reading",
        "(e) systematically",
        "(f) students/of the readers",
        "(g) dictionaries/encyclopedias",
        "(h) of academic categories",
        "(i) card",
        "(j) mainly/generally",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Barishal",
    data: {
      questions:
        "The roads (a)---(use an adjective phrase to post-modify the noun) are beset with problems. (b)---(pre-modify the noun) driving is one of them. Most of the drivers are not (c)--- (pre-modify the participle) trained. They are not well educated. They can (d)---(use an adverb to pre-modify the verb) put their signature and read Bengali. They are indifferent to (e) – (use a noun adjective) life. They do not realize that life is (f)---(use a determiner) valuable than time. They drive (g)---(postmodify the verb). They do (h)---(use an adverb to pre-modify the verb) drive consciously. Even they themselves are not conscious of (i)---(use a possessive) own lives. They drive (j)---(use an adverb phrase to post-modify the verb) and try to overtake others.",
      answers: [
        "(a) running across the country",
        "(b) Reckless",
        "(c) well",
        "(d) hardly/not",
        "(e) public",
        "(f) more",
        "(g) recklessly/desperately/inconsiderately",
        "(h) not",
        "(i) their",
        "(j) very fast/very quickly/very desperately/very speedily",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dinajpur",
    data: {
      questions:
        "Bangladesh is a (a) – (pre-modify the noun) country. Though it is a small country, it has a (b)---(pre-modify the noun) population. People (c)---(pre-modify the verb with an adverb) depend on agriculture. They grow different kinds of crops (d) — (post-modify the verb with an adverbial phrase). We earn (e) — (pre-modify the noun with a noun-adjective) currencies by exporting some of these crops. We are also rich in (f)--- (pre-modify the noun with an adjective) resources. Now, we are able (g)---(post-modify the adjective with an infinitive) natural gas from underground. Our industries are also rising (h) — (post-modify the verb with an adverb). We export (i)---(pre-modify the noun with a noun-adjective) products to the developed countries. In this regard, we have already earned a (j)---(pre-modify the noun) reputation.",
      answers: [
        "(a) small",
        "(b) large",
        "(c) mainly/basically",
        "(d) throughout the year",
        "(e) foreign",
        "(f) natural",
        "(g) to dig out",
        "(h) rapidly",
        "(i) garment",
        "(j) good",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Combined Board Kh Set",
    data: {
      questions:
        "Television has become the most common and (a)---(pre-modify the noun) source of entertainment of the (b) – (pre-modify the noun) world. A wide range of programs of (c)---(pre-modify the adjective) interest is telecast on (d)---(use quantifier to pre-modify the noun) channels. Almost every middle class and even working-class families have a television set today. (e)---(use a noun adjective to pre-modify the noun) programs are (f)---(pre-modify the adjective) entertaining. They can be (g) – (pre-modify the adjective) educative too. Courses (h)---(post modify the noun) by the Open University are shown on BTV. (i)---(pre-modify the noun) channels like the Discovery Channel and the National Geographic Channel telecast highly informative programs. However, watching TV has become (j)--- (use an article) addiction for many.",
      answers: [
        "(a) widespread/great/popular",
        "(b) present/current",
        "(c) varied/various",
        "(d) numerous",
        "(e) Various Television",
        "(f) very/highly",
        "(g) highly",
        "(h) run/conducted",
        "(i) several/some/many",
        "(j) an",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Combined Board Kha Set",
    data: {
      questions:
        "Kazi Nazrul Islam is called the Shelley of Bengali Literature. He was a (a)---(pre-modify the noun) poet. He wrote (b)---(post-modify the verb) in every branch of Bengali Literature. Nazrul, (c)--- (use an appositive), won the attention of everyone in his early childhood. He wrote ceaselessly until the death of (d)---(use possessive pronoun) poetic flair. He composed his songs (e)---(use an infinitive phrase to post-modify the verb). His songs are (f)---(use an intensifier to pre-modify the adjective) melodious. He enriched the Bengali Literature (g)---(use an adverb to pre-modify the verb). His literary works have enriched (h)---(use a noun adjective) literature. He was (i)---(use an article) secular poet. He sang the songs of equality (j) --- (use an adverbial phrase).",
      answers: [
        "(a) famous/great/rebel/renowned",
        "(b) almost/extensively/profusely",
        "(c) our national poet/a rebel poet/a small boy",
        "(d) his",
        "(e) to inspire people",
        "(f) very/highly",
        "(g) greatly/vastly",
        "(h) Bangla/Bengali",
        "(i) a",
        "(j) throughout his life/in a loud voice",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        "Deforestation means cutting down of trees (a) – (post-modify the verb). To meet up the basic needs of food and housing, trees are being cut in large scale and thus it causes (b) —- (pre-modify the noun) imbalance. Besides, there are some dishonest people who cut trees in our forest (c) —- (use an infinitive phrase to post-modify the verb). The (d) — (use a noun adjective to pre-modify the noun) level is rising and many parts of the world are going to be engulfed by the sea in near future. New areas of the world are (e) — (use a participle to pre-modify the verb) turned into desert as a result of deforestation. So, we must stop (f) — (use a participle to post-modify the verb) down trees unnecessarily. (g) – (use a participle to pre-modify the noun) trees indiscriminately will be hazardous for our future existence. If we destroy trees (h) – (use an adverbial phrase to postmodify the verb) one day the country will turn into a great dessert. The (i) —- (use a participle to pre modify the noun) temperature will cause the greenhouse effect. Necessary measures should be taken (j) — (use an infinitive phrase to post-modify the verb).",
      answers: [
        "(a) indiscriminately",
        "(b) ecological/environmental",
        "(c) to earn their livelihood/to earn money",
        "(d) sea/water",
        "(e) being",
        "(f) cutting",
        "(g) cutting",
        "(h) in an indiscriminate way/without any consideration/in an inconsiderate manner",
        "(i) rising",
        "(j) to stop deforestation",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "Ayesha Begum has three sons and two daughters. Her husband was a (a)---(pre-modify the noun) farmer who used (b) — (post-modify the verb by using infinitive) on other people’s land. With great effort, they married (c) — (use a pronoun) daughters off by the time they reached teenage. The sons also started (d) —- (use a present participle to modify the verb) with their father as (e) – (pre-modify the noun) labourers when they were old enough to help. By the time they were seventeen, they left for towns (f)--- (use the infinitive to post-modify the verb) money. At first, they used to send money to their parents (g) – (use an adverb to post-modify the verb) but after getting married they barely had enough to support their (h) – (pre-modify the noun) families. Out of desperation, Ayesha Begum started (i) — (post-modify the verb) in the village to feed her old, (j)--- (pre-modify the noun) husband and herself.",
      answers: [
        "(a) landless",
        "(b) to work",
        "(c) their",
        "(d) working",
        "(e) day",
        "(f) to earn",
        "(g) occasionally",
        "(h) own",
        "(i) begging",
        "(j) invalid",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Cumilla",
    data: {
      questions:
        "A balanced diet is a good mixture of (a) —- (pre-modify the noun) foods. It is essential for us (b) – (post-modify the adjective with an infinitive) a healthy life. There are many benefits of eating a (c) – (pre-modify the noun) diet because it prevents (d) — (use determiner to pre-modify the noun) diseases. As a result we do not get sick (e)---(post-modify the verb with an adverb). We should select (f)---(pre-modify the noun with possessive) diet according to our needs. We should not eat the (g)---(use adjective to pre-modify the noun) foods for the whole week. We can keep fit (h) – (use a participle) a balanced diet. But it is not easy (i)---(post-modify the adjective with an infinitive) a balanced diet. Here (j) — (use a determiner) nutritionist can help us.",
      answers: [
        "(a) good/various",
        "(b) to lead/to maintain",
        "(c) balanced",
        "(d) many",
        "(e) easily/frequently",
        "(f) our",
        "(g) same",
        "(h) eating/taking",
        "(i) to choose/select/combine/prepare",
        "(j) a",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Jashore",
    data: {
      questions:
        "A village doctor is a very (a) —- (pre-modify the noun) person in the rural areas of Bangladesh. He is (b) — (pre-modify the verb) known as quack. A village doctor is not a (c) – (pre-modify the noun) doctor. He usually sits in a small dispensary (d) — (post-modify the verb). He treats the patients (e) – (use a participle phrase to post-modify the verb). A village doctor is not a (f) —- (pre-modify the noun) man. His chamber is (g) — (pre-modify the verb) furnished. He cannot supply costly medicine to (h) —- (pre-modify the noun) patients. In our country, the number of qualified doctors is (i) – (use an intensifier to pre-modify the adjective) few. So, a village doctor is a great friend to the (j) – (pre-modify the noun) villagers.",
      answers: [
        "(a) familiar/common",
        "(b) usually/commonly",
        "(c) skilled/qualified",
        "(d) everyday/regularly",
        "(e) taking small money",
        "(f) rich/wealth",
        "(g) not/poorly",
        "(h) critical/poor",
        "(i) very/quite",
        "(j) poor",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Chattogram",
    data: {
      questions:
        "The people of Bangladesh have expressed their shock (a)---(post-modify the verb) at the reaction of the Pakistan Parliament. Pakistan strongly protested the execution of two (b)--- (pre-modify the noun) collaborators who committed Crimes against humanity on their own people in 1971. There is a demand for an apology from (c)---(use a noun adjective to pre-modify the noun) government for the crimes of its army during the liberation war of Bangladesh. Recently Pakistan’s National Assembly may be within its rights (d)---(use an infinitive phrase to post-modify the verb) for the execution of two collaborators. But it is quite clear to us that Pakistan always tries to erase its past history. To erase (e)---(use a demonstrative to pre-modify the noun) history is not easy because history continues to follow all of us. Pakistan, (f)---(post-modify the noun with an appositive), cannot come out of its military influence. As a result, the country has become (g)---(use an intensifier to premodify the adjective) barbarous. So, Pakistan is going down (h)--- (use an adverb to post-modify the verb). The founder of Pakistan Mr Jinnah was physically (i)---(use an intensifier to pre-modify the adjective) weak and so, the state always tried to show its physical strength since (j)--- (use a possessive to pre-modify the noun) birth.",
      answers: [
        "(a) strongly/deeply",
        "(b) notorious/ignoble",
        "(c) Pakistan",
        "(d) to blame/to condemn",
        "(e) this/that",
        "(f) the mostly military ruled country",
        "(g) so/very",
        "(h) gradually/slowly",
        "(i) very",
        "(j) its",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Barishal",
    data: {
      questions:
        "Raja, (a)--- (post-modify the noun with an appositive), is known to his classmates as a good student. He has (b)---(use a quantifier to pre-modify the noun) good qualities. He knows that the (c)--- (use an adjective to pre-modify the noun) duty of a Sudent is to study and he never neglects (d)---(use a demonstrative to pre-modify the noun) duty. He prepares (e)---(use possessive to pre-modify the noun) lessons regularly. He maintains discipline. He knows the value of time. He gets up (f)---(post-modify the verb with an adverb) so that he can get enough time to study. He goes to school (g)--- (post-modify the verb with an adverb). He never wastes a (h)---(use determiner to pre-modify the noun) moment in vain. Raja is (i)---(pre-modify the adjective with an intensifier) gentle. He always obeys his parents and teachers. He never mixes with (j)---(pre-modify the noun) boys. A student like Raja is a great asset of a nation.",
      answers: [
        "(a) a school boy",
        "(b) some/many",
        "(c) prime/chief",
        "(d) this",
        "(e) his",
        "(f) early",
        "(g) regularly",
        "(h) single",
        "(i) very",
        "(j) bad",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dinajpur",
    data: {
      questions:
        "Sabbir is (a)--- (use determiner to pre-modify the noun phrase) ideal student. He prepares (b) – (use possessive to pre-modify the noun) lessons in collaboration with his teachers. He does (c)---(post-modify the verb) in every examination as he does not waste time. He knows time once lost is lost forever. So, he utilizes every moment. During his free time, he goes to his native village. He teaches (d)---(pre-modify the noun) people. He wants (e)---(use an infinitive phrase to post-modify the verb) illiteracy from his village. (f)--- (use a present participle to pre-modify the verb) illiteracy from his village, he wants to bring about massive development there. He is (g)---(use an intensifier to pre modify the adjective) devoted to God. He says prayer (h)---(use quantifier to pre-modify the noun) times a day. He never tells a lie. He respects his parents very much. Other superiors are also respected by him. His father, (i)---(post-modify the noun phrase with an appositive) supports him cordially. His mother, an ideal housewife, (j)---(pre-modify the verb) supports him very much. Such a student like Sabbir is rarely found nowadays.",
      answers: [
        "(a) an",
        "(b) his",
        "(c) very well",
        "(d) illiterate",
        "(e) to remove",
        "(f) Removing",
        "(g) very",
        "(h) five",
        "(i) an ideal man",
        "(j) also",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "hsc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "Rabindranath Tagore was a (a)--- (pre-modify the noun) poet of Bengali literature. He was born in a (b)--- (pre-modify the noun) family at Jarasanko, Kolkata. He went to school (c)--- (post-modify the verb). He wrote his (d)---(pre-modify the noun) verse at the age of eight. At the age of seventeen, he went to London (e)--- (post-modify the verb with an infinitive) school there. He was put up in a lodging house under the care of a (f)---(pre-modify the noun) coach, Mr Scott. He was lucky (g)---(post-modify the adjective with an infinitive) an English family of Mr Scott. He also visited the House of Parliament (h)--- (post-modify the verb with an infinitive) Gladstone and John Bright’s debates on Irish rule. He wrote letters to Kolkata (i)---(post-modify the verb with a present participle) English society. At this, his family thought that they might lose their son (j)--- (post modify the verb).",
      answers: [
        "(a) famous/great/renowned",
        "(b) rich/solvent",
        "(c) early",
        "(d) first",
        "(e) to attend",
        "(f) professional",
        "(g) enough to get/to have/to find",
        "(h) to listen to",
        "(i) praising/admiring",
        "(j) ultimately/forever",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "It was a hot (a) — (use a noun adjective to pre-modify the noun) day. A (b) – (pre-modify the noun) crow flew all over the fields looking for water. For a long time, she could not find any water. She felt (c)---(use an intensifier to pre-modify the adjective) weak, almost giving up hope. Suddenly, she saw a water jug below her. She flew (d) – (post-modify the verb) to see if there was any water inside. Yes, she could see some water inside the jug. The crow tried (e)--- (use an infinitive phrase to post-modify the verb). Sadly, she found that the neck of the jug was too narrow. Then she tried to push the jug down for the water to flow out. But she found (f)---(use a demonstrative to pre-modify the noun) jug too heavy. The Crow thought (g)---(use a phrase to post-modify the verb) what to do. (h)---(use a participle to pre-modify the verb), she saw some pebbles nearby. She (i)---(pre modify the verb) had a good idea. She started picking up the pebbles one by one, dropping each into the jug. As more and more pebbles filled the jug, the water level kept rising. Soon it was high (j)---(post-modify the adjective) for the crow to drink. The crow quenched her thirst and flew away.",
      answers: [
        "(a) summer",
        "(b) thirsty",
        "(c) very",
        "(d) down",
        "(e) to drink water/to quench her thirst",
        "(f) this/that",
        "(g) for a while",
        "(h) Looking around/Roaming around the field",
        "(i) instantly/immediately",
        "(j) enough",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Cumilla",
    data: {
      questions:
        "I had a peculiar experience (a)---(Post-modify the verb) while travelling to St. Martin’s Island. I visited the island along with my family. Zahid, (b)--- (Post-modify the noun with an appositive), was our guide. On our way to the island, we watched (c)--- (use a determiner to pre-modify the noun) seagulls. The (d)---(pre-modify the noun) birds were flying (e)---(post-modify the verb) with the ship. They became (f)---(use an intensifier to pre-modify the adjective) dear and friendly to us. We entertained them with chips and biscuits. (g)---them (use a present participle to pre-modify the verb), we became (h)---(use an intensifier to pre-modify the adjective) excited. We decided (i)---(use an infinitive phrase to post-modify the verb) in the idyllic island for a couple of days. We can never forget (j)---(use a demonstrative to pre-modify the adjective phrase) lovely sea birds.",
      answers: [
        "(a) last year",
        "(b) a local boy",
        "(c) some",
        "(d) sea",
        "(e) along",
        "(f) very",
        "(g) Feeding",
        "(h) very",
        "(i) to stay",
        "(j) those",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Jashore",
    data: {
      questions:
        "Most of the people in (a)---(use possessive to pre-modify the noun) country do not know the importance of English. In fact, it is an (b)---(use an adjective to pre-modify the noun) language and we are living in a (c) – (pre-modify the noun) village. So, if you know English (d)---(post- modify the verb with an adverb), you can communicate with (e)--- (use the article to pre-modify the noun phrase) rest of the world. It is surely an important element of your (f)---(use a noun adjective to pre-modify the noun) skill. Without the knowledge of English with proper understanding, you cannot complete (g) – (use possessive to pre-modify the noun) higher studies because most of the books are written in English in the process of higher education. Poor knowledge of English will also hamper your (h) – (use a noun-adjective) development. In short, if you do not have a good command of English, you will suffer (i)--- (post-modify the verb with prepositional phrase/ Adverbial) of your life. So, don’t waste your time and try to learn English (j)---(post-modify the verb with an adverb) from today.",
      answers: [
        "(a) our",
        "(b) international",
        "(c) global",
        "(d) much/well",
        "(e) the",
        "(f) language",
        "(g) your",
        "(h) career",
        "(i) in the later part",
        "(j) well/right",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Chattogram",
    data: {
      questions:
        "Once there lived a (a)--- (pre-modify noun) fox in a jungle. One day, while he was walking (b) – (post-modify the verb) through the jungle, he fell into a trap and lost his tail. He felt (c)---(pre modify the adjective) unhappy and sad. But the fox was very cunning. He hit upon a plan. He invited all the foxes (d)---(post modify the verb with an infinitive) to a meeting. When all the foxes arrived, the fox without a tail said, “My dear friends, listen to me, please, I have discovered a (e)---(pre modify the noun) thing. It is that our tails are (f)---(pre-modify the adjective) useless. They look ugly and dirty. So, we all should cut off our tails, shouldn’t we?” All foxes listened to the cunning fox (g)--- (post-modify the verb). Most of them agreed (h)---(post-modify the verb with an infinitive) their tails. But an old and (i)---(pre-modify the noun) fox said to him, “My friend, your plan is nice but evil. Actually, you want to cut off our tails because you have (j)---(pre-modify the noun with a determiner) tail of your own.”",
      answers: [
        "(a) clever/cunning",
        "(b) alone",
        "(c) very",
        "(d) to come",
        "(e) significant/wonderful",
        "(f) really/quite",
        "(g) attentively",
        "(h) to cut off",
        "(i) wise",
        "(j) no",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "Othello, (a)---(use an appositive to post-modify the noun), had risen to become a general. He had shown his bravery in many (b)---(use an adjective to pre-modify the noun) battles against the Turks. Everyone praised him (c)--- (use an adverb to post-modify the verb) and the senate trusted and honoured him. Brabantio, a rich senator of Venice had a daughter named Desdemona (d)---(use a relative clause to post-modify the noun). Brabantio (e)---(use an adverb to pre-modify the verb) invited Othello to his house where he and his daughter listened in wonder to Othello as he spoke about his adventures. He told them of deserts, of caves and of mountains high (f)---(use an intensifier to pre-modify the adjective) to touch the sky. Desdemona had to weep (g)---(use a present participle to post-modify the verb phrase) and she never became tired of listening to it. She pitied Othello (h)---(use an adverb to post-modify the verb) for the misfortunes and hardships of his life. Her pity (i)---(use an adverb to post-modify the verb) turned to love. She refused all the young men (j)---(use an infinitive to post-modify the verb) because she loved Othello, a noble Muslim Moor from North Africa.",
      answers: [
        "(a) a noble Muslim Moor",
        "(b) fierce",
        "(c) highly",
        "(d) who was very beautiful and intelligent",
        "(e) often",
        "(f) enough",
        "(g) hearing his adventure/listening to his stories",
        "(h) much/great",
        "(i) finally/soon/ultimately",
        "(j) to marry",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        "Water is a (a)---(pre-modify the noun) substance. It has no colour of (b)--- (possessive to pre modify) own. The (c) – (determiner to pre-modify the noun) name of water is life. By drinking water, we can quench (d)---(possessive to pre-modify the noun) thirst. Thus we can survive on earth. But (e)---(pre-modify the noun) water is life killing. By drinking contaminated water, we suffer from diseases like diarrhoea, typhoid etc. We may (f)---(pre-modify the verb) face (g) – (pre-modify the noun) death by drinking such type of water. We are responsible for (h)---(noun adjective to pre modify the noun) pollution. Waste materials from mills and factories are thrown here and there. Farmers use fertilizers and insecticides on their land. During the rainy season, they are mixed with ponds and rivers. Besides, latrines (i) – (participle to post-modify the noun) on ponds and rivers cause water pollution. (j)---(pre-modify the noun) awareness should be raised to stop water pollution.",
      answers: [
        "(a) liquid",
        "(b) its",
        "(c) other",
        "(d) our",
        "(e) impure/contaminated",
        "(f) even",
        "(g) unexpected/sudden",
        "(h) water",
        "(i) build/standing",
        "(j) Public/Social",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
];
