export const prepositions = [
  {
    exam: "hsc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "Man is the best creation (a) ___ Almighty. Actually, he is the most intelligent living being (b) ___ earth. That is why, man is regarded (c) ___ a rational animal. But man becomes the worst animal when he is devoid (d) ___ sense and rationality. Man is endowed (e) ___ such qualities as are different (f) ___ other animals. So, to build (g) ___ civilization and to beautify the earth is possible only (h) ___ man (i) ___ his thinking power, hard work and inventions. However, man is also responsible (j) ___ mass destruction of human civilization.",
      answers: [
        "(a) of",
        "(b) on",
        "(c) as",
        "(d) of",
        "(e) with",
        "(f) from",
        "(g) up",
        "(h) for",
        "(i) with",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "The vast number (a) ___ plant species underwater forms a beautiful ecosystem. The plants which stay underwater depend (b) ___ the light coming (c) ___ the sun (d) ___ their growth. They also draw the atmospheric carbon dioxide (e) ___ the air above and convert them (f) ___ oxygen. The flora (g) ___ the surface (h) ___ the water adds (i) ___ the aesthetic beauty. These plants sometimes span vast lengths below the surface (j) ___ the ocean.",
      answers: [
        "(a) of",
        "(b) on",
        "(c) from",
        "(d) for",
        "(e) from",
        "(f) into",
        "(g) under",
        "(h) of",
        "(i) to",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        "Love for motherland is inherent (a) ____ man. A man who is devoid (b) ____ love for his motherland is not a true patriot. A genuine patriot loves his motherland (c) ____ the core of his heart. He dedicates his whole life (d) ____ the service of his own country. He is prepared to lay (e) ____ his life for the greatest interest of his motherland. Our freedom fighters are the proud sons of our country. They took pride (f) ____ fighting for the country (g) ____ our enemy. They never retreated (h) ____ the battle field rather swooped (i) ____ the enemy valiantly. Their sacrifice will end (j) ____ vain if we fail to build our own country.",
      answers: [
        "(a) in",
        "(b) of",
        "(c) from",
        "(d) to",
        "(e) down",
        "(f) in",
        "(g) against",
        "(h) from",
        "(i) on",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "Charity is a noble virtue. A person should be endowed (a) ______ this virtue. It makes people think favourably (b) ______ their fellowmen and do them good. It is also the cheerful giving of one’s possession to someone (c) ______ need. This quality brings happiness (d) ______ earth and strengthens the ties of relationship (e) ______ men. It should not be measured (f) ______ terms of money. Rather, it should be measured (g) ______ the sacrifice that one makes. In fact, it is a form (h) ______ self-sacrifice (i) ______ which our society cannot progress. So, everybody should practise this habit (j) ______ childhood.",
      answers: [
        "(a) with",
        "(b) of",
        "(c) in",
        "(d) on",
        "(e) among",
        "(f) in",
        "(g) by",
        "(h) of",
        "(i) without",
        "(j) from",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "Many people do not get enough nutrition (a) — what they eat. Many children become blind because they do not get necessary nutrition. Diarrhoea is a common disease. This is because many do not drink clean water or they eat dirty food. So, they often suffer (b) — diarrhoea. The condition (c) — our villages is very serious. The best way to keep in good health is to follow the rules (d) — cleanliness. A large number (e) — people do not follow the rules (f) — health. It is a great problem (g) — our country. So, (h) — order to keep in sound health, all the people must be strict (i) — the rules (j) — health.",
      answers: [
        "(a) from",
        "(b) from",
        "(c) of",
        "(d) of",
        "(e) of",
        "(f) of",
        "(g) in",
        "(h) in",
        "(i) about",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "The old man told him (a) ___ his last journey (b) ___ the sea. They had sailed away (c) ___ the South, he said, until they arrived (d) ___ cold grey seas. Even the sea was frozen, and ice was all (e) ___ them. (f) ___ those days there were no steamships, and the big white sails (g) ___ their ship opened wide as the strong wind blew them quickly (h) ___ the icy waters. The weather was very cold and there were no birds or animals (i) ___ that snow covered country, but one day the sailors saw an albatross flying (j) ___ the ship.",
      answers: [
        "(a) about",
        "(b) on",
        "(c) to",
        "(d) in",
        "(e) around",
        "(f) In",
        "(g) of",
        "(h) through",
        "(i) in",
        "(j) towards",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Mymensingh",
    data: {
      questions:
        "Gen Z refers (a) — the group of people born after 1996. They are called so because they are digital natives who have grown (b) — with technology like smartphones and the internet. Normally, Gen Z kids are fond (c) — using digital devices and gadgets daily. They are also very good (d) — using online apps and looking (e) — information whenever they need. This generation is absorbed (f) — important issues like politics, social inequality and even environmental concerns. Gen Z is different (g) — other generations because they are always connected (h) — social media and other online platforms. They enjoy learning (i) — new things (j) — videos and websites.",
      answers: [
        "(a) to",
        "(b) up",
        "(c) of",
        "(d) at",
        "(e) for",
        "(f) in",
        "(g) from",
        "(h) to",
        "(i) about",
        "(j) through",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "It is known (a) — all that one day all will pass away (b) — this earth. So, we have no escape (c) — death. One day everyone will lie (d) — the icy lap of death because death is common (e) — all. So, we should not mourn (f) — the dead. Death is inevitable. But those who die (g) — the country are immortal. Their memory does not sink (h) — oblivion. There is no medicine that can save a man (i) — death. Therefore, we should always be ready (j) — death.",
      answers: [
        "(a) to",
        "(b) from",
        "(c) from",
        "(d) in",
        "(e) to",
        "(f) for",
        "(g) for",
        "(h) into",
        "(i) from",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "Robert Hayden was born (a) ___ a poor family (b) ___ Detroit in USA in 1913 and had a difficult childhood beset (c) ___ eyesight problems. He was raised (d) ___ part (e) ___ foster parents and missed a father’s caring love. But in the sonnet, which is (f) ___ a childhood memory, he writes (g) ___ a father probably his own who is harsh and often angry, but does love his son (h) ___ his own way. Hayden, a black American, wrote (i) ___ black experiences and history. He died (j) ___ 1980.",
      answers: [
        "(a) into",
        "(b) in",
        "(c) with",
        "(d) in",
        "(e) by",
        "(f) about",
        "(g) about",
        "(h) in",
        "(i) about",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dhaka",
    data: {
      questions:
        "We learn etiquette and manners (a) --- our parents and various institutions such as schools, colleges or professional bodies. There are rules (b) --- behaviour (c) --- all kinds (d) --- social occasions and it is important to learn them and practise them (e) --- everyday life. The manners that are correct (f) --- a wedding reception will not do (g) --- debating club. Therefore, we have to be careful (h) --- etiquette and manners. We know how important it is to say 'please' and 'thank you' (i) --- everyday life. A few more polite expressions such (j) --- 'Pardon me', 'Excuse me', 'May I' are bound to make your day smooth and pleasant.",
      answers: [
        "(a) from",
        "(b) of",
        "(c) for",
        "(d) of",
        "(e) in",
        "(f) in",
        "(g) in",
        "(h) about",
        "(i) in",
        "(j) as",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Rajshahi",
    data: {
      questions:
        "Education is instrumental (a) --- bringing (b) --- socio-economic development. A man devoid (c) --- education cannot contribute (d) --- the society. On the other hand, an educated man plays a pivotal role (e) --- enhancing the pace (f) --- the socio-economic development. A country should put much emphasis (g) --- educating its citizens. The citizens have to be provided (h) --- ample opportunities so that they feel keen interest (i) --- getting themselves educated. The educated people are to be treated (j) --- much respect.",
      answers: [
        "(a) in",
        "(b) about",
        "(c) of",
        "(d) to",
        "(e) in",
        "(f) of",
        "(g) on",
        "(h) with",
        "(i) in",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Cumilla",
    data: {
      questions:
        "Social network is a network for virtual social interaction (a) --- internet users across the world. Actually, this is an age (b) --- globalisation. This is also an age of information and technology. People all over the world are virtually connected (c) --- one another (d) --- the borders. Hence, the necessity of social networks has emerged. But the young generations are getting addicted (e) --- social networks (f) --- Facebook, Twitter, Instagram etc. The lifestyle of the young before and after getting used (g) --- a social network has a noticeable change. In fact, the students who were used to studying at the table before, nowadays pass their valuable time by chatting (h) --- the social media. As a result, they are now lagging (i) --- So, they should be kept aloof (j) --- using internet excessively and unnecessarily.",
      answers: [
        "(a) among",
        "(b) of",
        "(c) with",
        "(d) beyond/across",
        "(e) to",
        "(f) like",
        "(g) to",
        "(h) on",
        "(i) behind",
        "(j) from",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Jashore",
    data: {
      questions:
        "In Bangladesh, the legal age (a) --- marriage (b) --- girls is 18. However, 33% of our girls get married before they are 15 and 60% (c) --- them become mothers (d) --- the time they reach 19. When an adolescent girl gets married, she usually drops (e) --- of school and thus loses her mobility. She gets confined (f) --- full-time work in her in-law's household. She loses social status and all the opportunities (g) --- economic independence. (h) --- her in-law's house, she gets marginalized. She becomes vulnerable (i) --- all sorts of abuse, including dowry-related violence.",
      answers: [
        "(a) of",
        "(b) for",
        "(c) of",
        "(d) by",
        "(e) out",
        "(f) to",
        "(g) for",
        "(h) In",
        "(i) to",
        "(j) —",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dinajpur",
    data: {
      questions:
        "It is known (a) --- all that one day all will pass away (b) --- this earth. So, we have no escape (c) --- death. One day, we all will roll down (d) --- the lap of death. Because death is common (e) --- all. So we should not mourn (f) --- the dead. But those who die (g) --- the country are immortal. Their memories do not sink (h) --- oblivion. There is no medicine that can save a man (i) --- death. So, we should always be ready (j) --- death.",
      answers: [
        "(a) to",
        "(b) from",
        "(c) from",
        "(d) into",
        "(e) to",
        "(f) for",
        "(g) for",
        "(h) into",
        "(i) from",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Barishal",
    data: {
      questions:
        "If you want to derive the best (a) --- your education you must be fully aware (b) --- some basic things. You should never be indifferent (c) --- your study. In Fact, fostering a kind of passion (d) --- learning appears to be very important for achieving your goal. Again, you should never try to learn anything (e) --- context. You should also not run (f) --- substandard traditional guide books. As a matter of fact, confining yourself (g) --- poor quality note books discourages you to learn something deeply. But (h) --- learning a thing very deeply, you cannot achieve the required mastery (i) --- the learnt thing. Thus, you may fail to get the desired benefits (j) --- your learning.",
      answers: [
        "(a) from",
        "(b) of",
        "(c) to",
        "(d) for",
        "(e) without/except",
        "(f) after",
        "(g) to",
        "(h) without",
        "(i) over",
        "(j) from",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Chattogram",
    data: {
      questions:
        "Life of common people besets (a) --- a number of troubles. Price spiral has added new sufferings (b) --- our life. Indeed, price of daily commodities has gone (c) --- the ability of the common people. Lack (d) --- supervision is responsible (e) --- it. Some dishonest businessmen devoid (f) --- morality hoard goods (g) --- quick profit. The govt. should take punitive action (h) --- those people. People from all walks (i) --- life should also co-operate (j) --- government.",
      answers: [
        "(a) with",
        "(b) to",
        "(c) beyond",
        "(d) of",
        "(e) for",
        "(f) of",
        "(g) for",
        "(h) against",
        "(i) of",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Mymensingh",
    data: {
      questions:
        "Ours is a riverine country. Rivers are everywhere (a) --- our life-literature, economy and culture. But are the rivers (b) --- good shape? Unfortunately, they are not. A few are already dead and several are going (c) --- the pangs of death. The river Buriganga is an example (d) --- a dying river. A report published in The Daily Sun describes what has happened (e) --- the river Buriganga and why. Its water is polluted and a perpetual stench fills the air (f) --- it. The report says that the river had a glorious past. Once it was a tributary (g) --- the Ganges and flowed (h) --- the Bay of Bengal (i) --- the river Dhaleswari. Gradually, it lost its link (j) --- the Ganges and got the name Buriganga.",
      answers: [
        "(a) in",
        "(b) in",
        "(c) through",
        "(d) of",
        "(e) to",
        "(f) around",
        "(g) of",
        "(h) into",
        "(i) through",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dhaka",
    data: {
      questions:
        "A good boy is accustomed (a) --- hard work. He is not addicted (b) --- any bad thing. He is not averse (c) --- any hard work. He clings (d) --- (লেগে থাকা) his determination. Since he is used (e) --- hard work, he is not doubtful (f) --- his success. He is very much conscious (g) --- his duties. He is not boastful (h) --- (দাম্ভিক) his talents. He behaves well (i) --- all. He attends (j) --- his studies.",
      answers: [
        "(a) to",
        "(b) to",
        "(c) to",
        "(d) to",
        "(e) to",
        "(f) about",
        "(g) of",
        "(h) of",
        "(i) towards",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Cumilla",
    data: {
      questions:
        "A craftwork is an applied form (a) --- art, a social and cultural product reflecting the inclusive nature (b) --- folk imagination. A craftwork, which usually doesn’t bear the signature of its maker, retains a personal touch. When we look (c) --- a thirty years old Nakshi Kantha, we wonder (d) --- its motifs and designs that point (e) --- the artistic (শৈল্পিক) ingenuity (অভিনবত্ব) and the presence of the maker (f) --- it. The fact that we do not know her name or any other details (g) --- her does not take anything (h) --- from our appreciation (i) --- the artist. Indeed, the intimate nature (j) --- the Kantha and the tactile feeling it generates animate the work and make it very inviting.",
      answers: [
        "(a) of",
        "(b) of",
        "(c) at",
        "(d) at",
        "(e) to",
        "(f) of",
        "(g) about",
        "(h) away",
        "(i) for",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Rajshahi",
    data: {
      questions:
        "But at last God took pity (a) --- him. One day the sailor was watching the water-snakes swimming (b) --- the ship. Their colours were so beautiful and he was filled (c) --- such a strange wonder that he felt a great love (d) --- them and blessed them (e) --- his heart. At once, the dead albatross fell (f) --- his neck (g) --- the sea. A gentle breeze began to blow (h) --- the south and the old man fell (i) --- a deep sleep. When he woke up, it was raining and he felt fresh again. Thus, the old man was relieved (j) --- his sufferings.",
      answers: [
        "(a) on",
        "(b) around",
        "(c) with",
        "(d) for",
        "(e) from",
        "(f) from",
        "(g) into",
        "(h) from",
        "(i) into",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Jashore",
    data: {
      questions:
        "Books are really our best friends as we can rely (a) --- them when we are bored, upset, depressed, lonely or annoyed. They share (b) --- us information and knowledge any time we need. They enable us to have a glimpse (c) --- cultures, traditions, arts, history, geography, health, psychology and many other subjects and aspects of life. Good books always guide us (d) --- the right path (e) --- life. Reading good books helps us understand the world (f) --- us better. While reading books, we build new and creative thoughts, images and opinions (g) --- our mind. This habit helps us explore life (h) --- different perspectives. In other words, it has several positive effects (i) --- our body, mind and soul. In fact, the habit of reading is one (j) --- the best qualities that a person can possess.",
      answers: [
        "(a) on",
        "(b) with",
        "(c) of",
        "(d) to",
        "(e) in",
        "(f) around",
        "(g) in",
        "(h) from",
        "(i) on",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Sylhet",
    data: {
      questions:
        "The Padma Bridge is a landmark achievement (a) --- Bangladesh. It stands (b) --- a symbol of progress and connectivity. The bridge spans (c) --- the Padma River, connecting the southern regions (d) --- the capital, Dhaka. It was constructed (e) --- the supervision of skilled engineers and workers. The project faced many challenges, but the government remained committed (f) --- its completion. The bridge has opened (g) --- new opportunities for trade and travel. People now move easily (h) --- one side of the river (i) --- the other. It is a matter of pride (j) --- every Bangladeshi.",
      answers: [
        "(a) for",
        "(b) as",
        "(c) across",
        "(d) to",
        "(e) under",
        "(f) to",
        "(g) up",
        "(h) from",
        "(i) to",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Barishal",
    data: {
      questions:
        "Speaking ill (a) --- others is a very bad human tendency. It develops a negative inclination (প্রবৃত্তি) (b) --- one’s mind. This habit tempts (প্রলুব্ধ) one (c) --- indulge (ডুবে থাকা) (d) --- a negative approach out of his unsound mind. It leaves bad effects (e) --- human individuals and society. It also hampers the happy and smooth run (f) --- the society. People very often burst (g) --- tears (h) --- this heinous act. We all should be aware (i) --- it and give (j) --- this bad habit.",
      answers: [
        "(a) of",
        "(b) to",
        "(c) to",
        "(d) in",
        "(e) on",
        "(f) of",
        "(g) into",
        "(h) at",
        "(i) of",
        "(j) up",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Chattogram",
    data: {
      questions:
        "Corruption is a curse (a) --- a nation. It is a great hindrance (b) --- development. (c) --- corrupt people, a nation will surely sink (d) --- oblivion. Corrupt people are hated by all. The common people have no respect (e) --- them. They are devoid (বিবর্জিত) (f) --- honesty. They stick (g) --- their evil activities. They do not abide (h) --- the social rules. Morality does not have any effect (i) --- them. They bring nothing for the nation. It is high time we stood (j) --- them.",
      answers: [
        "(a) for",
        "(b) to",
        "(c) Because of",
        "(d) into",
        "(e) for",
        "(f) of",
        "(g) to",
        "(h) by",
        "(i) on",
        "(j) against",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dinajpur",
    data: {
      questions:
        "Drug addiction has become a serious problem (a) --- modern society. Many young men and women are falling victims (b) --- this. There are many reasons (c) --- drug addiction. Drugs are expensive. So, to manage money, the addicts often go (d) --- stealing, killing or all sorts of misdeeds. Drugs are smuggled (e) --- a country and the smugglers carry (f) --- drug business freely. Bangladesh is not free (g) --- the curse of drugs. But we cannot allow this (h) --- our country. The first thing to do is to highlight its dangerous effects (i) --- people. The government and mass media can play an effective role (j) --- this respect.",
      answers: [
        "(a) in",
        "(b) of",
        "(c) behind",
        "(d) for",
        "(e) into",
        "(f) out",
        "(g) from",
        "(h) in",
        "(i) on",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Mymensingh",
    data: {
      questions:
        "The orphanage is high (a) --- the Carolina mountains. The writer was there (b) --- the autumn. She preferred peaceful environment to pen some troublesome writing. She wanted the mountain air to blow (c) --- the malaria from too long a time (d) --- the subtropics (গ্রীষ্মমন্ডলীয় অঞ্চল). She was homesick (e) --- flaming (f) --- maples (g) --- October and for many other things. She found a cabin all living (h) --- a cabin belonging (i) --- the orphanage, half a mile (j) --- the orphanage farm.",
      answers: [
        "(a) in",
        "(b) in",
        "(c) away",
        "(d) in",
        "(e) for",
        "(f) of",
        "(g) in",
        "(h) in",
        "(i) to",
        "(j) beyond",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Dhaka",
    data: {
      questions:
        "Camels are one of the few animals that can live in a desert. Camels have humps (কুঁজ) (a) --- their backs. They store fat (b) --- these humps. That fat gives them energy. Because camels do not store water, fat helps produce water when camel move (c) --- the dry desert. They can go (d) --- several months without water. Camels eat grass to get moisture. The camels are as useful (e) --- the people of the desert as the buffalo are (f) --- the grasslands. The meat of the camel is good to eat. People make cloth (g) --- camel hair. Shoes are made (h) --- the hides. The camels are also good (i) --- travel in the desert. Some people travel the desert (j) --- camels to make a living.",
      answers: [
        "(a) on",
        "(b) in",
        "(c) through",
        "(d) for",
        "(e) to",
        "(f) to",
        "(g) out of",
        "(h) from",
        "(i) for",
        "(j) by",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Cumilla",
    data: {
      questions:
        "Books are really our best friends as we can rely (a) --- them when we are bored, upset, depressed, lonely or annoyed. They share (b) --- us information and knowledge any time we need. They enable us to have a glimpse (c) --- cultures, traditions, arts, history, geography, health, psychology and many other subjects and aspects of life. Good books always guide us (d) --- the right path (e) --- life. Reading good books helps us understand the world (f) --- us better. While reading books, we build new and creative thoughts, images and opinions (g) --- our mind. This habit helps us explore life (h) --- different perspectives. In other words, it has several positive effects (i) --- our body, mind and soul. In fact, the habit of reading is one (j) --- the best qualities that a person can possess.",
      answers: [
        "(a) on",
        "(b) with",
        "(c) of",
        "(d) to",
        "(e) in",
        "(f) around",
        "(g) in",
        "(h) from",
        "(i) on",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Rajshahi",
    data: {
      questions:
        "Shilpi married Rashid (a) --- the age of fifteen. Marrying (b) --- daughters (c) --- an early age is a standard practice (d) --- many families living in rural Bangladesh. (e) --- her wedding, Shilpi joined a local empowerment group that helps her (f) --- the tools needed to gradually change cultural practices, particularly those pertaining (g) --- early marriage and pregnancy. The group’s activities include discussions (h) --- how to change behaviour related (i) --- reproductive health as well as one-on-one counselling. Like Shilpi, many of the girls got assistance (j) --- this empowerment group.",
      answers: [
        "(a) at",
        "(b) off",
        "(c) at",
        "(d) in",
        "(e) After",
        "(f) with",
        "(g) to",
        "(h) on",
        "(i) to",
        "(j) from",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Jashore",
    data: {
      questions:
        "The ceremony began (a) --- 10 a.m. Our principal Mr. Rahman presided over (b) --- the function and Member of Parliament Mr. Reza was the chief guest. The function started (c) --- the recitation from the holy Quran. One (d) --- our senior teachers read (e) --- the annual report. The honorable chief guest delivered a brief but inspiring speech (f) --- education. He advised the students to be regular (g) --- the class and attentive (h) --- studies and take part (i) --- the movement (j) --- illiteracy.",
      answers: [
        "(a) at",
        "(b) over",
        "(c) with",
        "(d) of",
        "(e) out",
        "(f) on",
        "(g) in",
        "(h) to",
        "(i) in",
        "(j) against",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Sylhet",
    data: {
      questions:
        "The moon is a very familiar figure (a) --- all of us. She awakens a feeling (b) --- love and tenderness (c) --- our hearts. Even infants in arms stretch (d) --- their hands to grasp the beautiful thing. Nor is her appeal confined only (e) --- children. Ever since the string of the poetic faculty in man, she has furnished a theme (f) --- poets and artists. The moon has no light (g) --- her own. The soft silvery brightness which forms her principal charms to us, is borrowed solely (h) --- the light of the sun. If we go out on a clear night, we can look (i) --- the magic of moonlight. It is often difficult (j) --- us to realize that the moon is shining in borrowed feathers.",
      answers: [
        "(a) to",
        "(b) of",
        "(c) in",
        "(d) out",
        "(e) to",
        "(f) for",
        "(g) of",
        "(h) from",
        "(i) at",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Barishal",
    data: {
      questions:
        "Traffic problem is a major problem (a) --- our day-to-day life. Mainly the city dwellers suffer (b) --- it. The drivers do not abide (c) --- the traffic rules. Most often traffic problems occur (d) --- the congested areas where the roads are very narrow in proportion (e) --- our population. There are many unlicensed vehicles which should be brought (f) --- control. Strict rules must be introduced (g) --- this regard. We should raise consciousness (h) --- the people of our country (i) --- a view to ensuring a good traffic system (j) --- the safety of the people.",
      answers: [
        "(a) in",
        "(b) from",
        "(c) by",
        "(d) in",
        "(e) to",
        "(f) under",
        "(g) in",
        "(h) among",
        "(i) with",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Chattogram",
    data: {
      questions:
        "Email has brought (a) --- a revolution (b) --- modern communication. Messages can be transmitted (c) --- one country to another (d) --- seconds. It is far cheaper than telephone calls. Trade and commerce has become greatly dependent (e) --- this speedy mode (f) --- communication. It has, however, not reached everyone, especially (g) --- developing countries (h) --- ours, as most people cannot afford (i) --- have a personal computer. But even here, people have started using commercially operated email facilities (j) --- important purposes.",
      answers: [
        "(a) about",
        "(b) in",
        "(c) from",
        "(d) within",
        "(e) on",
        "(f) of",
        "(g) in",
        "(h) like",
        "(i) to",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Dinajpur",
    data: {
      questions:
        "Japan is an island country (a) --- the east coast of Asia. It has more than 100 islands which were mostly formed (b) --- earthquakes and volcanoes. Most Japanese people live (c) --- the four largest islands. These islands are Honshu, Hokkaido, Shikohu and Kyushu. The name of Japan comes (d) --- the Chinese phrase meaning “land of the rising sun”. Japan has borrowed other things from the Chinese (e) --- its name. The Japanese written language, for example, is based (f) --- the Chinese system (g) --- picture writing. Japan has to buy almost all its raw materials (h) --- other countries. Trade is very important (i) --- the island nation of Japan. (j) --- the resources it buys, Japan makes products to sell all over the world.",
      answers: [
        "(a) off",
        "(b) by",
        "(c) in",
        "(d) from",
        "(e) besides",
        "(f) on",
        "(g) of",
        "(h) from",
        "(i) for",
        "(j) With",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Mymensingh",
    data: {
      questions:
        "A teacher is an architect (a) --- a nation. He plays an important role (b) --- building up an educated nation. He dispels the darkness (c) --- ignorance (d) --- the lot of a nation. He is an actor, so to speak. He has to suit his act according (e) --- the need of his audience which is his class. He is a clear speaker (f) --- good, strong and pleasing voice which is (g) --- his control. He does not sit motionless (h) --- his class. Everybody has something valuable (i) --- him. A good teacher discovers the treasure hidden inside each student. He also wants the students to be happy and for this he keeps them busy. A good teacher never hankers (j) --- money.",
      answers: [
        "(a) of",
        "(b) in",
        "(c) of",
        "(d) from",
        "(e) to",
        "(f) with",
        "(g) under",
        "(h) in",
        "(i) in",
        "(j) after",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dhaka",
    data: {
      questions:
        "Mr Reza works (a) --- a clerk in a local school. He is poor but honest. His honesty is known (b) --- everyone in his locality. He often suffers (c) --- hunger. He is deprived (d) --- comfort and many other things. Nevertheless, he does not long (e) --- wealth. He never hankers (f) --- name and fame. He leads his life (g) --- honest means. He is satisfied (h) --- what he has. But sometimes he runs into debt and poverty is responsible (i) --- this debt. However, he does not like to depend (j) --- others.",
      answers: [
        "(a) as",
        "(b) to",
        "(c) from",
        "(d) of",
        "(e) for",
        "(f) after",
        "(g) by",
        "(h) with",
        "(i) for",
        "(j) on",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Cumilla",
    data: {
      questions:
        "Preposition connects all types (a) --- words together and supports them make better sense (b) --- the readers. They help us to understand the relationship (c) --- objects. (d) --- example, the book and the table (e) --- the kitchen. This ensures you a basic understanding. If we add another preposition, it makes it even clearer. This book is (f) --- top of the table (g) --- the kitchen. We have a clear picture (h) --- our mind (i) --- the relation of those two objects and their relationship (j) --- each other.",
      answers: [
        "(a) of",
        "(b) to",
        "(c) among",
        "(d) For",
        "(e) in",
        "(f) on",
        "(g) in",
        "(h) in",
        "(i) about",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Rajshahi",
    data: {
      questions:
        "When the sun was setting (a) --- the treetops, the jailor came (b) --- the room of Socrates to bid him prepare (c) --- death. In those days, people were sentenced to death by giving a cup (d) --- poison in Athens. Socrates knew this and he nodded (e) --- the jailor. Bursting (f) --- tears the jailor went out of the room and returned (g) --- a cup of hemlock. Socrates lifted the cup to his lips. His pupils tried to keep back their tears but soon the room was filled (h) --- the sound of weeping. With the cup of poison (i) --- hand, Socrates said, “What is the strange sound? I have heard that a man should die (j) --- peace. So be silent and have patience.",
      answers: [
        "(a) behind",
        "(b) into",
        "(c) for",
        "(d) of",
        "(e) to",
        "(f) into",
        "(g) with",
        "(h) with",
        "(i) in",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Jashore",
    data: {
      questions:
        "Patriotism is the quality inherent (a) --- a man. This is why, he feels a natural attachment (b) --- his native land. Love (c) --- motherland is necessary for the betterment of a nation. The people who are patriotic are noted (d) --- their patriotism. They are different (e) --- other people. Their contribution does not sink (f) --- oblivion. They are worthy (g) --- praise. They lay down their lives for the good of the country. They are not unaware (h) --- their status in society. They are celebrated (i) --- their patriotism. They should not be looked down (j) --- in any way.",
      answers: [
        "(a) in",
        "(b) to",
        "(c) for",
        "(d) for",
        "(e) from",
        "(f) into",
        "(g) of",
        "(h) of",
        "(i) for",
        "(j) upon",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Sylhet",
    data: {
      questions:
        "Luna’s cat was missing. So she started looking around (a) --- it. She opened her closet and looked (b) --- it. Then she went to the bedroom crawling (c) --- the floor to look (d) --- the bed. The cat was not there. In fact, it was nowhere inside the house. Therefore, Luna decided to go (e) --- to look for it. Just as she was (f) --- to open the door, the doorbell rang. It was her neighbour, Mrs Haq, “Look, Luna! Your cat is (g) --- the sunshade!” said Mrs Haq pointing (h) --- a tall building opposite (i) --- her house. Luna smiled and thanked her friendly neighbour, saying that (j) --- her help she would not be able to find out her cat.",
      answers: [
        "(a) for",
        "(b) into",
        "(c) on",
        "(d) under",
        "(e) out",
        "(f) about",
        "(g) on",
        "(h) towards",
        "(i) to",
        "(j) without",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Barishal",
    data: {
      questions:
        "The old grey-bearded sailor sat (a) --- a stone (b) --- the church. The sailor watched the people walking (c) --- him. The marriage guest listened (d) --- him. He had a strange mad look (e) --- his eyes. The old man told him (f) --- his last journey (g) --- the sea. They had sailed away (h) --- the south (i) --- they arrived (j) --- cold grey seas.",
      answers: [
        "(a) on",
        "(b) outside",
        "(c) by",
        "(d) to",
        "(e) in",
        "(f) about",
        "(g) on",
        "(h) to",
        "(i) until",
        "(j) at",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Chattogram",
    data: {
      questions:
        "What are the qualities of a good student? A good student is always attentive (a) --- his studies. He is never indifferent (b) --- his studies. He does not learn things (c) --- note. He is always curious and innovative. He does not hunt only (d) --- traditional guide books. His thirst (e) --- knowledge knows no bounds. He does not confine himself (f) --- the traditional studies. He is aware (g) --- the current affairs (h) --- the world. He listens (i) --- his teachers and abides (j) --- their advice.",
      answers: [
        "(a) to",
        "(b) to",
        "(c) from",
        "(d) for",
        "(e) for",
        "(f) to",
        "(g) of",
        "(h) of",
        "(i) to",
        "(j) by",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dinajpur",
    data: {
      questions:
        "A craftwork is an applied form (a) --- art, a social and cultural product reflecting the inclusive nature (b) --- folk imagination. A craftwork, which usually doesn’t bear the signature of its maker, retains a personal touch. When we look (c) --- a thirty years old Nakshi Kantha, we wonder (d) --- its motifs and designs that point (e) --- the artistic (শৈল্পিক) ingenuity (অভিনবত্ব) and the presence of the maker (f) --- it. The fact that we do not know her name or any other details (g) --- her does not take anything (h) --- from our appreciation (i) --- the artist. Indeed, the intimate nature (j) --- the Kantha and the tactile feeling it generates animate the work and make it very inviting.",
      answers: [
        "(a) of",
        "(b) of",
        "(c) at",
        "(d) at",
        "(e) to",
        "(f) of",
        "(g) about",
        "(h) away",
        "(i) for",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Mymensingh",
    data: {
      questions:
        "Education is the backbone (a) --- a nation. It is essential (b) --- the development of any country. A good education system focuses (c) --- the holistic growth of students. It does not only depend (d) --- academic knowledge but also encourages creativity and critical thinking. Students should be exposed (e) --- practical experiences that prepare them (f) --- real-world challenges. Teachers play a vital role (g) --- shaping young minds. They guide students (h) --- the right path and inspire them (i) --- achieve their dreams. Education empowers individuals and contributes (j) --- the progress of society.",
      answers: [
        "(a) of",
        "(b) for",
        "(c) on",
        "(d) on",
        "(e) to",
        "(f) for",
        "(g) in",
        "(h) to",
        "(i) to",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Dhaka",
    data: {
      questions:
        "Trees are very useful (a) --- man. They are highly essential (b) --- our existence. They protect the rich topsoil (c) --- getting washed away (d) --- rainwater and floods. We can see trees being grown along the mountain slopes (e) --- the roadsides (f) --- the parks and gardens. They add beauty (g) --- our lives. They provide us (h) --- food, wood, shade, shelter and so on. They take (i) --- carbon-di-oxide and produce oxygen. So we should take care (j) --- trees.",
      answers: [
        "(a) to",
        "(b) for",
        "(c) from",
        "(d) by",
        "(e) along",
        "(f) in",
        "(g) to",
        "(h) with",
        "(i) in",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Cumilla",
    data: {
      questions:
        "Do you have any idea (a) --- a cyber cafe? It’s a place teeming (b) --- information. It’s a network (c) --- all networks. It is a place (d) --- computers (e) --- which customers can use the internet and send e-mails and so on. A cybercafe is closely associated (f) --- internet communication system. A customer sitting (g) --- the cafe can communicate (h) --- people (i) --- the world. In fact, a cyber cafe is not prejudicial (j) --- our development.",
      answers: [
        "(a) about",
        "(b) with",
        "(c) of",
        "(d) with",
        "(e) through",
        "(f) with",
        "(g) at",
        "(h) with",
        "(i) around",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Rajshahi",
    data: {
      questions:
        "The Sundarbans is a mangrove forest (a) --- the delta region of the Ganges, Brahmaputra, and Meghna rivers. It is famous (b) --- its unique ecosystem and biodiversity. The forest is home (c) --- the Royal Bengal Tiger, which is a major attraction (d) --- tourists. The local people depend (e) --- the forest (f) --- their livelihood, collecting honey, wood, and fish. However, the Sundarbans is vulnerable (g) --- climate change and rising sea levels. Conservation efforts are crucial (h) --- protecting this natural heritage. We must work (i) --- preserving it (j) --- future generations.",
      answers: [
        "(a) in",
        "(b) for",
        "(c) to",
        "(d) for",
        "(e) on",
        "(f) for",
        "(g) to",
        "(h) for",
        "(i) towards",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Jashore",
    data: {
      questions:
        "Books are the mirror (a) --- life. They reflect the experiences (b) --- human beings. Reading books helps us gain knowledge (c) --- various subjects. They guide us (d) --- the right path and protect us (e) --- making wrong choices. A good book is like a friend who is always there (f) --- you. People who are fond (g) --- reading often find solace (h) --- books. They open doors (i) --- new worlds and inspire us (j) --- think creatively.",
      answers: [
        "(a) of",
        "(b) of",
        "(c) about",
        "(d) to",
        "(e) from",
        "(f) for",
        "(g) of",
        "(h) in",
        "(i) to",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Sylhet",
    data: {
      questions:
        "Honesty is a great virtue (a) --- a person. It brings respect (b) --- others and builds trust (c) --- society. An honest person is never afraid (d) --- speaking the truth. He or she is always loyal (e) --- their principles. Dishonesty, on the other hand, leads (f) --- distrust and chaos. People who indulge (g) --- dishonest practices often lose their reputation (h) --- the long run. Honesty is the foundation (i) --- a peaceful life and contributes (j) --- a better world.",
      answers: [
        "(a) of",
        "(b) from",
        "(c) in",
        "(d) of",
        "(e) to",
        "(f) to",
        "(g) in",
        "(h) in",
        "(i) of",
        "(j) to",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Barishal",
    data: {
      questions:
        "A good teacher is a blessing (a) --- students. He or she is dedicated (b) --- teaching and always strives (c) --- impart knowledge effectively. Students look (d) --- their teachers (e) --- guidance and inspiration. A teacher’s role is not limited (f) --- the classroom; they shape the future (g) --- the nation. They encourage students to think (h) --- themselves and to be confident (i) --- their abilities. A teacher’s influence lasts (j) --- a lifetime.",
      answers: [
        "(a) to",
        "(b) to",
        "(c) to",
        "(d) to",
        "(e) for",
        "(f) to",
        "(g) of",
        "(h) for",
        "(i) in",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Chattogram",
    data: {
      questions:
        "The internet has become an integral part (a) --- our daily lives. It connects people (b) --- the world and provides access (c) --- vast information. Students rely (d) --- it (e) --- their studies, while businesses depend (f) --- it (g) --- communication and trade. However, excessive use can lead (h) --- addiction and distract us (i) --- our responsibilities. We must use the internet wisely (j) --- our benefit.",
      answers: [
        "(a) of",
        "(b) across",
        "(c) to",
        "(d) on",
        "(e) for",
        "(f) on",
        "(g) for",
        "(h) to",
        "(i) from",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Dinajpur",
    data: {
      questions:
        "Education is the key (a) --- success. It opens doors (b) --- opportunities and empowers individuals (c) --- achieve their dreams. Without education, one may struggle (d) --- life’s challenges. Teachers play a vital role (e) --- shaping young minds. Students should be attentive (f) --- their lessons and respectful (g) --- their teachers. Education is not just (h) --- academic knowledge; it is (i) --- building character and preparing (j) --- the future.",
      answers: [
        "(a) to",
        "(b) to",
        "(c) to",
        "(d) with",
        "(e) in",
        "(f) to",
        "(g) to",
        "(h) about",
        "(i) about",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Mymensingh",
    data: {
      questions:
        "A library is a treasure house (a) --- knowledge. It is a place where people can immerse themselves (b) --- books and gain wisdom. Students benefit (c) --- the vast collection of books available (d) --- a library. It is a quiet place, conducive (e) --- learning and reflection. Librarians assist users (f) --- finding the right resources. Reading (g) --- a library fosters a love (h) --- books. Everyone should make use (i) --- this facility to enrich their minds (j) --- knowledge.",
      answers: [
        "(a) of",
        "(b) in",
        "(c) from",
        "(d) in",
        "(e) to",
        "(f) in",
        "(g) in",
        "(h) for",
        "(i) of",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        "The environment plays an important role (a) --- our life. (b) --- short, what we have (c) --- us including people, houses, air, water etc. is called environment. These are the main elements (d) --- our environment. (e) --- ensuring sound life the balance (f) --- the natural elements is very significant. Sometimes (g) --- lack of knowledge, we don’t realise the importance (h) --- it. As a result, we are polluting our environment unknowingly. Living (i) --- a polluted environment is undoubtedly a matter (j) --- great concern.",
      answers: [
        "(a) in",
        "(b) In",
        "(c) around",
        "(d) of",
        "(e) For",
        "(f) among",
        "(g) for",
        "(h) of",
        "(i) in",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Cumilla",
    data: {
      questions:
        "We got our freedom (a) --- the sacrifice of hundreds and thousands (b) --- lives. The patriots (c) --- our land fought (d) --- the oppression of the West Pakistani rulers. Finally, the oppressors were bound to surrender (e) --- our freedom fighters. But a great number (f) --- the sons of the land died (g) --- the war. Soon (h) --- the war, the government (i) --- Bangladesh founded the National Memorial (j) --- memory of the martyrs.",
      answers: [
        "(a) at",
        "(b) of",
        "(c) of",
        "(d) against",
        "(e) to",
        "(f) of",
        "(g) in",
        "(h) after",
        "(i) of",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "Ours is a riverine country. Rivers are everywhere (a) --- our life-literature, economy and culture. But are the rivers (b) --- good shape? Unfortunately, they are not. A few are already dead and several are going (c) --- the pangs of death. The river Buriganga is an example (d) --- a dying river. A report published in The Daily Sun describes what has happened (e) --- the river Buriganga and why. Its water is polluted and a perpetual stench fills the air (f) --- it. The report says that the river had a glorious past. Once it was a tributary (g) --- the Ganges and flowed (h) --- the Bay of Bengal (i) --- the river Dhaleswari. Gradually, it lost its link (j) --- the Ganges and got the name Buriganga.",
      answers: [
        "(a) in",
        "(b) in",
        "(c) through",
        "(d) of",
        "(e) to",
        "(f) around",
        "(g) of",
        "(h) into",
        "(i) through",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Jashore",
    data: {
      questions:
        "It would be impossible (a) --- us to continue living in this world if each of us knew exactly what fate had (b) --- store for us. So, Allah in His mercy conceals (গোপন করে) the future (c) --- all His creatures and reveals only the present. He hides from the animals what men know, and He hides from men what the angels know. For example, if a lamb had a reason (d) --- a man, it could not gamble happily knowing it was destined to be killed (e) --- human food. But being quite ignorant (f) --- its fate, it is happy to the last moment of its short life contentedly grazing (g) --- the flowery meadow, and even in its innocence licks the hands (h) --- the butcher who is about to slaughter it. What a blessing it is that we are ignorant (i) --- the future! Allah, to whom the death of a sparrow is of equal importance with the death of a hero, has, in His mercy, thus limited our knowledge so that we might fulfil our duty in the sphere (j) --- which has appointed us.",
      answers: [
        "(a) for",
        "(b) in",
        "(c) from",
        "(d) as",
        "(e) for",
        "(f) of",
        "(g) in",
        "(h) of",
        "(i) of",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Sylhet",
    data: {
      questions:
        "I caught sight (a) --- him while crossing the road. I tried to talk (b) --- him. But he was (c) --- a hurry. He was one (d) --- my best friends. Both of us studied (e) --- the same school. I had an intimacy (f) --- him. Both of us got separated (g) --- each other after the completion (h) --- S.S.C. Examination. Though my heart bleeds (i) --- him, I hardly meet (j) --- him. This is the go of the world.",
      answers: [
        "(a) of",
        "(b) to",
        "(c) in",
        "(d) of",
        "(e) at",
        "(f) with",
        "(g) from",
        "(h) of",
        "(i) for",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Barishal",
    data: {
      questions:
        "I am glad to receive your letter. You have wanted to know (a) --- the picnic that we made. I am now writing (b) --- you about it. It was winter vacation. Our school was closed. I (c) --- some of my friends arranged a picnic. We selected Sonargaon (d) --- the picnic spot. It is some twenty miles from Dhaka. We got (e) --- the bus (f) --- about 9 am (g) --- all necessary utensils and materials. (h) --- reaching Sonargaon, we finished our breakfast (i) --- about 9:30 am. We did not take any cook (j) --- us.",
      answers: [
        "(a) about",
        "(b) to",
        "(c) with",
        "(d) as",
        "(e) on",
        "(f) at",
        "(g) with",
        "(h) After",
        "(i) at",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Chattogram",
    data: {
      questions:
        "Syed Shamsul Haq, legendary literature, was born in Kurigram (a) --- 1935. He received the Bangla Academy Award (b) --- the age of twenty-nine. It is noteworthy that he was the youngest (c) --- all who got the Bangla academy award. He was awarded the Swadhinata Padak in 2000, (d) --- his contributions (e) --- Bangla literature. His literary works are included (f) --- the curricula of secondary, higher secondary and graduation level (g) --- Bangladesh. Syed Shamsul Haq was married (h) --- Anwara Syed Haq who is a member (i) --- the Royal College of Psychiatrists in London. This renowned intellectual passed away (j) --- 27 September 2016 at the age of 81.",
      answers: [
        "(a) in",
        "(b) at",
        "(c) of",
        "(d) for",
        "(e) to",
        "(f) in",
        "(g) in",
        "(h) to",
        "(i) of",
        "(j) on",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dinajpur",
    data: {
      questions:
        "Badal lived (a) --- a village of Bangladesh. He was a schoolboy. There was a canal (b) --- his way (c) --- school. An old bridge was (d) --- that canal. It was useful to one and all of the villagers. Yet none cared (e) --- its repair. So one day it broke (f) --- and caused a good deal (g) --- hardship to the villagers. They were (h) --- difficulty. They could not go to the town (i) --- the other side of the canal to sell their fruits and vegetables profitably. They sold their production (j) --- local market at a nominal price.",
      answers: [
        "(a) in",
        "(b) on",
        "(c) to",
        "(d) over",
        "(e) for",
        "(f) down",
        "(g) of",
        "(h) in",
        "(i) on",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Mymensingh",
    data: {
      questions:
        "A good friend is a blessing (a) --- life. He stands (b) --- you (c) --- times of need. True friendship is based (d) --- trust and understanding. A friend is someone you can rely (e) --- when you face challenges. He shares your joys and sorrows and never hesitates (f) --- help you. A true friend is loyal (g) --- you and does not betray you (h) --- any circumstances. Such a friend is rare and valuable (i) --- life. We should cherish such friends (j) --- our hearts.",
      answers: [
        "(a) in",
        "(b) by",
        "(c) in",
        "(d) on",
        "(e) on",
        "(f) to",
        "(g) to",
        "(h) under",
        "(i) in",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "hsc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "A good stock (a) --- words is necessary (b) --- anybody who wants to use a language. Vocabulary is an essential component (c) --- successful communication. It is an integral part (d) --- reading skill. While grammar is important, a lack (e) --- vocabulary may result (f) --- complete failure to convey a message. Vocabulary includes conceptual knowledge (g) --- words that go well (h) --- an ordinary dictionary meaning. Students’ vocabulary knowledge is a building process that occurs (i) --- time as they tend to make connections (j) --- other words.",
      answers: [
        "(a) of",
        "(b) for",
        "(c) of",
        "(d) of",
        "(e) of",
        "(f) in",
        "(g) of",
        "(h) with",
        "(i) in",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Cumilla",
    data: {
      questions:
        "A good student is never indifferent (a) --- his studies. He always adheres (b) --- his studies. He does not learn things (c) --- rote. He does not hunt (d) --- traditional guide books. Moreover he has great thirst (e) --- knowledge. For this he does not confine himself (f) --- the traditional studies. He is always aware (g) --- the current affairs (h) --- the world. He abides (i) --- his teachers advice and jots (j) --- their lessons.",
      answers: [
        "(a) to",
        "(b) to",
        "(c) by",
        "(d) for",
        "(e) for",
        "(f) to",
        "(g) of",
        "(h) of",
        "(i) by",
        "(j) down",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "Once an English and a Bengalee gentleman were travelling (a) --- the same train and they were in the same compartment. The Englishman was very proud (b) --- himself because he was an Englishman. He looked (c) --- upon the Bengalee gentleman who, however, took no notice (d) --- it and went to sleep (e) --- peace. As soon as the Bengalee gentleman was asleep, the Englishman picked (f) --- the gentleman’s shoes and threw them (g) --- the window and went to sleep. When the Bengalee gentleman woke up, he looked for his shoes and understood it. Then he took the Englishman’s long coat (h) --- the wall and threw it outside the window and returned (i) --- bed laughingly. Next morning the Englishman became startled and shouted, “Where’s my coat gone?” “Your coat has gone to fetch my shoes,” said the gentleman (j) --- a smile. The Bengalee gentleman was Sir Ashutosh Mukherjee.",
      answers: [
        "(a) in",
        "(b) of",
        "(c) down",
        "(d) of",
        "(e) in",
        "(f) up",
        "(g) through",
        "(h) from",
        "(i) to",
        "(j) with",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Jashore",
    data: {
      questions:
        "A village market is an important place (a) --- the villagers. It is usually held (b) --- the bank of a river or (c) --- a big banyan tree. Villagers come (d) --- different areas to buy and sell goods. The market is a meeting place (e) --- friends and relatives. People gather there to exchange news and views (f) --- one another. It is a great attraction (g) --- the children who come to enjoy (h) --- their time. The market is beneficial (i) --- the local economy and helps (j) --- the development of the area.",
      answers: [
        "(a) for",
        "(b) on",
        "(c) under",
        "(d) from",
        "(e) for",
        "(f) with",
        "(g) for",
        "(h) —",
        "(i) to",
        "(j) in",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "The science fair held (a) --- our college paved a new way for us to gather practical knowledge. Many of our friends took part (b) --- the fair (c) --- their projects. We showed genuine interest (d) --- them. Most of the projects were made (e) --- consistent (f) --- the prevailing world situation. They were intended (g) --- acquaint us (h) --- the solutions (i) --- some common problems we are facing specially in regard to the environment we live in. We were sanguine (j) --- achieving success and we really achieved it.",
      answers: [
        "(a) in",
        "(b) in",
        "(c) with",
        "(d) in",
        "(e) in",
        "(f) with",
        "(g) to",
        "(h) with",
        "(i) to",
        "(j) of",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Barishal",
    data: {
      questions:
        "During holidays when my mother went to sleep (a) --- noon, we went to the railway line. There, along with other children, I watched how the trains passed (b) --- innumerable unknown facts. My father got an appointment (c) --- a town school and he moved (d) --- the town immediately with all the members of the family. I was admitted (e) --- my father’s school. I felt that my school fellows had no feeling (f) --- one another as we had in the village. However, I have gradually adjusted myself (g) --- town life. I am happy with my new friends but my heart aches (h) --- the happy childhood days. Childhood is free (i) --- worries and has infinite capacity (j) --- enjoyment.",
      answers: [
        "(a) at",
        "(b) with",
        "(c) in",
        "(d) to",
        "(e) to",
        "(f) for",
        "(g) to",
        "(h) for",
        "(i) from",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Chattogram",
    data: {
      questions:
        "Flowers are the excellent gift of nature. They have existed (a) --- the earth (b) --- prehistoric time. Since then they have been treated (c) --- the symbol of beauty. It is an undeniable fact that flowers are used (d) --- various spheres (e) --- our life. It is used mostly (f) --- decoration. People (g) --- all walks of life use flowers usually (h) --- national occasion and (i) --- wedding. Everyone prefers flowers (j) --- expressing their love and devotion.",
      answers: [
        "(a) on",
        "(b) from",
        "(c) as",
        "(d) in",
        "(e) of",
        "(f) for",
        "(g) of",
        "(h) on",
        "(i) for",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        "Greenhouse effect is the gradual warming (a) --- the air surrounding the earth as a result of heat being trapped (b) --- environment pollution. This is exemplified (c) --- the destruction and burning (d) --- tropical rain forests, (e) --- traffic that clogs (f) --- city streets, (g) --- the rapid growth of industry, the use of chlorofluorocarbons (CFCs) (h) --- packaging and manufacturing commercial products, the use of detergents like washing (i) --- liquids and so (j) ---.",
      answers: [
        "(a) of",
        "(b) by",
        "(c) by",
        "(d) of",
        "(e) by",
        "(f) up",
        "(g) by",
        "(h) in",
        "(i) up",
        "(j) on",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Mymensingh",
    data: {
      questions:
        "A healthy lifestyle is essential (a) --- a long and happy life. It depends (b) --- balanced nutrition, regular exercise, and mental well-being. People should be aware (c) --- the food they consume and avoid harmful habits. Regular exercise keeps us fit and protects us (d) --- many diseases. Mental peace is equally important (e) --- our overall health. We should engage (f) --- activities that bring joy and relaxation. A healthy lifestyle contributes (g) --- our productivity and success. Everyone should strive (h) --- maintaining it (i) --- the sake of their well-being and (j) --- the benefit of society.",
      answers: [
        "(a) for",
        "(b) on",
        "(c) of",
        "(d) from",
        "(e) for",
        "(f) in",
        "(g) to",
        "(h) for",
        "(i) for",
        "(j) for",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
];
