export const rightFormOfVerbs = [
  {
    exam: "hsc",
    year: 2025,
    board: "Sylhet",
    data: {
      questions:
        "Festivals (a) ——(be) common to all societies and cultures. With the change of social and economic structures, the nature of festivals also (b) ——(change). But some festivals (c) ——(be) so deeply (d) ——(root) in the social organism that they (e) ——(continue) to entertain from generation to generation. Some of the festivals (f) ——(bear) the mark of the community and nationality, some (g) ——(have) the stamp of religion and again some (h) ——(bear) the impression of politics. The festivals, which (i) ——(get started) in the primitive society centering on the prayer for food (j) ——(have) now been (k) ——(fill) with various colours and varieties. The main foundation of festivals (l) ——(be) ritual and most of the ancient rituals (m) ——(be) collective activities. Many of the rituals were (n) ——(relate) to agriculture and were determined by lunar months.",
      answers: [
        "(a) are",
        "(b) has changed / is changing",
        "(c) are",
        "(d) rooted",
        "(e) continue",
        "(f) bear",
        "(g) have",
        "(h) bear",
        "(i) got started",
        "(j) have",
        "(k) filled",
        "(l) is",
        "(m) were",
        "(n) related",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Barishal",
    data: {
      questions:
        "In the current social and economic system of Bangladesh, everyone (a) ___ (depend) on his income in order to (b) ___ (meet) the daily needs. However, many people of our country (c) ___ (not earn) enough to live comfortably. People of low income are to (d) ___ (struggle) a lot to buy food, clothes and medicine because prices of everything (e) ___ (rise) high day by day. Generally, people in rural areas (f) ___ (feel) the pressure even more as they earn less. In fact, they (g) ___ (have) fewer opportunities to improve their financial condition. When prices go up, many families (h) ___ (buy) enough healthy food and this causes malnourishment of the children. Sometimes they cannot help (i) ___ (borrow) money. Which (j) ___ (lead) to debt. High prices also (k) ___ (affect) their children's education. Many a student (l) ___ (drop) out of school as their parents cannot afford to (m) ___ (bear) their educational expenses. But for the true development of our country proper education must be (n) ___ (ensure) at any cost.",
      answers: [
        "(a) depends",
        "(b) meet",
        "(c) do not earn",
        "(d) struggle",
        "(e) are rising",
        "(f) feel",
        "(g) have",
        "(h) cannot buy",
        "(i) borrowing",
        "(j) leads",
        "(k) affect",
        "(l) drops",
        "(m) bear",
        "(n) ensured",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Chattagram",
    data: {
      questions:
        "A mother is a supreme gift (a) ______ (bestow) upon us by Allah. She (b) ______ (exercise) an undeniable influence in (c) ______ (mould) the character of a child and also in (d) ______ (shape) their future destiny. A mother (e) ______ (regard) as the best teacher, guide and protector. An educated mother (f) ______ (manage) the family in a far better way than a mother who has (g) ______ (have) no schooling. She (h) ______ (be) more interested in (i) ______ (get) her children educated. She (j) ______ (sacrifice) her own happiness to (k) ______ (ensure) a better future for her children. So, often it (l) ______ (say) that the hands that (m) ______ (rock) the cradle (n) ______ (rule) the world.",
      answers: [
        "(a) bestowed",
        "(b) exercises",
        "(c) moulding",
        "(d) shaping",
        "(e) is regarded",
        "(f) can manage",
        "(g) had",
        "(h) is",
        "(i) getting",
        "(j) sacrifices",
        "(k) ensure",
        "(l) is said",
        "(m) rock",
        "(n) rule",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Rajshahi",
    data: {
      questions:
        "Change (a) — (be) the order of nature because we know the proverb that old order changes (b) — (yield) place to the new. So, nothing (c) — (remain) new forever. The same we (d) — (notice) in entertainment also. Old and traditional forms (e) — (change) and (f) — (modify) by new and modern forms of entertainment. Many of them (g) — (exist) any longer. Today TV channels and satellite (h) — (supersede) radio; similarly band and pop music (i) — (replace) our popular old songs. Football (j) — (lose) its appeal day by day. Cricket and other games (k) — (become) more and more popular. Our idea about the popularity of entertainment also (l) — (change). We’ve started (m) — (look) upon our forms of all life in a new way and (n) — (get) habituated to it.",
      answers: [
        "(a) is",
        "(b) yielding",
        "(c) remains",
        "(d) notice",
        "(e) have changed",
        "(f) modified",
        "(g) do not exist",
        "(h) have superseded",
        "(i) have replaced",
        "(j) is losing",
        "(k) are becoming",
        "(l) has changed / is changing",
        "(m) looking / to look",
        "(n) have got / are getting",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Cumilla",
    data: {
      questions:
        'A teacher (a) ______ (compare) with an architect. Teachers (b) ______ (call) the correctness of a nation. They (c) ______ (play) an important role in order to build a nation. They are used (d) ______ (make) the illiterate people worthy citizens. But the teachers (e) ______ (hold) in high respect in our country. They are habituated to (f) ______ (lead) a humble life in the midst of want. Still they (g) ______ (keep) the light of education (h) ______ (burn) with a view to (i) ______ (remove) the darkness of illiteracy. It is high time we (j) ______ (change) our outlook towards the teachers. In many developed countries, teachers (k) ______ (give) high respect. A most important truth, which we are apt (l) ______ (forget), is that a teacher can never truly teach unless he is still (m) ______ (learn) himself. A lamp can never light another lamp unless it (n) ______ (continue) to burn its own flame," Tagore said.',
      answers: [
        "(a) is compared",
        "(b) are called",
        "(c) play",
        "(d) to make",
        "(e) are held",
        "(f) leading",
        "(g) keep",
        "(h) burning",
        "(i) removing",
        "(j) changed",
        "(k) are given",
        "(l) to forget",
        "(m) learning",
        "(n) continues",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dhaka",
    data: {
      questions:
        "In this world truth (a) —— (reign) over falsehood. Those who are always in the habit of (b) —— (speak) the truth (c) —— (respect) everywhere. But those who are involved in telling lies, (d) —— (shine) in life. That is why, we see that many great men in the history used to (e) —— (preach) truth among their countrymen. (f) —— (be) truthful is essential for our society. It (g) —— (hold) the highest value in (h) —— (make) our society better. This quality (i) —— (consider) as one of the essential factors that empower us from within. A truthful man is a (j) —— (trust) person. And this trust (k) —— (build) confidence in us. Confidence makes us (l) —— (feel) better. When we start (m) —— (get) comfortable with speaking the truth, we will begin to prosper. So, we should try hard (n) —— (stay) away from the lies.",
      answers: [
        "(a) reigns",
        "(b) speaking",
        "(c) are respected",
        "(d) do not shine",
        "(e) preach",
        "(f) Being",
        "(g) holds",
        "(h) making",
        "(i) is considered",
        "(j) trusted",
        "(k) builds",
        "(l) feel",
        "(m) getting",
        "(n) to stay",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Jashore",
    data: {
      questions:
        "Books (a) ______ (possess) as essence of immortality. They (b) ______ (be) the most precious products of human efforts. Temptations (c) ______ (crumble) into ashes. Pictures and statues (d) ______ (decay) but books (e) ______ (survive). Time is of no account for great thoughts which (f) ______ (be) as fresh today as they (g) ______ (be) when came through the authors' minds ages ago. What (h) ______ (be) then thought or said still (i) ______ (speak) to us. Books (j) ______ (introduce) us to the best society. They (k) ______ (bring) us into the presence of the noblest minds that have ever (l) ______ (live). We hear what they (m) ______ (think) or said. We see them as if they (n) ______ (be) really alive.",
      answers: [
        "(a) possess",
        "(b) are",
        "(c) crumble",
        "(d) decay",
        "(e) survive",
        "(f) are",
        "(g) were",
        "(h) was",
        "(i) speaks",
        "(j) introduce",
        "(k) bring",
        "(l) lived",
        "(m) thought",
        "(n) were",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Mymensingh",
    data: {
      questions:
        "One day in 1976, Professor Muhammad Yunus (a) — (visit) a poor village near Chittagong University. He (b) — (meet) a poor woman who made bamboo stools for a living. Although she (c) — (work) hard, she (d) — (remain) poor because she (e) — (force) to pay a high price for the bamboo. She did not have enough money (f) — (buy) the bamboo and used to (g) — (take) loans from the moneylenders on an exorbitant interest. Professor Yunus (h) — (know) that he could not simply (i) — (give) her the money she needed because it (j) — (rob) the woman of her dignity. Instead, he (k) — (ask) the people in the village how much money they (l) — (need) to start their own business and free themselves from poverty. He (m) — (lend) the equivalent of about US$27:00 from his pocket to 42 women of the village. Those women (n) — (set) up their small business and started to earn money to support their families.",
      answers: [
        "(a) visited",
        "(b) met",
        "(c) worked",
        "(d) remained",
        "(e) was forced",
        "(f) to buy",
        "(g) take",
        "(h) knew",
        "(i) give",
        "(j) would rob",
        "(k) asked",
        "(l) needed",
        "(m) lent",
        "(n) set",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dinajpur",
    data: {
      questions:
        "Jerry is an orphan. He (a) ______ (come) to the orphanage at the age of four. He (b) ______ (lose) his parents in his infancy. Then, he (c) ______ (commit) to the care of the orphanage. He could hardly (d) ______ (recollect) his parents’ memory. In spite of (e) ______ (be) an orphan, he had developed a strong fabric of morality. His inimitable morality (f) ______ (draw) him close to the writer. The writer (g) ______ (impress) with him. She started (h) ______ (show) affection for him. Jerry (i) ______ (take) her as his mother. He fabricated a lie (j) ______ (win) her heart. The orphan boy (k) ______ (come) closer to her. She also (l) ______ (love) him like her son. Once she (m) ______ (leave) the place but she (n) ______ (cherish) the memory of the boy till her old age.",
      answers: [
        "(a) came",
        "(b) lost",
        "(c) was committed",
        "(d) recollect",
        "(e) being",
        "(f) drew",
        "(g) was impressed",
        "(h) showing",
        "(i) took",
        "(j) to win",
        "(k) came",
        "(l) loved",
        "(m) left",
        "(n) cherished",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dhaka",
    data: {
      questions:
        "Once upon a time, there (a) _____ (be) a king who was very fond of (b) _____ (know) his future from the astrologers. A famous astrologer (c) _____ (stop) at his capital on his way to home. The king called on him to (d) _____ (know) about the future and the astrologer (e) ______ (tell) him something unpleasant. At this the king (f) _____ (get) furious and (g) _____ (condemn) him to death saying, “Men like you (h) _____ (live) to spoil the peace of the world.” But another thought (i) _____ (cross) his mind before the astrologer (j) _____ (send) for execution. “How long will you (k) ____ (live)?” asked the king. With ready wit, the astrologer said, “The stars (l) _____ (declare) that I shall die only a week before your majesty, so goodbye.” (m) _____ (hear) this, the king turned pale like a dead man and shouted, “Drive this wretch away, let him (n) _____(come) here again.”",
      answers: [
        "(a) was",
        "(b) knowing",
        "(c) stopped",
        "(d) know",
        "(e) told",
        "(f) got",
        "(g) condemned",
        "(h) should not live",
        "(i) crossed/had crossed",
        "(j) was sent",
        "(k) live",
        "(l) declare",
        "(m) Hearing",
        "(n) not come",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dinajpur",
    data: {
      questions:
        "We can't help (a) _____ (rely) on English. Now, English is (b) ______ (use) as a common language for global communication. It (c) _____ (recognize) as an international language. English is important for (d) _____ (maintain) communication with our development partners. A good command over English as well as regular practices (e) _____ (be) essential for us. 80% information of all the computers (f) _______ (be) in English. With a view to (g) ______ (exchange) our views with the rest of the world, we have to (h) ______ (learn) English. Moreover, we (i) ________ (provide) with the good scope of (j) ______ (enjoy) the best books through English. English (k) ____ (be) now no longer the native speaker's language. Now it (l) _______ (belong) to the world's people. It is high time we (m) ______ (pay) more attention to English. Otherwise, we (n) ________ (lag) behind.",
      answers: [
        "(a) relying",
        "(b) used",
        "(c) is recognized",
        "(d) maintaining",
        "(e) is",
        "(f) is",
        "(g) exchanging",
        "(h) learn",
        "(i) are provided",
        "(j) enjoying",
        "(k) is",
        "(l) belongs",
        "(m) paid",
        "(n) will lag",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Barishal",
    data: {
      questions:
        "Tigers (a) _____ (know) as ferocious animals. But they hardly (b) _____ (kill) any animal when they are not hungry. Usually the tigers (c) _____ (reside) in the deep forest. They are hardly (d) ______ (see) in the open unless there (e) ______ (to be) a strong necessity. They often remain (f) ______ (hide) under the deep green in search of the prey. Whenever they (g) ______ (discern) any prospective prey, they take a pose to (h) ______ (fall) upon it. Tigers often (i) _____ (unite) themselves to (j) ________ (attack) their prey from different directions. An adult tiger (k) _____ (devour) 20 to 30 kilograms of meat at a single meal. In our Sundarbans the number of tigers (l) _____ (decrease) day by day. Poaching and illegal trafficking (m) _____ (to be) the main reasons of decrease. So the concerned authority should be committed to (n) ______(take) action to protect the tigers.",
      answers: [
        "(a) are known",
        "(b) kill",
        "(c) reside",
        "(d) seen",
        "(e) is",
        "(f) hidden",
        "(g) discern",
        "(h) fall",
        "(i) unite",
        "(j) attack",
        "(k) devours",
        "(l) is decreasing",
        "(m) are",
        "(n) taking",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Rajshahi",
    data: {
      questions:
        "The life of our farmers (a) _____ (be) full of hardships. Many a farmer (b) _____ (not know) how to cultivate scientifically. They (c) ______ (work) hard from dawn to dusk. But their toil (d) _______ (go) awry due to lack of scientific knowledge. Our government offers a lot of opportunities to them with a view to (e) _____ (eliminate) their sufferings. Unfortunately, they (f) _______ (not avail) themselves of those opportunities. It is time they (g) _____ (to get) scientific education and all concerned (h) ______ (to help) them. If they (i) _________ (to educate), they (j) _______ (to contribute) better to the prosperity of the country. The prosperity of our country (k) ______ (to lie) in their proper education. (l) ______ (to educate) a farmer (m) ______ (mean) educating a family and a nation. And, it (n) _______ (to result) in greater success in every sector of the country.",
      answers: [
        "(a) is",
        "(b) does not know",
        "(c) work",
        "(d) goes",
        "(e) eliminating",
        "(f) do not avail",
        "(g) got",
        "(h) helped",
        "(i) were educated",
        "(j) would contribute",
        "(k) lies",
        "(l) Educating",
        "(m) means",
        "(n) may result / results",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Jashore",
    data: {
      questions:
        "Dear Mr. and Mrs. Biswas,\nWe are very (a)______ (concern) about your son Rahel's behaviour. He (b)_______ (play) truant from school three times last month. When he (c)_______ (come) to class, he usually (d)_______ (not concentrate) on his lessons. He does not seem to understand texts and never (e)_______ (ask) any questions. The only time he (f)______ (show) any initiative is in (g)________ (make) excuses for not (h)______ (to have) (i)________ (do) his homework. Although he (j)_____ (have) a natural talent for art, he even (k)_______ (not take) any interest in art lessons. This is (l)______ (disappoint), because even last year he (m)_________ (be) attentive in his studies. We hoped he (n)_______ (win) a scholarship.",
      answers: [
        "(a) concerned",
        "(b) played",
        "(c) comes",
        "(d) doesn't concentrate",
        "(e) asks",
        "(f) shows",
        "(g) making",
        "(h) having",
        "(i) done",
        "(j) has",
        "(k) doesn't take",
        "(l) disappointing",
        "(m) was",
        "(n) would win",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Mymensingh",
    data: {
      questions:
        "Man has unquenchable thirst for knowledge. He is never (a)___ (satisfy) with what he already (b)____ (know) and (c)___ (see). Naturally he (d)___ (want) to know and (e)(see) more and more. This curiosity for (f) (know) more has (g)__ (inspire) him (h)(undertake) and (i) (carry) out difficult and dangerous tasks which eventually (j)____ (result) in epoch making discoveries and inventions and (k)____ (lead) him in his long and continuous journey from his helpless state of caveman to his present situations of power and progress. He (l)____ (be) helpless still now, he would not have (m)____ (be) able to control all powers and forces. (n)___ (invent) so many technologies he now controls almost all destructive powers and forces.",
      answers: [
        "(a) satisfied",
        "(b) has known",
        "(c) seen",
        "(d) wants",
        "(e) see",
        "(f) knowing",
        "(g) inspired",
        "(h) to undertake",
        "(i) carry",
        "(j) have resulted / resulted",
        "(k) led/have led",
        "(l) is/has been",
        "(m) been",
        "(n) Inventing",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Cumilla",
    data: {
      questions:
        "Students get themselves (a) __ (admit) into universities for higher education. They acquire higher education from two streams; one is public and the other is private. The private universities (b) ___ (be) open to all but one has to (c) ____ (face) tough competition for (d) ___ (get) a seat there. The public universities are cheaper in terms of tuition fees. They (e) ___ (offer) residential and boarding facilities at subsidized rates. But public universities often (f) __ (face) a number of problems. Student politics (g) ___ (play) a vital role in (h) ___ (deteriorate) the academic environment there. As a result, students (i) (face) session jam. So, the conscious and moneyed persons (j) ___ (impress) by the private universities. Since this is the age of privatization, the private universities (k) ____ (become) popular day by day. Besides, it is less difficult (l) ____ (get) a seat in a private university but here they are to pay a lot. However, the private sectors have some limitations. In fact, the two streams should (m) ___ (develop) in a balanced way. Because, both sectors are playing important roles with a view to (n)_ (make) the nation highly educated.",
      answers: [
        "(a) admitted",
        "(b) are",
        "(c) face",
        "(d) getting",
        "(e) offer",
        "(f) face",
        "(g) plays",
        "(h) deteriorating",
        "(i) face",
        "(j) are impressed",
        "(k) are becoming",
        "(l) to get",
        "(m) be developed",
        "(n) making",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Chattagram",
    data: {
      questions:
        "Relationships (a)____ (be) of different kinds. Some (b)_____ (be) familial and intimate, (c)_____ (form) by blood and by marriage; some are social like the ones we have with friends and some (d)____ (make) in school where we (e)_____ (form) close bonds with classmates and teachers. Relationship can also (f)____ (foster) in workplace, which may quickly (g)_____ (change) from professional to social. There (h)____ (be) relationships also between human beings and animals, between children and their toys that they can't (i)____ (part) with. All these relationships (j). (keep) us close to each other and (k)____ (provide) us all kinds of support love and affection. A person (l) (have) no family feels the pain of loneliness and isolation. There (m)____ (be) no one to laugh or (n)____ (cry) with him/her.",
      answers: [
        "(a) are",
        "(b) are",
        "(c) formed",
        "(d) are made",
        "(e) form",
        "(f) be fostered",
        "(g) change",
        "(h) are",
        "(i) part",
        "(j) keep",
        "(k) provide",
        "(l) having",
        "(m) is",
        "(n) cry",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dhaka",
    data: {
      questions:
        "Student life is the best time for (a) ____ (prepare) ourself for future. It is (b) ___ (call) the seed time of life. So during this period of life students mustn't (c) ____ (waste) time. The main pursuit of the students (d) ___ (be) study. They should prepare themselves for the life (e) ____ (lie) ahead. They should also (f) ____ (participate) in co-curricular activities. By (g) ___ (read) newspaper they will know what (h) ____ (happen) in the world. When the country (i) ____ (face) with a natural calamity, they should (j) ____ (come) forward with a view to (k) ____ (remove) the sufferings of the affected people. Even in normal times they (l) ____ (engage) themselves in acts of social service. The students can not do well in the examination without (m) ____ (work) hard. It is a pity that many students are trying to (n) ___ (succeed) in the shortest and easiest way.",
      answers: [
        "(a) preparing",
        "(b) called",
        "(c) waste",
        "(d) is",
        "(e) lying",
        "(f) participate",
        "(g) reading",
        "(h) is happening",
        "(i) is faced",
        "(j) come",
        "(k) remove",
        "(l) engage",
        "(m) working",
        "(n) succeed",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Rajshahi",
    data: {
      questions:
        "If all the children (a) _____ (go) to school, the country (b) _____ (get) rid of the curse of illiteracy. To boost up education, the govt. (c) _____ (spend) more money. Subsidies must (d) _____ (give) in the education sector. Teachers (e) _____ (need) to (f) _____ (train) for good teaching. The poor students can (g) _____ (bring) under “Food for Education programme. We (h) _____ (take) care that no institution (i) _____ (close) down due to political clashes. All concerned (j) ______ (be) conscious about it. If we cannot (k) ______ (keep) pace with the present world, we (l) _____ (lag) behind. For this we have to (m) _____ (ensure) education for all and set a bright prospect for (n) _____ (implement) all necessary steps.",
      answers: [
        "(a) go",
        "(b) will get",
        "(c) should spend",
        "(d) be given",
        "(e) need",
        "(f) be trained",
        "(g) be brought",
        "(h) must take",
        "(i) be closed",
        "(j) should be",
        "(k) keep",
        "(l) will lag",
        "(m) ensure",
        "(n) implementing",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Jessore",
    data: {
      questions:
        "Dhaka, the world's densest and fastest growing city, (a) ____ (face) unbearable traffic jams. There (b) ____ (be) many reasons for this. The ever increasing number of vehicles and population (c) ___ (be) the main reason. During a traffic jam, people (d) ____ (has) to suffer much. They have to (e) ____ (move) inch by inch. They have to wait on roads hours after hours (f) ____ (face) unbearable sufferings. Again, the roads of Dhaka city (g) ____ (be not) spacious. Only seven percent of Dhaka city is (h) _____ (cover) by roads, compared with around 25 percent of Paris and Vienna. If anybody falls in a traffic jam, he (i) ____ (not know) when he will reach home. Sometimes, a distance of 1km (j) ____ (take) an hour to cross. Office and school goers find it very difficult (k) ____ (reach) their destination in time. Our government (l) ____ (try) heart and soul to solve this problem. Flyovers (m) ____ (build) in different places in order to control traffic jam. Besides, traffic police and sergeants (n) ____ (see) filing cases against vehicles breaking road transport rules. But still it is becoming impossible to control traffic jam.",
      answers: [
        "(a) is facing",
        "(b) are",
        "(c) is",
        "(d) have",
        "(e) move",
        "(f) facing",
        "(g) are not",
        "(h) covered",
        "(i) does not know",
        "(j) takes",
        "(k) to reach",
        "(l) is trying",
        "(m) are being built",
        "(n) are seen",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Cumilla",
    data: {
      questions:
        "Newspaper (a) _____ (consider) the people's parliament. The newspaper (b) _____ (play) a vital role in modern civilization. It (c) ____ (call) to be the mirror of the world. We must (d) _____ (develop) the habit of (e) ____ (read) the newspaper daily. It helps us (f) _____ (acquire) general knowledge, which (g) _____ (be) essential for our education. Nobody (h) ______ (maintain) contact with the outside world without reading the newspaper. Mere bookish knowledge (i) _____ (be) not sufficient in the struggle of life. A man who (j) _____ (read) the newspaper daily (k) _____ (be) like a creature of the narrow well. Being ignorant of current topics, he cannot (l) _____ (take) part in the talks and discussions in an enlightened society and he (m) ____ (live) like a fish out of water in it. Students (n) ____ (ask) for reading newspaper daily.",
      answers: [
        "(a) is considered",
        "(b) plays",
        "(c) is called",
        "(d) develop",
        "(e) reading",
        "(f) acquire",
        "(g) is",
        "(h) can maintain",
        "(i) is",
        "(j) reads",
        "(k) is",
        "(l) take",
        "(m) lives",
        "(n) are asked",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dinajpur",
    data: {
      questions:
        "Deforestation (a) ___ (mean) cutting down trees at random. It (b) ___ (cause) mainly by a group of dishonest people. They cut trees (c) ____ (make) profit. Ordinary people also (d) ___ (use) trees as fuel and furniture. Because of (e) ___ (cut) more and more trees, we are going (f) ___ (face) a great danger in the coming future. We (g) ___ (know) that oxygen (h) ___ (supply) by trees for animals. Without (i) ___ (take) oxygen, we cannot live a single moment. If trees (j) ____ (cut) down in this way, the amount of carbon dioxide (k) ____ (increase) in the atmosphere. As a result, the heat (l) ____ (rise). It (m) ____(call) greenhouse effect. (n) ____ (enjoy) a peaceful life, we must plant more and more trees.",
      answers: [
        "(a) means",
        "(b) is caused",
        "(c) to make",
        "(d) use",
        "(e) cutting",
        "(f) to face",
        "(g) know",
        "(h) is supplied",
        "(i) taking",
        "(j) are cut",
        "(k) will increase",
        "(l) will rise",
        "(m) is called",
        "(n) To enjoy",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Mymensingh",
    data: {
      questions:
        "Cricket (a) ____ (be) a popular game. Now-a-days, people (b) ____ (long) to watch it to get pleasure. Cricket (c) ____ (call) a gentlemen's game too. A bond of friendship (d) ____ (create) among the playing nations. The Bangladesh national cricket team is popularly (e) ____ (know) as the Tigers. Our cricket team (f) ___ (be) very organized. It already (g) ____ (prove) its worth in many an international match. Our cricketers (h) ____ (be) capable of (i) ____ (compete) with the renowned cricket teams of the world. The prestige of our country already (j)____ (go) up in the international arena; thanks to our cricket team. In spite of its renown, sometimes our cricket team (k) ____ (shock) us by (l) ___ (perform) poorly. Even after that, we believe, our cricketers (m)____ (outshine) all other competitors in future. However, they (n) ____ (need) more vigorous practice to reach their goals.",
      answers: [
        "(a) is",
        "(b) long",
        "(c) is called",
        "(d) is created",
        "(e) known",
        "(f) is",
        "(g) has proved",
        "(h) are",
        "(i) competing",
        "(j) has gone",
        "(k) shocks",
        "(l) performing",
        "(m) will outshine",
        "(n) need",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Barishal",
    data: {
      questions:
        "On 26 March, 1971, Bangabandhu Sheikh Mujibur Rahman (a) ____ (declare) the independence of Bangladesh. (b) ____ (follow) this declaration, a war began between the freedom-loving Bangalees and the brutal forces of West Pakistan, (c) _____ (result) the independence of Bangladesh. The Pakistani Military Janta (d) ____ (base) in West Pakistan (e) ____ (launch) the Operation Searchlight against the unarmed people of East Pakistan (f) _____ (initiate) genocide in Bangladesh. In response to the violence, members of Mukti Bahini (g) ____ (start) a mass guerrilla war against the occupation forces. People from all walks of life (h) _____ (respond) to the call of Bangabandhu and joined the war (i) _____ (liberate) their dear motherland. The war (j) ____ (continue) for about nine months. The heroic sons of the soil made the supreme sacrifices with a view to (k) ____ (snatch) away the long-cherished freedom and thus (l) _____ (establish) Bangladesh as an independent country in the world map. Now, it (m) ____ (be) our bounden duty (n) _____ (uphold) the freedom of the country.",
      answers: [
        "(a) declared",
        "(b) Following",
        "(c) resulting",
        "(d) based",
        "(e) launched",
        "(f) initiating",
        "(g) started",
        "(h) responded",
        "(i) to liberate",
        "(j) continued",
        "(k) snatch",
        "(l) establish",
        "(m) is",
        "(n) to uphold",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Sylhet",
    data: {
      questions:
        "It is natural that a man cannot (a) ____ (live) alone. He always (b) ____ (need) a company. He has to (c) ____ (express) his thought and ideas, (d) ____ (think) others while the others (e) ____ (be) of the same needs. He (f) ____ (have) also the need of others for (g) ____ (ensure) their safety and comfort. So, he is bound (h) ____ (live) with others (i) ____ (make) an institution and it (j) ____ (call) society. Society (k) ____ (be) the first organization which (l) ____ (make) by our primitive ancestors. They (m) ____ (be) the first to contribute to (n) ____ (develop) the civilization.",
      answers: [
        "(a) live",
        "(b) needs",
        "(c) express",
        "(d) thinking",
        "(e) are",
        "(f) has",
        "(g) to ensure",
        "(h) to live",
        "(i) to make",
        "(j) is called",
        "(k) is",
        "(l) was made",
        "(m) were",
        "(n) developing",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Dhaka",
    data: {
      questions:
        "When I was a child (a) -----(be) afraid of the dark, and I always (b) ------ (go) to sleep with a light on. Even then, I feared that monsters (c) ----- (climb) in through my bedroom window and kill me. And every sound I (d) ----- (hear) struck fear into me. Often, I ran away from the room and (e) ----- (sleep) on the floor at the foot of my parents' bed. Now that I (f) ----- (be) almost twenty years old, I obviously do better than what I (g) ----- (do) as a child. However, I (h) ----- (be) still scared of bedtime. I dislike (i) ----- (sleep) alone, and I still keep a tiny night-light on. And before I go to bed, I double-check every door and every window to make sure that they (j) ----- (be) locked. Indeed, imaginary beings do not invade from outside; they exist in our superstitious beliefs.",
      answers: [
        "(a) was",
        "(b) used to go",
        "(c) would climb",
        "(d) heard",
        "(e) slept",
        "(f) am",
        "(g) did",
        "(h) am",
        "(i) sleeping",
        "(j) are",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Cumilla",
    data: {
      questions:
        "(a) ----- (acquire) knowledge is not limited to any age or time. It can (b) ----- (gain) by any person all through life. It (c) ----- (be) like unlimited wealth which can never (d) ----- (finish). A person (e) ----- (develop) with his dedication, patience, and continuity. A person (f) ----- (have) some new knowledge through regular observation and experimentation. The progress of human beings largely (g) ----- (depend) on the growth of knowledge in various fields in positive and constructive ways. For example, Newton (h) ----- (discover) the theory of gravitation, and there are many famous scientists who (i) ----- (invent) amazing things (j) ----- (make) life easy on earth.",
      answers: [
        "(a) Acquiring",
        "(b) be gained",
        "(c) is",
        "(d) be finished",
        "(e) develops",
        "(f) may have",
        "(g) depends",
        "(h) discovered",
        "(i) invented",
        "(j) making/to make",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Chattagram",
    data: {
      questions:
        "Parents (a) ----- (be) blessings of God to us. When a child (b) ----- (bear), their joys (c) ----- (know) no bounds. They (d) ----- (start) (e) ----- (think) of (f) ----- (nurse) and (g) ----- (bring) up their children. They (h) ----- (remain) safe under the custody of their parents since birth. Parents never mind (i) ----- (take) pains for the upbringing of their offspring. We (j) ----- never (offend) our parents.",
      answers: [
        "(a) are",
        "(b) is born",
        "(c) know",
        "(d) start",
        "(e) thinking",
        "(f) nursing",
        "(g) bringing",
        "(h) remain",
        "(i) taking",
        "(j) should never offend",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Sylhet",
    data: {
      questions:
        "COVID-19 (a) ----- (transmit) when people (b) ----- (breathe) in air contaminated by droplets and small airborne particles (c) ----- (contain) the virus. The risk of breathing these in (d) ----- (be) highest when people (e) ----- (be) in close proximity, but they (f) ----- (inhale) over longer distances, particularly indoors. Transmission also (g) ----- (occur) if splashed or (h) ----- (spray) with contaminated fluids in the eyes, nose, or mouth, and rarely via contaminated surfaces. People remain contagious for up to 20 days and (i) ----- (spread) the virus even if they (j) ----- (not develop) symptoms.",
      answers: [
        "(a) is transmitted",
        "(b) breathe",
        "(c) containing",
        "(d) is",
        "(e) are",
        "(f) can inhale",
        "(g) occurs",
        "(h) sprayed",
        "(i) spread",
        "(j) do not develop",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2022,
    board: "Barisal",
    data: {
      questions:
        "Road mishap (a) ----- (happen) in our country almost every day. Recently it (b) ----- (rise) to an alarming rate (c) ----- (take) a heavy toll on human lives. The members of a family remain anxious if someone (d) ----- (travel) in a bus. In most cases, reckless driving (e) ----- (cause) road accidents. The drivers are in the habit of (f) ----- (violate) traffic rules. Road accidents can be (g) ----- (lessen) if the drivers drive their vehicles carefully. People should be conscious in this respect. While (h) ----- (cross) the road, they should be careful. Some people travel (i) ----- (climb) on the roof of buses and trains. Traffic rules (j) ----- (maintain) strictly with a view to controlling road accidents.",
      answers: [
        "(a) happens",
        "(b) has risen",
        "(c) taking",
        "(d) travels",
        "(e) causes",
        "(f) violating",
        "(g) lessened",
        "(h) crossing",
        "(i) climbing",
        "(j) should be/must be/ought to be maintained",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Dhaka",
    data: {
      questions:
        'If all the children of Bangladesh a) ___ (go) to school, the country b) ___ (get) rid of the curse of illiteracy. To boost up education, the government c) ___ (spend) more money. Subsidies must d) ___ (give) in the education sector. Teachers e) ___ (need) to f) ___ (train) for good teaching. The poor students can g) ___ (bring) under "Food for Education" programme. We h) ___ (take) care that no institution i) ___ (close) down due to political clashes. All concerned j) ___ (be) conscious about it.',
      answers: [
        "(a) go",
        "(b) will get",
        "(c) should spend",
        "(d) be given",
        "(e) need",
        "(f) be trained",
        "(g) be brought",
        "(h) should take / have to take",
        "(i) is closed",
        "(j) should be / must be",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Jessore",
    data: {
      questions:
        'If all the children of Bangladesh a) ___ (go) to school, the country b) ___ (get) rid of the curse of illiteracy. To boost up education, the government c) ___ (spend) more money. Subsidies must d) ___ (give) in the education sector. Teachers e) ___ (need) to f) ___ (train) for good teaching. The poor students can g) ___ (bring) under "Food for Education" programme. We h) ___ (take) care that no institution i) ___ (close) down due to political clashes. All concerned j) ___ (be) conscious about it.',
      answers: [
        "(a) go",
        "(b) will get",
        "(c) should spend",
        "(d) be given",
        "(e) need",
        "(f) be trained",
        "(g) be brought",
        "(h) should take / have to take",
        "(i) is closed",
        "(j) should be / must be",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Dinajpur",
    data: {
      questions:
        'If all the children of Bangladesh a) ___ (go) to school, the country b) ___ (get) rid of the curse of illiteracy. To boost up education, the government c) ___ (spend) more money. Subsidies must d) ___ (give) in the education sector. Teachers e) ___ (need) to f) ___ (train) for good teaching. The poor students can g) ___ (bring) under "Food for Education" programme. We h) ___ (take) care that no institution i) ___ (close) down due to political clashes. All concerned j) ___ (be) conscious about it.',
      answers: [
        "(a) go",
        "(b) will get",
        "(c) should spend",
        "(d) be given",
        "(e) need",
        "(f) be trained",
        "(g) be brought",
        "(h) should take / have to take",
        "(i) is closed",
        "(j) should be / must be",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Sylhet",
    data: {
      questions:
        'If all the children of Bangladesh a) ___ (go) to school, the country b) ___ (get) rid of the curse of illiteracy. To boost up education, the government c) ___ (spend) more money. Subsidies must d) ___ (give) in the education sector. Teachers e) ___ (need) to f) ___ (train) for good teaching. The poor students can g) ___ (bring) under "Food for Education" programme. We h) ___ (take) care that no institution i) ___ (close) down due to political clashes. All concerned j) ___ (be) conscious about it.',
      answers: [
        "(a) go",
        "(b) will get",
        "(c) should spend",
        "(d) be given",
        "(e) need",
        "(f) be trained",
        "(g) be brought",
        "(h) should take / have to take",
        "(i) is closed",
        "(j) should be / must be",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Rajshahi",
    data: {
      questions:
        "Trees contribute a lot to maintain ecological balance. A month-long tree fair a) ___ (begin) in Kurigram Stadium recently. It b) ___ (organize) by the local administration and the Department of Social Forestation. The fair c) ___ (inaugurate) yesterday by the DC of Kurigram. It was also addressed by other speakers who d) ___ (emphasize) the need for planting more trees. The chief guest in his speech e) ___ (put) importance on planting trees so that we f) ___ (save) our environment from other effects of climate change and natural disasters. A huge procession g) ___ (parade) down the streets of the town after the inaugural (উদ্বোধন). Various government and non-government organizations h) ___ (set) up stalls displaying saplings (তরুণ গাছ) of different varieties. Cultural functions i) ___ (arrange) every night j) ___ (inspire) people to plant trees.",
      answers: [
        "(a) has begun",
        "(b) has been organized",
        "(c) was inaugurated",
        "(d) emphasized",
        "(e) put",
        "(f) can save",
        "(g) paraded",
        "(h) have set",
        "(i) are being arranged",
        "(j) to inspire",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Chittagong",
    data: {
      questions:
        "Trees contribute a lot to maintain ecological balance. A month-long tree fair a) ___ (begin) in Kurigram Stadium recently. It b) ___ (organize) by the local administration and the Department of Social Forestation. The fair c) ___ (inaugurate) yesterday by the DC of Kurigram. It was also addressed by other speakers who d) ___ (emphasize) the need for planting more trees. The chief guest in his speech e) ___ (put) importance on planting trees so that we f) ___ (save) our environment from other effects of climate change and natural disasters. A huge procession g) ___ (parade) down the streets of the town after the inaugural (উদ্বোধন). Various government and non-government organizations h) ___ (set) up stalls displaying saplings (তরুণ গাছ) of different varieties. Cultural functions i) ___ (arrange) every night j) ___ (inspire) people to plant trees.",
      answers: [
        "(a) has begun",
        "(b) has been organized",
        "(c) was inaugurated",
        "(d) emphasized",
        "(e) put",
        "(f) can save",
        "(g) paraded",
        "(h) have set",
        "(i) are being arranged",
        "(j) to inspire",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Cumilla",
    data: {
      questions:
        "Trees contribute a lot to maintain ecological balance. A month-long tree fair a) ___ (begin) in Kurigram Stadium recently. It b) ___ (organize) by the local administration and the Department of Social Forestation. The fair c) ___ (inaugurate) yesterday by the DC of Kurigram. It was also addressed by other speakers who d) ___ (emphasize) the need for planting more trees. The chief guest in his speech e) ___ (put) importance on planting trees so that we f) ___ (save) our environment from other effects of climate change and natural disasters. A huge procession g) ___ (parade) down the streets of the town after the inaugural (উদ্বোধন). Various government and non-government organizations h) ___ (set) up stalls displaying saplings (তরুণ গাছ) of different varieties. Cultural functions i) ___ (arrange) every night j) ___ (inspire) people to plant trees.",
      answers: [
        "(a) has begun",
        "(b) has been organized",
        "(c) was inaugurated",
        "(d) emphasized",
        "(e) put",
        "(f) can save",
        "(g) paraded",
        "(h) have set",
        "(i) are being arranged",
        "(j) to inspire",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Barishal",
    data: {
      questions:
        "Trees contribute a lot to maintain ecological balance. A month-long tree fair a) ___ (begin) in Kurigram Stadium recently. It b) ___ (organize) by the local administration and the Department of Social Forestation. The fair c) ___ (inaugurate) yesterday by the DC of Kurigram. It was also addressed by other speakers who d) ___ (emphasize) the need for planting more trees. The chief guest in his speech e) ___ (put) importance on planting trees so that we f) ___ (save) our environment from other effects of climate change and natural disasters. A huge procession g) ___ (parade) down the streets of the town after the inaugural (উদ্বোধন). Various government and non-government organizations h) ___ (set) up stalls displaying saplings (তরুণ গাছ) of different varieties. Cultural functions i) ___ (arrange) every night j) ___ (inspire) people to plant trees.",
      answers: [
        "(a) has begun",
        "(b) has been organized",
        "(c) was inaugurated",
        "(d) emphasized",
        "(e) put",
        "(f) can save",
        "(g) paraded",
        "(h) have set",
        "(i) are being arranged",
        "(j) to inspire",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Barishal",
    data: {
      questions:
        "Air a) ___ (be) an important element of the environment. But it is constantly being b) ___ (pollute) in many ways. We make fire to cook food and c) ___ (do) many works. This fire emits (নিঃসৃত করে) smoke which d) ___ (contaminate) air. Vehicles pollute air to a great extent by e) ___ (burn) fuel. Air pollution also f) ___ (happen) when coal and oil g) ___ (burn). Mills and factories can be h) ___ (hold) responsible for this pollution. It is high time we i) ___ (check) air pollution. Otherwise, we j) ___ (suffer) a lot.",
      answers: [
        "(a) is",
        "(b) polluted",
        "(c) do",
        "(d) contaminates",
        "(e) burning",
        "(f) happens",
        "(g) are burnt",
        "(h) held",
        "(i) checked",
        "(j) will suffer",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Cumilla",
    data: {
      questions:
        "English a) ___ (be) the most widely used international language. It b) ___ (learn) to communicate with the foreigners for various purposes such as c) ___ (maintain) co-operation, co-existence and exchanging business information. There are also certain jobs which d) ___ (require) a good functional knowledge of English. The jobs of a pilot, a postman, a telephone operator, a tour guide, a mechanic, a receptionist of an international hotel, an executive of a multinational firm etc. e) ___ (be) a few of them. Besides, a student f) ___ (wish) to go for higher studies must learn English because the books on advanced education are mostly g) ___ (write) in English. So, the importance and demand of learning English in our country can, in no way, be h) ___ (ignore). Rather, we should i) ___ (put) high importance on j) ___ (learn) English to make room for ourselves in the competitive world.",
      answers: [
        "(a) is",
        "(b) is learnt",
        "(c) maintaining",
        "(d) require",
        "(e) are",
        "(f) wishing",
        "(g) written",
        "(h) ignored",
        "(i) put",
        "(j) learning",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Rajshahi",
    data: {
      questions:
        "It has been over three hundred years since Emperor Shah Jahan of Delhi a) ___ (build) the Taj Mahal as a tomb for his wife in Agra. Architecturally, it b) ___ (be) one of the most beautiful buildings in the world. The buildings c) ___ (make) of fine white marble with inlays of coloured marble. It d) ___ (have) eight sides and many open arches. It e) ___ (rest) on a platform or terrace of red sandstone. Four slender (সরল) white towers f) ___ (rise) from the corners of the terrace. A large dome g) ___ (stand) above the centre of the building. Around this large dome there h) ___ (be) four smaller domes. Just inside the outer walls, there is an open corridor from which the visitors i) ___ (look) through carved marble screens into a central room. The bodies of Shah Jahan and his wife Mumtaz j) ___ (lie) in two graves below this room.",
      answers: [
        "(a) built",
        "(b) is",
        "(c) is made",
        "(d) has",
        "(e) rests",
        "(f) rise",
        "(g) stands",
        "(h) are",
        "(i) can look",
        "(j) lie",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Sylhet",
    data: {
      questions:
        "Jerry is an orphan. He a) ___ (come) to the orphanage at the age of four. He b) ___ (lose) his parents in his infancy (শৈশবে). Then, he c) ___ (commit) to the care of the orphanage. He could hardly d) ___ (recollect) his parents' memory. In spite of e) ___ (be) an orphan, he had developed a strong fabric of morality. His inimitable (অনুকরণীয়) morality f) ___ (draw) him close to the writer. The writer g) ___ (impress) with him. She started h) ___ (show) affection for him. Jerry i) ___ (take) her for his mother. He fabricated (গঠন করা) a lie j) ___ (win) her heart.",
      answers: [
        "(a) came",
        "(b) lost",
        "(c) was committed",
        "(d) recollect",
        "(e) being",
        "(f) drew",
        "(g) was impressed",
        "(h) showing",
        "(i) took",
        "(j) to win",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dhaka",
    data: {
      questions:
        "Road mishap a) ___ (happen) in our country almost everyday. Recently it b) ___ (rise) to an alarming rate c) ___ (take) a heavy toll of human lives. The members of a family remain anxious if someone d) ___ (travel) in a bus. In most cases, reckless driving e) ___ (cause) road accidents. The drivers are in the habit of f) ___ (violate) traffic rules. Toad accidents can be g) ___ (lessen) if the drives drive their vehicles carefully. People should be conscious in this respect. While h) ___ (cross) the road, they should be careful. Some people travel i) ___ (climb) on the roof of the buses and trains. Traffic rules must be maintained strictly with a view to j) ___ (control) road accidents.",
      answers: [
        "(a) happens",
        "(b) has risen",
        "(c) taking",
        "(d) travels",
        "(e) causes",
        "(f) violating",
        "(g) lessened",
        "(h) crossing",
        "(i) climbing",
        "(j) controlling",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Chittagong",
    data: {
      questions:
        'The liberation war of Bangladesh inspired many artists, singers and cultural activities. Eminent artist Shaheen Samad a) ___ (join) Bangladesh Muktijuddho Sangeeti Shilpi Sangstha during the liberation war. She along with others b) ___ (inspire) millions with her voice c) ___ (raise) funds for the refugee camps. The cultural troupe (দল) used to d) ___ (travel) to refugee camps and different areas in Mukta Anchal. They e) ___ (perform) patriotic songs and arranged puppet shows besides f) ___ (stage) dramas. Shaheed Samad said, "Liberation war always g) ___ (be) an inspiration for me." She sang a lot of songs during that time and now h) ___ (feel) honoured to have been able to inspire the freedom fighters. She has the memorable harmonium with which she sang in 1971. Now she i) ___ (wish) to hand it over to Liberation War Museum. This eminent (প্রখ্যাত) artist wants to see live performance of those moving songs on TV channel, at least one song in a week and thus j) ___ (cover) all the year around.',
      answers: [
        "(a) joined",
        "(b) inspired",
        "(c) raising",
        "(d) travel",
        "(e) performed",
        "(f) staging",
        "(g) has been",
        "(h) feels",
        "(i) wishes",
        "(j) covering",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dinajpur",
    data: {
      questions:
        "In the last autumn vacation I a) ___ (get) sufficient time. So I b) ___ (make) up my mind to make a journey by train from Dhaka to Chattogram. I c) ___ (reach) the station about half an hour before the departure of the train. It d) ___ (be) then a very busy time. Rickshaw, motorcars and other vehicles e) ___ (come) to the station with passengers. Coolies f) ___ (run) behind them. There g) ___ (be) shouts and rush of the passengers and the coolies. After sometime, hearing a whistle, the passengers h) ___ (stand) in queue (পঙ্গু) before the ticket counter. I also i) ___ (stand) in the line and j) ___ (buy) a second class ticket.",
      answers: [
        "(a) got",
        "(b) made",
        "(c) reached",
        "(d) was",
        "(e) were coming",
        "(f) were running",
        "(g) were",
        "(h) stood",
        "(i) stood",
        "(j) bought",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Jessore",
    data: {
      questions:
        "Most of the people who a) ___ (appear) most often gloriously in the pages of history b) ___ (be) great conquerors and generals and soldiers, whereas the people who really c) ___ (help) civilization forward are often never d) ___ (mention) at all. We do not know who first e) ___ (set) a broken leg, or launched a sea worthy boat or f) ___ (calculate) the length of a year, but we g) ___ (know) all about the killers and destroyers. People think a great deal of them, so much so that on all the highest pillars in great cities of the world you h) ___ (find) figures of a conqueror or a general soldier. And I think that most people i) ___ (believe) that the greatest countries are those that j) ___ (beat) in the greatest number of countries and ruled over them as conquerors.",
      answers: [
        "(a) appeared/appear",
        "(b) were/are",
        "(c) helped/help",
        "(d) mentioned",
        "(e) set",
        "(f) calculated",
        "(g) know",
        "(h) would find",
        "(i) believe",
        "(j) have beaten",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Cumilla",
    data: {
      questions:
        "Parents a) ___ (be) blessings of God to us. When a child b) ___ (bear), their joys c) ___ (know) no bounds. They d) ___ (start) e) ___ (think) of f) ___ (nurse) and g) ___ (bring) up their children. They h) ___ (remain) safe under the custody of their parents since birth. Parents never mind i) ___ (take) pains for the upbringing (উৎপাদন) of their off spring (সন্তান). We j) ___ (never) (offend) our parents.",
      answers: [
        "(a) are",
        "(b) is born",
        "(c) know",
        "(d) start",
        "(e) thinking / to think",
        "(f) nursing",
        "(g) bringing",
        "(h) remain",
        "(i) taking",
        "(j) should never offend",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Rajshahi",
    data: {
      questions:
        "Once there a) ___ (live) an idle king. He b) ___ (not undergo) physical labour. As a result, he c) ___ (get) bulky and could not move from one place to another. He d) ___ (call) in a doctor. The doctor e) ___ (be) clever and wise. He didn’t f) ___ (prescribe) any medicine for the king. He asked the king to buy a club (ডান্ডা) and g) ___ (move) in the air till his hands h) ___ (get) moistened (আর্দ্র). The king started i) ___ (follow) the prescription. Thus, the king j) ___ (relieve) of his problem.",
      answers: [
        "(a) lived",
        "(b) did not undergo",
        "(c) got",
        "(d) called",
        "(e) was",
        "(f) prescribe",
        "(g) move",
        "(h) got",
        "(i) following",
        "(j) was relieved",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },

  {
    exam: "hsc",
    year: 2016,
    board: "Chittagong",
    data: {
      questions:
        "To err is human. If a man commits crime anytime and repents (পশ্চাত্তাপ করে) truly for his misdeed, he may a) ___ (forgive). But the man who b) ___ (not give up) the wrong, c) ___ (suffer) surely. In the long run, he d) ___ (will take) to the land of death. The old sailor e) ___ (be) a wrong-doer in his long journey. He committed a crime f) ___ (kill) a sea bird g) ___ (call) Albatross. That crime ultimately h) ___ (bring) bad luck to them. The ship i) ___ (leave) in the icy sea. The sun shone over their head. The wind j) ___ (drop) down. It was a great disaster.",
      answers: [
        "(a) be forgiven",
        "(b) does not give up",
        "(c) suffers / will suffer",
        "(d) will be taken",
        "(e) was",
        "(f) killing",
        "(g) called",
        "(h) brought",
        "(i) was left",
        "(j) dropped",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Barisal",
    data: {
      questions:
        "There are many people who a) ___ (not take) physical exercise. They can hardly b) ___ (realize) that they themselves c) ___ (ruin) their health. They d) ___ (fall) victim to many diseases. Life e) ___ (become) dull to them. They f) ___ (remain) always ill tempered. We g) ___ (build) good health and sound mind through physical exercise. Physical exercise h) ___ (make) our body active and the muscles strong. It also i) ___ (improve) our power of digestion and blood circulation. It j) ___ (give) strength to our brain.",
      answers: [
        "(a) do not take",
        "(b) realize",
        "(c) are ruining / ruin",
        "(d) fall",
        "(e) becomes",
        "(f) remain",
        "(g) can build",
        "(h) makes",
        "(i) improves",
        "(j) gives",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Dhaka",
    data: {
      questions:
        "Football is a favourite game in our country. It a) ___ (arrange) between two teams b) ___ (contain) eleven players each. The captains of both teams c) ___ (lead) their groups. This is the most exciting and enjoyable game ever d) ___ (play) across the world. It e) ___ (run) for an hour and a half with a interval (বিরতি) after half of the time f) ___ (be) over. Any football tournament g) ___ (arrange) between two strong teams can be exciting. The result h) ___ (remain) almost unpredictable till the end because any team might win against the other team i) ___ (score) a goal within seconds. The referee is to see whether rules and order j) ___ (maintain) by the players.",
      answers: [
        "(a) is arranged",
        "(b) containing",
        "(c) lead",
        "(d) played",
        "(e) runs",
        "(f) is",
        "(g) arranged",
        "(h) remains",
        "(i) scoring",
        "(j) are maintained",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Dinajpur",
    data: {
      questions:
        "Many events of great importance a) ___ (take) place during the last century. Significant advances b) ___ (make) in the field of science and technology. Many European colonies c) ___ (gain) independence. The movement for democracy d) ___ (become) prominent (প্রকট) in many parts of the world. Two World Wars e) ___ (break) out in this century. It also f) ___ (witness) the misuse of atomic energy. Two cities of Japan were completely g) ___ (destroy) as a result of dropping of atom bombs. However, the emergence (উদ্ভব) of Bangladesh as an independent nation h) ___ (become) a momentous event. After a bloody war of nine months Bangladesh i) ___ (bear). Now we j) ___ (hold) our heads high in the community of nations.",
      answers: [
        "(a) took",
        "(b) were made",
        "(c) gained",
        "(d) became",
        "(e) broke",
        "(f) witnessed",
        "(g) destroyed",
        "(h) became",
        "(i) was born",
        "(j) can hold",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Jessore",
    data: {
      questions:
        "Idle brain is devil’s workshop. If we a) ___ (waste) our time in idleness, all sorts of evil thoughts will crowd our brain. Idle persons who b) ___ (kill) their time are burdens of society. They c) ___ (sit) idle and cherish no high ideal and lofty ambition (উচ্চাকাঙ্ক্ষা) in life. They d) ___ (not support) themselves. They e) ___ (lead) an unhappy life and f) ___ (suffer) in the long run. There should be time for reading, for office or other work, time for physical exercise, time for recreation and time for prayer. This g) ___ (indicate) that we should do everything at the right moment. We h) ___ (lead) a healthy and prosperous life only when we i) ___ (follow) the routine which we j) ___ (make) for our guidance.",
      answers: [
        "(a) waste",
        "(b) kill",
        "(c) sit",
        "(d) cannot support",
        "(e) lead",
        "(f) suffer",
        "(g) indicates",
        "(h) can lead",
        "(i) follow",
        "(j) make",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
  {
    exam: "hsc",
    year: 2016,
    board: "Sylhet",
    data: {
      questions:
        "One night the entire village was sleeping. The boy Bayzid Bustami was busy in study. His mother a) ___ (sleep). Suddenly she woke up and b) ___ (feel) thirsty. c) ___ (call) her son, she told her son to give her a glass of water and d) ___ (fall) asleep again. When Bayzid went to the pitcher, he e) ___ (find) it empty. So, he went out with the pitcher in search of water. After a while he f) ___ (come) back home with water and found his mother g) ___ (sleep). Then he waited h) ___ (stand) by her bed with a glass of water. He did not make any sound lest she i) ___ (wake) up. Suddenly his mother woke up and saw him with the glass of water. At once she j) ___ (understand) what was the matter.",
      answers: [
        "(a) was sleeping",
        "(b) felt",
        "(c) Calling",
        "(d) fell",
        "(e) found",
        "(f) came",
        "(g) sleeping",
        "(h) standing",
        "(i) should wake",
        "(j) understood",
      ],
      isDifficult: false,
      isCompleted: true,
    },
  },
];
