export const specialPhrasesData = [
  {
    exam: "hsc",
    year: 2025,
    board: "Dinajpur",
    data: {
      options: [
        "had better",
        "it",
        "have to/has to",
        "what does...look like",
        "let alone",
        "would rather",
        "there",
        "as soon as",
        "was born",
        "what's...like",
      ],
      questions: [
        "Our spring is very charming. During spring various kinds of flowers bloom. — seems that everything has got a new life.",
        "— the weather — today?",
        "Don't disturb me. You — leave me alone at this moment.",
        "The poor man — starve than beg.",
        "— exists no life on Mars.",
        "Baby: Mom, — an owl —?",
        "Sir Walter Scott was both a poet and novelist. He — in 1971.",
        "Everybody — pay the electricity bill in time.",
        "— we reached the station, the train started.",
        "He did not even see a hill, — a mountain.",
      ],
      answers: [
        "it",
        "What's...like",
        "had better",
        "would rather",
        "There",
        "what does...look like",
        "was born",
        "has to",
        "As soon as",
        "let alone",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Jashore",
    data: {
      options: [
        "had better",
        "there",
        "would rather",
        "no sooner",
        "was born",
        "let alone",
        "would",
        "what does …",
        "had",
        "enough",
        "do you mind",
        "look like",
      ],
      questions: [
        "He cannot buy a pen — a box of pens.",
        "— we reached the station than the train started.",
        "All seasons are very charming. During spring various kinds of flowers bloom.— seems that everything has got a new life.",
        "Baby: Mom, — an owl — ?",
        "Don’t disturb me, you — leave me alone at this moment.",
        "The poor man — starve than beg.",
        "— exists no life on Mars.",
        "— taking tea with me?",
        "Sir Walter Scott was both a poet and a novelist. He — in 1771.",
        "He was meritorious — to understand English literature.",
      ],
      answers: [
        "let alone",
        "No sooner had",
        "there",
        "what does … look like",
        "had better",
        "would rather",
        "there",
        "do you mind",
        "was born",
        "enough",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Sylhet",
    data: {
      options: [
        "was born",
        "as soon as",
        "would rather",
        "what does...look like",
        "had better",
        "what's...like",
        "have to/has to",
        "let alone",
        "there",
        "it",
      ],
      questions: [
        "Manners make a man. Students ______ practise good manners in everyday life.",
        "You look exhausted. You ______ take rest to refresh yourself.",
        "Mansib has not yet got 1st dose of Covid-19 vaccine, ______ booster dose.",
        "Our spring is very charming. During spring, various flowers bloom. ______ seems everything has new life.",
        "Rodela: ______ the frozen mountain peak ______?",
        "Kazi Nazrul is our rebel poet. He ______ in Churulia, West Bengal.",
        "The sky is cloudy; we should start our journey ______ possible.",
        "______ your family ______? I belong to a nuclear family.",
        "I ______ remain silent than quarrel.",
        "______ was a time people traveled on foot.",
      ],
      answers: [
        "have to",
        "had better",
        "let alone",
        "It",
        "What does...look like",
        "was born",
        "as soon as",
        "What's...like",
        "would rather",
        "There",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Dhaka",
    data: {
      options: [
        "let alone",
        "have to",
        "it",
        "was born",
        "as soon as",
        "there",
        "what's...like",
        "what does...look like",
        "had better",
        "would rather",
      ],
      questions: [
        "You ______ not touch the crocodile. It's dangerous.",
        "She has never boiled an egg, ______ prepared a meal.",
        "He will go to the shop ______ the rain stops.",
        "I don't need a lift. I ______ walk.",
        "They ______ solve these problems soon.",
        "______ was John who cleaned the house.",
        "______ goes a proverb: morning shows the day.",
        "______ an alligator ______? I've never seen one.",
        "He ______ of German parents.",
        "______ the journey ______? It was enjoyable.",
      ],
      answers: [
        "had better",
        "let alone",
        "as soon as",
        "would rather",
        "have to",
        "It",
        "There",
        "What does...look like",
        "was born",
        "What's...like",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Chittagong",
    data: {
      options: [
        "There",
        "It",
        "have to",
        "was born",
        "what's...like",
        "would rather",
        "as soon as",
        "let alone",
        "had better",
        "what does...look like",
      ],
      questions: [
        "The baby stopped crying ______ it saw its mother.",
        "If ______ is any change, I'll inform you.",
        "______ is good to walk in morning.",
        "I ______ start now for my 4pm appointment.",
        "She ______ decorate her room for her birthday.",
        "______ the newborn baby ______?",
        "______ it ______ swimming in the river?",
        "He doesn't behave well with parents, ______ others.",
      ],
      answers: [
        "as soon as",
        "there",
        "It",
        "had better",
        "has to",
        "What does...look like",
        "What's...like",
        "let alone",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Cumilla",
    data: {
      options: [
        "let alone",
        "there",
        "what does...look like",
        "was born",
        "as soon as",
        "has to",
        "what's...like",
        "it",
        "would rather",
        "had better",
      ],
      questions: [
        "Rifat ______ see a dentist for his toothache.",
        "Rima ______ in Indonesia, raised in America.",
        "The game will resume ______ the rain stops.",
        "______ has been great change in superstitious beliefs.",
        "You ______ take rest; you look anxious.",
        "I ______ use keyboard than write with pen.",
        "We can't save trees, ______ our forest.",
        "______ mother's love ______? It's incomparable.",
        "______ is unfortunate students spoil time on Facebook.",
        "______ the frozen mountain peak ______?",
      ],
      answers: [
        "had better",
        "was born",
        "as soon as",
        "There",
        "had better",
        "would rather",
        "let alone",
        "What's...like",
        "It",
        "What does...look like",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Barishal",
    data: {
      options: [
        "there",
        "what does...look like",
        "would rather",
        "what's...like",
        "have to",
        "as soon as",
        "let alone",
        "had better",
        "it",
        "was born",
      ],
      questions: [
        "We ______ hospitalize the alive man soon.",
        "______ is only early morning with fresh air.",
        "My cousin ______ in Singapore, raised in America.",
        "You ______ start journey now; weather is good.",
        "Kamrul: ______ university admission test ______?",
        "My father ______ resign than compromise.",
        "______ is no fish in this pool.",
        "Teacher: ______ Bangladesh's national flower ______?",
        "He doesn't deserve to be enemy, ______ friend.",
        "He repaid loan ______ he made profit.",
      ],
      answers: [
        "have to",
        "It",
        "was born",
        "had better",
        "What's...like",
        "would rather",
        "there",
        "What does...look like",
        "let alone",
        "as soon as",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Rajshahi",
    data: {
      options: [
        "what does...look like",
        "would rather",
        "let alone",
        "was born",
        "have to",
        "there",
        "what's...like",
        "had better",
        "as soon as",
      ],
      questions: [
        "A.K. Fazlul Haq ______ in Barishal.",
        "The thief ran away ______ we saw him.",
        "Rickshaw-puller can't afford meals, ______ rickshaw.",
        "A warrior ______ die than yield.",
        "You ______ apply for stipend.",
        "A farmer ______ work hard daily.",
        "______ your principal ______?",
        "______ is unfortunate students waste time.",
        "______ was a time letters took days.",
        "Son: Dad, ______ an alien ______?",
      ],
      answers: [
        "was born",
        "as soon as",
        "let alone",
        "would rather",
        "had better",
        "has to",
        "What's...like",
        "It",
        "There",
        "what does...look like",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2025,
    board: "Mymensingh",
    data: {
      options: [
        "there",
        "as soon as",
        "what does...look like",
        "have to",
        "let alone",
        "was born",
        "would rather",
        "what's...like",
        "it",
        "had better",
      ],
      questions: [
        "You ______ not ask me the truth.",
        "I ______ leave than endure humiliation.",
        "Steve Jobs ______ into a humble family.",
        "Audience leaves ______ Nambi finishes storytelling.",
        "He can't finish a chapter, ______ whole book.",
        "______ are many life challenges.",
      ],
      answers: [
        "had better",
        "would rather",
        "was born",
        "as soon as",
        "let alone",
        "There",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dhaka",
    data: {
      options: [
        "what does...look",
        "what's it like",
        "would rather",
        "had better",
        "as if",
        "like",
        "was born",
        "let alone",
        "as soon as",
        "have to",
        "What if",
      ],
      questions: [
        "Sumi talks too much. It ___ she were a mad.",
        "Can anyone tell me ___? I have never seen an elephant.",
        "I am eagerly waiting for your reply. Please answer me ___ you can.",
        "___ swimming in a river? I am so excited.",
        "Helmet should be used while driving a motorbike. ___ you were in a bike and met a serious accident?",
        "This is a secret matter. We ___ not discuss this in public.",
        "Socrates who was sentenced to death by drinking hemlock ___ in 469 BC.",
        "I ___ take an auto bike than go to college on foot. The exam is about to start.",
        "Sometimes we ___ accept something unwillingly for the sake of peace.",
        "I can hardly walk ___ run a race.",
      ],
      answers: [
        "as if",
        "what does...look",
        "as soon as",
        "What's it like",
        "What if",
        "had better",
        "was born",
        "would rather",
        "have to",
        "let alone",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Rajshahi",
    data: {
      options: [
        "would that",
        "had better",
        "since",
        "let alone",
        "as soon as",
        "it",
        "no sooner",
        "too...to",
        "as if",
        "what's it like",
        "had...than",
      ],
      questions: [
        "You look exhausted. You ___ take rest for a while.",
        "The thief has fled away ___ he might be caught.",
        "___ I seen the snake ___ I became awe-struck.",
        "It would render my cooperation to you if ___ requires.",
        "It was long ___ I had met you.",
        "He met me, he hugged me warmly.",
        "I don’t expect any help from him. He is ___ busy ___ help you.",
        "I am an orphan now. ___ my father had lived longer.",
        "He cannot walk for few steps ___ run for a mile.",
        "He overlooks me ___ he never knew me.",
      ],
      answers: [
        "had better",
        "as if",
        "No sooner...than",
        "it",
        "since",
        "As soon as",
        "too...to",
        "Would that",
        "let alone",
        "as if",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Cumilla",
    data: {
      options: [
        "there",
        "what does...look",
        "would rather",
        "what's...like",
        "have to/has to",
        "like",
        "as soon as",
        "let alone",
        "had better",
        "it",
        "was born",
      ],
      questions: [
        "___ looks dangerous to reach the top. Very few number of people can arrive there safely.",
        "All passengers ___ fill in an immigration form on arrival. It is mandatory.",
        "My cousin ___ in Malaysia and raised in America. Now she has a dual citizenship.",
        "___ your family ___? Is it an extended family like ours?",
        "Your mother seems to be very weak. You ___ consult an experienced doctor about her health.",
        "His parents ___ stay in village than live with him in Dhaka. Both of them don’t like city life.",
        "___ have been significant changes in the types of entertainment over time. Many of those no longer exist.",
        "Teacher learners ___ the national flower of Bangladesh ___? Students! It looks a bit like the lotus.",
        "It is not easy to score a goal ___ hat trick.",
        "We informed the police ___ the incident took place. But the police didn’t arrive even after two hours.",
      ],
      answers: [
        "It",
        "have to",
        "was born",
        "What's...like",
        "had better",
        "would rather",
        "There",
        "what's...like",
        "let alone",
        "as soon as",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Jashore",
    data: {
      options: [
        "had better",
        "there",
        "what does...look",
        "it",
        "let alone",
        "like",
        "as soon as",
        "what's...like",
        "have to",
        "would rather",
        "was born",
      ],
      questions: [
        "He headed for the new workplace ___ he received the transfer order.",
        "___ your new teacher ___? He is nice but a bit strict.",
        "The Bangladesh cricket team dropped out from the tournament in the first round, ___ make it to the final.",
        "I am trying to catch upon some sleep. You ___ turn off the TV.",
        "___ she ___? She is tall and has blonde hair.",
        "Although Lalon Shah ___ into a Hindu family, he grew up in a Muslim family.",
        "Nowadays we cannot think of a single day without cell phones but ___ was a time when even land phones were a luxury.",
        "My aunt is shy by nature, in social gatherings, she stays ___ alone than interact with others.",
        "___ was a wonderful night. The sky was cloudless and full of stars.",
        "You ___ follow traffic rules. You cannot drive as you like.",
      ],
      answers: [
        "as soon as",
        "What does...look",
        "let alone",
        "had better",
        "What's...like",
        "was born",
        "there",
        "would rather",
        "It",
        "have to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Dinajpur",
    data: {
      options: [
        "would rather",
        "what's...like",
        "has to",
        "let alone",
        "it",
        "was born",
        "what",
        "as soon as",
        "there",
        "had better",
        "does...look like",
      ],
      questions: [
        "Most of the kids are fun-loving. They ___ play than study.",
        "___ the weather today?",
        "Rani is an examinee. She ___ study a lot to make a good result.",
        "I have been suffering from cold and cough. I can't speak clearly ___ sing.",
        "___ seems to be a crowd on the road. Let's go and see.",
        "The Nightingale was a nurse. She ___ was born in 1820.",
        "The plane flying above from below? It ___ looks like a bird.",
        "It is a cold day. ___ the sun rises, the fog disappears.",
        "___ is a lack of communication. They don't understand the problem at all.",
        "We ___ go home. It's getting dark.",
      ],
      answers: [
        "would rather",
        "What's...like",
        "has to",
        "let alone",
        "There",
        "was born",
        "What...does...look",
        "As soon as",
        "It",
        "had better",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Barisal",
    data: {
      options: [
        "would rather",
        "have to",
        "what does...look",
        "it",
        "there",
        "let alone",
        "had better",
        "as soon as",
        "was born",
        "what's...like",
      ],
      questions: [
        "Begging is quite disgraceful. I think he knows it very well. He ___ starve than do so.",
        "Deforestation is detrimental to the environment. We ___ stop cutting down trees.",
        "What does ___ look like? He is friendly and he can help you.",
        "It ___ is difficult to regain lost health. So we should always take care of health.",
        "There ___ flows a river beside our village. The river is useful to us in many ways.",
        "What's ___ like? Have you seen a camel?",
        "He cannot express his ideas in Bangla, ___ in English.",
        "I ___ take coffee in lieu of tea. But I like both of them.",
        "As soon as ___ the incident took place. We informed the police.",
        "Robert Herrick ___ in 1591. He was a famous poet of English literature.",
      ],
      answers: [
        "would rather",
        "had better",
        "what...does...look",
        "it",
        "there",
        "what's...like",
        "let alone",
        "have to",
        "as soon as",
        "was born",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Chattogram",
    data: {
      options: [
        "what does...look",
        "it",
        "as soon as",
        "was born",
        "has to",
        "there",
        "would rather",
        "let alone",
        "had better",
      ],
      questions: [
        "Bangladesh Sheikh Mujibur Rahman ___ in 1920 in Tungipara of Gopalganj district.",
        "Professor Nathaniel Kleitman ___? Though he looks serious, he is an interesting physiologist and sleep researcher.",
        "The train blew whistle. ___ the passenger heard the whistle, they got into it.",
        "___ is very hot today. Moreover, load-shedding is aggravating the situation.",
        "___ mother's love ___? It is incomparable.",
        "My nephew's father is very sick. ___ seems to be no hope of recovery.",
        "The sky is getting dark. Nahian ___ carry an umbrella.",
        "Thamid was too tired to walk. He ___ run.",
        "Ahsan ___ walk home than take a rickshaw. The road is jam-packed.",
        "There is a charitable dispensary in our locality. None ___ pay for the service.",
      ],
      answers: [
        "was born",
        "What...does...look",
        "As soon as",
        "It",
        "What's...like",
        "There",
        "had better",
        "let alone",
        "would rather",
        "has to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2024,
    board: "Mymensingh",
    data: {
      options: [
        "there",
        "has to",
        "let alone",
        "as soon as",
        "what does...look like",
        "was born",
        "it",
        "had better",
        "would rather",
        "what's...like",
      ],
      questions: [
        "Selina is a poor student. She cannot afford to buy a cell phone ___ a laptop.",
        "The sky is cloudy. It may rain today. You ___ leave early.",
        "___ is many years since we first met. How time does fly!",
        "His mother is sick. He needs to go home ___ possible.",
        "We ___ develop our humanity than observe hartal and strike.",
        "The browning is my favourite poet. He ___ was born in 1812.",
        "There ___ was a pandemic all over the world in 2020 and 2021.",
        "A good citizen ___ perform a lot of things.",
        "___ the national flower of Bangladesh ___?",
        "___ honesty ___? It is the best quality of life.",
      ],
      answers: [
        "let alone",
        "had better",
        "It",
        "as soon as",
        "would rather",
        "was born",
        "there",
        "has to",
        "What's...like",
        "What...does...look",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Dhaka",
    data: {
      options: [
        "There",
        "would rather",
        "what does... look like",
        "as soon as",
        "what's it like",
        "It",
        "was born",
        "have to",
        "let alone",
        "had better",
      ],
      questions: [
        "Time is very valuable. We ___ utilize time properly.",
        "I ___ take a taxi than walk home. It is already too late.",
        "Long ago ___ lived a mighty king Kubla Khan. He built an amazing palace in a deep dark forest.",
        "___ watching a horror film at midnight? You are really scared.",
        "It is winter. You ___ buy a coat.",
        "___ the balcony ___? It looks very beautiful, but it is really small.",
        "Bangladesh ___ as an independent state on 16 December 1971 after nine months of bloody war against the occupying Pakistan Army.",
        "___ was in China that the art of Bonsai originated, perhaps more than 1000 years ago.",
        "I cannot ride a bicycle ___ a motorcycle. I have no money to buy any of them.",
        "___ the rain stopped, I started for home.",
      ],
      answers: [
        "have to",
        "would rather",
        "There",
        "What's it like",
        "had better",
        "What does... look like",
        "was born",
        "It",
        "let alone",
        "as soon as",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Rajshahi",
    data: {
      options: [
        "would rather",
        "was born",
        "let alone",
        "It",
        "There",
        "has to",
        "what's... like",
        "had better",
        "as soon as",
        "what does... look like",
      ],
      questions: [
        "Rupa ___ take up the profession of teaching than be a nurse. She thinks teaching is a noble profession.",
        "Edmund Burke was an orator, writer, and shrewd politician. He ___ in 1729 in England.",
        "___ is difficult to regain lost health. So, we should always take care of our health.",
        "___ flows a river beside our village. The river is useful to us in many ways.",
        "Sarika is an examinee. She ___ study a lot to make a good result.",
        "___ honesty ___? I think it to be a noble virtue.",
        "Rita is ill. We ___ go to see her. She will be happy to see us.",
        "The food was contaminated. ___ an elephant ___? I have never seen it before.",
        "He cannot teach in a high school ___ in a university.",
      ],
      answers: [
        "would rather",
        "was born",
        "It",
        "There",
        "has to",
        "What's... like",
        "had better",
        "What does... look like",
        "let alone",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Cumilla",
    data: {
      options: [
        "as soon as",
        "have to",
        "it",
        "was born",
        "there",
        "would rather",
        "had better",
        "what's... like",
        "let alone",
        "what does... look like",
      ],
      questions: [
        "The tennis match restarted ___ the rain had stopped.",
        "In England, most school children ___ wear a uniform. Is it the same in Bangladesh?",
        "In our country, the rainy season is very different. During this season ___ rains heavily without any gap.",
        "Socrates was a great Greek philosopher. He ___ in 469 BC. He spoke against traditional Greek beliefs and so he was sentenced to death by drinking hemlock.",
        "Long ago ___ lived a mighty warrior, Kubla Khan. He built an amazing palace in a deep dark, and mysterious forest.",
        "A warrior ___ die than surrender to enemies.",
        "He loves his country more than his life.",
        "___ the weather ___ today?",
        "Baby Mom, a ghost ___? It has been many years since I saw him. So, I cannot recognize him.",
        "It may rain today. We ___ take an umbrella.",
      ],
      answers: [
        "as soon as",
        "have to",
        "there",
        "was born",
        "there",
        "would rather",
        "had better",
        "What's... like",
        "What does... look like",
        "have to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Jashore",
    data: {
      options: [
        "have to",
        "had better",
        "let alone",
        "It",
        "what does... look like",
        "was born",
        "as soon as",
        "what's... like",
        "would rather",
        "there",
      ],
      questions: [
        "Manners make a man. Students ___ practice good manners in everyday life.",
        "You look exhausted. You ___ take rest to refresh yourself.",
        "Raihan has not yet got the 1st dose of the COVID-19 vaccine, ___ booster dose.",
        "Our spring is very charming. During spring, various kinds of flowers bloom. ___ seems that everything has got a new life.",
        "Ria ___ the frozen mountain peak ___? Purnima! It looks like a white dome.",
        "Kazi Nazrul Islam is our rebel poet. He ___ in Churulia of West Bengal.",
        "The sky is cloudy and it may storm at any moment. So, we should start our journey ___ possible.",
        "___ your family ___? I belong to a nuclear family.",
        "___ was a time when people used to travel on foot or ride animals.",
      ],
      answers: [
        "have to",
        "had better",
        "let alone",
        "It",
        "What's... like",
        "was born",
        "as soon as",
        "What does... look like",
        "There",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Sylhet",
    data: {
      options: [
        "let alone",
        "had better",
        "It",
        "as soon as",
        "have to",
        "There",
        "was born",
        "what's... like",
        "would rather",
      ],
      questions: [
        "Anika can't afford a bus ticket ___ an air ticket.",
        "It may rain today. You ___ reach home earlier.",
        "___ is many years since we first met. How time does fly!",
        "As his brother met with an accident, he needs to go to the hospital ___ possible.",
        "We ___ develop our view about hartal and strikes. Let's change our destructive culture.",
        "___ have been remarkable changes in the behavior of our young generation.",
        "Maria Munda is a promising footballer of our country. She ___ in a remote village.",
        "Kamrul ___ having integrity in one's character? It is the best quality of a man.",
        "He is very poor but honest. He ___ starve than cheat anybody.",
        "___ a squirrel ___?",
      ],
      answers: [
        "let alone",
        "had better",
        "It",
        "as soon as",
        "have to",
        "There",
        "was born",
        "What's... like",
        "would rather",
        "What does... look like",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Barishal",
    data: {
      options: [
        "used to",
        "had better",
        "as if",
        "what does... look like",
        "as soon as",
        "would rather",
        "what if",
        "feel like",
        "There",
        "It",
      ],
      questions: [
        "Jolly is my friend; she ___ sing in a choir, but she gave it up for some unavoidable reasons.",
        "The world economy is passing through a great crisis due to the war situation. The world leaders ___ concentrate on the economy and security of the common people.",
        "We went to John's office yesterday. He behaved ___ he had not known us.",
        "___ a dinosaur ___? Have you ever seen it?",
        "We are waiting outside. You ___ finish your dinner, don't delay to join us.",
        "How do you ___ solving the problem? I find it quite interesting.",
        "___ one of your family members have an accident? You should call the hospital right now!",
        "___ you stay outside? It is dangerous to stay out at this hour.",
        "___ too many distractions are not good for students.",
        "___ finished eating your food, you can go out to play.",
      ],
      answers: [
        "used to",
        "had better",
        "as if",
        "What does... look like",
        "have to",
        "feel like",
        "What if",
        "Would rather",
        "There",
        "As soon as",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Khulna",
    data: {
      options: [
        "as if",
        "have to",
        "what if",
        "would rather",
        "as soon as",
        "there",
        "it",
        "had better",
        "was born",
        "what does... look like",
      ],
      questions: [
        "She behaves ___ she knows everything, but in reality, she is not well-informed.",
        "If you want to go out tonight, you ___ finish your homework first.",
        "___ he ___ a nice car? I've never seen it.",
        "You ___ take a taxi rather than walk home at this hour.",
        "The sun is setting. We should leave ___ possible.",
        "The doctor advised him to exercise regularly; ___ be more active.",
        "Yesterday, ___ was an interesting program on television about space exploration.",
        "I am not sure ___ you would like this new restaurant.",
        "He ___ run than walk if he is in a hurry.",
        "The teacher asked the students ___ they had prepared for the exam.",
      ],
      answers: [
        "as if",
        "have to",
        "What does... look like",
        "had better",
        "as soon as",
        "would rather",
        "there",
        "what if",
        "would rather",
        "it",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2023,
    board: "Mymensingh",
    data: {
      options: [
        "as soon as",
        "there",
        "what does... look like",
        "would rather",
        "had better",
        "let alone",
        "it",
        "was born",
        "have to",
        "as if",
      ],
      questions: [
        "He will call you ___ he arrives home.",
        "They are so busy that they can't even attend the meeting, ___ join the party.",
        "The sunset is beautiful today. ___ look like a painting.",
        "I ___ stay home and read a book than go to that boring party.",
        "The sky ___? It looks quite dark.",
        "We ___ start preparing for the upcoming exam.",
        "The famous artist ___ in this city many years ago.",
        "You ___ tell him the truth about the matter.",
        "The new mall has opened. How ___?",
        "She talks ___ she is the expert in everything.",
      ],
      answers: [
        "as soon as",
        "let alone",
        "what does... look like",
        "would rather",
        "it",
        "had better",
        "was born",
        "have to",
        "there",
        "as if",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Dhaka",
    data: {
      options: [
        "would you mind",
        "there",
        "as soon as",
        "was born",
        "it is high time",
        "as if",
        "would rather",
        "unless",
        "what does... look like",
        "have to",
      ],
      questions: [
        "Your enemies are looking for you. ___ you left this place.",
        "It is raining heavily, ___ closing the window.",
        "Rifat often behaves ___ he were a prince. It becomes very difficult for me to tolerate him.",
        "Humayun Ahmed was a teacher, author, dramatist, and filmmaker. He ___ on 13 November 1948.",
        "___ you work hard, you will not make a good result.",
        "I ___ resign my job than tolerate injustice. I have the moral courage to raise my voice against injustice.",
        "___ a satellite ___? Father, I have heard of it but never got a chance to see it.",
        "The traffic jam ___ the incident took place. But the police didn’t arrive even after two hours.",
        "Our society is full of bad persons. We ___ remain aware of them.",
        "Something must have happened.",
      ],
      answers: [
        "as soon as",
        "have to",
        "as if",
        "was born",
        "unless",
        "would rather",
        "What does... look like",
        "there",
        "have to",
        "it is high time",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Rajshahi",
    data: {
      options: [
        "had better",
        "let alone",
        "what does... look like",
        "as soon as",
        "as if",
        "there",
        "would you mind",
        "would rather",
        "it",
        "was born",
      ],
      questions: [
        "Our spring is very charming. During spring various kinds of flowers bloom. ___ seems that everything has got a new life.",
        "Baby: Mom, ___ an owl ___? Don’t disturb me; you ___ leave me alone at this moment.",
        "The poor man ___ starve than beg.",
        "___ exists no life on Mars.",
        "___ taking tea with me?",
        "Sir Walter Scott was both a poet and a novelist. He ___ in 1771.",
        "She acts ___ she were mad.",
        "___ we reached the station, the train started.",
        "He did not even see a hill, ___ a mountain.",
      ],
      answers: [
        "It",
        "What does... look like",
        "had better",
        "there",
        "would you mind",
        "was born",
        "as if",
        "as soon as",
        "let alone",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Cumilla",
    data: {
      options: [
        "what does... look like",
        "how to",
        "in order that",
        "it is high time",
        "was born",
        "had to",
        "let alone",
        "unless",
        "lest",
        "what's it like",
      ],
      questions: [
        "The child cannot walk ___ run in the field.",
        "Tareq Ahmed is a renowned teacher. He ___ in 1960.",
        "At present, the children do not know ___ swim in water.",
        "Parents ___ work hard to take care of their children.",
        "Rima studies hard ___ GPA-5 should be missed.",
        "Father, ___ a ghost ___?",
        "Tanisha went to college ___ she could learn something.",
        "People stopped corruption from society.",
        "___ swimming in the river? For the first time, it seems a new experience for all.",
        "You will not succeed in life ___ you work hard.",
      ],
      answers: [
        "let alone",
        "was born",
        "how to",
        "have to",
        "lest",
        "What does... look like",
        "in order that",
        "it is high time",
        "What's it like",
        "unless",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Jashore",
    data: {
      options: [
        "would you mind",
        "was born",
        "let alone",
        "had better",
        "there",
        "what does... look like",
        "as if",
        "would rather",
        "as soon as",
        "have to",
      ],
      questions: [
        "___ flying in the sky? I think you will enjoy a lot.",
        "___ was a king named Robert Bruce. He was very famous.",
        "I ___ and brought up in Bangladesh. This is a very beautiful country.",
        "Bangladesh is an emerging power in the world cricket. But we ___ struggle more to win the world cup.",
        "He cannot tell my name, ___ my address. He is really a liar.",
        "___ the earth ___? It's not completely round.",
        "We ___ walk fast than get on the train. The train is overcrowded.",
        "The class started ___ I reached my college. I was really lucky.",
        "You ___ go home as early as possible.",
        "The man pretended ___ he had been very poor. So, we disliked him.",
      ],
      answers: [
        "Would you mind",
        "There",
        "was born",
        "have to",
        "let alone",
        "What does... look like",
        "would rather",
        "as soon as",
        "had better",
        "as if",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Sylhet",
    data: {
      options: [
        "as if",
        "it is about time",
        "would rather",
        "feel like",
        "blow one's own trumpet",
        "is used to",
        "as far as",
        "when it comes to",
        "had better",
        "needn't have",
      ],
      questions: [
        "“Can I smoke here?” “___ you didn’t. It’s a no-smoking zone.”",
        "This car is absolutely fine ___ the engine is concerned.",
        "We rushed to the station lest we might miss the train. But the train was late and we had to wait for an hour. We ___ hurried.",
        "It’s well past 10 and Diba is still in bed. ___ she got up.",
        "Nishi is a nice girl. But ___ cooking, she is absolutely hopeless.",
        "Lima has always lived alone. She ___ living alone.",
        "Well, you don’t need to ___ how that you have some talent.",
        "Look at that building! It looks ___ it’s going to fall down.",
        "I am very tired. I don’t ___ going out this evening.",
        "“It’s getting late. I have to go now.” “You ___ not. It’s raining very hard.”",
      ],
      answers: [
        "as if",
        "as far as",
        "needn't have",
        "it is about time",
        "when it comes to",
        "is used to",
        "blow one's own trumpet",
        "as if",
        "feel like",
        "would rather",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Barishal",
    data: {
      options: [
        "as though",
        "was born",
        "what does... look like",
        "it",
        "had to",
        "had better",
        "let alone",
        "as soon as",
        "there",
        "would rather",
      ],
      questions: [
        "We ___ hire a rickshaw. It’s already too late. We have to reach the exam hall in time.",
        "I can’t remember the name of the story, ___ the details about the different characters. I read the story many years ago.",
        "Rima studies very hard. She will get GPA-5. ___ she deserves it.",
        "Dola told me that the train would arrive at 7. But now it’s already 7:30. So, ___ we leave right now.",
        "She has a lot of homework to do. ___ time to study.",
        "Everyone thinks he is an expert in the field, but he hardly knows anything. ___ the basics.",
        "I saw a bird in the tree. It ___ it was a parrot.",
        "I think he is very proud of himself. He often ___ a lot.",
        "My father ___ in a village. He has a great sense of humor.",
        "___ a great idea! We can start our own business together.",
      ],
      answers: [
        "had better",
        "let alone",
        "as though",
        "it",
        "it is high time",
        "there",
        "what does... look like",
        "would rather",
        "was born",
        "had to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Chattogram",
    data: {
      options: [
        "there",
        "it is high time",
        "had to",
        "when it comes to",
        "would you mind",
        "as if",
        "what does... look like",
        "is used to",
        "would rather",
        "was born",
      ],
      questions: [
        "You are not in a hurry. ___ have a cup of tea?",
        "Alif was asking ___ to come home with him.",
        "I am not feeling well. I ___ go to the doctor.",
        "The children need to be more careful about their health. ___ this is the first time they have had such a serious illness.",
        "My uncle ___ a great author. I really admire him.",
        "I am going to quit my job; ___ I could not bear it any longer.",
        "It is true that ___ they took my advice, they would be better off now.",
        "You have been in Dhaka for a long time. So, you ___ traffic jams.",
        "___ to read this book? It has been praised by many readers.",
        "“Why didn’t you tell me about the program?” “I thought you knew about it. ___ you didn’t.”",
      ],
      answers: [
        "Would you mind",
        "what does... look like",
        "had to",
        "it",
        "was born",
        "when it comes to",
        "as if",
        "is used to",
        "would you mind",
        "there",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2019,
    board: "Mymensingh",
    data: {
      options: [
        "it",
        "as soon as",
        "when it comes to",
        "what does... look like",
        "is used to",
        "there",
        "was born",
        "as if",
        "had to",
        "would rather",
      ],
      questions: [
        "I can hardly hear you. ___ very loud.",
        "Shabnoor is a beautiful girl. I don’t know ___ her.",
        "I ___ not to attend any social functions.",
        "The train will leave ___ the passengers arrive.",
        "My mother ___ in a small village. She is very kind-hearted.",
        "I am afraid I ___ my attention.",
        "You really ___ leave me alone for some time.",
        "He acts ___ he is an experienced engineer.",
        "They played so well. If they had practiced more, they ___ won the match.",
        "The money is not ___ education is concerned.",
      ],
      answers: [
        "it",
        "what does... look like",
        "would rather",
        "as soon as",
        "was born",
        "had to",
        "have to",
        "as if",
        "there",
        "when it comes to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Ka Set",
    data: {
      options: [
        "as if",
        "have to",
        "as soon as",
        "it",
        "was born",
        "let alone",
        "would rather",
        "there",
        "had better",
        "what if",
      ],
      questions: [
        "We --- pay a visit to Cox’s Bazar than the Sundarban. We have already visited the Sundarbans.",
        "The storm was raging violently. We got out --- it abated.",
        "Fardin is always boastful of his uncles. He talks --- they were the most powerful men in the country.",
        "My college is far away from our house. I --- walk a long way to go to my college.",
        "Jasim Uddin is a rural poet. He --- in 1903 in a village named Tambulkhana in Faridpur.",
        "--- is very hot today. Load shedding is aggravating the situation.",
        "Maruf cannot earn 50 marks --- 80 marks. He is a student of average standard.",
        "--- are many mango trees around our home. They give us very sweet mangoes.",
        "Falaz seems to be weak. He --- consult an experienced doctor.",
        "The river is calm. --- we swim in the river? To swim in the river is a nice experience.",
      ],
      answers: [
        "would rather",
        "as soon as",
        "as if",
        "have to",
        "was born",
        "It",
        "let alone",
        "There",
        "had better",
        "What if",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2018,
    board: "Kha Set",
    data: {
      options: [
        "would you mind",
        "used to",
        "as if",
        "as soon as",
        "let alone",
        "had better",
        "it",
        "would rather",
        "so that",
        "what if",
      ],
      questions: [
        "He acts --- he were rich. So nobody likes him.",
        "--- eating sea fish? I think you will enjoy a lot.",
        "Aloka can’t afford to buy a cellphone, --- a laptop. Actually she is very poor.",
        "It may rain today. You --- leave earlier.",
        "Sometimes we become speechless remembering our childhood memories. We --- swim in the river.",
        "--- is many years since we first met. How time does fly!",
        "His mother being sick, he needs to go home --- possible.",
        "We --- develop our humanity than observe hartal and strike. Let us change our destructive culture.",
        "There started a heavy storm when I was about to go out --- I had been out there?",
        "He took a part time job --- he could earn some money. He was very sincere.",
      ],
      answers: [
        "as if",
        "Would you mind",
        "let alone",
        "had better",
        "used to",
        "It",
        "as soon as",
        "would rather",
        "What if",
        "so that",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dhaka",
    data: {
      options: [
        "as soon as",
        "what does... look like",
        "what if",
        "what's it like",
        "it",
        "had better",
        "was born",
        "let alone",
        "have to",
        "would rather",
      ],
      questions: [
        "Deforestation is a matter of great concern. We ___ take immediate steps against cutting down trees at random.",
        "To tell a lie is a great sin. We ___ die than tell a lie. Otherwise none will believe us.",
        "Helmet should be used while driving a motorcycle. ___ you were driving your bike and met a serious accident?",
        "___ swimming in the sea? It seems to be very heroic to me.",
        "___ mother heard the news, she cried loudly. She lost her child in a car accident.",
        "Rome was not built in a day. ___ took a long-time and hard labour to build this city.",
        "Rahman is a poor man. He cannot buy a shirt ___ a car.",
        "Kazi Nazrul Islam is our rebel poet. He ___ in Churulia of West Bengal.",
        "Rina's dress looks very dirty. It is old enough. She ___ buy a new dress.",
        "Rana: Hi, Robi ___ a Pea-cock ___? Robi: It’s a very nice bird. It knows how to dance?",
      ],
      answers: [
        "have to",
        "would rather",
        "what if",
        "What's it like",
        "as soon as",
        "it",
        "let alone",
        "was born",
        "had better",
        "what does... look like",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Cumilla",
    data: {
      options: [
        "it is high time",
        "in case",
        "lest",
        "as though",
        "no sooner had",
        "unless",
        "would you mind",
        "have to",
        "used to",
        "as long as",
      ],
      questions: [
        "There is foul smell in the room. ___ opening the windows?",
        "Tomorrow I will be very busy. So, I’ll say good bye now ___ I don’t see you again.",
        "We ___ educate all and work hard to develop our country.",
        "Nobody likes Karim at all. He talks ___ he knew everything.",
        "The poor will continue to suffer ___ they are illiterate.",
        "Nobody likes you here ___ you left this place.",
        "He saw a bear coming towards him. So, he climbed up a tree ___ the bear might attack him.",
        "Everybody disliked Rakib. He ___ do many harmful activities.",
        "Time is very important in our life. You cannot prosper in life ___ you make proper use of time.",
        "The students were talking in the class. ___ the teacher entered the class than they stopped talking.",
      ],
      answers: [
        "would you mind",
        "lest",
        "have to",
        "as though",
        "unless",
        "as long as",
        "lest",
        "used to",
        "unless",
        "no sooner had",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Rajshahi",
    data: {
      options: [
        "there",
        "what if",
        "have to",
        "no sooner had",
        "would rather",
        "lest",
        "as if",
        "let alone",
        "what does... look like",
        "be born",
      ],
      questions: [
        "The students were loitering in the corridor, ___ they seen the teacher than they entered the classroom.",
        "Bangabandhu Sheikh Mujibur Rahman is the father of our nation. He ___ in 1920 in Tungipara of Gopalganj district.",
        "I can’t stand Rubel. He always acts ___ he were smarter than everyone.",
        "The little girl was suddenly crossing the road. A bus was passing by. As it came near the girl, the driver halted it. ___ he wouldn’t have stopped the bus?",
        "Shoma ___ live in a hostel than live in her relative’s home. She feels free and comfortable in the hostel.",
        "You started late. Now you are walking slowly. Walk fast ___ you should miss the bus.",
        "He is very poor. He can’t afford to travel by an AC bus ___ an aeroplane.",
        "Daughter: Mom, ___ an albatross ___? Mother: My dear, an albatross is a very large white bird that lives in the Pacific and Southern Oceans.",
        "Long ago, ___ lived a mighty warrior named Kubla Khan. He was the grandson of Chenghis Khan.",
        "I ___ seek advice from a doctor. I have been suffering from fever for a long time.",
      ],
      answers: [
        "no sooner had",
        "was born",
        "as if",
        "what if",
        "would rather",
        "lest",
        "let alone",
        "what does... look like",
        "there",
        "have to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Dinajpur",
    data: {
      options: [
        "there",
        "let alone",
        "it",
        "as if",
        "what... look like",
        "have to",
        "as soon as",
        "was born",
        "had better",
        "would rather",
      ],
      questions: [
        "We ___ not go out today. A riot has broken out in our locality.",
        "___ is a good idea to walk in the morning. One can take it as an important form of physical exercise, because it refreshes both body and mind.",
        "Do you often ___ travel on business? You are always seen travelling abroad.",
        "Long ago ___ lived a very pious man. His name was Hatem Tai and he was very kind hearted.",
        "___ does a clown ___? You’ve seen a clown in the circus many a time.",
        "I got a job at a bar. But I hate working at a bar. I ___ be a waiter than a barman.",
        "I fills up with joy. I am very much fond of my father.",
        "Kazi Nazrul Islam ___ in an impoverished family. He had to earn even when he was a small boy.",
        "The economic condition of Robi is very poor. He cannot afford one meal per day ___ square meals.",
        "After the final match of the FIFA World Cup 2014, Messi looked ___ he were completely routed. His cherished dream had been shattered.",
      ],
      answers: [
        "had better",
        "there",
        "have to",
        "there",
        "what... look like",
        "would rather",
        "as soon as",
        "was born",
        "let alone",
        "as if",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Jashore",
    data: {
      options: [
        "as if",
        "let alone",
        "what does... look like",
        "was born",
        "there",
        "what's it like",
        "have to",
        "as soon as",
        "had better",
        "would rather",
      ],
      questions: [
        "In modern times, ___ has been a great change in the attitude of man regarding superstitious belief.",
        "Our learners develop a very poor writing skill. They cannot write fairly well even in Bangla ___ in English.",
        "Some city dwellers’ behaviour is often too formal. They speak in such a way ___ they were never in the village.",
        "I have never travelled by air. ___ flying in the sky?",
        "Riaz: ___ the frozen mountain peak...? Purnima: It looks like a white dome.",
        "Sheela is suffering from tooth-ache. She ___ see a dentist.",
        "Play is delayed due to rain. It will resume ___ the rain stops.",
        "Sohel is a very good natured boy. He ___ stay at home than mix with bad companies.",
        "Milton was a poet of versatile genius. He ___ in 1608 in England. He used to believe that one should start a profession after taking necessary preparations.",
        "We have discussed for quite a long time. We can’t take much time any more. We ___ come to a conclusion.",
      ],
      answers: [
        "there",
        "let alone",
        "as if",
        "What's it like",
        "what does... look like",
        "had better",
        "as soon as",
        "would rather",
        "was born",
        "have to",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
  {
    exam: "hsc",
    year: 2017,
    board: "Chittagong",
    data: {
      options: [
        "there",
        "as soon as",
        "what does... look like",
        "was born",
        "what if",
        "has to",
        "as if",
        "what's it like",
        "let alone",
        "would rather",
      ],
      questions: [
        "It was 45 years ago when a new country named Bangladesh in the world map ___ at the cost of million of lives.",
        "During the Liberation War of Bangladesh ___ was a great American singer George Harison who sang for Bangladesh.",
        "___ living in Bangladesh? You seem to be very happy with your life in Bangladesh.",
        "My foreign friend told me you ___ leave this country than live here. I replied “This is my motherland.”",
        "In 1971 the Pakistani army did terrible atrocities against the Bangladesh. Pakistan ___ apologize for this to Bangladesh.",
        "Pakistan always plays a role against Bangladesh. We cannot expect any co-operation from them ___ apology.",
        "The elements of anti-liberation forces came out of their cocoons ___ the father of the nation Bangabandhu Sheikh Mujibur Rahman was killed.",
        "Some persons living in Bangladesh always try to make conspiracy against the country ___ Bangladesh were not their own country.",
        "The authority of Dhaka University cut ties with Pakistan. ___ the government of Bangladesh takes initiatives to cut diplomatic relation with Pakistan?",
        "Teacher: Learners, ___ the national flower of Bangladesh ___?",
      ],
      answers: [
        "was born",
        "there",
        "What's it like",
        "would rather",
        "has to",
        "let alone",
        "as soon as",
        "as if",
        "what if",
        "what does... look like",
      ],
      isDifficult: false,
      isCompleted: false,
    },
  },
];
